% GOAL
%   Concatenate all completed 500 Hz EEG recordings for one participant after
%   GRF-derived gait events and project channel locations have been added.
%
% METHOD
%   Preserve the current true-LSL chronological ordering, channel/layout
%   validation, gait-event provenance, boundary insertion, source manifest,
%   and safe subject-level processing-table update logic.

function [mergedSetPath, subjectSummary] = ...
        concatenate_subject_grf_eeg(subjectOutputFolder, varargin)

if nargin < 1
    subjectOutputFolder = "";
end

parser = inputParser;

addOptional(parser, 'subjectOutputFolder', subjectOutputFolder, ...
    @(x) ischar(x) || (isstring(x) && isscalar(x)));

addParameter(parser, 'ForceReprocess', false, ...
    @(x) islogical(x) && isscalar(x));

addParameter(parser, 'AllowPartialSubject', false, ...
    @(x) islogical(x) && isscalar(x));

parse(parser, subjectOutputFolder, varargin{:});

subjectOutputFolder = ...
    char(string(parser.Results.subjectOutputFolder));

forceReprocess = logical(parser.Results.ForceReprocess);
allowPartialSubject = logical(parser.Results.AllowPartialSubject);

packageFolder = fileparts(mfilename('fullpath'));
scriptsRoot = fileparts(packageFolder);

addpath(scriptsRoot, '-begin');
addpath(fullfile(scriptsRoot, 'config'), '-begin');

P = project_paths();

grfSegmentationFolder = P.grfSegmentationFolder;
subjectLevelEEGFolder = P.subjectLevelEEGFolder;
subjectLevelEEGTableFile = P.subjectLevelEEGTableFile;

if ~isfolder(subjectLevelEEGFolder)
    mkdir(subjectLevelEEGFolder);
end

%% All subjects mode

if isempty(strtrim(subjectOutputFolder))

    subjectDirectories = dir(fullfile( ...
        grfSegmentationFolder, ...
        'sub-*'));

    subjectDirectories = ...
        subjectDirectories([subjectDirectories.isdir]);

    if isempty(subjectDirectories)

        error([ ...
            'No subject GRF/EEG output folders found below:\n%s'], ...
            grfSegmentationFolder);
    end

    mergedSetPath = strings(0,1);
    subjectSummary = table();

    for iSubject = 1:numel(subjectDirectories)

        currentSubjectFolder = fullfile( ...
            subjectDirectories(iSubject).folder, ...
            subjectDirectories(iSubject).name);

        try

            [currentMergedPath, currentSummary] = ...
                hipexo.concatenate_subject_grf_eeg( ...
                    currentSubjectFolder, ...
                    'ForceReprocess', forceReprocess, ...
                    'AllowPartialSubject', allowPartialSubject);

            mergedSetPath(end+1,1) = ...
                string(currentMergedPath); %#ok<AGROW>

            if isempty(subjectSummary)
                subjectSummary = currentSummary;
            else
                subjectSummary = ...
                    [subjectSummary; currentSummary]; %#ok<AGROW>
            end

        catch currentError

            fprintf(2, ...
                '\nSubject concatenation failed:\n%s\n%s\n', ...
                currentSubjectFolder, ...
                currentError.message);
        end
    end

    if isempty(subjectSummary)
        error('No subject-level EEG dataset was created.');
    end

    return;
end

%% Batch status

if ~isfolder(subjectOutputFolder)
    error('Subject output folder does not exist:\n%s', ...
        subjectOutputFolder);
end

batchLogs = dir(fullfile( ...
    subjectOutputFolder, ...
    '*_GRF_EEG_batch_status.csv'));

if numel(batchLogs) ~= 1
    error('Expected exactly one subject batch-status CSV.');
end

batchLogFile = fullfile( ...
    batchLogs(1).folder, ...
    batchLogs(1).name);

batchStatus = read_csv_with_string_text(batchLogFile);

requiredBatchVariables = { ...
    'Subject', ...
    'SessionFolder', ...
    'XDFPath', ...
    'EEG_LSL_Start', ...
    'EEG_LSL_End', ...
    'EEG_LSL_DurationSec', ...
    'GRF_LSL_Start', ...
    'GRF_LSL_End', ...
    'GRF_LSL_DurationSec', ...
    'GRF_EEG_LSL_OverlapSec', ...
    'OverallStatus', ...
    'EEGSetFile', ...
    'MappedEventCount', ...
    'FirstGRFEventSample', ...
    'FirstGRFEventLSLTime', ...
    'FirstMappedEEGSample', ...
    'FirstMatchedEEGLSLTime', ...
    'LastGRFEventSample', ...
    'LastGRFEventLSLTime', ...
    'LastMappedEEGSample', ...
    'LastMatchedEEGLSLTime', ...
    'MedianAbsMappingErrorMs', ...
    'MaxAbsMappingErrorMs'};

for iVariable = 1:numel(requiredBatchVariables)

    if ~ismember( ...
            requiredBatchVariables{iVariable}, ...
            batchStatus.Properties.VariableNames)

        error('Batch-status CSV missing "%s":\n%s', ...
            requiredBatchVariables{iVariable}, ...
            batchLogFile);
    end
end

numericBatchVariables = { ...
    'EEG_LSL_Start', ...
    'EEG_LSL_End', ...
    'EEG_LSL_DurationSec', ...
    'GRF_LSL_Start', ...
    'GRF_LSL_End', ...
    'GRF_LSL_DurationSec', ...
    'GRF_EEG_LSL_OverlapSec', ...
    'MappedEventCount', ...
    'FirstGRFEventSample', ...
    'FirstGRFEventLSLTime', ...
    'FirstMappedEEGSample', ...
    'FirstMatchedEEGLSLTime', ...
    'LastGRFEventSample', ...
    'LastGRFEventLSLTime', ...
    'LastMappedEEGSample', ...
    'LastMatchedEEGLSLTime', ...
    'MedianAbsMappingErrorMs', ...
    'MaxAbsMappingErrorMs'};

for iVariable = 1:numel(numericBatchVariables)

    currentVariable = numericBatchVariables{iVariable};

    batchStatus.(currentVariable) = ...
        numeric_column_local( ...
        batchStatus.(currentVariable));
end

batchStatus.Subject = string(batchStatus.Subject);
batchStatus.SessionFolder = string(batchStatus.SessionFolder);
batchStatus.XDFPath = string(batchStatus.XDFPath);
batchStatus.OverallStatus = string(batchStatus.OverallStatus);
batchStatus.EEGSetFile = string(batchStatus.EEGSetFile);

failedRows = batchStatus.OverallStatus ~= "completed";

if any(failedRows) && ~allowPartialSubject

    error([ ...
        '%d selected XDF file(s) did not complete. ' ...
        'Concatenation blocked.'], ...
        sum(failedRows));
end

readyRows = ...
    batchStatus.OverallStatus == "completed" & ...
    batchStatus.MappedEventCount > 0 & ...
    strlength(strtrim(batchStatus.EEGSetFile)) > 0;

if ~any(readyRows)
    error('No completed mapped EEG datasets available.');
end

sourceTable = batchStatus(readyRows,:);

for iSource = 1:height(sourceTable)

    if ~isfile(sourceTable.EEGSetFile(iSource))
        error('Mapped EEG does not exist:\n%s', ...
            sourceTable.EEGSetFile(iSource));
    end
end

subjectLabels = unique(sourceTable.Subject);
subjectLabels(strlength(strtrim(subjectLabels)) == 0) = [];

if numel(subjectLabels) ~= 1
    error('Rows do not resolve to exactly one subject.');
end

subjectLabel = subjectLabels(1);

%% Output

subjectDestinationFolder = fullfile( ...
    subjectLevelEEGFolder, ...
    char(subjectLabel));

if ~isfolder(subjectDestinationFolder)
    mkdir(subjectDestinationFolder);
end

mergedSetName = char( ...
    subjectLabel + ...
    "_all_sessions_500Hz_with_GRF_events.set");

mergedSetPath = fullfile( ...
    subjectDestinationFolder, ...
    mergedSetName);

manifestFile = fullfile( ...
    subjectDestinationFolder, ...
    char(subjectLabel + ...
    "_all_sessions_source_manifest.csv"));

sourceInputSignature = ...
    build_source_input_signature(sourceTable.EEGSetFile);

%% EEGLAB

if exist('pop_loadset','file') ~= 2
    eeglab nogui;
end

try

    pop_editoptions( ...
        'option_saveversion6', 0, ...
        'option_single', 0, ...
        'option_memmapdata', 0, ...
        'option_savetwofiles', 1, ...
        'option_storedisk', 0);

catch

    warning('Could not set every EEGLAB save option.');
end

%% Reuse validation

if isfile(mergedSetPath) && ...
        isfile(manifestFile) && ...
        ~forceReprocess

    existingEEG = [];
    storedSignature = "";

    try

        existingEEG = pop_loadset( ...
            'filename', mergedSetName, ...
            'filepath', subjectDestinationFolder);

    catch reuseLoadError

        fprintf( ...
            '\nExisting merged EEG could not be loaded: %s\n', ...
            reuseLoadError.message);
    end

    if ~isempty(existingEEG) && ...
            isfield(existingEEG,'etc') && ...
            isfield(existingEEG.etc, ...
            'subject_merge_input_signature')

        storedSignature = string( ...
            existingEEG.etc.subject_merge_input_signature);
    end

    if storedSignature == sourceInputSignature

        try

            sourceManifest = ...
                read_csv_with_string_text(manifestFile);

            validate_merged_subject_eeg( ...
                existingEEG, ...
                height(sourceManifest));

            subjectSummary = ...
                build_subject_summary( ...
                    subjectLabel, ...
                    mergedSetPath, ...
                    manifestFile, ...
                    sourceManifest, ...
                    existingEEG, ...
                    sourceInputSignature, ...
                    "reused_existing");

            update_subject_processing_table( ...
                subjectSummary, ...
                subjectLevelEEGTableFile);

            fprintf('\nReusing subject-level EEG:\n%s\n', ...
                mergedSetPath);

            return;

        catch
        end
    end
end

%% Load all source EEGs and independently read RAW XDF LSL timestamps

nSources = height(sourceTable);

loadedEEG = cell(nSources,1);
sourceMetadata = cell(nSources,1);

eegFirstLSLTime = nan(nSources,1);
eegLastLSLTime = nan(nSources,1);

referenceSrate = NaN;
referenceChannelLabels = strings(0,1);
referenceChannelXYZ = [];

for iSource = 1:nSources

    currentSetPath = ...
        char(sourceTable.EEGSetFile(iSource));

    [currentSetFolder, ...
     currentSetBase, ...
     currentSetExtension] = ...
        fileparts(currentSetPath);

    currentEEG = pop_loadset( ...
        'filename', ...
        [currentSetBase currentSetExtension], ...
        'filepath', ...
        currentSetFolder);

    currentEEG = eeg_checkset(currentEEG);

    currentMetadata = resolve_source_metadata( ...
        currentEEG, ...
        sourceTable.XDFPath(iSource));

    if currentMetadata.SubjectLabel ~= subjectLabel
        error('Source EEG subject mismatch.');
    end

    validate_source_eeg( ...
        currentEEG, ...
        currentMetadata, ...
        referenceSrate, ...
        referenceChannelLabels, ...
        referenceChannelXYZ);

    if iSource == 1

        referenceSrate = double(currentEEG.srate);

        referenceChannelLabels = ...
            string({currentEEG.chanlocs.labels})';

        referenceChannelXYZ = ...
            channel_xyz_matrix(currentEEG.chanlocs);
    end

    % IMPORTANT:
    % chronology is independently read from the original XDF here.
    [eegFirstLSLTime(iSource), ...
     eegLastLSLTime(iSource)] = ...
        source_xdf_eeg_lsl_bounds( ...
        sourceTable.XDFPath(iSource));

    loadedEEG{iSource} = currentEEG;
    sourceMetadata{iSource} = currentMetadata;
end

if numel(unique(eegFirstLSLTime)) ~= nSources
    error('Duplicate EEG first LSL timestamps detected.');
end

%% REAL chronological order

[~, chronologicalOrder] = ...
    sort(eegFirstLSLTime, 'ascend');

sourceTable = sourceTable(chronologicalOrder,:);
loadedEEG = loadedEEG(chronologicalOrder);
sourceMetadata = sourceMetadata(chronologicalOrder);

eegFirstLSLTime = ...
    eegFirstLSLTime(chronologicalOrder);

eegLastLSLTime = ...
    eegLastLSLTime(chronologicalOrder);

fprintf('\n====================================================\n');
fprintf('TRUE EEG LSL ACQUISITION ORDER\n');
fprintf('====================================================\n');

for iSource = 1:nSources

    currentMetadata = sourceMetadata{iSource};

    fprintf( ...
        '%02d %s run-%03d Start=%.6f End=%.6f\n', ...
        iSource, ...
        currentMetadata.SessionLabel, ...
        currentMetadata.RunNumber, ...
        eegFirstLSLTime(iSource), ...
        eegLastLSLTime(iSource));
end

%% Build chronologically sorted recordings

ALLEEG = [];
CURRENTSET = 0;

sourceIndex = (1:nSources)';

eegLSLDurationSec = ...
    eegLastLSLTime - eegFirstLSLTime;

grfFirstLSLTime = sourceTable.GRF_LSL_Start;
grfLastLSLTime = sourceTable.GRF_LSL_End;
grfLSLDurationSec = sourceTable.GRF_LSL_DurationSec;

grfEEGLSLOverlapSec = ...
    sourceTable.GRF_EEG_LSL_OverlapSec;

firstGRFEventSample = ...
    sourceTable.FirstGRFEventSample;

firstGRFEventLSLTime = ...
    sourceTable.FirstGRFEventLSLTime;

firstMappedEEGSample = ...
    sourceTable.FirstMappedEEGSample;

firstMatchedEEGLSLTime = ...
    sourceTable.FirstMatchedEEGLSLTime;

lastGRFEventSample = ...
    sourceTable.LastGRFEventSample;

lastGRFEventLSLTime = ...
    sourceTable.LastGRFEventLSLTime;

lastMappedEEGSample = ...
    sourceTable.LastMappedEEGSample;

lastMatchedEEGLSLTime = ...
    sourceTable.LastMatchedEEGLSLTime;

medianAbsMappingErrorMs = ...
    sourceTable.MedianAbsMappingErrorMs;

maxAbsMappingErrorMs = ...
    sourceTable.MaxAbsMappingErrorMs;

manifestSubject = ...
    repmat(subjectLabel, nSources,1);

dayLabel = strings(nSources,1);
sessionLabel = strings(nSources,1);
conditionLabel = strings(nSources,1);
taskLabel = strings(nSources,1);
runNumber = nan(nSources,1);

xdfPath = sourceTable.XDFPath;
sourceSetPath = sourceTable.EEGSetFile;

startSample = nan(nSources,1);
endSample = nan(nSources,1);
sampleCount = nan(nSources,1);
durationSec = nan(nSources,1);
gaitEventCount = nan(nSources,1);
internalBoundaryCount = nan(nSources,1);

cumulativeSamples = 0;

validGaitEventTypes = ...
    ["RHS","RTO","LHS","LTO"];

for iSource = 1:nSources

    currentEEG = loadedEEG{iSource};
    currentMetadata = sourceMetadata{iSource};

    currentEEG = ...
        add_source_metadata_to_events( ...
            currentEEG, ...
            currentMetadata, ...
            iSource);

    currentEEG = ...
        add_recording_start_event( ...
            currentEEG, ...
            currentMetadata, ...
            iSource);

    currentEEG = eeg_checkset( ...
        currentEEG, ...
        'eventconsistency');

    currentEventTypes = ...
        event_type_strings(currentEEG.event);

    currentGaitEventCount = ...
        sum(ismember( ...
        currentEventTypes, ...
        validGaitEventTypes));

    missingGaitEventTypes = ...
        validGaitEventTypes( ...
        ~ismember( ...
        validGaitEventTypes, ...
        currentEventTypes));

    if ~isempty(missingGaitEventTypes)
        error('Required gait events missing.');
    end

    dayLabel(iSource) = currentMetadata.DayLabel;
    sessionLabel(iSource) = currentMetadata.SessionLabel;
    conditionLabel(iSource) = currentMetadata.ConditionLabel;
    taskLabel(iSource) = currentMetadata.TaskLabel;
    runNumber(iSource) = currentMetadata.RunNumber;

    startSample(iSource) = cumulativeSamples + 1;
    endSample(iSource) = cumulativeSamples + currentEEG.pnts;
    sampleCount(iSource) = currentEEG.pnts;

    durationSec(iSource) = ...
        currentEEG.pnts / currentEEG.srate;

    gaitEventCount(iSource) = ...
        currentGaitEventCount;

    internalBoundaryCount(iSource) = ...
        sum(currentEventTypes == "boundary");

    cumulativeSamples = endSample(iSource);

    [ALLEEG, currentEEG, CURRENTSET] = ...
        eeg_store(ALLEEG, currentEEG, 0);

    loadedEEG{iSource} = [];
end

%% Source manifest = supervisor audit evidence

sourceManifest = table( ...
    sourceIndex, ...
    manifestSubject, ...
    dayLabel, ...
    sessionLabel, ...
    conditionLabel, ...
    taskLabel, ...
    runNumber, ...
    xdfPath, ...
    eegFirstLSLTime, ...
    eegLastLSLTime, ...
    eegLSLDurationSec, ...
    grfFirstLSLTime, ...
    grfLastLSLTime, ...
    grfLSLDurationSec, ...
    grfEEGLSLOverlapSec, ...
    firstGRFEventSample, ...
    firstGRFEventLSLTime, ...
    firstMappedEEGSample, ...
    firstMatchedEEGLSLTime, ...
    lastGRFEventSample, ...
    lastGRFEventLSLTime, ...
    lastMappedEEGSample, ...
    lastMatchedEEGLSLTime, ...
    medianAbsMappingErrorMs, ...
    maxAbsMappingErrorMs, ...
    sourceSetPath, ...
    startSample, ...
    endSample, ...
    sampleCount, ...
    durationSec, ...
    gaitEventCount, ...
    internalBoundaryCount, ...
    'VariableNames', { ...
        'SourceIndex', ...
        'SubjectLabel', ...
        'DayLabel', ...
        'SessionLabel', ...
        'ConditionLabel', ...
        'TaskLabel', ...
        'RunNumber', ...
        'XDFPath', ...
        'EEG_LSL_Start', ...
        'EEG_LSL_End', ...
        'EEG_LSL_DurationSec', ...
        'GRF_LSL_Start', ...
        'GRF_LSL_End', ...
        'GRF_LSL_DurationSec', ...
        'GRF_EEG_LSL_OverlapSec', ...
        'FirstGRFEventSample', ...
        'FirstGRFEventLSLTime', ...
        'FirstMappedEEGSample', ...
        'FirstMatchedEEGLSLTime', ...
        'LastGRFEventSample', ...
        'LastGRFEventLSLTime', ...
        'LastMappedEEGSample', ...
        'LastMatchedEEGLSLTime', ...
        'MedianAbsMappingErrorMs', ...
        'MaxAbsMappingErrorMs', ...
        'SourceSetPath', ...
        'StartSampleInMergedEEG', ...
        'EndSampleInMergedEEG', ...
        'SampleCount', ...
        'DurationSec', ...
        'MappedGaitEventCount', ...
        'InternalBoundaryCount'});

%% Merge

if numel(ALLEEG) == 1
    EEG = ALLEEG(1);
else
    EEG = pop_mergeset( ...
        ALLEEG, ...
        1:numel(ALLEEG), ...
        0);
end

EEG = eeg_checkset(EEG);

EEG = normalize_merged_event_metadata( ...
    EEG, ...
    sourceManifest);

EEG = eeg_checkset( ...
    EEG, ...
    'eventconsistency');

EEG.setname = ...
    char(erase(string(mergedSetName), ".set"));

EEG.subject = char(subjectLabel);
EEG.condition = 'AllSessions';

EEG.etc.subject_level_concatenation = true;

EEG.etc.subject_merge_input_signature = ...
    char(sourceInputSignature);

EEG.etc.subject_merge_source_manifest = ...
    sourceManifest;

EEG.etc.subject_merge_source_set_paths = ...
    sourceSetPath;

EEG.etc.subject_merge_source_xdf_paths = ...
    xdfPath;

EEG.etc.subject_merge_source_recording_count = ...
    nSources;

EEG.etc.subject_merge_created_at = ...
    char(current_time_text);

validate_merged_subject_eeg(EEG, nSources);

%% Save

writetable(sourceManifest, manifestFile);

EEG = pop_saveset( ...
    EEG, ...
    'filename', mergedSetName, ...
    'filepath', subjectDestinationFolder, ...
    'savemode', 'twofiles');

if ~isfile(mergedSetPath)
    error('Merged EEG was not created.');
end

subjectSummary = build_subject_summary( ...
    subjectLabel, ...
    mergedSetPath, ...
    manifestFile, ...
    sourceManifest, ...
    EEG, ...
    sourceInputSignature, ...
    "completed");

update_subject_processing_table( ...
    subjectSummary, ...
    subjectLevelEEGTableFile);

fprintf('\n====================================================\n');
fprintf('SUBJECT-LEVEL EEG CONCATENATION COMPLETED\n');
fprintf('====================================================\n');
fprintf('Subject: %s\n', subjectLabel);
fprintf('Sources: %d\n', nSources);
fprintf('Merged EEG:\n%s\n', mergedSetPath);
fprintf('Source manifest:\n%s\n', manifestFile);

end

%% ------------------------------------------------------------
function validate_source_eeg( ...
        EEG, ...
        metadata, ...
        referenceSrate, ...
        referenceChannelLabels, ...
        referenceChannelXYZ)

if EEG.trials ~= 1
    error('Source EEG must be continuous.');
end

if EEG.nbchan ~= 64
    error('Expected 64 EEG channels.');
end

if abs(double(EEG.srate)-500) > 1e-6
    error('Expected 500 Hz EEG.');
end

if isfinite(referenceSrate) && ...
        abs(double(EEG.srate)-referenceSrate) > 1e-6
    error('Sampling-rate mismatch.');
end

currentChannelLabels = ...
    string({EEG.chanlocs.labels})';

if numel(unique(lower(strtrim(currentChannelLabels)))) ~= EEG.nbchan
    error('Channel labels are not unique.');
end

if ~isempty(referenceChannelLabels) && ...
        ~isequal( ...
        lower(strtrim(currentChannelLabels)), ...
        lower(strtrim(referenceChannelLabels)))

    error('Channel labels/order differ.');
end

if ~channel_locations_complete(EEG.chanlocs)
    error('Channel locations incomplete.');
end

currentChannelXYZ = ...
    channel_xyz_matrix(EEG.chanlocs);

if ~isempty(referenceChannelXYZ) && ...
        (size(currentChannelXYZ,1) ~= size(referenceChannelXYZ,1) || ...
         any(abs( ...
         currentChannelXYZ(:)-referenceChannelXYZ(:)) > 1e-9))

    error('Channel coordinates differ.');
end

if any(~isfinite(double(EEG.data(:))))
    error('EEG contains NaN/Inf.');
end

if isempty(EEG.event)
    error('Source EEG contains no events.');
end

end

function tf = channel_locations_complete(chanlocs)

tf = ~isempty(chanlocs);

if ~tf
    return;
end

requiredFields = {'X','Y','Z'};

for iField = 1:numel(requiredFields)

    fieldName = requiredFields{iField};

    if ~isfield(chanlocs,fieldName)
        tf = false;
        return;
    end

    for iChannel = 1:numel(chanlocs)

        value = chanlocs(iChannel).(fieldName);

        if isempty(value) || ...
                ~isnumeric(value) || ...
                ~isfinite(double(value(1)))

            tf = false;
            return;
        end
    end
end

end

function xyz = channel_xyz_matrix(chanlocs)

xyz = nan(numel(chanlocs),3);

for iChannel = 1:numel(chanlocs)

    xyz(iChannel,:) = [ ...
        double(chanlocs(iChannel).X), ...
        double(chanlocs(iChannel).Y), ...
        double(chanlocs(iChannel).Z)];
end

end

%% Read actual EEG LSL timestamps directly from original XDF

function [firstLSLTime,lastLSLTime] = ...
        source_xdf_eeg_lsl_bounds(xdfPath)

if exist('load_xdf','file') ~= 2
    error('load_xdf is not available.');
end

[streams,~] = load_xdf(char(xdfPath));

nStreams = numel(streams);

streamName = strings(nStreams,1);
streamType = strings(nStreams,1);
nominalSrate = nan(nStreams,1);
channelCount = nan(nStreams,1);
sampleCount = nan(nStreams,1);

for iStream = 1:nStreams

    currentStream = streams{iStream};

    streamName(iStream) = ...
        xdf_stream_text_field(currentStream,'name');

    streamType(iStream) = ...
        xdf_stream_text_field(currentStream,'type');

    nominalSrate(iStream) = ...
        xdf_stream_nominal_srate(currentStream);

    if isfield(currentStream,'time_stamps')

        currentTimestamps = ...
            currentStream.time_stamps;

        sampleCount(iStream) = ...
            numel(currentTimestamps);

        if isfield(currentStream,'time_series') && ...
                isnumeric(currentStream.time_series)

            currentData = ...
                currentStream.time_series;

            if size(currentData,2) == sampleCount(iStream)

                channelCount(iStream) = ...
                    size(currentData,1);

            elseif size(currentData,1) == sampleCount(iStream)

                channelCount(iStream) = ...
                    size(currentData,2);
            end
        end
    end
end

candidateMask = ...
    strcmpi(streamName,"LiveAmpSN-102108-1139") & ...
    channelCount >= 64 & ...
    channelCount <= 80 & ...
    abs(nominalSrate-500) <= 1;

candidateIndices = find(candidateMask);

if isempty(candidateIndices)

    candidateMask = ...
        channelCount >= 64 & ...
        channelCount <= 80 & ...
        abs(nominalSrate-500) <= 1 & ...
        (contains(lower(streamType),'eeg') | ...
         contains(lower(streamName),'liveamp'));

    candidateIndices = find(candidateMask);
end

if numel(candidateIndices) ~= 1

    streamSummary = table( ...
        (1:nStreams)', ...
        streamName, ...
        streamType, ...
        nominalSrate, ...
        channelCount, ...
        sampleCount, ...
        'VariableNames', ...
        {'StreamIndex','Name','Type','NominalSrate', ...
         'ChannelCount','SampleCount'});

    disp(streamSummary);

    error('Could not uniquely identify EEG stream:\n%s', ...
        xdfPath);
end

eegStream = streams{candidateIndices(1)};
eegTimestamps = double(eegStream.time_stamps(:));

if isempty(eegTimestamps) || ...
        any(~isfinite(eegTimestamps)) || ...
        any(diff(eegTimestamps)<=0)

    error('Invalid EEG LSL timestamps:\n%s', xdfPath);
end

firstLSLTime = eegTimestamps(1);
lastLSLTime = eegTimestamps(end);

end

function textValue = ...
        xdf_stream_text_field(stream,fieldName)

textValue = "";

if ~isfield(stream,'info') || ...
        ~isfield(stream.info,fieldName)
    return;
end

rawValue = stream.info.(fieldName);

while iscell(rawValue) && ~isempty(rawValue)
    rawValue = rawValue{1};
end

if isempty(rawValue)
    return;
end

textValue = string(rawValue);
textValue = textValue(1);

end

function nominalSrate = ...
        xdf_stream_nominal_srate(stream)

nominalSrate = NaN;

if ~isfield(stream,'info') || ...
        ~isfield(stream.info,'nominal_srate')
    return;
end

rawValue = stream.info.nominal_srate;

while iscell(rawValue) && ~isempty(rawValue)
    rawValue = rawValue{1};
end

if isnumeric(rawValue)
    nominalSrate = double(rawValue(1));
else
    nominalSrate = str2double(string(rawValue));
end

end

%% Metadata

function metadata = ...
        resolve_source_metadata(EEG,xdfPath)

[~,xdfBaseName,xdfExtension] = ...
    fileparts(char(xdfPath));

if ~isempty(regexpi( ...
        [xdfBaseName xdfExtension], ...
        '_old\d*\.xdf$', ...
        'once'))

    error('Old XDF cannot enter concatenation:\n%s', ...
        xdfPath);
end

if isfield(EEG,'etc') && ...
        isfield(EEG.etc,'source_metadata')

    metadata = EEG.etc.source_metadata;

    requiredFields = { ...
        'SubjectLabel', ...
        'DayLabel', ...
        'SessionLabel', ...
        'ConditionLabel', ...
        'TaskLabel', ...
        'RunNumber', ...
        'RecordingLabel', ...
        'XDFPath'};

    if all(isfield(metadata,requiredFields))

        metadata.SubjectLabel = ...
            string(metadata.SubjectLabel);

        if ~startsWith(metadata.SubjectLabel,"sub-")
            metadata.SubjectLabel = ...
                "sub-" + metadata.SubjectLabel;
        end

        metadata.DayLabel = string(metadata.DayLabel);
        metadata.SessionLabel = string(metadata.SessionLabel);
        metadata.ConditionLabel = string(metadata.ConditionLabel);
        metadata.TaskLabel = string(metadata.TaskLabel);
        metadata.XDFPath = string(xdfPath);

        resolvedRunNumber = ...
            numeric_column_local(metadata.RunNumber);

        if numel(resolvedRunNumber) ~= 1 || ...
                ~isfinite(resolvedRunNumber)

            error('Invalid run metadata.');
        end

        metadata.RunNumber = resolvedRunNumber;

        if ~ismember(metadata.RunNumber,[1 2])
            error('Only run-001/run-002 accepted.');
        end

        metadata.RecordingLabel = ...
            metadata.SubjectLabel + "_" + ...
            metadata.DayLabel + "_" + ...
            metadata.SessionLabel + "_" + ...
            compose("run-%03d",metadata.RunNumber);

        return;
    end
end

metadata = parse_xdf_source_metadata_local(xdfPath);

end

function metadata = ...
        parse_xdf_source_metadata_local(xdfPath)

[~,baseName,extension] = ...
    fileparts(char(xdfPath));

fullName = string([baseName extension]);

if ~isempty(regexpi( ...
        char(fullName), ...
        '_old\d*\.xdf$', ...
        'once'))

    error('Old XDF cannot enter concatenation.');
end

token = regexp( ...
    baseName, ...
    ['^sub-(?<subject>.+?)_' ...
     '(?<day>day\d+)_' ...
     'ses-(?<session>.+?)_' ...
     'task-(?<task>.+?)_' ...
     'run-(?<run>\d+)_' ...
     'eeg$'], ...
    'names', ...
    'once');

if isempty(token)
    error('Could not parse XDF metadata:\n%s',xdfPath);
end

runNumber = str2double(token.run);

if ~ismember(runNumber,[1 2])
    error('Only run-001/run-002 accepted.');
end

metadata = struct();

metadata.SubjectLabel = ...
    "sub-" + string(token.subject);

metadata.DayLabel = string(token.day);

metadata.SessionLabel = ...
    "ses-" + string(token.session);

metadata.ConditionLabel = ...
    string(token.session);

metadata.TaskLabel = ...
    string(token.task);

metadata.RunNumber = runNumber;

metadata.RecordingLabel = ...
    metadata.SubjectLabel + "_" + ...
    metadata.DayLabel + "_" + ...
    metadata.SessionLabel + "_" + ...
    compose("run-%03d",runNumber);

metadata.XDFPath = string(xdfPath);

end

function EEG = ...
        add_source_metadata_to_events( ...
            EEG,metadata,sourceIndex)

for iEvent = 1:numel(EEG.event)

    EEG.event(iEvent).subject_label = ...
        char(metadata.SubjectLabel);

    EEG.event(iEvent).day_label = ...
        char(metadata.DayLabel);

    EEG.event(iEvent).session_label = ...
        char(metadata.SessionLabel);

    EEG.event(iEvent).condition_label = ...
        char(metadata.ConditionLabel);

    EEG.event(iEvent).task_label = ...
        char(metadata.TaskLabel);

    EEG.event(iEvent).run_number = ...
        metadata.RunNumber;

    EEG.event(iEvent).source_xdf = ...
        char(metadata.XDFPath);

    EEG.event(iEvent).source_recording = ...
        char(metadata.RecordingLabel);

    EEG.event(iEvent).source_recording_index = ...
        sourceIndex;
end

end

function EEG = ...
        add_recording_start_event( ...
            EEG,metadata,sourceIndex)

iEvent = numel(EEG.event)+1;

EEG.event(iEvent).type = 'recording_start';
EEG.event(iEvent).latency = 1;
EEG.event(iEvent).duration = 0;

EEG.event(iEvent).subject_label = ...
    char(metadata.SubjectLabel);

EEG.event(iEvent).day_label = ...
    char(metadata.DayLabel);

EEG.event(iEvent).session_label = ...
    char(metadata.SessionLabel);

EEG.event(iEvent).condition_label = ...
    char(metadata.ConditionLabel);

EEG.event(iEvent).task_label = ...
    char(metadata.TaskLabel);

EEG.event(iEvent).run_number = ...
    metadata.RunNumber;

EEG.event(iEvent).source_xdf = ...
    char(metadata.XDFPath);

EEG.event(iEvent).source_recording = ...
    char(metadata.RecordingLabel);

EEG.event(iEvent).source_recording_index = ...
    sourceIndex;

end

function EEG = ...
        normalize_merged_event_metadata( ...
            EEG,sourceManifest)

requiredTextFields = { ...
    'subject_label', ...
    'day_label', ...
    'session_label', ...
    'condition_label', ...
    'task_label', ...
    'source_xdf', ...
    'source_recording'};

for iEvent = 1:numel(EEG.event)

    for iField = 1:numel(requiredTextFields)

        fieldName = requiredTextFields{iField};

        if ~isfield(EEG.event,fieldName) || ...
                ~has_nonempty_event_text_value( ...
                EEG.event(iEvent).(fieldName))

            EEG.event(iEvent).(fieldName) = '';
        end
    end

    if ~isfield(EEG.event,'run_number') || ...
            isempty(EEG.event(iEvent).run_number)

        EEG.event(iEvent).run_number = NaN;
    end

    if ~isfield(EEG.event,'source_recording_index') || ...
            isempty(EEG.event(iEvent).source_recording_index)

        EEG.event(iEvent).source_recording_index = NaN;
    end

    currentType = ...
        event_type_strings(EEG.event(iEvent));

    if currentType == "boundary" && ...
            ~has_nonempty_event_text_value( ...
            EEG.event(iEvent).source_recording)

        EEG.event(iEvent).source_recording = ...
            'dataset_join_boundary';
    end
end

expectedJoinLatencies = ...
    double( ...
    sourceManifest.EndSampleInMergedEEG(1:end-1)) + 0.5;

allEventTypes = ...
    event_type_strings(EEG.event);

allEventLatencies = ...
    double([EEG.event.latency])';

for iJoin = 1:numel(expectedJoinLatencies)

    matchingBoundary = find( ...
        allEventTypes == "boundary" & ...
        abs( ...
        allEventLatencies - ...
        expectedJoinLatencies(iJoin)) <= 1e-6);

    if numel(matchingBoundary) ~= 1

        error( ...
            'Expected one join boundary at latency %.9g.', ...
            expectedJoinLatencies(iJoin));
    end

    eventIndex = matchingBoundary(1);

    EEG.event(eventIndex).source_recording = ...
        'dataset_join_boundary';

    EEG.event(eventIndex).source_recording_index = ...
        NaN;

    if isfield(EEG.event,'mapping_status')

        EEG.event(eventIndex).mapping_status = ...
            'dataset_join_boundary';
    end
end

end

function tf = has_nonempty_event_text_value(rawValue)

if iscell(rawValue)

    if isempty(rawValue)
        tf = false;
        return;
    end

    rawValue = rawValue{1};
end

if ischar(rawValue) || ...
        isstring(rawValue) || ...
        iscategorical(rawValue)

    textValue = string(rawValue);

    tf = ...
        ~isempty(textValue) && ...
        any(~ismissing(textValue) & ...
        strlength(strtrim(textValue)) > 0);

else

    tf = false;
end

end

function validate_merged_subject_eeg( ...
        EEG,expectedSourceCount)

if EEG.trials ~= 1 || ...
        EEG.nbchan ~= 64 || ...
        abs(double(EEG.srate)-500) > 1e-6

    error('Merged EEG failed basic structure QC.');
end

if ~channel_locations_complete(EEG.chanlocs)
    error('Merged EEG channel locations incomplete.');
end

if any(~isfinite(double(EEG.data(:))))
    error('Merged EEG contains NaN/Inf.');
end

eventTypes = event_type_strings(EEG.event);

requiredGaitEventTypes = ...
    ["RHS","RTO","LHS","LTO"];

missingGaitEventTypes = ...
    requiredGaitEventTypes( ...
    ~ismember( ...
    requiredGaitEventTypes, ...
    eventTypes));

if ~isempty(missingGaitEventTypes)
    error('Merged EEG missing gait event types.');
end

recordingStartCount = ...
    sum(eventTypes=="recording_start");

if recordingStartCount ~= expectedSourceCount
    error('Incorrect number of recording_start events.');
end

recordingStartIndices = ...
    event_numeric_field_values( ...
    EEG.event(eventTypes=="recording_start"), ...
    'source_recording_index');

if numel(recordingStartIndices) ~= expectedSourceCount || ...
        ~isequal( ...
        sort(recordingStartIndices(:))', ...
        1:expectedSourceCount)

    error('recording_start indices invalid.');
end

gaitEventSourceIndices = ...
    event_numeric_field_values( ...
    EEG.event(ismember( ...
    eventTypes, ...
    requiredGaitEventTypes)), ...
    'source_recording_index');

if any(~isfinite(gaitEventSourceIndices)) || ...
        any(gaitEventSourceIndices < 1) || ...
        any(gaitEventSourceIndices > expectedSourceCount)

    error('Gait event source index invalid.');
end

expectedJoinBoundaries = ...
    max(0,expectedSourceCount-1);

boundarySources = ...
    event_text_field_values( ...
    EEG.event(eventTypes=="boundary"), ...
    'source_recording');

joinBoundaryCount = ...
    sum(boundarySources=="dataset_join_boundary");

if joinBoundaryCount ~= expectedJoinBoundaries
    error('Incorrect dataset-join boundary count.');
end

end

function eventTypes = event_type_strings(events)

if isempty(events)
    eventTypes = strings(0,1);
    return;
end

eventTypes = strings(numel(events),1);

for iEvent = 1:numel(events)

    rawType = events(iEvent).type;

    if isnumeric(rawType)
        eventTypes(iEvent) = string(rawType);

    elseif iscell(rawType) && ~isempty(rawType)
        eventTypes(iEvent) = string(rawType{1});

    else
        eventTypes(iEvent) = string(rawType);
    end
end

end

function values = ...
        event_text_field_values(events,fieldName)

values = strings(numel(events),1);

if isempty(events) || ~isfield(events,fieldName)
    return;
end

for iEvent = 1:numel(events)

    rawValue = events(iEvent).(fieldName);

    if iscell(rawValue) && ~isempty(rawValue)
        rawValue = rawValue{1};
    end

    if ~isempty(rawValue)
        values(iEvent) = string(rawValue);
    end
end

end

function values = ...
        event_numeric_field_values(events,fieldName)

values = nan(numel(events),1);

if isempty(events) || ~isfield(events,fieldName)
    return;
end

for iEvent = 1:numel(events)

    rawValue = events(iEvent).(fieldName);

    if iscell(rawValue) && ~isempty(rawValue)
        rawValue = rawValue{1};
    end

    if isnumeric(rawValue) || islogical(rawValue)

        if ~isempty(rawValue)
            values(iEvent) = double(rawValue(1));
        end

    elseif ~isempty(rawValue)

        values(iEvent) = str2double(string(rawValue));
    end
end

end

%% Signature build

function signature = ...
        build_source_input_signature(sourceSetPaths)

sourceSetPaths = ...
    sort(string(sourceSetPaths(:)));

parts = strings(numel(sourceSetPaths),1);

for iFile = 1:numel(sourceSetPaths)

    setPath = string(sourceSetPaths(iFile));
    setInfo = dir(setPath);

    if isempty(setInfo)
        error('Source SET missing:\n%s',setPath);
    end

    [setFolder,setBase,~] = ...
        fileparts(char(setPath));

    fdtPath = fullfile( ...
        setFolder, ...
        [setBase '.fdt']);

    fdtPart = "";

    if isfile(fdtPath)

        fdtInfo = dir(fdtPath);

        fdtPart = compose( ...
            "|fdt=%d@%.12f", ...
            fdtInfo.bytes, ...
            fdtInfo.datenum);
    end

    parts(iFile) = ...
        string(setPath) + ...
        compose( ...
        "|set=%d@%.12f", ...
        setInfo.bytes, ...
        setInfo.datenum) + ...
        fdtPart;
end

signature = ...
    "raw_xdf_eeg_lsl_chronological_merge_v5||" + ...
    strjoin(parts,"||");

end

function signature = ...
        build_continuous_input_signature(sourceManifest, EEG)

% This signature answers a different question from
% SubjectInputSignature. SubjectInputSignature changes whenever a mapped
% source .set is regenerated, including an event-only update. The
% continuous signature changes only when the source XDF identity/order,
% sample layout, sampling rate, or channel layout changes.

nSources = height(sourceManifest);
parts = strings(nSources, 1);

for iSource = 1:nSources

    xdfPath = string(sourceManifest.XDFPath(iSource));
    xdfInfo = dir(xdfPath);

    if isempty(xdfInfo)
        error(['Cannot build the continuous-input signature because ' ...
            'the source XDF is missing:\n%s'], xdfPath);
    end

    parts(iSource) = compose( ...
        ['%d|%s|xdf=%d@%.12f|start=%d|end=%d|samples=%d|' ...
         'condition=%s|run=%g'], ...
        double(sourceManifest.SourceIndex(iSource)), ...
        xdfPath, ...
        xdfInfo.bytes, ...
        xdfInfo.datenum, ...
        double(sourceManifest.StartSampleInMergedEEG(iSource)), ...
        double(sourceManifest.EndSampleInMergedEEG(iSource)), ...
        double(sourceManifest.SampleCount(iSource)), ...
        string(sourceManifest.ConditionLabel(iSource)), ...
        double(sourceManifest.RunNumber(iSource)));
end

channelLabels = strjoin(string({EEG.chanlocs.labels}), '|');

signature = ...
    "continuous_xdf_chronological_layout_v1" + ...
    "||nbchan=" + string(double(EEG.nbchan)) + ...
    "||srate=" + compose('%.15g', double(EEG.srate)) + ...
    "||pnts=" + string(double(EEG.pnts)) + ...
    "||channels=" + channelLabels + ...
    "||" + strjoin(parts, "||");

end

function summary = ...
        build_subject_summary( ...
            subjectLabel, ...
            mergedSetPath, ...
            manifestFile, ...
            sourceManifest, ...
            EEG, ...
            sourceInputSignature, ...
            mergeStatus)

[bidsSubject,processingSessionLabel] = ...
    make_subject_processing_labels(subjectLabel);

eventTypes = event_type_strings(EEG.event);

DoImport = 1;

XdfPath = strjoin( ...
    string(sourceManifest.XDFPath), ...
    " | ");

[~,mergedBase,mergedExtension] = ...
    fileparts(mergedSetPath);

FileName = string([mergedBase mergedExtension]);

BidsSubject = bidsSubject;
BidsSession = processingSessionLabel;
RunNumber = NaN;

EEGStreamName = "LiveAmpSN-102108-1139";

RawSetPath = string(mergedSetPath);
RawSetStatus = "OK_subject_level_merged";

RecommendedDoPreprocess = 1;
DoPreprocess = 1;

SubjectLabel = string(subjectLabel);
SubjectInputSignature = string(sourceInputSignature);
ContinuousInputSignature = ...
    build_continuous_input_signature(sourceManifest, EEG);

SourceRecordingCount = height(sourceManifest);
SampleCount = double(EEG.pnts);

MappedGaitEventCount = sum( ...
    ismember( ...
    eventTypes, ...
    ["RHS","RTO","LHS","LTO"]));

BoundaryEventCount = ...
    sum(eventTypes=="boundary");

ChannelCount = double(EEG.nbchan);
SamplingRate = double(EEG.srate);

DurationSec = ...
    double(EEG.pnts)/double(EEG.srate);

MergeStatus = string(mergeStatus);
ManifestPath = string(manifestFile);
MergeDate = current_time_text;
EventUpdateCompatibility = "not_yet_compared_with_previous_table_row";

summary = table( ...
    DoImport, ...
    XdfPath, ...
    FileName, ...
    BidsSubject, ...
    BidsSession, ...
    RunNumber, ...
    EEGStreamName, ...
    RawSetPath, ...
    RawSetStatus, ...
    RecommendedDoPreprocess, ...
    DoPreprocess, ...
    SubjectLabel, ...
    SubjectInputSignature, ...
    ContinuousInputSignature, ...
    SourceRecordingCount, ...
    SampleCount, ...
    MappedGaitEventCount, ...
    BoundaryEventCount, ...
    ChannelCount, ...
    SamplingRate, ...
    DurationSec, ...
    MergeStatus, ...
    ManifestPath, ...
    MergeDate, ...
    EventUpdateCompatibility);

end

function [bidsSubject,processingSessionLabel] = ...
        make_subject_processing_labels(subjectLabel)

token = regexp( ...
    char(subjectLabel), ...
    '^sub-Pilot(?<pilot>\d+)_(?<subject>\d+)$', ...
    'names', ...
    'once');

if isempty(token)
    error('Invalid subject label: %s',subjectLabel);
end

bidsSubject = str2double(token.subject);

processingSessionLabel = ...
    "Pilot" + ...
    string(token.pilot) + ...
    "p" + ...
    string(token.subject) + ...
    "AllSessions";

end

function update_subject_processing_table(newRow,tableFile)

baseVariables = newRow.Properties.VariableNames;

if ~isfile(tableFile)
    writetable(newRow,tableFile);
    return;
end

oldTable = read_csv_with_string_text(tableFile);

if ~ismember( ...
        'SubjectLabel', ...
        oldTable.Properties.VariableNames)

    backupFile = char( ...
        string(tableFile) + ...
        ".incompatible_backup_" + ...
        string(datetime( ...
        'now', ...
        'Format','yyyyMMdd_HHmmss')) + ...
        ".csv");

    copyfile(tableFile,backupFile);

    writetable(newRow,tableFile);

    return;
end

oldTable.SubjectLabel = ...
    string(oldTable.SubjectLabel);

if ismember( ...
        'SubjectInputSignature', ...
        oldTable.Properties.VariableNames)

    oldTable.SubjectInputSignature = ...
        string(oldTable.SubjectInputSignature);
end

matchingRows = ...
    find(oldTable.SubjectLabel == newRow.SubjectLabel);

if numel(matchingRows) > 1
    error(['The subject-level processing table contains duplicate rows ' ...
        'for %s. Resolve the duplicate rows before concatenation.'], ...
        newRow.SubjectLabel);
end

% Keep a recoverable copy before replacing an existing participant row.
% This is intentionally done before any downstream-state decision.
if ~isempty(matchingRows)
    backupFile = char( ...
        string(tableFile) + ...
        ".before_subject_update_" + ...
        string(datetime('now', 'Format','yyyyMMdd_HHmmss_SSS')) + ...
        ".csv");
    copyfile(tableFile, backupFile);
end

oldVariableNames = ...
    oldTable.Properties.VariableNames;

for iVariable = 1:numel(baseVariables)

    variableName = baseVariables{iVariable};

    if ~ismember(variableName,oldVariableNames)

        oldTable.(variableName) = ...
            make_missing_column_like( ...
            newRow.(variableName), ...
            height(oldTable));
    end
end

oldVariableNames = ...
    oldTable.Properties.VariableNames;

for iVariable = 1:numel(oldVariableNames)

    variableName = oldVariableNames{iVariable};

    if ~ismember( ...
            variableName, ...
            newRow.Properties.VariableNames)

        newRow.(variableName) = ...
            make_missing_column_like( ...
            oldTable.(variableName), ...
            1);
    end
end

newRow = ...
    newRow(:,oldTable.Properties.VariableNames);

if ~isempty(matchingRows)

    previousRow = matchingRows(1);

    signatureUnchanged = false;

    if ismember('SubjectInputSignature', ...
            oldTable.Properties.VariableNames)
        signatureUnchanged = ...
            string(oldTable.SubjectInputSignature(previousRow)) == ...
            string(newRow.SubjectInputSignature);
    end

    continuousLayoutCompatible = ...
        continuous_layout_compatible_local( ...
            oldTable, newRow, previousRow);

    preserveDownstream = ...
        signatureUnchanged || continuousLayoutCompatible;

    if signatureUnchanged
        newRow.EventUpdateCompatibility(1) = ...
            "identical_source_signature_downstream_preserved";
    elseif continuousLayoutCompatible
        newRow.EventUpdateCompatibility(1) = ...
            "event_only_compatible_downstream_preserved";
    else
        newRow.EventUpdateCompatibility(1) = ...
            "continuous_layout_changed_downstream_reset";
    end

    if preserveDownstream

        columnsToPreserve = setdiff( ...
            oldTable.Properties.VariableNames, ...
            baseVariables, ...
            'stable');

        if ismember('DoPreprocess',baseVariables)
            columnsToPreserve = ...
                [{'DoPreprocess'},columnsToPreserve];
        end

        for iColumn = 1:numel(columnsToPreserve)

            columnName = ...
                columnsToPreserve{iColumn};

            newRow.(columnName)(1,:) = ...
                oldTable.(columnName)(previousRow,:);
        end
    end
else
    newRow.EventUpdateCompatibility(1) = ...
        "new_subject_no_previous_downstream_state";
end

oldTable(matchingRows,:) = [];

updatedTable = [oldTable;newRow];

if ismember( ...
        'BidsSubject', ...
        updatedTable.Properties.VariableNames)

    updatedTable = ...
        sortrows(updatedTable,'BidsSubject');
end

writetable(updatedTable,tableFile);

end

function compatible = continuous_layout_compatible_local( ...
        oldTable, newRow, previousRow)

compatible = false;

% This signature depends on source XDF identity/order, sample layout, sampling
% rate, and channels, but deliberately not on gait-event latencies/counts.
if ismember('ContinuousInputSignature', ...
        oldTable.Properties.VariableNames) && ...
        ismember('ContinuousInputSignature', ...
        newRow.Properties.VariableNames)

    oldSignature = strtrim(string( ...
        oldTable.ContinuousInputSignature(previousRow)));
    newSignature = strtrim(string( ...
        newRow.ContinuousInputSignature(1)));

    if strlength(oldSignature) > 0 && strlength(newSignature) > 0
        compatible = oldSignature == newSignature;
        return;
    end
end

% These fields together establish that the same recordings remain in the same merged
% continuous sample layout. MappedGaitEventCount is intentionally absent.
requiredStringFields = {'SubjectLabel','BidsSession','XdfPath'};
requiredNumericFields = { ...
    'SourceRecordingCount', ...
    'BoundaryEventCount', ...
    'ChannelCount', ...
    'SamplingRate', ...
    'DurationSec'};

if ~all(ismember(requiredStringFields, ...
        oldTable.Properties.VariableNames)) || ...
        ~all(ismember(requiredStringFields, ...
        newRow.Properties.VariableNames)) || ...
        ~all(ismember(requiredNumericFields, ...
        oldTable.Properties.VariableNames)) || ...
        ~all(ismember(requiredNumericFields, ...
        newRow.Properties.VariableNames))
    return;
end

for k = 1:numel(requiredStringFields)
    fieldName = requiredStringFields{k};
    oldValue = strtrim(string(oldTable.(fieldName)(previousRow)));
    newValue = strtrim(string(newRow.(fieldName)(1)));

    if strlength(oldValue) == 0 || strlength(newValue) == 0 || ...
            ~strcmpi(oldValue, newValue)
        return;
    end
end

for k = 1:numel(requiredNumericFields)
    fieldName = requiredNumericFields{k};
    oldValue = numeric_column_local( ...
        oldTable.(fieldName)(previousRow));
    newValue = numeric_column_local(newRow.(fieldName)(1));

    if ~isscalar(oldValue) || ~isscalar(newValue) || ...
            ~isfinite(oldValue) || ~isfinite(newValue)
        return;
    end

    tolerance = max(1e-9, abs(newValue) * 1e-9);
    if abs(oldValue - newValue) > tolerance
        return;
    end
end

compatible = true;

end

function column = ...
        make_missing_column_like(example,numberOfRows)

if isstring(example)

    column = strings( ...
        numberOfRows,size(example,2));

elseif islogical(example)

    column = false( ...
        numberOfRows,size(example,2));

elseif isnumeric(example)

    column = nan( ...
        numberOfRows,size(example,2));

elseif isdatetime(example)

    column = NaT( ...
        numberOfRows,size(example,2));

elseif iscell(example)

    column = cell( ...
        numberOfRows,size(example,2));

elseif iscategorical(example)

    column = repmat( ...
        categorical(missing), ...
        numberOfRows, ...
        size(example,2));

else

    column = strings( ...
        numberOfRows,size(example,2));
end

end

function outputTable = ...
        read_csv_with_string_text(csvFile)

options = detectImportOptions( ...
    csvFile, ...
    'FileType','text', ...
    'Delimiter',',', ...
    'VariableNamingRule','preserve');

textVariables = ...
    options.VariableNames( ...
    ismember( ...
    options.VariableTypes, ...
    {'char','categorical'}));

if ~isempty(textVariables)

    options = setvartype( ...
        options, ...
        textVariables, ...
        'string');
end

outputTable = readtable(csvFile,options);

end

function values = numeric_column_local(values)

if isnumeric(values)

    values = double(values);

elseif islogical(values)

    values = double(values);

else

    textValues = ...
        lower(strtrim(string(values)));

    values = str2double(textValues);

    values(ismember( ...
        textValues, ...
        ["true","yes"])) = 1;

    values(ismember( ...
        textValues, ...
        ["false","no"])) = 0;
end

end

function value = current_time_text

value = string(datetime( ...
    'now', ...
    'TimeZone','local', ...
    'Format','yyyy-MM-dd HH:mm:ss'));

end
