function [eventTable, diagnostics, qcFigure] = ...
        detect_GRF_gait_events( ...
            grfData, ...
            grfTimeStamps, ...
            intervalStartLSLTime, ...
            intervalEndLSLTime, ...
            varargin)
% GOAL
%   Detect RHS, RTO, LHS, and LTO from one accepted GRF walking interval.
%
% METHOD
%   Sum right/left force channels, low-pass filter the signals, remove the
%   low-force baseline, apply hysteresis threshold crossing, enforce contact
%   and stride-duration constraints, and return chronologically sorted events.

p = inputParser;

addRequired(p, 'grfData');
addRequired(p, 'grfTimeStamps');
addRequired(p, 'intervalStartLSLTime');
addRequired(p, 'intervalEndLSLTime');

addParameter(p, 'RightChannels', [1 4 5 8]);
addParameter(p, 'LeftChannels', [2 3 6 7]);
addParameter(p, 'LowpassHz', 15);
addParameter(p, 'ThresholdOn', 0.03);
addParameter(p, 'ThresholdOff', 0.02);
addParameter(p, 'MinimumContactSec', 0.20);
addParameter(p, 'MaximumContactSec', 1.50);
addParameter(p, 'MinimumStrideSec', 0.60);
addParameter(p, 'Plot', true);

parse( ...
    p, ...
    grfData, ...
    grfTimeStamps, ...
    intervalStartLSLTime, ...
    intervalEndLSLTime, ...
    varargin{:});

opt = p.Results;

%% Validate and orient the data

grfData = double(grfData);
grfTimeStamps = double(grfTimeStamps(:)');

if size(grfData, 2) ~= numel(grfTimeStamps) && ...
        size(grfData, 1) == numel(grfTimeStamps)

    grfData = grfData';
end

if size(grfData, 2) ~= numel(grfTimeStamps)
    error([ ...
        'GRF data and timestamps do not have matching sample counts.\n' ...
        'Data size: %d x %d\n' ...
        'Timestamps: %d'], ...
        size(grfData, 1), ...
        size(grfData, 2), ...
        numel(grfTimeStamps));
end

if any(~isfinite(grfTimeStamps)) || ...
        any(diff(grfTimeStamps) <= 0)

    error('GRF timestamps must be finite and strictly increasing.');
end

if ~isscalar(intervalStartLSLTime) || ...
        ~isscalar(intervalEndLSLTime) || ...
        ~isfinite(intervalStartLSLTime) || ...
        ~isfinite(intervalEndLSLTime) || ...
        intervalEndLSLTime <= intervalStartLSLTime

    error('The walking interval must have finite StartLSLTime < EndLSLTime.');
end

rightChannels = double(opt.RightChannels(:)');
leftChannels = double(opt.LeftChannels(:)');

allRequestedChannels = [rightChannels, leftChannels];

if any(allRequestedChannels < 1) || ...
        any(allRequestedChannels > size(grfData, 1)) || ...
        any(allRequestedChannels ~= round(allRequestedChannels))

    error('One or more requested GRF channel indices are invalid.');
end

if ~isempty(intersect(rightChannels, leftChannels))
    error('RightChannels and LeftChannels must not overlap.');
end

if opt.ThresholdOff >= opt.ThresholdOn || ...
        opt.ThresholdOff < 0 || ...
        opt.ThresholdOn <= 0

    error('ThresholdOff must satisfy 0 <= ThresholdOff < ThresholdOn.');
end

%% Select the accepted walking interval using original LSL timestamps

startGRFSample = find( ...
    grfTimeStamps >= intervalStartLSLTime, ...
    1, ...
    'first');

endGRFSample = find( ...
    grfTimeStamps <= intervalEndLSLTime, ...
    1, ...
    'last');

if isempty(startGRFSample) || ...
        isempty(endGRFSample) || ...
        endGRFSample <= startGRFSample

    error('The accepted walking interval does not overlap the GRF stream.');
end

segmentSamples = startGRFSample:endGRFSample;
segmentTimeStamps = grfTimeStamps(segmentSamples);

measuredSrate = ...
    1 / median(diff(segmentTimeStamps));

if ~isfinite(measuredSrate) || ...
        measuredSrate <= 2 * opt.LowpassHz

    error([ ...
        'The measured GRF sampling rate %.6g Hz is not valid for a ' ...
        '%.6g Hz low-pass filter.'], ...
        measuredSrate, ...
        opt.LowpassHz);
end

%% Sum the four sensors belonging to each side

rightRaw = sum( ...
    grfData(rightChannels, segmentSamples), ...
    1, ...
    'omitnan')';

leftRaw = sum( ...
    grfData(leftChannels, segmentSamples), ...
    1, ...
    'omitnan')';

if any(~isfinite(rightRaw)) || ...
        any(~isfinite(leftRaw))

    error('The summed left/right GRF signals contain non-finite values.');
end

%% Low-pass filter

filterMethod = "";

if exist('butter', 'file') == 2 && ...
        exist('filtfilt', 'file') == 2

    [filterB, filterA] = butter( ...
        4, ...
        opt.LowpassHz / (measuredSrate / 2), ...
        'low');

    rightFiltered = filtfilt( ...
        filterB, ...
        filterA, ...
        rightRaw);

    leftFiltered = filtfilt( ...
        filterB, ...
        filterA, ...
        leftRaw);

    filterMethod = "4th_order_zero_phase_Butterworth";

else

    warning([ ...
        'butter/filtfilt could not be found. ' ...
        'Using a moving-mean fallback filter.']);

    smoothingSamples = max( ...
        1, ...
        round(measuredSrate / opt.LowpassHz));

    rightFiltered = smoothdata( ...
        rightRaw, ...
        'movmean', ...
        smoothingSamples);

    leftFiltered = smoothdata( ...
        leftRaw, ...
        'movmean', ...
        smoothingSamples);

    filterMethod = "moving_mean_fallback";
end

%% Remove the low-force baseline and determine side-specific thresholds

rightBaseline = robust_quantile(rightFiltered, 0.05);
leftBaseline = robust_quantile(leftFiltered, 0.05);

rightContactSignal = max( ...
    rightFiltered - rightBaseline, ...
    0);

leftContactSignal = max( ...
    leftFiltered - leftBaseline, ...
    0);

rightRobustPeak = robust_quantile( ...
    rightContactSignal, ...
    0.99);

leftRobustPeak = robust_quantile( ...
    leftContactSignal, ...
    0.99);

if rightRobustPeak <= 0 || ...
        leftRobustPeak <= 0

    error('A positive robust GRF range could not be determined.');
end

rightThresholdOn = ...
    opt.ThresholdOn * rightRobustPeak;

rightThresholdOff = ...
    opt.ThresholdOff * rightRobustPeak;

leftThresholdOn = ...
    opt.ThresholdOn * leftRobustPeak;

leftThresholdOff = ...
    opt.ThresholdOff * leftRobustPeak;

%% Detect contact intervals

rightEvents = detect_one_side( ...
    rightContactSignal, ...
    segmentTimeStamps, ...
    startGRFSample, ...
    rightThresholdOn, ...
    rightThresholdOff, ...
    opt.MinimumContactSec, ...
    opt.MaximumContactSec, ...
    opt.MinimumStrideSec);

leftEvents = detect_one_side( ...
    leftContactSignal, ...
    segmentTimeStamps, ...
    startGRFSample, ...
    leftThresholdOn, ...
    leftThresholdOff, ...
    opt.MinimumContactSec, ...
    opt.MaximumContactSec, ...
    opt.MinimumStrideSec);

%% Build the event table

rightHSRows = build_event_rows( ...
    "RHS", ...
    "Right", ...
    rightEvents.hsSegmentSamples, ...
    rightEvents.hsGRFSamples, ...
    rightEvents.hsTimeStamps, ...
    segmentTimeStamps(1));

rightTORows = build_event_rows( ...
    "RTO", ...
    "Right", ...
    rightEvents.toSegmentSamples, ...
    rightEvents.toGRFSamples, ...
    rightEvents.toTimeStamps, ...
    segmentTimeStamps(1));

leftHSRows = build_event_rows( ...
    "LHS", ...
    "Left", ...
    leftEvents.hsSegmentSamples, ...
    leftEvents.hsGRFSamples, ...
    leftEvents.hsTimeStamps, ...
    segmentTimeStamps(1));

leftTORows = build_event_rows( ...
    "LTO", ...
    "Left", ...
    leftEvents.toSegmentSamples, ...
    leftEvents.toGRFSamples, ...
    leftEvents.toTimeStamps, ...
    segmentTimeStamps(1));

eventTable = [ ...
    rightHSRows; ...
    rightTORows; ...
    leftHSRows; ...
    leftTORows];

eventTable = sortrows( ...
    eventTable, ...
    'LSLTime');

%% Diagnostics

rightStrideSec = diff( ...
    rightEvents.hsTimeStamps);

leftStrideSec = diff( ...
    leftEvents.hsTimeStamps);

[alternationFraction, firstHS, lastHS] = ...
    compute_hs_alternation( ...
        rightEvents.hsTimeStamps, ...
        leftEvents.hsTimeStamps);

diagnostics = struct;

diagnostics.measuredSrate = measuredSrate;
diagnostics.filterMethod = filterMethod;
diagnostics.lowpassHz = opt.LowpassHz;

diagnostics.rightChannels = rightChannels;
diagnostics.leftChannels = leftChannels;

diagnostics.intervalStartLSLTime = ...
    segmentTimeStamps(1);

diagnostics.intervalEndLSLTime = ...
    segmentTimeStamps(end);

diagnostics.startGRFSample = startGRFSample;
diagnostics.endGRFSample = endGRFSample;

diagnostics.rightBaseline = rightBaseline;
diagnostics.leftBaseline = leftBaseline;
diagnostics.rightRobustPeak = rightRobustPeak;
diagnostics.leftRobustPeak = leftRobustPeak;

diagnostics.rightThresholdOn = rightThresholdOn;
diagnostics.rightThresholdOff = rightThresholdOff;
diagnostics.leftThresholdOn = leftThresholdOn;
diagnostics.leftThresholdOff = leftThresholdOff;

diagnostics.nRHS = numel(rightEvents.hsTimeStamps);
diagnostics.nRTO = numel(rightEvents.toTimeStamps);
diagnostics.nLHS = numel(leftEvents.hsTimeStamps);
diagnostics.nLTO = numel(leftEvents.toTimeStamps);

diagnostics.medianRightStrideSec = ...
    safe_median(rightStrideSec);

diagnostics.medianLeftStrideSec = ...
    safe_median(leftStrideSec);

diagnostics.alternationFraction = ...
    alternationFraction;

diagnostics.firstHeelStrike = firstHS;
diagnostics.lastHeelStrike = lastHS;

diagnostics.segmentTimeStamps = segmentTimeStamps;
diagnostics.rightRaw = rightRaw;
diagnostics.leftRaw = leftRaw;
diagnostics.rightFiltered = rightContactSignal;
diagnostics.leftFiltered = leftContactSignal;

fprintf('\n====================================================\n');
fprintf('GRF GAIT EVENT DETECTION\n');
fprintf('====================================================\n');
fprintf('Measured GRF rate: %.6f Hz\n', measuredSrate);
fprintf('Walking interval: %.6f to %.6f LSL s\n', ...
    segmentTimeStamps(1), segmentTimeStamps(end));
fprintf('RHS / RTO: %d / %d\n', ...
    diagnostics.nRHS, diagnostics.nRTO);
fprintf('LHS / LTO: %d / %d\n', ...
    diagnostics.nLHS, diagnostics.nLTO);
fprintf('Median right stride: %.4f s\n', ...
    diagnostics.medianRightStrideSec);
fprintf('Median left stride:  %.4f s\n', ...
    diagnostics.medianLeftStrideSec);
fprintf('HS alternation fraction: %.4f\n', ...
    diagnostics.alternationFraction);

if abs(diagnostics.nRHS - diagnostics.nLHS) > 1
    warning('Right and left heel-strike counts differ by more than one.');
end

if isfinite(alternationFraction) && ...
        alternationFraction < 0.90

    warning([ ...
        'Heel-strike alternation is below 0.90. ' ...
        'Inspect the QC figure before accepting the result.']);
end

%% QC figure

qcFigure = gobjects(0);

if opt.Plot

    qcFigure = create_qc_figure( ...
        segmentTimeStamps, ...
        rightContactSignal, ...
        leftContactSignal, ...
        rightThresholdOn, ...
        rightThresholdOff, ...
        leftThresholdOn, ...
        leftThresholdOff, ...
        rightEvents, ...
        leftEvents);
end
end

function sideEvents = detect_one_side( ...
        signal, ...
        timeStamps, ...
        firstOriginalSample, ...
        thresholdOn, ...
        thresholdOff, ...
        minimumContactSec, ...
        maximumContactSec, ...
        minimumStrideSec)

signal = double(signal(:));
timeStamps = double(timeStamps(:));

contact = false(size(signal));
contactState = false;

for iSample = 1:numel(signal)

    if ~contactState && ...
            signal(iSample) >= thresholdOn

        contactState = true;

    elseif contactState && ...
            signal(iSample) <= thresholdOff

        contactState = false;
    end

    contact(iSample) = contactState;
end

contactTransitions = diff([ ...
    false; ...
    contact; ...
    false]);

contactStarts = find(contactTransitions == 1);
% Toe-off is assigned to the first sample at or below ThresholdOff: the
% actual falling-threshold crossing, not the preceding in-contact sample.
contactEnds = find(contactTransitions == -1);

if isempty(contactStarts)
    sideEvents = empty_side_events;
    return;
end

% A contact already active at the first selected sample does not provide
% an observable heel strike. Likewise, a contact continuing beyond the
% last sample does not provide an observable toe off.
completeContacts = ...
    contactStarts > 1 & ...
    contactEnds <= numel(signal);

contactStarts = contactStarts(completeContacts);
contactEnds = contactEnds(completeContacts);

if isempty(contactStarts)
    sideEvents = empty_side_events;
    return;
end

contactDurationSec = ...
    timeStamps(contactEnds) - ...
    timeStamps(contactStarts);

validDuration = ...
    contactDurationSec >= minimumContactSec & ...
    contactDurationSec <= maximumContactSec;

contactStarts = contactStarts(validDuration);
contactEnds = contactEnds(validDuration);

if isempty(contactStarts)
    sideEvents = empty_side_events;
    return;
end

% Remove implausibly close consecutive contacts on the same side.
keepContact = true(size(contactStarts));
lastKeptContact = 1;

for iContact = 2:numel(contactStarts)

    timeSincePreviousHS = ...
        timeStamps(contactStarts(iContact)) - ...
        timeStamps(contactStarts(lastKeptContact));

    if timeSincePreviousHS < minimumStrideSec
        keepContact(iContact) = false;
    else
        lastKeptContact = iContact;
    end
end

contactStarts = contactStarts(keepContact);
contactEnds = contactEnds(keepContact);

sideEvents = struct;

sideEvents.hsSegmentSamples = ...
    contactStarts;

sideEvents.toSegmentSamples = ...
    contactEnds;

sideEvents.hsGRFSamples = ...
    firstOriginalSample + contactStarts - 1;

sideEvents.toGRFSamples = ...
    firstOriginalSample + contactEnds - 1;

sideEvents.hsTimeStamps = ...
    timeStamps(contactStarts);

sideEvents.toTimeStamps = ...
    timeStamps(contactEnds);
end

function sideEvents = empty_side_events

sideEvents = struct;

sideEvents.hsSegmentSamples = zeros(0, 1);
sideEvents.toSegmentSamples = zeros(0, 1);

sideEvents.hsGRFSamples = zeros(0, 1);
sideEvents.toGRFSamples = zeros(0, 1);

sideEvents.hsTimeStamps = zeros(0, 1);
sideEvents.toTimeStamps = zeros(0, 1);
end

function eventRows = build_event_rows( ...
        eventType, ...
        side, ...
        segmentSamples, ...
        grfSamples, ...
        timeStamps, ...
        segmentStartTime)

nEvents = numel(timeStamps);

eventRows = table( ...
    repmat(string(eventType), nEvents, 1), ...
    repmat(string(side), nEvents, 1), ...
    double(segmentSamples(:)), ...
    double(grfSamples(:)), ...
    double(timeStamps(:)), ...
    double(timeStamps(:) - segmentStartTime), ...
    'VariableNames', { ...
        'EventType', ...
        'Side', ...
        'SegmentSample', ...
        'GRFSample', ...
        'LSLTime', ...
        'TimeFromSegmentStartSec'});
end

function value = robust_quantile(data, probability)

data = double(data(:));
data = data(isfinite(data));

if isempty(data)
    value = NaN;
    return;
end

data = sort(data);

index = round( ...
    probability * numel(data));

index = min( ...
    max(index, 1), ...
    numel(data));

value = data(index);
end

function value = safe_median(data)

data = double(data(:));
data = data(isfinite(data));

if isempty(data)
    value = NaN;
else
    value = median(data);
end
end

function [fraction, firstHS, lastHS] = ...
        compute_hs_alternation( ...
            rightHSTimeStamps, ...
            leftHSTimeStamps)

allTimes = [ ...
    double(rightHSTimeStamps(:)); ...
    double(leftHSTimeStamps(:))];

allSides = [ ...
    repmat("Right", numel(rightHSTimeStamps), 1); ...
    repmat("Left", numel(leftHSTimeStamps), 1)];

if isempty(allTimes)
    fraction = NaN;
    firstHS = "";
    lastHS = "";
    return;
end

[allTimes, sortOrder] = sort(allTimes); %#ok<ASGLU>
allSides = allSides(sortOrder);

firstHS = allSides(1);
lastHS = allSides(end);

if numel(allSides) < 2
    fraction = NaN;
else
    fraction = mean( ...
        allSides(2:end) ~= ...
        allSides(1:end-1));
end
end

function qcFigure = create_qc_figure( ...
        timeStamps, ...
        rightSignal, ...
        leftSignal, ...
        rightThresholdOn, ...
        rightThresholdOff, ...
        leftThresholdOn, ...
        leftThresholdOff, ...
        rightEvents, ...
        leftEvents)

relativeTime = ...
    double(timeStamps(:)) - ...
    double(timeStamps(1));

rightColor = [0.00 0.75 1.00];
leftColor = [1.00 0.25 0.70];
hsColor = [0.10 0.80 0.25];
toColor = [1.00 0.75 0.00];

qcFigure = figure( ...
    'Color', ...
    'w', ...
    'Name', ...
    'GRF gait-event detection QC', ...
    'NumberTitle', ...
    'off', ...
    'Visible', ...
    figure_visibility_for_current_mode, ...
    'Position', ...
    [50 50 1500 900]);

qcLayout = tiledlayout( ...
    qcFigure, ...
    3, ...
    1, ...
    'TileSpacing', ...
    'compact', ...
    'Padding', ...
    'compact');

rightAxes = nexttile(qcLayout, 1);

plot( ...
    rightAxes, ...
    relativeTime, ...
    rightSignal, ...
    'Color', ...
    rightColor, ...
    'LineWidth', ...
    1.0);

hold(rightAxes, 'on');

yline( ...
    rightAxes, ...
    rightThresholdOn, ...
    '--', ...
    'On', ...
    'Color', ...
    hsColor);

yline( ...
    rightAxes, ...
    rightThresholdOff, ...
    ':', ...
    'Off', ...
    'Color', ...
    toColor);

plot( ...
    rightAxes, ...
    relativeTime(rightEvents.hsSegmentSamples), ...
    rightSignal(rightEvents.hsSegmentSamples), ...
    'v', ...
    'Color', ...
    hsColor, ...
    'MarkerFaceColor', ...
    hsColor, ...
    'MarkerSize', ...
    5);

plot( ...
    rightAxes, ...
    relativeTime(rightEvents.toSegmentSamples), ...
    rightSignal(rightEvents.toSegmentSamples), ...
    '^', ...
    'Color', ...
    toColor, ...
    'MarkerFaceColor', ...
    toColor, ...
    'MarkerSize', ...
    5);

grid(rightAxes, 'on');
ylabel(rightAxes, 'Right GRF');
title(rightAxes, 'Right: RHS and RTO');

leftAxes = nexttile(qcLayout, 2);

plot( ...
    leftAxes, ...
    relativeTime, ...
    leftSignal, ...
    'Color', ...
    leftColor, ...
    'LineWidth', ...
    1.0);

hold(leftAxes, 'on');

yline( ...
    leftAxes, ...
    leftThresholdOn, ...
    '--', ...
    'On', ...
    'Color', ...
    hsColor);

yline( ...
    leftAxes, ...
    leftThresholdOff, ...
    ':', ...
    'Off', ...
    'Color', ...
    toColor);

plot( ...
    leftAxes, ...
    relativeTime(leftEvents.hsSegmentSamples), ...
    leftSignal(leftEvents.hsSegmentSamples), ...
    'v', ...
    'Color', ...
    hsColor, ...
    'MarkerFaceColor', ...
    hsColor, ...
    'MarkerSize', ...
    5);

plot( ...
    leftAxes, ...
    relativeTime(leftEvents.toSegmentSamples), ...
    leftSignal(leftEvents.toSegmentSamples), ...
    '^', ...
    'Color', ...
    toColor, ...
    'MarkerFaceColor', ...
    toColor, ...
    'MarkerSize', ...
    5);

grid(leftAxes, 'on');
ylabel(leftAxes, 'Left GRF');
title(leftAxes, 'Left: LHS and LTO');

bothAxes = nexttile(qcLayout, 3);

plot( ...
    bothAxes, ...
    relativeTime, ...
    rightSignal, ...
    'Color', ...
    rightColor, ...
    'LineWidth', ...
    0.9);

hold(bothAxes, 'on');

plot( ...
    bothAxes, ...
    relativeTime, ...
    leftSignal, ...
    'Color', ...
    leftColor, ...
    'LineWidth', ...
    0.9);

plot( ...
    bothAxes, ...
    relativeTime(rightEvents.hsSegmentSamples), ...
    rightSignal(rightEvents.hsSegmentSamples), ...
    'v', ...
    'Color', ...
    hsColor, ...
    'MarkerFaceColor', ...
    hsColor, ...
    'MarkerSize', ...
    4);

plot( ...
    bothAxes, ...
    relativeTime(leftEvents.hsSegmentSamples), ...
    leftSignal(leftEvents.hsSegmentSamples), ...
    'o', ...
    'Color', ...
    hsColor, ...
    'MarkerFaceColor', ...
    'w', ...
    'MarkerSize', ...
    4);

grid(bothAxes, 'on');

xlabel( ...
    bothAxes, ...
    'Time from accepted interval start (s)');

ylabel(bothAxes, 'GRF above baseline');
title(bothAxes, 'Both sides: heel-strike alternation');

legend( ...
    bothAxes, ...
    { ...
        'Right GRF', ...
        'Left GRF', ...
        'RHS', ...
        'LHS'}, ...
    'Location', ...
    'eastoutside');

linkaxes( ...
    [rightAxes, leftAxes, bothAxes], ...
    'x');
end

function visibility = figure_visibility_for_current_mode

if strcmpi(strtrim( ...
        getenv('GRF_BATCH_UNATTENDED')), '1')
    visibility = 'off';
else
    visibility = 'on';
end
end
