% GOAL
%   Concatenate all Step 04-eligible run-separated EEG recordings for one
%   participant after GRF-derived gait events and project channel locations
%   are present.
%
% APPROACH
%   1. Read the Step 04-updated subject batch-status CSV.
%   2. Use only recordings that passed final gait-EEG QC.
%   3. Verify source EEG structure, channel layout, sampling rate, and events.
%   4. Sort recordings by true source-XDF EEG LSL acquisition time.
%   5. Preserve retained-EEG sample-selection identity.
%   6. Concatenate recordings while preserving source/run event metadata.
%   7. Save the subject-level continuous EEG and source manifest.
%
% USED BY
%   step04_process_subject_grf_eeg.m

function [mergedSetPath, subjectSummary] = ...
        concatenate_subject_grf_eeg(subjectOutputFolder, varargin)

if nargin < 1
    subjectOutputFolder = "";
end

parser = inputParser;

addOptional(parser, 'subjectOutputFolder', subjectOutputFolder, ...
    @(x) ischar(x) || (isstring(x) && isscalar(x)));

addParameter(parser, 'ForceReprocess', false, ...
    @(x) islogical(x) && isscalar(x));

addParameter(parser, 'AllowPartialSubject', false, ...
    @(x) islogical(x) && isscalar(x));

parse(parser, subjectOutputFolder, varargin{:});

subjectOutputFolder = ...
    char(string(parser.Results.subjectOutputFolder));

forceReprocess = ...
    logical(parser.Results.ForceReprocess);

allowPartialSubject = ...
    logical(parser.Results.AllowPartialSubject);

packageFolder = fileparts(mfilename('fullpath'));
scriptsRoot = fileparts(packageFolder);

addpath(scriptsRoot, '-begin');
addpath(fullfile(scriptsRoot, 'config'), '-begin');

P = project_paths();

grfSegmentationFolder = P.grfSegmentationFolder;
subjectLevelEEGFolder = P.subjectLevelEEGFolder;
subjectLevelEEGTableFile = P.subjectLevelEEGTableFile;

if ~isfolder(subjectLevelEEGFolder)
    mkdir(subjectLevelEEGFolder);
end

% All subjects mode

if isempty(strtrim(subjectOutputFolder))

    subjectDirectories = dir(fullfile( ...
        grfSegmentationFolder, ...
        'sub-*'));

    subjectDirectories = ...
        subjectDirectories([subjectDirectories.isdir]);

    if isempty(subjectDirectories)
        error('No subject GRF/EEG output folders found below:\n%s', ...
            grfSegmentationFolder);
    end

    mergedSetPath = strings(0,1);
    subjectSummary = table();

    for iSubject = 1:numel(subjectDirectories)

        currentSubjectFolder = fullfile( ...
            subjectDirectories(iSubject).folder, ...
            subjectDirectories(iSubject).name);

        try

            [currentMergedPath, currentSummary] = ...
                hipexo.concatenate_subject_grf_eeg( ...
                    currentSubjectFolder, ...
                    'ForceReprocess', forceReprocess, ...
                    'AllowPartialSubject', allowPartialSubject);

            mergedSetPath(end+1,1) = ...
                string(currentMergedPath); %#ok<AGROW>

            if isempty(subjectSummary)
                subjectSummary = currentSummary;
            else
                subjectSummary = ...
                    [subjectSummary; currentSummary]; %#ok<AGROW>
            end

        catch currentError

            fprintf(2, ...
                '\nSubject concatenation failed:\n%s\n%s\n', ...
                currentSubjectFolder, ...
                getReport(currentError, ...
                    'extended', ...
                    'hyperlinks', ...
                    'off'));
        end
    end

    if isempty(subjectSummary)
        error('No subject-level EEG dataset was created.');
    end

    return;
end

% Batch status

if ~isfolder(subjectOutputFolder)
    error('Subject output folder does not exist:\n%s', ...
        subjectOutputFolder);
end

batchLogs = dir(fullfile( ...
    subjectOutputFolder, ...
    '*_GRF_EEG_batch_status.csv'));

if numel(batchLogs) ~= 1
    error('Expected exactly one subject batch-status CSV below:\n%s', ...
        subjectOutputFolder);
end

batchLogFile = fullfile( ...
    batchLogs(1).folder, ...
    batchLogs(1).name);

batchStatus = ...
    hipexo.read_csv_with_string_text(batchLogFile);

requiredBatchVariables = { ...
    'Subject', ...
    'SessionFolder', ...
    'XDFPath', ...
    'EEG_LSL_Start', ...
    'EEG_LSL_End', ...
    'EEG_LSL_DurationSec', ...
    'GRF_LSL_Start', ...
    'GRF_LSL_End', ...
    'GRF_LSL_DurationSec', ...
    'GRF_EEG_LSL_OverlapSec', ...
    'OverallStatus', ...
    'GRFGaitQCStatus', ...
    'EEGMappingStatus', ...
    'EEGSetFile', ...
    'MappedEventCount', ...
    'FinalRecommendedCycleCount', ...
    'FinalGaitEEGStatus', ...
    'FirstGRFEventSample', ...
    'FirstGRFEventLSLTime', ...
    'FirstMappedEEGSample', ...
    'FirstMatchedEEGLSLTime', ...
    'LastGRFEventSample', ...
    'LastGRFEventLSLTime', ...
    'LastMappedEEGSample', ...
    'LastMatchedEEGLSLTime', ...
    'MedianAbsMappingErrorMs', ...
    'MaxAbsMappingErrorMs'};

for iVariable = 1:numel(requiredBatchVariables)

    variableName = requiredBatchVariables{iVariable};

    if ~ismember(variableName, ...
            batchStatus.Properties.VariableNames)

        error('Batch-status CSV missing "%s":\n%s', ...
            variableName, ...
            batchLogFile);
    end
end

numericBatchVariables = { ...
    'EEG_LSL_Start', ...
    'EEG_LSL_End', ...
    'EEG_LSL_DurationSec', ...
    'GRF_LSL_Start', ...
    'GRF_LSL_End', ...
    'GRF_LSL_DurationSec', ...
    'GRF_EEG_LSL_OverlapSec', ...
    'MappedEventCount', ...
    'FinalRecommendedCycleCount', ...
    'FirstGRFEventSample', ...
    'FirstGRFEventLSLTime', ...
    'FirstMappedEEGSample', ...
    'FirstMatchedEEGLSLTime', ...
    'LastGRFEventSample', ...
    'LastGRFEventLSLTime', ...
    'LastMappedEEGSample', ...
    'LastMatchedEEGLSLTime', ...
    'MedianAbsMappingErrorMs', ...
    'MaxAbsMappingErrorMs'};

for iVariable = 1:numel(numericBatchVariables)

    variableName = numericBatchVariables{iVariable};

    batchStatus.(variableName) = ...
        numeric_column_local( ...
            batchStatus.(variableName));
end

batchStatus.Subject = string(batchStatus.Subject);
batchStatus.SessionFolder = string(batchStatus.SessionFolder);
batchStatus.XDFPath = string(batchStatus.XDFPath);
batchStatus.OverallStatus = string(batchStatus.OverallStatus);
batchStatus.GRFGaitQCStatus = string(batchStatus.GRFGaitQCStatus);
batchStatus.EEGMappingStatus = string(batchStatus.EEGMappingStatus);
batchStatus.EEGSetFile = string(batchStatus.EEGSetFile);
batchStatus.FinalGaitEEGStatus = ...
    string(batchStatus.FinalGaitEEGStatus);

% GRF/QC exclusion is not a technical subject failure.
% Only a GRF-qualified run whose Step 04 EEG mapping actually failed
% blocks subject concatenation when partial subjects are disallowed.

hardFailureRows = ...
    lower(strtrim(batchStatus.GRFGaitQCStatus)) == ...
        "ready_for_step04" & ...
    lower(strtrim(batchStatus.EEGMappingStatus)) == ...
        "failed";

if any(hardFailureRows) && ~allowPartialSubject

    error([ ...
        '%d GRF-qualified run(s) failed during Step 04 EEG mapping. ' ...
        'Subject concatenation blocked.'], ...
        sum(hardFailureRows));
end

% Only recordings surviving the final Step 04 gait-EEG gate are merged.

readyRows = ...
    lower(strtrim(batchStatus.OverallStatus)) == "completed" & ...
    lower(strtrim(batchStatus.FinalGaitEEGStatus)) == "included" & ...
    batchStatus.FinalRecommendedCycleCount > 0 & ...
    batchStatus.MappedEventCount > 0 & ...
    strlength(strtrim(batchStatus.EEGSetFile)) > 0;

if ~any(readyRows)
    error('No Step 04-eligible mapped EEG datasets are available.');
end

sourceTable = batchStatus(readyRows,:);

for iSource = 1:height(sourceTable)

    if ~isfile(sourceTable.EEGSetFile(iSource))
        error('Mapped EEG does not exist:\n%s', ...
            sourceTable.EEGSetFile(iSource));
    end
end

subjectLabels = unique(sourceTable.Subject);
subjectLabels(strlength(strtrim(subjectLabels)) == 0) = [];

if numel(subjectLabels) ~= 1
    error('Rows do not resolve to exactly one subject.');
end

subjectLabel = subjectLabels(1);

% Output

subjectDestinationFolder = fullfile( ...
    subjectLevelEEGFolder, ...
    char(subjectLabel));

if ~isfolder(subjectDestinationFolder)
    mkdir(subjectDestinationFolder);
end

mergedSetName = char( ...
    subjectLabel + ...
    "_desc-continuousGRF_eeg.set");

mergedSetPath = fullfile( ...
    subjectDestinationFolder, ...
    mergedSetName);

manifestFile = fullfile( ...
    subjectDestinationFolder, ...
    char(subjectLabel + ...
    "_desc-continuousGRF_sources.csv"));

sourceInputSignature = ...
    build_source_input_signature( ...
        sourceTable.EEGSetFile, sourceTable.XDFPath);

% EEGLAB

if exist('pop_loadset','file') ~= 2
    eeglab nogui;
end

try
    pop_editoptions( ...
        'option_saveversion6', 0, ...
        'option_single', 0, ...
        'option_memmapdata', 0, ...
        'option_savetwofiles', 1, ...
        'option_storedisk', 0);
catch
    warning('Could not set every EEGLAB save option.');
end

% Reuse validation

if isfile(mergedSetPath) && ...
        isfile(manifestFile) && ...
        ~forceReprocess

    existingEEG = [];
    storedSignature = "";

    try
        existingEEG = pop_loadset( ...
            'filename', mergedSetName, ...
            'filepath', subjectDestinationFolder);
    catch reuseLoadError
        fprintf( ...
            '\nExisting merged EEG could not be loaded: %s\n', ...
            reuseLoadError.message);
    end

    if ~isempty(existingEEG) && ...
            isfield(existingEEG,'etc') && ...
            isstruct(existingEEG.etc) && ...
            isfield(existingEEG.etc, ...
                'subject_merge_input_signature')

        storedSignature = string( ...
            existingEEG.etc.subject_merge_input_signature);
    end

    if storedSignature == sourceInputSignature

        try

            sourceManifest = ...
                hipexo.read_csv_with_string_text( ...
                    manifestFile);

            validate_merged_subject_eeg( ...
                existingEEG, ...
                height(sourceManifest));

            subjectSummary = ...
                build_subject_summary( ...
                    subjectLabel, ...
                    mergedSetPath, ...
                    manifestFile, ...
                    sourceManifest, ...
                    existingEEG, ...
                    sourceInputSignature, ...
                    "reused_existing");

            update_subject_processing_table( ...
                subjectSummary, ...
                subjectLevelEEGTableFile);

            fprintf('\nReusing subject-level EEG:\n%s\n', ...
                mergedSetPath);

            return;

        catch
            % Rebuild below if reuse validation fails.
        end
    end
end

% Load source EEGs and read source-XDF EEG LSL timestamps

nSources = height(sourceTable);

loadedEEG = cell(nSources,1);
sourceMetadata = cell(nSources,1);

eegFirstLSLTime = nan(nSources,1);
eegLastLSLTime = nan(nSources,1);

referenceSrate = NaN;
referenceChannelLabels = strings(0,1);
referenceChannelXYZ = [];

for iSource = 1:nSources

    currentSetPath = ...
        char(sourceTable.EEGSetFile(iSource));

    [currentSetFolder, ...
     currentSetBase, ...
     currentSetExtension] = ...
        fileparts(currentSetPath);

    currentEEG = pop_loadset( ...
        'filename', ...
        [currentSetBase currentSetExtension], ...
        'filepath', ...
        currentSetFolder);

    currentEEG = eeg_checkset(currentEEG);

    currentMetadata = ...
        resolve_source_metadata( ...
            currentEEG, ...
            sourceTable.XDFPath(iSource));

    if currentMetadata.SubjectLabel ~= subjectLabel
        error([ ...
            'Source EEG subject mismatch. Expected %s, found %s.'], ...
            subjectLabel, ...
            currentMetadata.SubjectLabel);
    end

    validate_source_eeg( ...
        currentEEG, ...
        currentMetadata, ...
        referenceSrate, ...
        referenceChannelLabels, ...
        referenceChannelXYZ);

    if iSource == 1

        referenceSrate = ...
            double(currentEEG.srate);

        referenceChannelLabels = ...
            string({currentEEG.chanlocs.labels})';

        referenceChannelXYZ = ...
            channel_xyz_matrix( ...
                currentEEG.chanlocs);
    end

    [eegFirstLSLTime(iSource), ...
     eegLastLSLTime(iSource)] = ...
        source_xdf_eeg_lsl_bounds( ...
            sourceTable.XDFPath(iSource));

    loadedEEG{iSource} = currentEEG;
    sourceMetadata{iSource} = currentMetadata;
end

if numel(unique(eegFirstLSLTime)) ~= nSources
    error('Duplicate EEG first LSL timestamps detected.');
end

% Chronological order

[~, chronologicalOrder] = ...
    sort(eegFirstLSLTime, 'ascend');

sourceTable = ...
    sourceTable(chronologicalOrder,:);

loadedEEG = ...
    loadedEEG(chronologicalOrder);

sourceMetadata = ...
    sourceMetadata(chronologicalOrder);

eegFirstLSLTime = ...
    eegFirstLSLTime(chronologicalOrder);

eegLastLSLTime = ...
    eegLastLSLTime(chronologicalOrder);

fprintf('\nTRUE EEG LSL ACQUISITION ORDER\n');

for iSource = 1:nSources

    currentMetadata = sourceMetadata{iSource};

    fprintf( ...
        '%02d %s run-%03d Start=%.6f End=%.6f\n', ...
        iSource, ...
        currentMetadata.SessionLabel, ...
        currentMetadata.RunNumber, ...
        eegFirstLSLTime(iSource), ...
        eegLastLSLTime(iSource));
end

% Build chronologically sorted recordings

ALLEEG = [];
CURRENTSET = 0;

sourceIndex = (1:nSources)';

eegLSLDurationSec = ...
    eegLastLSLTime - eegFirstLSLTime;

grfFirstLSLTime = ...
    sourceTable.GRF_LSL_Start;

grfLastLSLTime = ...
    sourceTable.GRF_LSL_End;

grfLSLDurationSec = ...
    sourceTable.GRF_LSL_DurationSec;

grfEEGLSLOverlapSec = ...
    sourceTable.GRF_EEG_LSL_OverlapSec;

firstGRFEventSample = ...
    sourceTable.FirstGRFEventSample;

firstGRFEventLSLTime = ...
    sourceTable.FirstGRFEventLSLTime;

firstMappedEEGSample = ...
    sourceTable.FirstMappedEEGSample;

firstMatchedEEGLSLTime = ...
    sourceTable.FirstMatchedEEGLSLTime;

lastGRFEventSample = ...
    sourceTable.LastGRFEventSample;

lastGRFEventLSLTime = ...
    sourceTable.LastGRFEventLSLTime;

lastMappedEEGSample = ...
    sourceTable.LastMappedEEGSample;

lastMatchedEEGLSLTime = ...
    sourceTable.LastMatchedEEGLSLTime;

medianAbsMappingErrorMs = ...
    sourceTable.MedianAbsMappingErrorMs;

maxAbsMappingErrorMs = ...
    sourceTable.MaxAbsMappingErrorMs;

manifestSubject = ...
    repmat(subjectLabel,nSources,1);

sessionLabel = strings(nSources,1);
conditionLabel = strings(nSources,1);
taskLabel = strings(nSources,1);
runNumber = nan(nSources,1);

xdfPath = sourceTable.XDFPath;
sourceSetPath = sourceTable.EEGSetFile;

startSample = nan(nSources,1);
endSample = nan(nSources,1);
sampleCount = nan(nSources,1);
durationSec = nan(nSources,1);
gaitEventCount = nan(nSources,1);
internalBoundaryCount = nan(nSources,1);

% These two values must be collected BEFORE loadedEEG is cleared.
eegRetainedSourceSampleRanges = ...
    strings(nSources,1);

eegSampleSelectionSignature = ...
    strings(nSources,1);

cumulativeSamples = 0;

validGaitEventTypes = ...
    ["RHS","RTO","LHS","LTO"];

for iSource = 1:nSources

    currentEEG = loadedEEG{iSource};
    currentMetadata = sourceMetadata{iSource};

    currentEEG = ...
        add_source_metadata_to_events( ...
            currentEEG, ...
            currentMetadata, ...
            iSource);

    currentEEG = ...
        add_recording_start_event( ...
            currentEEG, ...
            currentMetadata, ...
            iSource);

    currentEEG = eeg_checkset( ...
        currentEEG, ...
        'eventconsistency');

    currentEventTypes = ...
        event_type_strings( ...
            currentEEG.event);

    currentGaitEventCount = ...
        sum(ismember( ...
            currentEventTypes, ...
            validGaitEventTypes));

    missingGaitEventTypes = ...
        validGaitEventTypes( ...
            ~ismember( ...
                validGaitEventTypes, ...
                currentEventTypes));

    if ~isempty(missingGaitEventTypes)

        error('Required gait events missing from %s: %s', ...
            sourceSetPath(iSource), ...
            strjoin(missingGaitEventTypes, ', '));
    end

    sessionLabel(iSource) = ...
        currentMetadata.SessionLabel;

    conditionLabel(iSource) = ...
        currentMetadata.ConditionLabel;

    taskLabel(iSource) = ...
        currentMetadata.TaskLabel;

    runNumber(iSource) = ...
        currentMetadata.RunNumber;

    startSample(iSource) = ...
        cumulativeSamples + 1;

    endSample(iSource) = ...
        cumulativeSamples + currentEEG.pnts;

    sampleCount(iSource) = ...
        currentEEG.pnts;

    durationSec(iSource) = ...
        currentEEG.pnts / currentEEG.srate;

    gaitEventCount(iSource) = ...
        currentGaitEventCount;

    internalBoundaryCount(iSource) = ...
        sum(currentEventTypes == "boundary");

    % Preserve the identity of the EEG samples retained from the original
    % BIDS-derived source before currentEEG is released from memory.

    sourceRanges = ...
        [1 double(currentEEG.pnts)];

    sourceCount = ...
        double(currentEEG.pnts);

    if isfield(currentEEG,'etc') && ...
            isstruct(currentEEG.etc)

        if isfield(currentEEG.etc, ...
                'eeg_retained_source_sample_ranges') && ...
                ~isempty(currentEEG.etc.eeg_retained_source_sample_ranges)

            sourceRanges = ...
                currentEEG.etc.eeg_retained_source_sample_ranges;
        end

        if isfield(currentEEG.etc, ...
                'eeg_source_sample_count') && ...
                ~isempty(currentEEG.etc.eeg_source_sample_count)

            sourceCount = ...
                double(currentEEG.etc.eeg_source_sample_count);
        end
    end

    eegRetainedSourceSampleRanges(iSource) = ...
        string(jsonencode(sourceRanges));

    boundarySamples = ...
        double([ ...
        currentEEG.event( ...
            currentEventTypes == "boundary").latency]);

    if ~isequal(sourceRanges,[1 sourceCount]) || ...
            ~isempty(boundarySamples)

        eegSampleSelectionSignature(iSource) = ...
            hipexo.content_signature( ...
                struct( ...
                    'ranges', ...
                    sourceRanges, ...
                    'boundary_samples', ...
                    boundarySamples));
    end

    cumulativeSamples = ...
        endSample(iSource);

    [ALLEEG,currentEEG,CURRENTSET] = ...
        eeg_store( ...
            ALLEEG, ...
            currentEEG, ...
            0);

    % Safe now: everything required from currentEEG has already been
    % transferred into ALLEEG or stored in the manifest variables.
    loadedEEG{iSource} = [];
end

% Source manifest

sourceManifest = table( ...
    sourceIndex, ...
    manifestSubject, ...
    sessionLabel, ...
    conditionLabel, ...
    taskLabel, ...
    runNumber, ...
    xdfPath, ...
    eegFirstLSLTime, ...
    eegLastLSLTime, ...
    eegLSLDurationSec, ...
    grfFirstLSLTime, ...
    grfLastLSLTime, ...
    grfLSLDurationSec, ...
    grfEEGLSLOverlapSec, ...
    firstGRFEventSample, ...
    firstGRFEventLSLTime, ...
    firstMappedEEGSample, ...
    firstMatchedEEGLSLTime, ...
    lastGRFEventSample, ...
    lastGRFEventLSLTime, ...
    lastMappedEEGSample, ...
    lastMatchedEEGLSLTime, ...
    medianAbsMappingErrorMs, ...
    maxAbsMappingErrorMs, ...
    sourceSetPath, ...
    startSample, ...
    endSample, ...
    sampleCount, ...
    durationSec, ...
    gaitEventCount, ...
    internalBoundaryCount, ...
    'VariableNames', { ...
        'SourceIndex', ...
        'SubjectLabel', ...
        'SessionLabel', ...
        'ConditionLabel', ...
        'TaskLabel', ...
        'RunNumber', ...
        'XDFPath', ...
        'EEG_LSL_Start', ...
        'EEG_LSL_End', ...
        'EEG_LSL_DurationSec', ...
        'GRF_LSL_Start', ...
        'GRF_LSL_End', ...
        'GRF_LSL_DurationSec', ...
        'GRF_EEG_LSL_OverlapSec', ...
        'FirstGRFEventSample', ...
        'FirstGRFEventLSLTime', ...
        'FirstMappedEEGSample', ...
        'FirstMatchedEEGLSLTime', ...
        'LastGRFEventSample', ...
        'LastGRFEventLSLTime', ...
        'LastMappedEEGSample', ...
        'LastMatchedEEGLSLTime', ...
        'MedianAbsMappingErrorMs', ...
        'MaxAbsMappingErrorMs', ...
        'SourceSetPath', ...
        'StartSampleInMergedEEG', ...
        'EndSampleInMergedEEG', ...
        'SampleCount', ...
        'DurationSec', ...
        'MappedGaitEventCount', ...
        'InternalBoundaryCount'});

sourceManifest.EEGRetainedSourceSampleRanges = ...
    eegRetainedSourceSampleRanges;

sourceManifest.EEGSampleSelectionSignature = ...
    eegSampleSelectionSignature;

% Merge

if numel(ALLEEG) == 1
    EEG = ALLEEG(1);
else
    EEG = pop_mergeset( ...
        ALLEEG, ...
        1:numel(ALLEEG), ...
        0);
end

EEG = eeg_checkset(EEG);

EEG = ...
    normalize_merged_event_metadata( ...
        EEG, ...
        sourceManifest);

EEG = eeg_checkset( ...
    EEG, ...
    'eventconsistency');

EEG.setname = ...
    char(erase( ...
        string(mergedSetName), ...
        ".set"));

EEG.subject = ...
    char(subjectLabel);

EEG.condition = ...
    'AllSessions';

% pop_mergeset may leave EEG.etc empty/non-struct.
if ~isfield(EEG,'etc') || ...
        ~isstruct(EEG.etc)

    EEG.etc = struct();
end

EEG.etc.subject_level_concatenation = ...
    true;

EEG.etc.subject_merge_input_signature = ...
    char(sourceInputSignature);

EEG.etc.subject_merge_source_manifest = ...
    sourceManifest;

EEG.etc.subject_merge_source_set_paths = ...
    sourceSetPath;

EEG.etc.subject_merge_source_xdf_paths = ...
    xdfPath;

EEG.etc.subject_merge_source_recording_count = ...
    nSources;

EEG.etc.subject_merge_created_at = ...
    char(current_time_text);

validate_merged_subject_eeg( ...
    EEG, ...
    nSources);

% Save

writetable( ...
    sourceManifest, ...
    manifestFile);

EEG = pop_saveset( ...
    EEG, ...
    'filename', mergedSetName, ...
    'filepath', subjectDestinationFolder, ...
    'savemode', 'twofiles');

if ~isfile(mergedSetPath)
    error('Merged EEG was not created:\n%s', ...
        mergedSetPath);
end

subjectSummary = ...
    build_subject_summary( ...
        subjectLabel, ...
        mergedSetPath, ...
        manifestFile, ...
        sourceManifest, ...
        EEG, ...
        sourceInputSignature, ...
        "completed");

update_subject_processing_table( ...
    subjectSummary, ...
    subjectLevelEEGTableFile);

fprintf('\nSUBJECT-LEVEL EEG CONCATENATION COMPLETED\n');
fprintf('Subject: %s\n',subjectLabel);
fprintf('Sources: %d\n',nSources);
fprintf('Merged EEG:\n%s\n',mergedSetPath);
fprintf('Source manifest:\n%s\n',manifestFile);

end


function validate_source_eeg( ...
        EEG, ...
        metadata, ...
        referenceSrate, ...
        referenceChannelLabels, ...
        referenceChannelXYZ) %#ok<INUSD>

if EEG.trials ~= 1
    error('Source EEG must be continuous.');
end

if EEG.nbchan ~= 64
    error('Expected 64 EEG channels.');
end

if abs(double(EEG.srate)-500) > 1e-6
    error('Expected 500 Hz EEG.');
end

if isfinite(referenceSrate) && ...
        abs(double(EEG.srate)-referenceSrate) > 1e-6

    error('Sampling-rate mismatch.');
end

currentChannelLabels = ...
    string({EEG.chanlocs.labels})';

if numel(unique( ...
        lower(strtrim(currentChannelLabels)))) ~= EEG.nbchan

    error('Channel labels are not unique.');
end

if ~isempty(referenceChannelLabels) && ...
        ~isequal( ...
            lower(strtrim(currentChannelLabels)), ...
            lower(strtrim(referenceChannelLabels)))

    error('Channel labels/order differ.');
end

if ~channel_locations_complete(EEG.chanlocs)
    error('Channel locations incomplete.');
end

currentChannelXYZ = ...
    channel_xyz_matrix( ...
        EEG.chanlocs);

if ~isempty(referenceChannelXYZ) && ...
        (size(currentChannelXYZ,1) ~= ...
            size(referenceChannelXYZ,1) || ...
        any(abs( ...
            currentChannelXYZ(:) - ...
            referenceChannelXYZ(:)) > 1e-9))

    error('Channel coordinates differ.');
end

if any(~isfinite(double(EEG.data(:))))
    error('EEG contains NaN/Inf.');
end

if isempty(EEG.event)
    error('Source EEG contains no events.');
end

end


function tf = ...
        channel_locations_complete(chanlocs)

tf = ~isempty(chanlocs);

if ~tf
    return;
end

requiredFields = {'X','Y','Z'};

for iField = 1:numel(requiredFields)

    fieldName = ...
        requiredFields{iField};

    if ~isfield(chanlocs,fieldName)
        tf = false;
        return;
    end

    for iChannel = 1:numel(chanlocs)

        value = ...
            chanlocs(iChannel).(fieldName);

        if isempty(value) || ...
                ~isnumeric(value) || ...
                ~isfinite(double(value(1)))

            tf = false;
            return;
        end
    end
end

end


function xyz = ...
        channel_xyz_matrix(chanlocs)

xyz = ...
    nan(numel(chanlocs),3);

for iChannel = 1:numel(chanlocs)

    xyz(iChannel,:) = [ ...
        double(chanlocs(iChannel).X), ...
        double(chanlocs(iChannel).Y), ...
        double(chanlocs(iChannel).Z)];
end

end


function [firstLSLTime,lastLSLTime] = ...
        source_xdf_eeg_lsl_bounds(xdfPath)

if exist('load_xdf','file') ~= 2
    error('load_xdf is not available.');
end

[streams,~] = ...
    load_xdf(char(xdfPath));

nStreams = numel(streams);

streamName = strings(nStreams,1);
streamType = strings(nStreams,1);
nominalSrate = nan(nStreams,1);
channelCount = nan(nStreams,1);
sampleCount = nan(nStreams,1);

for iStream = 1:nStreams

    currentStream = streams{iStream};

    streamName(iStream) = ...
        xdf_stream_text_field( ...
            currentStream, ...
            'name');

    streamType(iStream) = ...
        xdf_stream_text_field( ...
            currentStream, ...
            'type');

    nominalSrate(iStream) = ...
        xdf_stream_nominal_srate( ...
            currentStream);

    if isfield(currentStream,'time_stamps')

        currentTimestamps = ...
            currentStream.time_stamps;

        sampleCount(iStream) = ...
            numel(currentTimestamps);

        if isfield(currentStream,'time_series') && ...
                isnumeric(currentStream.time_series)

            currentData = ...
                currentStream.time_series;

            if size(currentData,2) == ...
                    sampleCount(iStream)

                channelCount(iStream) = ...
                    size(currentData,1);

            elseif size(currentData,1) == ...
                    sampleCount(iStream)

                channelCount(iStream) = ...
                    size(currentData,2);
            end
        end
    end
end

candidateMask = ...
    strcmpi( ...
        streamName, ...
        "LiveAmpSN-102108-1139") & ...
    channelCount >= 64 & ...
    channelCount <= 80 & ...
    abs(nominalSrate-500) <= 1;

candidateIndices = ...
    find(candidateMask);

if isempty(candidateIndices)

    candidateMask = ...
        channelCount >= 64 & ...
        channelCount <= 80 & ...
        abs(nominalSrate-500) <= 1 & ...
        (contains(lower(streamType),'eeg') | ...
         contains(lower(streamName),'liveamp'));

    candidateIndices = ...
        find(candidateMask);
end

if numel(candidateIndices) ~= 1

    streamSummary = table( ...
        (1:nStreams)', ...
        streamName, ...
        streamType, ...
        nominalSrate, ...
        channelCount, ...
        sampleCount, ...
        'VariableNames', ...
        {'StreamIndex','Name','Type', ...
         'NominalSrate','ChannelCount','SampleCount'});

    disp(streamSummary);

    error('Could not uniquely identify EEG stream:\n%s', ...
        xdfPath);
end

eegStream = ...
    streams{candidateIndices(1)};

eegTimestamps = ...
    double(eegStream.time_stamps(:));

if isempty(eegTimestamps) || ...
        any(~isfinite(eegTimestamps)) || ...
        any(diff(eegTimestamps)<=0)

    error('Invalid EEG LSL timestamps:\n%s', ...
        xdfPath);
end

firstLSLTime = eegTimestamps(1);
lastLSLTime = eegTimestamps(end);

end


function textValue = ...
        xdf_stream_text_field(stream,fieldName)

textValue = "";

if ~isfield(stream,'info') || ...
        ~isstruct(stream.info) || ...
        ~isfield(stream.info,fieldName)

    return;
end

rawValue = ...
    stream.info.(fieldName);

while iscell(rawValue) && ...
        ~isempty(rawValue)

    rawValue = rawValue{1};
end

if isempty(rawValue)
    return;
end

textValue = string(rawValue);
textValue = textValue(1);

end


function nominalSrate = ...
        xdf_stream_nominal_srate(stream)

nominalSrate = NaN;

if ~isfield(stream,'info') || ...
        ~isstruct(stream.info) || ...
        ~isfield(stream.info,'nominal_srate')

    return;
end

rawValue = ...
    stream.info.nominal_srate;

while iscell(rawValue) && ...
        ~isempty(rawValue)

    rawValue = rawValue{1};
end

if isnumeric(rawValue)
    nominalSrate = double(rawValue(1));
else
    nominalSrate = ...
        str2double(string(rawValue));
end

end


function metadata = ...
        resolve_source_metadata(EEG,xdfPath)

[~,xdfBaseName,xdfExtension] = ...
    fileparts(char(xdfPath));

if ~isempty(regexpi( ...
        [xdfBaseName xdfExtension], ...
        '_old\d*\.xdf$', ...
        'once'))

    error('Old XDF cannot enter concatenation:\n%s', ...
        xdfPath);
end

hasEtc = ...
    isfield(EEG,'etc') && ...
    isstruct(EEG.etc);

if hasEtc && ...
        isfield(EEG.etc,'source_metadata') && ...
        isstruct(EEG.etc.source_metadata)

    metadata = ...
        EEG.etc.source_metadata;

    requiredFields = { ...
        'SubjectLabel', ...
        'SessionLabel', ...
        'ConditionLabel', ...
        'TaskLabel', ...
        'RunNumber', ...
        'RecordingLabel', ...
        'XDFPath'};

    if all(isfield(metadata,requiredFields))

        metadata.SubjectLabel = ...
            string(metadata.SubjectLabel);

        if ~startsWith( ...
                metadata.SubjectLabel, ...
                "sub-")

            metadata.SubjectLabel = ...
                "sub-" + ...
                metadata.SubjectLabel;
        end

        metadata.SessionLabel = ...
            string(metadata.SessionLabel);

        metadata.ConditionLabel = ...
            string(metadata.ConditionLabel);

        metadata.TaskLabel = ...
            string(metadata.TaskLabel);

        metadata.XDFPath = ...
            string(xdfPath);

        if isfield(EEG.etc,'canonical_subject_id') && ...
                strlength(strtrim(string( ...
                    EEG.etc.canonical_subject_id))) > 0

            metadata.SubjectLabel = ...
                string( ...
                    EEG.etc.canonical_subject_id);
        end

        resolvedRunNumber = ...
            numeric_column_local( ...
                metadata.RunNumber);

        if numel(resolvedRunNumber) ~= 1 || ...
                ~isfinite(resolvedRunNumber)

            error('Invalid run metadata.');
        end

        metadata.RunNumber = ...
            resolvedRunNumber;

        if metadata.RunNumber < 1 || ...
                metadata.RunNumber ~= ...
                round(metadata.RunNumber)

            error('Run number must be a positive integer.');
        end

        metadata.RecordingLabel = ...
            metadata.SubjectLabel + "_" + ...
            metadata.SessionLabel + "_" + ...
            compose( ...
                "run-%03d", ...
                metadata.RunNumber);

        return;
    end
end

metadata = ...
    parse_xdf_source_metadata_local( ...
        xdfPath);

end


function metadata = ...
        parse_xdf_source_metadata_local(xdfPath)

[~,baseName,extension] = ...
    fileparts(char(xdfPath));

fullName = ...
    string([baseName extension]);

if ~isempty(regexpi( ...
        char(fullName), ...
        '_old\d*\.xdf$', ...
        'once'))

    error('Old XDF cannot enter concatenation.');
end

token = regexp( ...
    baseName, ...
    ['^sub-(?<subject>.+?)_' ...
     '(?:day\d+_)?' ...
     'ses-(?<session>.+?)_' ...
     'task-(?<task>.+?)_' ...
     'run-(?<run>\d+)_' ...
     'eeg$'], ...
    'names', ...
    'once');

if isempty(token)
    error('Could not parse XDF metadata:\n%s', ...
        xdfPath);
end

runNumber = ...
    str2double(token.run);

if ~isfinite(runNumber) || ...
        runNumber < 1 || ...
        runNumber ~= round(runNumber)

    error('Run number must be a positive integer.');
end

metadata = struct();

metadata.SubjectLabel = ...
    "sub-" + string(token.subject);

metadata.SessionLabel = ...
    "ses-" + string(token.session);

metadata.ConditionLabel = ...
    string(token.session);

metadata.TaskLabel = ...
    string(token.task);

metadata.RunNumber = ...
    runNumber;

metadata.RecordingLabel = ...
    metadata.SubjectLabel + "_" + ...
    metadata.SessionLabel + "_" + ...
    compose("run-%03d",runNumber);

metadata.XDFPath = ...
    string(xdfPath);

end


function EEG = ...
        add_source_metadata_to_events( ...
            EEG,metadata,sourceIndex)

for iEvent = 1:numel(EEG.event)

    EEG.event(iEvent).subject_label = ...
        char(metadata.SubjectLabel);

    EEG.event(iEvent).session_label = ...
        char(metadata.SessionLabel);

    EEG.event(iEvent).condition_label = ...
        char(metadata.ConditionLabel);

    EEG.event(iEvent).task_label = ...
        char(metadata.TaskLabel);

    EEG.event(iEvent).run_number = ...
        metadata.RunNumber;

    EEG.event(iEvent).source_xdf = ...
        char(metadata.XDFPath);

    EEG.event(iEvent).source_recording = ...
        char(metadata.RecordingLabel);

    EEG.event(iEvent).source_recording_index = ...
        sourceIndex;
end

end


function EEG = ...
        add_recording_start_event( ...
            EEG,metadata,sourceIndex)

iEvent = numel(EEG.event)+1;

EEG.event(iEvent).type = ...
    'recording_start';

EEG.event(iEvent).latency = ...
    1;

EEG.event(iEvent).duration = ...
    0;

EEG.event(iEvent).subject_label = ...
    char(metadata.SubjectLabel);

EEG.event(iEvent).session_label = ...
    char(metadata.SessionLabel);

EEG.event(iEvent).condition_label = ...
    char(metadata.ConditionLabel);

EEG.event(iEvent).task_label = ...
    char(metadata.TaskLabel);

EEG.event(iEvent).run_number = ...
    metadata.RunNumber;

EEG.event(iEvent).source_xdf = ...
    char(metadata.XDFPath);

EEG.event(iEvent).source_recording = ...
    char(metadata.RecordingLabel);

EEG.event(iEvent).source_recording_index = ...
    sourceIndex;

end


function EEG = ...
        normalize_merged_event_metadata( ...
            EEG,sourceManifest)

requiredTextFields = { ...
    'subject_label', ...
    'session_label', ...
    'condition_label', ...
    'task_label', ...
    'source_xdf', ...
    'source_recording'};

for iEvent = 1:numel(EEG.event)

    for iField = 1:numel(requiredTextFields)

        fieldName = ...
            requiredTextFields{iField};

        if ~isfield(EEG.event,fieldName) || ...
                ~has_nonempty_event_text_value( ...
                    EEG.event(iEvent).(fieldName))

            EEG.event(iEvent).(fieldName) = '';
        end
    end

    if ~isfield(EEG.event,'run_number') || ...
            isempty( ...
                EEG.event(iEvent).run_number)

        EEG.event(iEvent).run_number = NaN;
    end

    if ~isfield(EEG.event, ...
            'source_recording_index') || ...
            isempty( ...
                EEG.event(iEvent).source_recording_index)

        EEG.event(iEvent).source_recording_index = NaN;
    end

    currentType = ...
        event_type_strings( ...
            EEG.event(iEvent));

    if currentType == "boundary" && ...
            ~has_nonempty_event_text_value( ...
                EEG.event(iEvent).source_recording)

        EEG.event(iEvent).source_recording = ...
            'dataset_join_boundary';
    end
end

expectedJoinLatencies = ...
    double( ...
        sourceManifest.EndSampleInMergedEEG(1:end-1)) + ...
        0.5;

allEventTypes = ...
    event_type_strings(EEG.event);

allEventLatencies = ...
    double([EEG.event.latency])';

for iJoin = 1:numel(expectedJoinLatencies)

    matchingBoundary = find( ...
        allEventTypes == "boundary" & ...
        abs( ...
            allEventLatencies - ...
            expectedJoinLatencies(iJoin)) <= 1e-6);

    if numel(matchingBoundary) ~= 1

        error( ...
            'Expected one join boundary at latency %.9g.', ...
            expectedJoinLatencies(iJoin));
    end

    eventIndex = ...
        matchingBoundary(1);

    EEG.event(eventIndex).source_recording = ...
        'dataset_join_boundary';

    EEG.event(eventIndex).source_recording_index = ...
        NaN;

    if isfield(EEG.event,'mapping_status')

        EEG.event(eventIndex).mapping_status = ...
            'dataset_join_boundary';
    end
end

end


function tf = ...
        has_nonempty_event_text_value(rawValue)

if iscell(rawValue)

    if isempty(rawValue)
        tf = false;
        return;
    end

    rawValue = rawValue{1};
end

if ischar(rawValue) || ...
        isstring(rawValue) || ...
        iscategorical(rawValue)

    textValue = ...
        string(rawValue);

    tf = ...
        ~isempty(textValue) && ...
        any( ...
            ~ismissing(textValue) & ...
            strlength( ...
                strtrim(textValue)) > 0);
else
    tf = false;
end

end


function validate_merged_subject_eeg( ...
        EEG,expectedSourceCount)

if EEG.trials ~= 1 || ...
        EEG.nbchan ~= 64 || ...
        abs(double(EEG.srate)-500) > 1e-6

    error('Merged EEG failed basic structure QC.');
end

if ~channel_locations_complete(EEG.chanlocs)
    error('Merged EEG channel locations incomplete.');
end

if any(~isfinite(double(EEG.data(:))))
    error('Merged EEG contains NaN/Inf.');
end

eventTypes = ...
    event_type_strings(EEG.event);

requiredGaitEventTypes = ...
    ["RHS","RTO","LHS","LTO"];

missingGaitEventTypes = ...
    requiredGaitEventTypes( ...
        ~ismember( ...
            requiredGaitEventTypes, ...
            eventTypes));

if ~isempty(missingGaitEventTypes)

    error('Merged EEG missing gait event types: %s', ...
        strjoin(missingGaitEventTypes,', '));
end

recordingStartCount = ...
    sum(eventTypes == "recording_start");

if recordingStartCount ~= ...
        expectedSourceCount

    error([ ...
        'Expected %d recording_start events, found %d.'], ...
        expectedSourceCount, ...
        recordingStartCount);
end

recordingStartIndices = ...
    event_numeric_field_values( ...
        EEG.event( ...
            eventTypes == "recording_start"), ...
        'source_recording_index');

if numel(recordingStartIndices) ~= ...
        expectedSourceCount || ...
        ~isequal( ...
            sort(recordingStartIndices(:))', ...
            1:expectedSourceCount)

    error('recording_start source indices invalid.');
end

gaitEventSourceIndices = ...
    event_numeric_field_values( ...
        EEG.event( ...
            ismember( ...
                eventTypes, ...
                requiredGaitEventTypes)), ...
        'source_recording_index');

if any(~isfinite(gaitEventSourceIndices)) || ...
        any(gaitEventSourceIndices < 1) || ...
        any(gaitEventSourceIndices > expectedSourceCount)

    error('Gait event source index invalid.');
end

expectedJoinBoundaries = ...
    max(0,expectedSourceCount-1);

boundarySources = ...
    event_text_field_values( ...
        EEG.event(eventTypes=="boundary"), ...
        'source_recording');

joinBoundaryCount = ...
    sum( ...
        boundarySources == ...
        "dataset_join_boundary");

if joinBoundaryCount ~= ...
        expectedJoinBoundaries

    error([ ...
        'Expected %d dataset-join boundaries, found %d.'], ...
        expectedJoinBoundaries, ...
        joinBoundaryCount);
end

end


function eventTypes = ...
        event_type_strings(events)

if isempty(events)

    eventTypes = strings(0,1);
    return;
end

eventTypes = ...
    strings(numel(events),1);

for iEvent = 1:numel(events)

    rawType = ...
        events(iEvent).type;

    if isnumeric(rawType)

        eventTypes(iEvent) = ...
            string(rawType);

    elseif iscell(rawType) && ...
            ~isempty(rawType)

        eventTypes(iEvent) = ...
            string(rawType{1});

    else

        eventTypes(iEvent) = ...
            string(rawType);
    end
end

end


function values = ...
        event_text_field_values( ...
            events,fieldName)

values = ...
    strings(numel(events),1);

if isempty(events) || ...
        ~isfield(events,fieldName)

    return;
end

for iEvent = 1:numel(events)

    rawValue = ...
        events(iEvent).(fieldName);

    if iscell(rawValue) && ...
            ~isempty(rawValue)

        rawValue = rawValue{1};
    end

    if ~isempty(rawValue)
        values(iEvent) = ...
            string(rawValue);
    end
end

end


function values = ...
        event_numeric_field_values( ...
            events,fieldName)

values = ...
    nan(numel(events),1);

if isempty(events) || ...
        ~isfield(events,fieldName)

    return;
end

for iEvent = 1:numel(events)

    rawValue = ...
        events(iEvent).(fieldName);

    if iscell(rawValue) && ...
            ~isempty(rawValue)

        rawValue = rawValue{1};
    end

    if isnumeric(rawValue) || ...
            islogical(rawValue)

        if ~isempty(rawValue)
            values(iEvent) = ...
                double(rawValue(1));
        end

    elseif ~isempty(rawValue)

        values(iEvent) = ...
            str2double( ...
                string(rawValue));
    end
end

end


function signature = build_source_input_signature(sourceSetPaths, sourceXdfPaths)
[sourceSetPaths, order] = sort(string(sourceSetPaths(:)));
sourceXdfPaths = string(sourceXdfPaths(:));
sourceXdfPaths = sourceXdfPaths(order);
parts = strings(numel(sourceSetPaths), 1);
timingSources = strings(numel(sourceSetPaths), 1);
for k = 1:numel(sourceSetPaths)
    parts(k) = hipexo.eeglab_dataset_signature(sourceSetPaths(k));
    % Concatenation also reads raw XDF clock bounds to determine source order.
    timingSources(k) = hipexo.file_metadata_signature(sourceXdfPaths(k));
end
signature = hipexo.content_signature(struct('sources', sourceSetPaths, ...
    'contents', parts, 'timingSources', timingSources));
end

function signature = build_continuous_input_signature(sourceManifest, EEG)
% Event labels may change without changing continuous EEG or source layout.
fields = {'SourceIndex','XDFPath','StartSampleInMergedEEG','EndSampleInMergedEEG', ...
    'SampleCount','ConditionLabel','RunNumber','EEGSampleSelectionSignature'};
fields = fields(ismember(fields, sourceManifest.Properties.VariableNames));
signature = hipexo.content_signature(struct( ...
    'signal', hipexo.eeglab_dataset_signature(EEG, "signal"), ...
    'layout', table2struct(sourceManifest(:, fields))));
end

function summary = ...
        build_subject_summary( ...
            subjectLabel, ...
            mergedSetPath, ...
            manifestFile, ...
            sourceManifest, ...
            EEG, ...
            sourceInputSignature, ...
            mergeStatus)

[bidsSubject,processingSessionLabel] = ...
    make_subject_processing_labels( ...
        subjectLabel);

eventTypes = ...
    event_type_strings(EEG.event);

DoImport = 1;

XdfPath = ...
    strjoin( ...
        string(sourceManifest.XDFPath), ...
        " | ");

[~,mergedBase,mergedExtension] = ...
    fileparts(mergedSetPath);

FileName = ...
    string( ...
        [mergedBase mergedExtension]);

BidsSubject = ...
    bidsSubject;

BidsSession = ...
    processingSessionLabel;

RunNumber = NaN;

EEGStreamName = ...
    "LiveAmpSN-102108-1139";

RawSetPath = ...
    string(mergedSetPath);

RawSetStatus = ...
    "OK_subject_level_merged";

RecommendedDoPreprocess = 1;
DoPreprocess = 1;

SubjectLabel = ...
    string(subjectLabel);

SubjectInputSignature = ...
    string(sourceInputSignature);

ContinuousInputSignature = ...
    build_continuous_input_signature( ...
        sourceManifest, ...
        EEG);

SourceRecordingCount = ...
    height(sourceManifest);

SampleCount = ...
    double(EEG.pnts);

MappedGaitEventCount = ...
    sum(ismember( ...
        eventTypes, ...
        ["RHS","RTO","LHS","LTO"]));

BoundaryEventCount = ...
    sum(eventTypes == "boundary");

ChannelCount = ...
    double(EEG.nbchan);

SamplingRate = ...
    double(EEG.srate);

DurationSec = ...
    double(EEG.pnts) / ...
    double(EEG.srate);

MergeStatus = ...
    string(mergeStatus);

ManifestPath = ...
    string(manifestFile);

MergeDate = ...
    current_time_text;

EventUpdateCompatibility = ...
    "not_yet_compared_with_previous_table_row";

summary = table( ...
    DoImport, ...
    XdfPath, ...
    FileName, ...
    BidsSubject, ...
    BidsSession, ...
    RunNumber, ...
    EEGStreamName, ...
    RawSetPath, ...
    RawSetStatus, ...
    RecommendedDoPreprocess, ...
    DoPreprocess, ...
    SubjectLabel, ...
    SubjectInputSignature, ...
    ContinuousInputSignature, ...
    SourceRecordingCount, ...
    SampleCount, ...
    MappedGaitEventCount, ...
    BoundaryEventCount, ...
    ChannelCount, ...
    SamplingRate, ...
    DurationSec, ...
    MergeStatus, ...
    ManifestPath, ...
    MergeDate, ...
    EventUpdateCompatibility);

end


function [bidsSubject,processingSessionLabel] = ...
        make_subject_processing_labels(subjectLabel)

token = regexp( ...
    char(subjectLabel), ...
    '^sub-(?<subject>\d+)$', ...
    'names', ...
    'once');

if isempty(token)

    error([ ...
        'Invalid canonical subject label: %s. ' ...
        'Expected sub-XX, for example sub-01.'], ...
        subjectLabel);
end

bidsSubject = ...
    str2double(token.subject);

processingSessionLabel = ...
    "allSessions";

end


function update_subject_processing_table( ...
        newRow,tableFile)

baseVariables = ...
    newRow.Properties.VariableNames;

if ~isfile(tableFile)

    writetable(newRow,tableFile);
    return;
end

oldTable = ...
    hipexo.read_csv_with_string_text( ...
        tableFile);

if ~ismember( ...
        'SubjectLabel', ...
        oldTable.Properties.VariableNames)

    backupFile = char( ...
        string(tableFile) + ...
        ".incompatible_backup_" + ...
        string(datetime( ...
            'now', ...
            'Format','yyyyMMdd_HHmmss')) + ...
        ".csv");

    copyfile(tableFile,backupFile);
    writetable(newRow,tableFile);

    return;
end

oldTable.SubjectLabel = ...
    string(oldTable.SubjectLabel);

if ismember( ...
        'SubjectInputSignature', ...
        oldTable.Properties.VariableNames)

    oldTable.SubjectInputSignature = ...
        string( ...
            oldTable.SubjectInputSignature);
end

matchingRows = ...
    find( ...
        oldTable.SubjectLabel == ...
        newRow.SubjectLabel);

if numel(matchingRows) > 1

    error([ ...
        'The subject-level processing table contains duplicate rows ' ...
        'for %s.'], ...
        newRow.SubjectLabel);
end

if ~isempty(matchingRows)

    backupFile = char( ...
        string(tableFile) + ...
        ".before_subject_update_" + ...
        string(datetime( ...
            'now', ...
            'Format','yyyyMMdd_HHmmss_SSS')) + ...
        ".csv");

    copyfile(tableFile,backupFile);
end

oldVariableNames = ...
    oldTable.Properties.VariableNames;

for iVariable = 1:numel(baseVariables)

    variableName = ...
        baseVariables{iVariable};

    if ~ismember( ...
            variableName, ...
            oldVariableNames)

        oldTable.(variableName) = ...
            make_missing_column_like( ...
                newRow.(variableName), ...
                height(oldTable));
    end
end

oldVariableNames = ...
    oldTable.Properties.VariableNames;

for iVariable = 1:numel(oldVariableNames)

    variableName = ...
        oldVariableNames{iVariable};

    if ~ismember( ...
            variableName, ...
            newRow.Properties.VariableNames)

        newRow.(variableName) = ...
            make_missing_column_like( ...
                oldTable.(variableName), ...
                1);
    end
end

newRow = ...
    newRow(:, ...
        oldTable.Properties.VariableNames);

if ~isempty(matchingRows)

    previousRow = ...
        matchingRows(1);

    signatureUnchanged = false;

    if ismember( ...
            'SubjectInputSignature', ...
            oldTable.Properties.VariableNames)

        signatureUnchanged = ...
            string( ...
                oldTable.SubjectInputSignature(previousRow)) == ...
            string( ...
                newRow.SubjectInputSignature);
    end

    continuousLayoutCompatible = ...
        continuous_layout_compatible_local( ...
            oldTable, ...
            newRow, ...
            previousRow);

    preserveDownstream = ...
        signatureUnchanged || ...
        continuousLayoutCompatible;

    if signatureUnchanged

        newRow.EventUpdateCompatibility(1) = ...
            "identical_source_signature_downstream_preserved";

    elseif continuousLayoutCompatible

        newRow.EventUpdateCompatibility(1) = ...
            "event_only_compatible_downstream_preserved";

    else

        newRow.EventUpdateCompatibility(1) = ...
            "continuous_layout_changed_downstream_reset";
    end

    if preserveDownstream

        columnsToPreserve = ...
            setdiff( ...
                oldTable.Properties.VariableNames, ...
                baseVariables, ...
                'stable');

        if ismember( ...
                'DoPreprocess', ...
                baseVariables)

            columnsToPreserve = ...
                [{'DoPreprocess'}, ...
                 columnsToPreserve];
        end

        for iColumn = 1:numel(columnsToPreserve)

            columnName = ...
                columnsToPreserve{iColumn};

            newRow.(columnName)(1,:) = ...
                oldTable.(columnName)( ...
                    previousRow,:);
        end
    end

else

    newRow.EventUpdateCompatibility(1) = ...
        "new_subject_no_previous_downstream_state";
end

oldTable(matchingRows,:) = [];

updatedTable = ...
    [oldTable;newRow];

if ismember( ...
        'BidsSubject', ...
        updatedTable.Properties.VariableNames)

    updatedTable = ...
        sortrows( ...
            updatedTable, ...
            'BidsSubject');
end

writetable( ...
    updatedTable, ...
    tableFile);

end


function compatible = continuous_layout_compatible_local(oldTable, newRow, previousRow)
compatible = false;
field = 'ContinuousInputSignature';
if ~ismember(field, oldTable.Properties.VariableNames) || ...
        ~ismember(field, newRow.Properties.VariableNames)
    return;
end
oldSignature = string(oldTable.(field)(previousRow));
newSignature = string(newRow.(field)(1));
% Missing legacy fingerprints cannot establish sample equality.
compatible = startsWith(oldSignature, "content-sha256:") && ...
    oldSignature == newSignature;
end

function column = ...
        make_missing_column_like( ...
            example,numberOfRows)

if isstring(example)

    column = ...
        strings( ...
            numberOfRows, ...
            size(example,2));

elseif islogical(example)

    column = ...
        false( ...
            numberOfRows, ...
            size(example,2));

elseif isnumeric(example)

    column = ...
        nan( ...
            numberOfRows, ...
            size(example,2));

elseif isdatetime(example)

    column = ...
        NaT( ...
            numberOfRows, ...
            size(example,2));

elseif iscell(example)

    column = ...
        cell( ...
            numberOfRows, ...
            size(example,2));

elseif iscategorical(example)

    column = ...
        repmat( ...
            categorical(missing), ...
            numberOfRows, ...
            size(example,2));

else

    column = ...
        strings( ...
            numberOfRows, ...
            size(example,2));
end

end


function value = ...
        current_time_text

value = string(datetime( ...
    'now', ...
    'TimeZone','local', ...
    'Format','yyyy-MM-dd HH:mm:ss'));

end


function values = ...
        numeric_column_local(values)

if isnumeric(values)

    values = double(values);

elseif islogical(values)

    values = double(values);

else

    textValues = ...
        lower(strtrim(string(values)));

    values = ...
        str2double(textValues);

    values(ismember( ...
        textValues, ...
        ["true","yes"])) = 1;

    values(ismember( ...
        textValues, ...
        ["false","no"])) = 0;
end

end