function [startSec, endSec, threshold] = ...
        detect_walking_intervals( ...
            activityTrace, ...
            timeSec, ...
            sampleRate, ...
            cfg)
% GOAL
%   Detect sustained walking intervals from GRF activity when valid
%   GRF START/END markers are unavailable.
%
% METHOD
%   Estimate quiet and active GRF levels using robust quantiles, threshold
%   between them, require sustained activity, merge short gaps, remove short
%   intervals, and trim the start/stop transitions.

activityTrace = double(activityTrace(:));
timeSec = double(timeSec(:));

startSec = zeros(0, 1);
endSec = zeros(0, 1);
threshold = NaN;

validSamples = ...
    isfinite(activityTrace) & ...
    isfinite(timeSec);

if nnz(validSamples) < 10 || ...
        ~isfinite(sampleRate) || ...
        sampleRate <= 0
    return;
end

validActivity = activityTrace(validSamples);
sortedActivity = sort(validActivity);

lowIndex = max( ...
    1, ...
    round(cfg.activityLowQuantile * numel(sortedActivity)));

highIndex = max( ...
    1, ...
    round(cfg.activityHighQuantile * numel(sortedActivity)));

lowActivity = sortedActivity(lowIndex);
highActivity = sortedActivity(highIndex);

if ~isfinite(lowActivity) || ...
        ~isfinite(highActivity) || ...
        highActivity <= lowActivity
    return;
end

threshold = ...
    lowActivity + ...
    cfg.thresholdFraction * ...
    (highActivity - lowActivity);

aboveThreshold = ...
    activityTrace > threshold;

confirmationWindowSamples = max( ...
    1, ...
    round(cfg.confirmationWindowSec * sampleRate));

activeFraction = movmean( ...
    double(aboveThreshold), ...
    confirmationWindowSamples, ...
    'Endpoints', ...
    'shrink');

stableActivity = ...
    activeFraction >= cfg.minimumActiveFraction;

transitionVector = diff([ ...
    false; ...
    stableActivity; ...
    false]);

startSamples = find(transitionVector == 1);
endSamples = find(transitionVector == -1) - 1;

if isempty(startSamples)
    return;
end

%% Merge short inactive gaps

mergedStartSamples = startSamples(1);
mergedEndSamples = endSamples(1);

for iInterval = 2:numel(startSamples)

    gapSec = ...
        timeSec(startSamples(iInterval)) - ...
        timeSec(mergedEndSamples(end));

    if gapSec <= cfg.maximumInactiveGapSec

        mergedEndSamples(end) = ...
            endSamples(iInterval);

    else

        mergedStartSamples(end + 1, 1) = ...
            startSamples(iInterval); %#ok<AGROW>

        mergedEndSamples(end + 1, 1) = ...
            endSamples(iInterval); %#ok<AGROW>
    end
end

startSamples = mergedStartSamples(:);
endSamples = mergedEndSamples(:);

%% Remove short movements

intervalDurationSec = ...
    timeSec(endSamples) - ...
    timeSec(startSamples);

keepInterval = ...
    intervalDurationSec >= ...
    cfg.minimumWalkingDurationSec;

startSamples = startSamples(keepInterval);
endSamples = endSamples(keepInterval);

if isempty(startSamples)
    return;
end

%% Trim transition periods

transitionMarginSamples = max( ...
    0, ...
    round(cfg.transitionMarginSec * sampleRate));

adjustedStartSamples = min( ...
    startSamples + transitionMarginSamples, ...
    endSamples);

adjustedEndSamples = max( ...
    endSamples - transitionMarginSamples, ...
    adjustedStartSamples);

validAdjustedIntervals = ...
    timeSec(adjustedEndSamples) - ...
    timeSec(adjustedStartSamples) >= ...
    cfg.minimumWalkingDurationSec;

adjustedStartSamples = ...
    adjustedStartSamples(validAdjustedIntervals);

adjustedEndSamples = ...
    adjustedEndSamples(validAdjustedIntervals);

startSec = timeSec(adjustedStartSamples);
endSec = timeSec(adjustedEndSamples);

end
