function result = inspect_xdf_file(xdfPath, fileIndex, cfg)
% GOAL
%   Inspect one XDF file and independently evaluate its EEG and GRF streams
%   for structural usability before downstream processing.
% METHOD
%   Load the XDF once, derive timestamp/data integrity measures for each
%   stream, evaluate EEG and GRF independently, then create the same audit
%   table schema used by the current working pipeline.

arguments
    xdfPath
    fileIndex (1,1) double {mustBeInteger, mustBePositive}
    cfg (1,1) struct
end

xdfPath = string(xdfPath);
[~, name, ext] = fileparts(xdfPath);
fileName = string(name) + string(ext);

result = struct();
result.fileSummary = table();
result.streamDetail = table();

try
    streams = load_xdf(char(xdfPath));
catch ME
    result.fileSummary = make_load_error_row( ...
        fileIndex, fileName, xdfPath, ME);
    return;
end

nStreams = numel(streams);

streamNames = strings(nStreams, 1);
streamTypes = strings(nStreams, 1);
streamRates = strings(nStreams, 1);
streamChans = strings(nStreams, 1);

isEEGCandidate = false(nStreams, 1);
isUsableEEG = false(nStreams, 1);
isGRFCandidate = false(nStreams, 1);
isUsableGRF = false(nStreams, 1);

nDataSamples = nan(nStreams, 1);
nTimeStamps = nan(nStreams, 1);
durationSec = nan(nStreams, 1);
effectiveSrate = nan(nStreams, 1);
medianDtSec = nan(nStreams, 1);
minDtSec = nan(nStreams, 1);
maxDtSec = nan(nStreams, 1);
srateAbsDiff = nan(nStreams, 1);
srateRelDiff = nan(nStreams, 1);
sampleTimestampMatch = false(nStreams, 1);
timestampsFinite = false(nStreams, 1);
timestampsStrictlyIncreasing = false(nStreams, 1);
dataFiniteSampled = false(nStreams, 1);
robustGapLimitSec = nan(nStreams, 1);

eegQualityStatus = strings(nStreams, 1);
eegQualityReason = strings(nStreams, 1);
grfQualityStatus = strings(nStreams, 1);
grfQualityReason = strings(nStreams, 1);

for s = 1:nStreams

    info = streams{s}.info;

    streamNames(s) = strtrim(get_xdf_info_field(info, 'name'));
    streamTypes(s) = strtrim(get_xdf_info_field(info, 'type'));
    streamRates(s) = strtrim(get_xdf_info_field(info, 'nominal_srate'));
    streamChans(s) = strtrim(get_xdf_info_field(info, 'channel_count'));

    srateNum = str2double(streamRates(s));
    chanNum = str2double(streamChans(s));

    if isfield(streams{s}, 'time_stamps')
        ts = double(streams{s}.time_stamps);
    else
        ts = [];
    end

    if isfield(streams{s}, 'time_series')
        data = streams{s}.time_series;
    else
        data = [];
    end

    nTimeStamps(s) = numel(ts);
    nDataSamples(s) = estimate_sample_count(data, nTimeStamps(s));

    timestampsFinite(s) = ...
        ~isempty(ts) && all(isfinite(ts(:)));

    dataFiniteSampled(s) = ...
        check_data_finite_sampled(data);

    if nTimeStamps(s) > 1

        dt = diff(ts);
        durationSec(s) = ts(end) - ts(1);

        if durationSec(s) > 0
            effectiveSrate(s) = ...
                (nTimeStamps(s) - 1) / durationSec(s);
        end

        medianDtSec(s) = median(dt);
        minDtSec(s) = min(dt);
        maxDtSec(s) = max(dt);

        timestampsStrictlyIncreasing(s) = ...
            timestampsFinite(s) && all(dt > 0);

        if isfinite(medianDtSec(s)) && medianDtSec(s) > 0
            robustGapLimitSec(s) = min( ...
                cfg.timestamp.maximumGapSec, ...
                max( ...
                    cfg.timestamp.minimumRobustGapSec, ...
                    cfg.timestamp.robustGapFactor * medianDtSec(s)));
        end
    end

    if isfinite(nDataSamples(s)) && isfinite(nTimeStamps(s))
        sampleTimestampMatch(s) = ...
            nDataSamples(s) == nTimeStamps(s);
    end

    if isfinite(srateNum) && isfinite(effectiveSrate(s))
        srateAbsDiff(s) = ...
            abs(effectiveSrate(s) - srateNum);

        if srateNum > 0
            srateRelDiff(s) = ...
                srateAbsDiff(s) / srateNum;
        end
    end

    %% Candidate detection

    isEEGCandidate(s) = ...
        strcmpi(streamTypes(s), "EEG") && ...
        isfinite(srateNum) && srateNum > 0 && ...
        isfinite(chanNum) && ...
        chanNum > cfg.eeg.minimumChannelCount;

    % Keep empty/bad GRF streams visible as candidates so they are audited
    % as unusable rather than being interpreted as "no GRF".
    isGRFCandidate(s) = ...
        strcmpi(streamNames(s), cfg.grf.streamName) || ...
        strcmpi(streamTypes(s), cfg.grf.streamType);

    %% Independent EEG and GRF usability checks

    [ ...
        isUsableEEG(s), ...
        eegQualityStatus(s), ...
        eegQualityReason(s)] = ...
        check_eeg_usability( ...
            isEEGCandidate(s), ...
            streamNames(s), ...
            srateNum, ...
            chanNum, ...
            nDataSamples(s), ...
            nTimeStamps(s), ...
            durationSec(s), ...
            effectiveSrate(s), ...
            maxDtSec(s), ...
            minDtSec(s), ...
            robustGapLimitSec(s), ...
            sampleTimestampMatch(s), ...
            timestampsFinite(s), ...
            timestampsStrictlyIncreasing(s), ...
            dataFiniteSampled(s), ...
            cfg);

    [ ...
        isUsableGRF(s), ...
        grfQualityStatus(s), ...
        grfQualityReason(s)] = ...
        check_grf_usability( ...
            isGRFCandidate(s), ...
            streamNames(s), ...
            streamTypes(s), ...
            chanNum, ...
            nDataSamples(s), ...
            nTimeStamps(s), ...
            durationSec(s), ...
            effectiveSrate(s), ...
            maxDtSec(s), ...
            minDtSec(s), ...
            robustGapLimitSec(s), ...
            sampleTimestampMatch(s), ...
            timestampsFinite(s), ...
            timestampsStrictlyIncreasing(s), ...
            dataFiniteSampled(s), ...
            cfg);
end

%% File-level EEG result

hasRealEEG = any(isEEGCandidate);
hasUsableEEG = any(isUsableEEG);

if hasUsableEEG
    fileEEGQualityStatus = "OK";
    fileEEGQualityReason = ...
        "at_least_one_usable_eeg_stream_found";
elseif hasRealEEG
    firstEEGIndex = find(isEEGCandidate, 1, 'first');
    fileEEGQualityStatus = ...
        eegQualityStatus(firstEEGIndex);
    fileEEGQualityReason = ...
        eegQualityReason(firstEEGIndex);
else
    fileEEGQualityStatus = "NO_EEG";
    fileEEGQualityReason = ...
        "no_real_eeg_stream_found";
end

%% File-level GRF result

grfCandidateIndices = find(isGRFCandidate);
hasGRFStream = ~isempty(grfCandidateIndices);

if numel(grfCandidateIndices) > 1

    % Downstream GRF extraction requires exactly one GRF candidate.
    isUsableGRF(grfCandidateIndices) = false;
    grfQualityStatus(grfCandidateIndices) = ...
        "BAD_multiple_grf_streams";
    grfQualityReason(grfCandidateIndices) = ...
        "more_than_one_GRF_or_Force_stream_was_found";

    hasUsableGRF = false;
    fileGRFQualityStatus = ...
        "BAD_multiple_grf_streams";
    fileGRFQualityReason = ...
        "exactly_one_GRF_or_Force_stream_is_required";

elseif numel(grfCandidateIndices) == 1

    grfIndex = grfCandidateIndices(1);

    hasUsableGRF = ...
        isUsableGRF(grfIndex);

    fileGRFQualityStatus = ...
        grfQualityStatus(grfIndex);

    fileGRFQualityReason = ...
        grfQualityReason(grfIndex);

else

    hasUsableGRF = false;
    fileGRFQualityStatus = "NO_GRF";
    fileGRFQualityReason = ...
        "no_GRF_name_or_Force_type_stream_found";
end

%% File summary

result.fileSummary = table( ...
    fileIndex, ...
    fileName, ...
    xdfPath, ...
    string(strjoin(cellstr(streamNames), ' | ')), ...
    hasRealEEG, ...
    hasUsableEEG, ...
    fileEEGQualityStatus, ...
    fileEEGQualityReason, ...
    hasGRFStream, ...
    hasUsableGRF, ...
    fileGRFQualityStatus, ...
    fileGRFQualityReason, ...
    'VariableNames', { ...
        'FileIndex', ...
        'FileName', ...
        'FullPath', ...
        'AllStreams', ...
        'HasRealEEG', ...
        'HasUsableEEG', ...
        'FileEEGQualityStatus', ...
        'FileEEGQualityReason', ...
        'HasGRFStream', ...
        'HasUsableGRF', ...
        'FileGRFQualityStatus', ...
        'FileGRFQualityReason'});

%% Stream-level tables

for s = 1:nStreams

    streamRow = table( ...
        fileIndex, ...
        fileName, ...
        xdfPath, ...
        s, ...
        streamNames(s), ...
        streamTypes(s), ...
        streamRates(s), ...
        streamChans(s), ...
        isEEGCandidate(s), ...
        isUsableEEG(s), ...
        isGRFCandidate(s), ...
        isUsableGRF(s), ...
        nDataSamples(s), ...
        nTimeStamps(s), ...
        durationSec(s), ...
        effectiveSrate(s), ...
        medianDtSec(s), ...
        minDtSec(s), ...
        maxDtSec(s), ...
        srateAbsDiff(s), ...
        srateRelDiff(s), ...
        sampleTimestampMatch(s), ...
        timestampsFinite(s), ...
        timestampsStrictlyIncreasing(s), ...
        dataFiniteSampled(s), ...
        robustGapLimitSec(s), ...
        eegQualityStatus(s), ...
        eegQualityReason(s), ...
        grfQualityStatus(s), ...
        grfQualityReason(s), ...
        'VariableNames', { ...
            'FileIndex', ...
            'FileName', ...
            'FullPath', ...
            'StreamIndex', ...
            'StreamName', ...
            'StreamType', ...
            'NominalSrate', ...
            'ChannelCount', ...
            'IsRealEEG', ...
            'IsUsableEEG', ...
            'IsGRFCandidate', ...
            'IsUsableGRF', ...
            'NDataSamples', ...
            'NTimeStamps', ...
            'DurationSec', ...
            'EffectiveSrate', ...
            'MedianDtSec', ...
            'MinDtSec', ...
            'MaxDtSec', ...
            'SrateAbsDiff', ...
            'SrateRelDiff', ...
            'SampleTimestampMatch', ...
            'TimestampsFinite', ...
            'TimestampsStrictlyIncreasing', ...
            'DataFiniteSampled', ...
            'RobustGapLimitSec', ...
            'EEGQualityStatus', ...
            'EEGQualityReason', ...
            'GRFQualityStatus', ...
            'GRFQualityReason'});

    result.streamDetail = ...
        [result.streamDetail; streamRow]; %#ok<AGROW>

end

end

function value = get_xdf_info_field(info, fieldName)

value = "";

try
    if ~isfield(info, fieldName)
        return;
    end

    rawValue = info.(fieldName);

    if iscell(rawValue)
        if ~isempty(rawValue)
            value = string(rawValue{1});
        end
    elseif ischar(rawValue) || ...
            isstring(rawValue) || ...
            isnumeric(rawValue)
        value = string(rawValue);
    else
        value = string(rawValue);
    end
catch
    value = "";
end

end

function nSamples = estimate_sample_count(data, nTimeStamps)

nSamples = NaN;

if isempty(data)
    nSamples = 0;
    return;
end

try
    if iscell(data)
        nSamples = numel(data);
        return;
    end

    if ~(isnumeric(data) || islogical(data))
        nSamples = numel(data);
        return;
    end

    if isvector(data)
        nSamples = numel(data);
        return;
    end

    dataSize = size(data);
    dim1 = dataSize(1);
    dim2 = dataSize(2);

    if isfinite(nTimeStamps) && nTimeStamps > 0
        if dim2 == nTimeStamps
            nSamples = dim2;
        elseif dim1 == nTimeStamps
            nSamples = dim1;
        else
            nSamples = max(dim1, dim2);
        end
    else
        nSamples = max(dim1, dim2);
    end

catch
    nSamples = NaN;
end

end

function [usable, status, reason] = check_eeg_usability( ...
        isEEGCandidate, ...
        streamName, ...
        nominalSrate, ...
        channelCount, ...
        nDataSamples, ...
        nTimeStamps, ...
        durationSec, ...
        effectiveSrate, ...
        maxDtSec, ...
        minDtSec, ...
        robustGapLimitSec, ...
        sampleTimestampMatch, ...
        timestampsFinite, ...
        timestampsStrictlyIncreasing, ...
        dataFiniteSampled, ...
        cfg)

usable = false;
status = "NOT_EEG";
reason = "stream_is_not_a_real_eeg_candidate";

if ~isEEGCandidate
    return;
end

streamNameWarning = ...
    streamName ~= cfg.eeg.streamName;

if strlength(streamName) == 0

    status = "BAD_missing_stream_name";
    reason = "eeg_stream_name_is_empty";

elseif ~isfinite(nominalSrate) || ...
        nominalSrate <= 0 || ...
        abs(nominalSrate - cfg.eeg.nominalSrateHz) > ...
            cfg.eeg.absoluteSrateToleranceHz

    status = "BAD_nominal_srate";
    reason = ...
        "nominal_sampling_rate_is_not_close_to_expected_500_Hz";

elseif ~isfinite(channelCount) || ...
        channelCount <= cfg.eeg.minimumChannelCount

    status = "BAD_channel_count";
    reason = "channel_count_is_too_low_for_eeg";

elseif ~isfinite(nDataSamples) || nDataSamples <= 0

    status = "BAD_no_data_samples";
    reason = "eeg_data_samples_are_empty";

elseif ~isfinite(nTimeStamps) || nTimeStamps <= 0

    status = "BAD_no_timestamps";
    reason = "eeg_timestamps_are_empty";

elseif ~sampleTimestampMatch

    status = "BAD_sample_timestamp_mismatch";
    reason = ...
        "number_of_data_samples_does_not_match_number_of_timestamps";

elseif ~timestampsFinite

    status = "BAD_nonfinite_timestamps";
    reason = "timestamps_contain_NaN_or_Inf";

elseif ~timestampsStrictlyIncreasing || ...
        ~isfinite(minDtSec) || minDtSec <= 0

    status = "BAD_nonmonotonic_timestamps";
    reason = ...
        "timestamps_are_repeated_or_not_strictly_increasing";

elseif ~dataFiniteSampled

    status = "BAD_nonfinite_data";
    reason = ...
        "sampled_EEG_data_contain_NaN_or_Inf";

elseif ~isfinite(durationSec) || durationSec <= 0

    status = "BAD_duration";
    reason = "eeg_duration_is_missing_or_invalid";

elseif durationSec < cfg.eeg.minimumDurationSec

    status = "BAD_too_short";
    reason = ...
        "eeg_duration_is_shorter_than_minimum_required_duration";

elseif ~isfinite(effectiveSrate) || effectiveSrate <= 0

    status = "BAD_effective_srate";
    reason = ...
        "effective_sampling_rate_is_missing_or_invalid";

elseif abs(effectiveSrate - nominalSrate) > ...
        max( ...
            cfg.eeg.absoluteSrateToleranceHz, ...
            nominalSrate * cfg.eeg.relativeSrateTolerance)

    status = "BAD_effective_srate";
    reason = ...
        "effective_sampling_rate_is_too_far_from_nominal_sampling_rate";

elseif ~isfinite(maxDtSec) || maxDtSec <= 0 || ...
        ~isfinite(robustGapLimitSec) || robustGapLimitSec <= 0

    status = "BAD_timestamp_gap";
    reason = ...
        "timestamp_gap_information_is_missing_or_invalid";

elseif maxDtSec > robustGapLimitSec

    status = "BAD_large_timestamp_gap";
    reason = ...
        "maximum_timestamp_gap_exceeds_robust_limit";

else

    usable = true;

    if streamNameWarning
        status = "WARNING_unexpected_eeg_stream_name";
        reason = ...
            "eeg_stream_is_usable_but_name_is_not_the_expected_liveamp_stream";
    else
        status = "OK";
        reason = ...
            "eeg_stream_passed_basic_usability_checks";
    end
end

end

function [usable, status, reason] = check_grf_usability( ...
        isGRFCandidate, ...
        streamName, ...
        streamType, ...
        channelCount, ...
        nDataSamples, ...
        nTimeStamps, ...
        durationSec, ...
        effectiveSrate, ...
        maxDtSec, ...
        minDtSec, ...
        robustGapLimitSec, ...
        sampleTimestampMatch, ...
        timestampsFinite, ...
        timestampsStrictlyIncreasing, ...
        dataFiniteSampled, ...
        cfg)

usable = false;
status = "NOT_GRF";
reason = "stream_is_not_a_GRF_candidate";

if ~isGRFCandidate
    return;
end

identityWarning = ...
    ~strcmpi(streamName, cfg.grf.streamName) || ...
    ~strcmpi(streamType, cfg.grf.streamType);

if ~isfinite(channelCount) || ...
        channelCount ~= cfg.grf.expectedChannelCount

    status = "BAD_channel_count";
    reason = ...
        "GRF_stream_does_not_have_the_expected_8_channels";

elseif ~isfinite(nDataSamples) || nDataSamples <= 0

    status = "BAD_no_data_samples";
    reason = "GRF_data_samples_are_empty";

elseif ~isfinite(nTimeStamps) || nTimeStamps <= 0

    status = "BAD_no_timestamps";
    reason = "GRF_timestamps_are_empty";

elseif ~sampleTimestampMatch

    status = "BAD_sample_timestamp_mismatch";
    reason = ...
        "number_of_GRF_data_samples_does_not_match_timestamps";

elseif ~timestampsFinite

    status = "BAD_nonfinite_timestamps";
    reason = "GRF_timestamps_contain_NaN_or_Inf";

elseif ~timestampsStrictlyIncreasing || ...
        ~isfinite(minDtSec) || minDtSec <= 0

    status = "BAD_nonmonotonic_timestamps";
    reason = ...
        "GRF_timestamps_are_repeated_or_not_strictly_increasing";

elseif ~dataFiniteSampled

    status = "BAD_nonfinite_data";
    reason = ...
        "sampled_GRF_data_contain_NaN_or_Inf";

elseif ~isfinite(durationSec) || durationSec <= 0

    status = "BAD_duration";
    reason = ...
        "GRF_duration_is_missing_or_invalid";

elseif durationSec < cfg.grf.minimumDurationSec

    status = "BAD_too_short";
    reason = ...
        "GRF_duration_is_shorter_than_minimum_required_duration";

elseif ~isfinite(effectiveSrate) || effectiveSrate <= 0

    status = "BAD_effective_srate";
    reason = ...
        "GRF_effective_sampling_rate_is_missing_or_invalid";

elseif ~isfinite(maxDtSec) || maxDtSec <= 0 || ...
        ~isfinite(robustGapLimitSec) || robustGapLimitSec <= 0

    status = "BAD_timestamp_gap";
    reason = ...
        "GRF_timestamp_gap_information_is_missing_or_invalid";

elseif maxDtSec > robustGapLimitSec

    status = "BAD_large_timestamp_gap";
    reason = ...
        "maximum_GRF_timestamp_gap_exceeds_robust_limit";

else

    usable = true;

    if identityWarning
        status = "WARNING_unexpected_grf_identity";
        reason = ...
            "GRF_is_usable_but_name_or_type_differs_from_expected";
    else
        status = "OK";
        reason = ...
            "GRF_stream_passed_basic_usability_checks";
    end
end

end

function finiteOK = check_data_finite_sampled(data)

finiteOK = false;

if isempty(data) || ...
        ~(isnumeric(data) || islogical(data))
    return;
end

try
    n = numel(data);
    step = max(1, floor(n / 500000));
    sampled = double(data(1:step:end));
    finiteOK = all(isfinite(sampled(:)));
catch
    finiteOK = false;
end

end

function fileRow = make_load_error_row( ...
        fileIndex, fileName, xdfPath, ME)

fileRow = table( ...
    fileIndex, ...
    fileName, ...
    xdfPath, ...
    string("ERROR: " + ME.message), ...
    false, ...
    false, ...
    "LOAD_ERROR", ...
    string(ME.message), ...
    false, ...
    false, ...
    "LOAD_ERROR", ...
    string(ME.message), ...
    'VariableNames', { ...
        'FileIndex', ...
        'FileName', ...
        'FullPath', ...
        'AllStreams', ...
        'HasRealEEG', ...
        'HasUsableEEG', ...
        'FileEEGQualityStatus', ...
        'FileEEGQualityReason', ...
        'HasGRFStream', ...
        'HasUsableGRF', ...
        'FileGRFQualityStatus', ...
        'FileGRFQualityReason'});

end
