function outputTable = read_csv_with_string_text(csvFile)
%READ_CSV_WITH_STRING_TEXT Read a HipExo CSV table using string text columns.

outputTable = readtable( ...
    csvFile, ...
    'FileType', 'text', ...
    'Delimiter', ',', ...
    'ReadVariableNames', true, ...
    'TextType', 'string', ...
    'VariableNamingRule', 'preserve');

end
