function resolvedPath = resolve_current_xdf_path( ...
        originalPath, ...
        currentRawDataFolder, ...
        rawSubject, ...
        rawDay, ...
        rawSession, ...
        fileName)
% GOAL
%   Resolve an XDF referenced by an existing QC table after the project has
%   moved between computers, drives, or operating systems.
% METHOD
%   Prefer the path rebuilt below the current raw-data root. If that does
%   not exist, fall back to the original stored path.

originalPath = string(originalPath);

configuredPath = string(fullfile( ...
    currentRawDataFolder, ...
    char(rawSubject), ...
    char(rawDay), ...
    'data', ...
    char(rawSession), ...
    'eeg', ...
    char(fileName)));

if isfile(configuredPath)
    resolvedPath = configuredPath;
    return;
end

if isfile(originalPath)
    resolvedPath = originalPath;
    return;
end

error([ ...
    'Cannot resolve an XDF file from the QC table.\n' ...
    'Current raw-data candidate:\n%s\n\n' ...
    'Path stored in the QC table:\n%s\n\n' ...
    'Check project_paths.m or rerun Step 01.'], ...
    configuredPath, ...
    originalPath);

end
