function [cycleQC, segmentSummary, edgeEvents] = ...
    validate_grf_gait_event_table(eventTable, sourceEventFile, settings)
% Validate one GRF gait-event table before any EEG mapping.
%
% This function performs only GRF-domain gait-cycle QC. EEG overlap and
% boundary checks are applied later in Step 04.

requiredVariables = { ...
    'Subject', ...
    'Day', ...
    'Session', ...
    'Condition', ...
    'SegmentIndex', ...
    'EventType', ...
    'Side', ...
    'GRFSample', ...
    'SegmentSample', ...
    'LSLTime', ...
    'TimeFromSegmentStartSec', ...
    'XDFPath', ...
    'SourceGRFFile'};

missingVariables = requiredVariables( ...
    ~ismember(requiredVariables, eventTable.Properties.VariableNames));

if ~isempty(missingVariables)
    error('Event source is missing required columns: %s\nFile: %s', ...
        strjoin(missingVariables, ', '), sourceEventFile);
end

stringVariables = { ...
    'Subject', 'Day', 'Session', 'Condition', 'EventType', ...
    'Side', 'XDFPath', 'SourceGRFFile'};

for iVariable = 1:numel(stringVariables)
    variableName = stringVariables{iVariable};
    eventTable.(variableName) = ...
        strtrim(string(eventTable.(variableName)));
end

eventTable.EventType = upper(eventTable.EventType);

numericVariables = { ...
    'SegmentIndex', 'GRFSample', 'SegmentSample', ...
    'LSLTime', 'TimeFromSegmentStartSec'};

for iVariable = 1:numel(numericVariables)
    variableName = numericVariables{iVariable};
    eventTable.(variableName) = ...
        numeric_column_local(eventTable.(variableName));
end

if any(~isfinite(eventTable.SegmentIndex)) || ...
        any(~isfinite(eventTable.SegmentSample)) || ...
        any(~isfinite(eventTable.LSLTime))
    error('Event source contains non-numeric segment/sample/time values:\n%s', ...
        sourceEventFile);
end

knownEventTypes = ["RHS", "LTO", "LHS", "RTO"];
unknownEventTypes = unique(eventTable.EventType( ...
    ~ismember(eventTable.EventType, knownEventTypes)));

if ~isempty(unknownEventTypes)
    warning('Unknown event type(s) in %s: %s', ...
        sourceEventFile, strjoin(unknownEventTypes, ', '));
end

cycleQC = empty_cycle_table_local();
segmentSummary = empty_summary_table_local();
edgeEvents = empty_edge_event_table_local();

xdfPaths = unique(eventTable.XDFPath, 'stable');

for iXDF = 1:numel(xdfPaths)

    currentXDF = xdfPaths(iXDF);
    xdfRows = eventTable.XDFPath == currentXDF;
    segmentIndices = unique(eventTable.SegmentIndex(xdfRows), 'stable');

    for iSegment = 1:numel(segmentIndices)

        currentSegment = segmentIndices(iSegment);
        currentRows = xdfRows & ...
            eventTable.SegmentIndex == currentSegment;

        segmentEvents = eventTable(currentRows, :);
        segmentEvents = sortrows(segmentEvents, ...
            {'SegmentSample', 'LSLTime'});

        [currentCycles, currentSummary, currentEdgeEvents] = ...
            validate_one_segment_local( ...
                segmentEvents, sourceEventFile, settings);

        cycleQC = append_table_local(cycleQC, currentCycles);
        segmentSummary = append_table_local(segmentSummary, currentSummary);
        edgeEvents = append_table_local(edgeEvents, currentEdgeEvents);
    end
end

end

function [cycleQC, summaryTable, edgeEvents] = ...
    validate_one_segment_local(segmentEvents, sourceEventFile, settings)

eventTypes = string(segmentEvents.EventType);
rhsRows = find(eventTypes == "RHS");
numberOfCycles = max(0, numel(rhsRows) - 1);

cycleRows = repmat(cycle_row_template_local(), 0, 1);

subject = string(segmentEvents.Subject(1));
day = string(segmentEvents.Day(1));
session = string(segmentEvents.Session(1));
condition = string(segmentEvents.Condition(1));
xdfPath = string(segmentEvents.XDFPath(1));
sourceGRFFile = string(segmentEvents.SourceGRFFile(1));
segmentIndex = double(segmentEvents.SegmentIndex(1));
runLabel = extract_run_label_local(xdfPath);

[~, xdfBaseName] = fileparts(char(xdfPath));

for iCycle = 1:numberOfCycles

    firstRHSRow = rhsRows(iCycle);
    secondRHSRow = rhsRows(iCycle + 1);
    cycleIndices = firstRHSRow:secondRHSRow;
    sequence = eventTypes(cycleIndices);

    row = cycle_row_template_local();

    row.SourceEventFile = string(sourceEventFile);
    row.Subject = subject;
    row.Day = day;
    row.Session = session;
    row.Condition = condition;
    row.Run = runLabel;
    row.XDFPath = xdfPath;
    row.SourceGRFFile = sourceGRFFile;
    row.SegmentIndex = segmentIndex;
    row.CycleIndex = iCycle;
    row.CycleID = string(sprintf( ...
        '%s_segment-%02d_cycle-%04d', ...
        xdfBaseName, round(segmentIndex), iCycle));

    row.SequenceObserved = strjoin(sequence, "-");
    row.LTOCount = sum(sequence == "LTO");
    row.LHSCount = sum(sequence == "LHS");
    row.RTOCount = sum(sequence == "RTO");
    row.RHSCountInWindow = sum(sequence == "RHS");

    expectedSequence = ["RHS"; "LTO"; "LHS"; "RTO"; "RHS"];

    row.LogicValid = ...
        numel(sequence) == numel(expectedSequence) && ...
        all(sequence(:) == expectedSequence);

    row.EdgeCycle = ...
        iCycle == 1 || iCycle == numberOfCycles;

    row.RHS1_GRFSample = segmentEvents.GRFSample(firstRHSRow);
    row.RHS2_GRFSample = segmentEvents.GRFSample(secondRHSRow);
    row.RHS1_SegmentSample = segmentEvents.SegmentSample(firstRHSRow);
    row.RHS2_SegmentSample = segmentEvents.SegmentSample(secondRHSRow);
    row.RHS1_LSLTime = segmentEvents.LSLTime(firstRHSRow);
    row.RHS2_LSLTime = segmentEvents.LSLTime(secondRHSRow);
    row.RHS1_TimeFromSegmentStartSec = ...
        segmentEvents.TimeFromSegmentStartSec(firstRHSRow);
    row.RHS2_TimeFromSegmentStartSec = ...
        segmentEvents.TimeFromSegmentStartSec(secondRHSRow);

    row.LTO_GRFSample = first_event_value_local( ...
        segmentEvents, eventTypes, cycleIndices, "LTO", 'GRFSample');
    row.LHS_GRFSample = first_event_value_local( ...
        segmentEvents, eventTypes, cycleIndices, "LHS", 'GRFSample');
    row.RTO_GRFSample = first_event_value_local( ...
        segmentEvents, eventTypes, cycleIndices, "RTO", 'GRFSample');

    row.LTO_LSLTime = first_event_value_local( ...
        segmentEvents, eventTypes, cycleIndices, "LTO", 'LSLTime');
    row.LHS_LSLTime = first_event_value_local( ...
        segmentEvents, eventTypes, cycleIndices, "LHS", 'LSLTime');
    row.RTO_LSLTime = first_event_value_local( ...
        segmentEvents, eventTypes, cycleIndices, "RTO", 'LSLTime');

    row.LTO_TimeFromSegmentStartSec = first_event_value_local( ...
        segmentEvents, eventTypes, cycleIndices, "LTO", ...
        'TimeFromSegmentStartSec');
    row.LHS_TimeFromSegmentStartSec = first_event_value_local( ...
        segmentEvents, eventTypes, cycleIndices, "LHS", ...
        'TimeFromSegmentStartSec');
    row.RTO_TimeFromSegmentStartSec = first_event_value_local( ...
        segmentEvents, eventTypes, cycleIndices, "RTO", ...
        'TimeFromSegmentStartSec');

    row.StrideSec = row.RHS2_LSLTime - row.RHS1_LSLTime;

    if row.LTOCount == 1 && row.LHSCount == 1 && row.RTOCount == 1
        row.RHS_to_LTO_Sec = row.LTO_LSLTime - row.RHS1_LSLTime;
        row.LTO_to_LHS_Sec = row.LHS_LSLTime - row.LTO_LSLTime;
        row.LHS_to_RTO_Sec = row.RTO_LSLTime - row.LHS_LSLTime;
        row.RTO_to_RHS2_Sec = row.RHS2_LSLTime - row.RTO_LSLTime;
        row.RightStanceSec = row.RTO_LSLTime - row.RHS1_LSLTime;
    end

    row.AbsoluteStrideFlag = ...
        ~isfinite(row.StrideSec) || ...
        row.StrideSec < settings.MinimumStrideSec || ...
        row.StrideSec > settings.MaximumStrideSec;

    row.QCReason = structural_reason_local( ...
        sequence, row.LTOCount, row.LHSCount, row.RTOCount, row.LogicValid);

    cycleRows(end + 1, 1) = row; %#ok<AGROW>
end

if isempty(cycleRows)
    cycleQC = empty_cycle_table_local();
else
    cycleQC = struct2table(cycleRows);
end

if ~isempty(cycleQC)

    usableForReference = ...
        cycleQC.LogicValid & ...
        isfinite(cycleQC.StrideSec) & ...
        ~cycleQC.AbsoluteStrideFlag;

    referenceStrides = cycleQC.StrideSec(usableForReference);

    if numel(referenceStrides) >= 5
        strideMedian = median(referenceStrides);
        strideMAD = median(abs(referenceStrides - strideMedian));

        if isfinite(strideMAD) && strideMAD > eps(strideMedian)
            robustScale = 1.4826 * strideMAD;
            robustDistance = abs( ...
                cycleQC.StrideSec - strideMedian) ./ robustScale;

            cycleQC.RobustStrideOutlier = ...
                cycleQC.LogicValid & ...
                isfinite(robustDistance) & ...
                robustDistance > settings.RobustOutlierZ;
        end
    end

    cycleQC.StrideFlag = ...
        cycleQC.AbsoluteStrideFlag | ...
        cycleQC.RobustStrideOutlier;

    conservativeEdgeExclusion = ...
        settings.ExcludeFirstAndLastCycle & cycleQC.EdgeCycle;

    cycleQC.GRFRecommendedForEpoch = ...
        cycleQC.LogicValid & ...
        ~cycleQC.StrideFlag & ...
        ~conservativeEdgeExclusion;

    cycleQC.ManualGRFReviewRecommended = ...
        (~cycleQC.LogicValid & ~cycleQC.EdgeCycle) | ...
        cycleQC.StrideFlag;

    for iCycle = 1:height(cycleQC)
        reason = cycleQC.QCReason(iCycle);

        if cycleQC.AbsoluteStrideFlag(iCycle)
            reason = append_reason_local(reason, sprintf( ...
                'StrideOutside%.2fTo%.2fSec', ...
                settings.MinimumStrideSec, ...
                settings.MaximumStrideSec));
        end

        if cycleQC.RobustStrideOutlier(iCycle)
            reason = append_reason_local(reason, 'RobustStrideOutlier');
        end

        if conservativeEdgeExclusion(iCycle)
            reason = append_reason_local( ...
                reason, 'ConservativeSegmentEdgeExclusion');
        end

        if strlength(reason) == 0
            reason = "OK";
        end

        cycleQC.QCReason(iCycle) = reason;
    end
end

edgeEvents = build_edge_event_table_local( ...
    segmentEvents, rhsRows, sourceEventFile, runLabel);

leadingEventCount = sum( ...
    edgeEvents.EdgePosition == "before_first_RHS");
trailingPartialEventCount = sum( ...
    edgeEvents.EdgePosition == "trailing_partial_cycle");

summary = summary_row_template_local();
summary.SourceEventFile = string(sourceEventFile);
summary.Subject = subject;
summary.Day = day;
summary.Session = session;
summary.Condition = condition;
summary.Run = runLabel;
summary.XDFPath = xdfPath;
summary.SourceGRFFile = sourceGRFFile;
summary.SegmentIndex = segmentIndex;
summary.RecordingStartLSLTime = min(segmentEvents.LSLTime);
summary.TotalEventCount = height(segmentEvents);
summary.RHSCount = numel(rhsRows);
summary.CycleCount = height(cycleQC);
summary.LogicValidCycleCount = sum(cycleQC.LogicValid);
summary.LogicInvalidCycleCount = sum(~cycleQC.LogicValid);
summary.InternalInvalidCycleCount = sum( ...
    ~cycleQC.LogicValid & ~cycleQC.EdgeCycle);
summary.EdgeInvalidCycleCount = sum( ...
    ~cycleQC.LogicValid & cycleQC.EdgeCycle);
summary.StrideFlagCount = sum(cycleQC.StrideFlag);
summary.GRFRecommendedCycleCount = sum(cycleQC.GRFRecommendedForEpoch);
summary.ManualGRFReviewCycleCount = sum( ...
    cycleQC.ManualGRFReviewRecommended);
summary.LeadingEventCount = leadingEventCount;
summary.TrailingPartialEventCount = trailingPartialEventCount;

finiteStrides = cycleQC.StrideSec(isfinite(cycleQC.StrideSec));

if ~isempty(finiteStrides)
    summary.MedianStrideSec = median(finiteStrides);
    summary.MinimumStrideSec = min(finiteStrides);
    summary.MaximumStrideSec = max(finiteStrides);
end

if numel(rhsRows) < 2
    summary.SegmentStatus = "fail_no_complete_RHS_cycle";
elseif summary.InternalInvalidCycleCount > 0 || summary.StrideFlagCount > 0
    summary.SegmentStatus = "needs_raw_grf_review";
elseif summary.GRFRecommendedCycleCount == 0
    summary.SegmentStatus = "fail_no_recommended_GRF_cycle";
elseif summary.LogicInvalidCycleCount > 0 || ...
        leadingEventCount > 0 || trailingPartialEventCount > 0
    summary.SegmentStatus = "pass_with_exclusions";
else
    summary.SegmentStatus = "pass";
end

summaryTable = struct2table(summary);

end

function edgeTable = build_edge_event_table_local( ...
    segmentEvents, rhsRows, sourceEventFile, runLabel)

edgeRows = repmat(edge_event_row_template_local(), 0, 1);

if isempty(rhsRows)
    edgeIndices = 1:height(segmentEvents);
    edgePositions = repmat("no_RHS_in_segment", numel(edgeIndices), 1);
else
    leadingIndices = 1:(rhsRows(1) - 1);

    if rhsRows(end) < height(segmentEvents)
        trailingIndices = rhsRows(end):height(segmentEvents);
    else
        trailingIndices = zeros(1, 0);
    end

    edgeIndices = [leadingIndices, trailingIndices];
    edgePositions = [ ...
        repmat("before_first_RHS", numel(leadingIndices), 1); ...
        repmat("trailing_partial_cycle", numel(trailingIndices), 1)];
end

for iEvent = 1:numel(edgeIndices)
    sourceRow = edgeIndices(iEvent);
    row = edge_event_row_template_local();

    row.SourceEventFile = string(sourceEventFile);
    row.Subject = string(segmentEvents.Subject(sourceRow));
    row.Day = string(segmentEvents.Day(sourceRow));
    row.Session = string(segmentEvents.Session(sourceRow));
    row.Condition = string(segmentEvents.Condition(sourceRow));
    row.Run = runLabel;
    row.XDFPath = string(segmentEvents.XDFPath(sourceRow));
    row.SourceGRFFile = string(segmentEvents.SourceGRFFile(sourceRow));
    row.SegmentIndex = double(segmentEvents.SegmentIndex(sourceRow));
    row.EventType = string(segmentEvents.EventType(sourceRow));
    row.Side = string(segmentEvents.Side(sourceRow));
    row.GRFSample = double(segmentEvents.GRFSample(sourceRow));
    row.SegmentSample = double(segmentEvents.SegmentSample(sourceRow));
    row.LSLTime = double(segmentEvents.LSLTime(sourceRow));
    row.TimeFromSegmentStartSec = double( ...
        segmentEvents.TimeFromSegmentStartSec(sourceRow));
    row.EdgePosition = edgePositions(iEvent);

    edgeRows(end + 1, 1) = row; %#ok<AGROW>
end

if isempty(edgeRows)
    edgeTable = empty_edge_event_table_local();
else
    edgeTable = struct2table(edgeRows);
end

end

function row = cycle_row_template_local()

row = struct( ...
    'SourceEventFile', "", ...
    'Subject', "", ...
    'Day', "", ...
    'Session', "", ...
    'Condition', "", ...
    'Run', "", ...
    'XDFPath', "", ...
    'SourceGRFFile', "", ...
    'SegmentIndex', NaN, ...
    'CycleIndex', NaN, ...
    'CycleID', "", ...
    'SequenceObserved', "", ...
    'LTOCount', NaN, ...
    'LHSCount', NaN, ...
    'RTOCount', NaN, ...
    'RHSCountInWindow', NaN, ...
    'LogicValid', false, ...
    'EdgeCycle', false, ...
    'RHS1_GRFSample', NaN, ...
    'LTO_GRFSample', NaN, ...
    'LHS_GRFSample', NaN, ...
    'RTO_GRFSample', NaN, ...
    'RHS2_GRFSample', NaN, ...
    'RHS1_SegmentSample', NaN, ...
    'RHS2_SegmentSample', NaN, ...
    'RHS1_LSLTime', NaN, ...
    'LTO_LSLTime', NaN, ...
    'LHS_LSLTime', NaN, ...
    'RTO_LSLTime', NaN, ...
    'RHS2_LSLTime', NaN, ...
    'RHS1_TimeFromSegmentStartSec', NaN, ...
    'LTO_TimeFromSegmentStartSec', NaN, ...
    'LHS_TimeFromSegmentStartSec', NaN, ...
    'RTO_TimeFromSegmentStartSec', NaN, ...
    'RHS2_TimeFromSegmentStartSec', NaN, ...
    'StrideSec', NaN, ...
    'RHS_to_LTO_Sec', NaN, ...
    'LTO_to_LHS_Sec', NaN, ...
    'LHS_to_RTO_Sec', NaN, ...
    'RTO_to_RHS2_Sec', NaN, ...
    'RightStanceSec', NaN, ...
    'AbsoluteStrideFlag', false, ...
    'RobustStrideOutlier', false, ...
    'StrideFlag', false, ...
    'GRFRecommendedForEpoch', false, ...
    'EEGMappingAvailable', false, ...
    'EEGAllEventsMapped', false, ...
    'EEGCycleCrossesBoundary', false, ...
    'EEGValidCycle', false, ...
    'EEGQCReason', "not_evaluated_until_step04", ...
    'RecommendedForEpoch', false, ...
    'ManualGRFReviewRecommended', false, ...
    'QCReason', "");

end

function row = edge_event_row_template_local()

row = struct( ...
    'SourceEventFile', "", ...
    'Subject', "", ...
    'Day', "", ...
    'Session', "", ...
    'Condition', "", ...
    'Run', "", ...
    'XDFPath', "", ...
    'SourceGRFFile', "", ...
    'SegmentIndex', NaN, ...
    'EventType', "", ...
    'Side', "", ...
    'GRFSample', NaN, ...
    'SegmentSample', NaN, ...
    'LSLTime', NaN, ...
    'TimeFromSegmentStartSec', NaN, ...
    'EdgePosition', "");

end

function row = summary_row_template_local()

row = struct( ...
    'SourceEventFile', "", ...
    'Subject', "", ...
    'Day', "", ...
    'Session', "", ...
    'Condition', "", ...
    'Run', "", ...
    'XDFPath', "", ...
    'SourceGRFFile', "", ...
    'SegmentIndex', NaN, ...
    'RecordingStartLSLTime', NaN, ...
    'TotalEventCount', NaN, ...
    'RHSCount', NaN, ...
    'CycleCount', NaN, ...
    'LogicValidCycleCount', NaN, ...
    'LogicInvalidCycleCount', NaN, ...
    'InternalInvalidCycleCount', NaN, ...
    'EdgeInvalidCycleCount', NaN, ...
    'StrideFlagCount', NaN, ...
    'GRFRecommendedCycleCount', NaN, ...
    'EEGValidCycleCount', NaN, ...
    'EEGInvalidCycleCount', NaN, ...
    'RecommendedCycleCount', NaN, ...
    'ManualGRFReviewCycleCount', NaN, ...
    'LeadingEventCount', NaN, ...
    'TrailingPartialEventCount', NaN, ...
    'MedianStrideSec', NaN, ...
    'MinimumStrideSec', NaN, ...
    'MaximumStrideSec', NaN, ...
    'SegmentStatus', "");

end

function tableOutput = empty_cycle_table_local()
tableOutput = struct2table(cycle_row_template_local());
tableOutput(1, :) = [];
end

function tableOutput = empty_edge_event_table_local()
tableOutput = struct2table(edge_event_row_template_local());
tableOutput(1, :) = [];
end

function tableOutput = empty_summary_table_local()
tableOutput = struct2table(summary_row_template_local());
tableOutput(1, :) = [];
end

function output = append_table_local(output, input)
if isempty(input)
    return;
elseif isempty(output)
    output = input;
else
    output = [output; input]; %#ok<AGROW>
end
end

function value = first_event_value_local( ...
    eventTable, eventTypes, cycleIndices, targetType, variableName)
matchingRows = cycleIndices(eventTypes(cycleIndices) == targetType);
if isempty(matchingRows)
    value = NaN;
else
    value = double(eventTable.(variableName)(matchingRows(1)));
end
end

function runLabel = extract_run_label_local(xdfPath)
tokens = regexp(char(xdfPath), 'run-([0-9]+)', 'tokens', 'once');
if isempty(tokens)
    runLabel = "unknown";
else
    runLabel = "run-" + string(tokens{1});
end
end

function reason = structural_reason_local( ...
    sequence, ltoCount, lhsCount, rtoCount, logicValid)
if logicValid
    reason = "";
    return;
end
reasons = strings(0, 1);
reasons = add_count_reason_local(reasons, "LTO", ltoCount);
reasons = add_count_reason_local(reasons, "LHS", lhsCount);
reasons = add_count_reason_local(reasons, "RTO", rtoCount);
knownTypes = ["RHS", "LTO", "LHS", "RTO"];
unknownTypes = unique(sequence(~ismember(sequence, knownTypes)));
if ~isempty(unknownTypes)
    reasons(end + 1, 1) = ...
        "UnexpectedEventType(" + strjoin(unknownTypes, "+") + ")";
end
if isempty(reasons)
    reasons(end + 1, 1) = "WrongEventOrder";
end
reason = strjoin(reasons, ";");
end

function reasons = add_count_reason_local(reasons, eventType, count)
if count == 0
    reasons(end + 1, 1) = "Missing" + eventType;
elseif count > 1
    reasons(end + 1, 1) = ...
        "Duplicate" + eventType + "(" + string(count) + ")";
end
end

function outputReason = append_reason_local(inputReason, newReason)
inputReason = string(inputReason);
newReason = string(newReason);
if strlength(inputReason) == 0
    outputReason = newReason;
else
    outputReason = inputReason + ";" + newReason;
end
end

function values = numeric_column_local(values)
if isnumeric(values)
    values = double(values);
elseif islogical(values)
    values = double(values);
else
    values = str2double(string(values));
end
end
