% GOAL
%   Detect RHS, RTO, LHS, and LTO for every accepted walking interval in
%   one batch-selected extracted GRF recording.
% INPUT
%   GRF_BATCH_GRF_STREAM_FILE and GRF_BATCH_GRF_OUTPUT_FOLDER supplied
%   internally by step03_process_subject_grf_eeg.m.
% OUTPUT
%   *_GRF_gait_events.mat
%   *_GRF_gait_events.csv
%   *_GRF_gait_events_QC*.png
% METHOD
%   Call hipexo.detect_GRF_gait_events() for each accepted interval and
%   preserve the current unattended QC gate and provenance logic.

batchModeRequested = ~isempty(strtrim( ...
    getenv('GRF_BATCH_GRF_OUTPUT_FOLDER')));

batchUnattended = strcmpi(strtrim( ...
    getenv('GRF_BATCH_UNATTENDED')), '1');

processingVersion = ...
    "GRF_gait_events_v2_threshold_crossing_QC_2026-08-22";

if ~batchModeRequested
    clear;
    clc;
    close all;
end

%% Load project paths and Step 03 configuration

internalFolder = fileparts(mfilename('fullpath'));
scriptsRoot = fileparts(internalFolder);

addpath(scriptsRoot, '-begin');
addpath(fullfile(scriptsRoot, 'config'), '-begin');

P = project_paths();
cfg = config_step03_04_grf_processing();

grfSegmentationFolder = P.grfSegmentationFolder;

batchGRFOutputFolder = strtrim( ...
    getenv('GRF_BATCH_GRF_OUTPUT_FOLDER'));

if ~isempty(batchGRFOutputFolder)
    grfSegmentationFolder = batchGRFOutputFolder;
end

if ~isfolder(grfSegmentationFolder)
    error('The GRF output folder does not exist:\n%s', ...
        grfSegmentationFolder);
end

%% Detection settings

rightChannels = cfg.detection.rightChannels;
leftChannels = cfg.detection.leftChannels;
lowpassHz = cfg.detection.lowpassHz;
thresholdOn = cfg.detection.thresholdOn;
thresholdOff = cfg.detection.thresholdOff;
minimumContactSec = cfg.detection.minimumContactSec;
maximumContactSec = cfg.detection.maximumContactSec;
minimumStrideSec = cfg.detection.minimumStrideSec;
qcZoomWindowSec = cfg.detection.qcZoomWindowSec;

%% Select one extracted GRF file

batchGRFStreamFile = strtrim( ...
    getenv('GRF_BATCH_GRF_STREAM_FILE'));

if ~isempty(batchGRFStreamFile)

    sourceGRFFile = batchGRFStreamFile;

else

    % Use *.mat on macOS, then validate the filename manually.
    [selectedFile, selectedFolder] = uigetfile( ...
        {'*.mat', 'MAT files (*.mat)'}, ...
        'Select one extracted GRF stream', ...
        grfSegmentationFolder);

    if isequal(selectedFile, 0)
        error('No extracted GRF file was selected.');
    end

    sourceGRFFile = fullfile( ...
        selectedFolder, ...
        selectedFile);
end

[~, selectedGRFBaseName, selectedGRFExtension] = ...
    fileparts(sourceGRFFile);

selectedGRFName = [ ...
    selectedGRFBaseName ...
    selectedGRFExtension];

if ~endsWith( ...
        string(selectedGRFName), ...
        "_GRF_stream.mat", ...
        'IgnoreCase', ...
        true)

    error([ ...
        'The selected file is not an extracted *_GRF_stream.mat file:\n%s'], ...
        sourceGRFFile);
end

if ~isfile(sourceGRFFile)
    error('The selected GRF stream file does not exist:\n%s', ...
        sourceGRFFile);
end

sourceGRFSignature = hipexo.file_signature(sourceGRFFile);

loadedGRF = load(sourceGRFFile);

requiredVariables = { ...
    'grfData', ...
    'grfTimeStamps', ...
    'intervalTable', ...
    'xdfFile'};

for iVariable = 1:numel(requiredVariables)

    if ~isfield(loadedGRF, requiredVariables{iVariable})
        error([ ...
            'The selected MAT file does not contain %s:\n%s'], ...
            requiredVariables{iVariable}, ...
            sourceGRFFile);
    end
end

grfData = loadedGRF.grfData;
grfTimeStamps = loadedGRF.grfTimeStamps;
intervalTable = loadedGRF.intervalTable;
xdfFile = string(loadedGRF.xdfFile);

if isempty(intervalTable)
    error('The selected GRF file contains no accepted walking interval.');
end

fprintf('\n====================================================\n');
fprintf('GRF GAIT-EVENT RUNNER\n');
fprintf('====================================================\n');
fprintf('Source GRF MAT:\n%s\n\n', sourceGRFFile);
fprintf('Source XDF:\n%s\n\n', xdfFile);

%% Detect events for every accepted interval

allEventTable = table;
diagnosticsAll = cell(height(intervalTable), 1);

qcOverviewFigures = ...
    gobjects(height(intervalTable), 1);

qcZoomFigures = ...
    gobjects(height(intervalTable), 1);

qcZoomWindowsSec = ...
    nan(height(intervalTable), 2);

for iInterval = 1:height(intervalTable)

    fprintf('\nProcessing interval %d of %d\n', ...
        iInterval, ...
        height(intervalTable));

    [currentEvents, ...
     currentDiagnostics, ...
     currentFigure] = hipexo.detect_GRF_gait_events( ...
        grfData, ...
        grfTimeStamps, ...
        intervalTable.StartLSLTime(iInterval), ...
        intervalTable.EndLSLTime(iInterval), ...
        'RightChannels', ...
        rightChannels, ...
        'LeftChannels', ...
        leftChannels, ...
        'LowpassHz', ...
        lowpassHz, ...
        'ThresholdOn', ...
        thresholdOn, ...
        'ThresholdOff', ...
        thresholdOff, ...
        'MinimumContactSec', ...
        minimumContactSec, ...
        'MaximumContactSec', ...
        maximumContactSec, ...
        'MinimumStrideSec', ...
        minimumStrideSec, ...
        'Plot', ...
        true);

    nEvents = height(currentEvents);

    currentEvents.Subject = repmat( ...
        string(intervalTable.Subject(iInterval)), ...
        nEvents, ...
        1);

    currentEvents.Day = repmat( ...
        string(intervalTable.Day(iInterval)), ...
        nEvents, ...
        1);

    currentEvents.Session = repmat( ...
        string(intervalTable.Session(iInterval)), ...
        nEvents, ...
        1);

    currentEvents.Condition = repmat( ...
        string(intervalTable.Condition(iInterval)), ...
        nEvents, ...
        1);

    currentEvents.SegmentIndex = repmat( ...
        double(intervalTable.SegmentIndex(iInterval)), ...
        nEvents, ...
        1);

    currentEvents.XDFPath = repmat( ...
        xdfFile, ...
        nEvents, ...
        1);

    currentEvents.SourceGRFFile = repmat( ...
        string(sourceGRFFile), ...
        nEvents, ...
        1);

    currentEvents = currentEvents(:, { ...
        'Subject', ...
        'Day', ...
        'Session', ...
        'Condition', ...
        'SegmentIndex', ...
        'EventType', ...
        'Side', ...
        'GRFSample', ...
        'SegmentSample', ...
        'LSLTime', ...
        'TimeFromSegmentStartSec', ...
        'XDFPath', ...
        'SourceGRFFile'});

    if isempty(allEventTable)

        allEventTable = currentEvents;

    else

        allEventTable = [ ...
            allEventTable; ...
            currentEvents]; %#ok<AGROW>
    end

    currentDiagnostics.Subject = ...
        string(intervalTable.Subject(iInterval));

    currentDiagnostics.Day = ...
        string(intervalTable.Day(iInterval));

    currentDiagnostics.Session = ...
        string(intervalTable.Session(iInterval));

    currentDiagnostics.Condition = ...
        string(intervalTable.Condition(iInterval));

    currentDiagnostics.SegmentIndex = ...
        double(intervalTable.SegmentIndex(iInterval));

    qcOverviewFigures(iInterval) = ...
        currentFigure;

    sgtitle( ...
        currentFigure, ...
        sprintf( ...
            '%s | %s | segment %d', ...
            char(string(intervalTable.Subject(iInterval))), ...
            char(string(intervalTable.Condition(iInterval))), ...
            double(intervalTable.SegmentIndex(iInterval))), ...
        'Interpreter', ...
        'none');

    % Keep full overview for saving but hide it during review.
    set(currentFigure, 'Visible', 'off');

    [qcZoomFigures(iInterval), ...
     qcZoomWindowsSec(iInterval, :)] = ...
        create_zoomed_qc_figure( ...
            currentDiagnostics, ...
            currentEvents, ...
            qcZoomWindowSec, ...
            string(intervalTable.Subject(iInterval)), ...
            string(intervalTable.Condition(iInterval)), ...
            double(intervalTable.SegmentIndex(iInterval)));

    currentDiagnostics.qcZoomStartSec = ...
        qcZoomWindowsSec(iInterval, 1);

    currentDiagnostics.qcZoomEndSec = ...
        qcZoomWindowsSec(iInterval, 2);

    diagnosticsAll{iInterval} = ...
        currentDiagnostics;
end

if isempty(allEventTable)
    error('No gait events were detected in any accepted interval.');
end

%% Print concise event summary

fprintf('\nEvent table created successfully.\n');
fprintf('Total detected events: %d\n', ...
    height(allEventTable));

fprintf('RHS: %d | RTO: %d | LHS: %d | LTO: %d\n', ...
    sum(string(allEventTable.EventType) == "RHS"), ...
    sum(string(allEventTable.EventType) == "RTO"), ...
    sum(string(allEventTable.EventType) == "LHS"), ...
    sum(string(allEventTable.EventType) == "LTO"));

previewVariables = { ...
    'EventType', ...
    'Side', ...
    'SegmentIndex', ...
    'TimeFromSegmentStartSec', ...
    'LSLTime'};

nPreviewRows = ...
    min(12, height(allEventTable));

fprintf('\nFirst %d events:\n', nPreviewRows);

disp( ...
    allEventTable( ...
        1:nPreviewRows, ...
        previewVariables));

if height(allEventTable) > nPreviewRows

    fprintf( ...
        '... %d additional event rows are not printed.\n', ...
        height(allEventTable) - nPreviewRows);
end

%% Require visual confirmation or a strict unattended QC gate before saving

if batchUnattended

    unattendedFailures = strings(0, 1);

    for iInterval = 1:numel(diagnosticsAll)
        d = diagnosticsAll{iInterval};

        if d.nRHS < 2 || d.nLHS < 2
            unattendedFailures(end+1,1) = sprintf( ...
                'segment %d has fewer than two heel strikes per side', ...
                iInterval); %#ok<AGROW>
        end

        if d.nRHS ~= d.nRTO || d.nLHS ~= d.nLTO
            unattendedFailures(end+1,1) = sprintf( ...
                'segment %d has unequal HS/TO counts', ...
                iInterval); %#ok<AGROW>
        end

        if abs(d.nRHS - d.nLHS) > 1
            unattendedFailures(end+1,1) = sprintf( ...
                'segment %d has right/left HS count difference > 1', ...
                iInterval); %#ok<AGROW>
        end

        if ~isfinite(d.alternationFraction) || ...
                d.alternationFraction < 0.90
            unattendedFailures(end+1,1) = sprintf( ...
                'segment %d has HS alternation below 0.90', ...
                iInterval); %#ok<AGROW>
        end
    end

    if ~isempty(unattendedFailures)
        error([ ...
            'Unattended GRF detection failed the automated QC gate:\n%s\n' ...
            'Inspect the saved source interval interactively before ' ...
            'accepting gait events.'], ...
            strjoin(unattendedFailures, newline));
    end

    reviewAnswer = 'Automated QC pass and save';
    reviewStatus = "AUTOMATED_QC_PASS_NOT_VISUALLY_REVIEWED";

    fprintf([ ...
        '\nUnattended mode: all intervals passed the strict automated ' ...
        'QC gate. Saving with NOT_VISUALLY_REVIEWED status.\n']);

else

    reviewAnswer = questdlg( ...
        ['Inspect the zoomed gait-event QC figure(s). ' ...
         'The full-interval overview will also be saved. ' ...
         'Do the detected events look correct?'], ...
        'Confirm GRF gait events', ...
        'Accept and save', ...
        'Cancel without saving', ...
        'Accept and save');

    if ~strcmp(reviewAnswer, 'Accept and save')
        error('Gait-event results were not saved.');
    end

    reviewStatus = "VISUALLY_ACCEPTED";
end


allEventTable.DetectionReviewStatus = ...
    repmat(reviewStatus, height(allEventTable), 1);


for iInterval = 1:numel(diagnosticsAll)
    diagnosticsAll{iInterval}.detectionReviewStatus = reviewStatus;
end

%% Define output files

[~, sourceBaseName] = ...
    fileparts(sourceGRFFile);

outputBaseName = regexprep( ...
    sourceBaseName, ...
    '_GRF_stream$', ...
    '');

sharedCSVFile = fullfile( ...
    grfSegmentationFolder, ...
    'grf_gait_events.csv');

perXDFMATFile = fullfile( ...
    grfSegmentationFolder, ...
    [outputBaseName '_GRF_gait_events.mat']);

%% Update the shared event CSV

% Re-running the same XDF replaces its existing rows.
if isfile(sharedCSVFile)

    existingEvents = readtable( ...
        sharedCSVFile, ...
        'TextType', ...
        'string', ...
        'VariableNamingRule', ...
        'preserve');

    [existingEvents, ...
     canMergeExistingCSV, ...
     csvStructureChanged, ...
     csvChangeDescription] = ...
        align_existing_event_table( ...
            existingEvents, ...
            allEventTable);

    if csvStructureChanged

        csvBackupFile = ...
            make_csv_backup_path(sharedCSVFile);

        [backupSucceeded, backupMessage] = ...
            copyfile( ...
                sharedCSVFile, ...
                csvBackupFile);

        if ~backupSucceeded

            error([ ...
                'Could not back up the existing shared CSV before ' ...
                'updating its structure:\n%s'], ...
                backupMessage);
        end

        fprintf([ ...
            '\nExisting shared CSV structure was different.\n' ...
            'Adjustment: %s\n' ...
            'Original CSV backed up to:\n%s\n'], ...
            csvChangeDescription, ...
            csvBackupFile);
    end

    if canMergeExistingCSV

        sameXDF = strcmp( ...
            string(existingEvents.XDFPath), ...
            xdfFile);

        existingEvents(sameXDF, :) = [];

        combinedEventTable = [ ...
            existingEvents; ...
            allEventTable];

    else

        warning([ ...
            'The old shared CSV could not be merged safely because it ' ...
            'did not contain a usable XDFPath column. ' ...
            'A backup was created and the shared CSV will be rebuilt ' ...
            'from the current XDF.']);

        combinedEventTable = ...
            allEventTable;
    end

else

    combinedEventTable = ...
        allEventTable;
end

combinedEventTable = sortrows( ...
    combinedEventTable, ...
    {'Subject', 'LSLTime'});

writetable( ...
    combinedEventTable, ...
    sharedCSVFile);

%% Save per-XDF event results

processingInfo = struct();
processingInfo.version = char(processingVersion);
processingInfo.source_grf_file = sourceGRFFile;
processingInfo.source_grf_signature = char(sourceGRFSignature);
processingInfo.source_xdf = char(xdfFile);
processingInfo.right_channels = rightChannels;
processingInfo.left_channels = leftChannels;
processingInfo.lowpass_hz = lowpassHz;
processingInfo.threshold_on = thresholdOn;
processingInfo.threshold_off = thresholdOff;
processingInfo.minimum_contact_sec = minimumContactSec;
processingInfo.maximum_contact_sec = maximumContactSec;
processingInfo.minimum_stride_sec = minimumStrideSec;
processingInfo.review_status = char(reviewStatus);
processingInfo.created_on = char(datetime( ...
    'now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

save( ...
    perXDFMATFile, ...
    'allEventTable', ...
    'diagnosticsAll', ...
    'intervalTable', ...
    'rightChannels', ...
    'leftChannels', ...
    'lowpassHz', ...
    'thresholdOn', ...
    'thresholdOff', ...
    'minimumContactSec', ...
    'maximumContactSec', ...
    'minimumStrideSec', ...
    'qcZoomWindowSec', ...
    'qcZoomWindowsSec', ...
    'sourceGRFFile', ...
    'xdfFile', ...
    'reviewStatus', ...
    'processingInfo', ...
    '-v7.3');

%% Save QC figures

qcOverviewFigureFiles = ...
    strings(height(intervalTable), 1);

qcZoomFigureFiles = ...
    strings(height(intervalTable), 1);

for iInterval = 1:height(intervalTable)

    segmentIndex = ...
        double(intervalTable.SegmentIndex(iInterval));

    qcOverviewFigureFiles(iInterval) = fullfile( ...
        grfSegmentationFolder, ...
        sprintf( ...
            '%s_segment-%02d_GRF_gait_events_QC_overview.png', ...
            outputBaseName, ...
            segmentIndex));

    exportgraphics( ...
        qcOverviewFigures(iInterval), ...
        char(qcOverviewFigureFiles(iInterval)), ...
        'Resolution', ...
        200);

    qcZoomFigureFiles(iInterval) = fullfile( ...
        grfSegmentationFolder, ...
        sprintf( ...
            '%s_segment-%02d_GRF_gait_events_QC_zoom.png', ...
            outputBaseName, ...
            segmentIndex));

    exportgraphics( ...
        qcZoomFigures(iInterval), ...
        char(qcZoomFigureFiles(iInterval)), ...
        'Resolution', ...
        200);
end

%% Print completion summary

fprintf('\n====================================================\n');
fprintf('GRF GAIT-EVENT DETECTION COMPLETED\n');
fprintf('====================================================\n');

fprintf('Events saved: %d\n', ...
    height(allEventTable));

fprintf('\nShared event table:\n%s\n', ...
    sharedCSVFile);

fprintf('\nPer-XDF event MAT:\n%s\n', ...
    perXDFMATFile);

fprintf('\nFull-interval QC figures:\n');

for iFigure = 1:numel(qcOverviewFigureFiles)

    fprintf('%s\n', ...
        qcOverviewFigureFiles(iFigure));
end

fprintf('\nZoomed QC figures:\n');

for iFigure = 1:numel(qcZoomFigureFiles)

    fprintf('%s\n', ...
        qcZoomFigureFiles(iFigure));
end

fprintf('\nNo EEG data were modified.\n');

%% Local functions

function [qcFigure, zoomWindowSec] = ...
        create_zoomed_qc_figure( ...
            diagnostics, ...
            eventTable, ...
            requestedWindowSec, ...
            subjectName, ...
            conditionName, ...
            segmentIndex)

relativeTime = ...
    double(diagnostics.segmentTimeStamps(:)) - ...
    double(diagnostics.segmentTimeStamps(1));

rightSignal = ...
    double(diagnostics.rightFiltered(:));

leftSignal = ...
    double(diagnostics.leftFiltered(:));

eventTypes = ...
    string(eventTable.EventType);

eventTimes = ...
    double(eventTable.TimeFromSegmentStartSec);

eventSamples = ...
    double(eventTable.SegmentSample);

intervalDurationSec = ...
    relativeTime(end);

actualWindowSec = ...
    min(requestedWindowSec, intervalDurationSec);

heelStrikeTimes = eventTimes( ...
    eventTypes == "RHS" | ...
    eventTypes == "LHS");

if isempty(heelStrikeTimes)

    zoomCenterSec = ...
        intervalDurationSec / 2;

else

    heelStrikeTimes = ...
        sort(heelStrikeTimes);

    zoomCenterSec = heelStrikeTimes( ...
        max(1, round(numel(heelStrikeTimes) / 2)));
end

zoomStartSec = max( ...
    0, ...
    zoomCenterSec - actualWindowSec / 2);

zoomStartSec = min( ...
    zoomStartSec, ...
    max(0, intervalDurationSec - actualWindowSec));

zoomEndSec = min( ...
    intervalDurationSec, ...
    zoomStartSec + actualWindowSec);

zoomWindowSec = [ ...
    zoomStartSec, ...
    zoomEndSec];

rightColor = [0.00 0.45 0.74];
leftColor = [0.80 0.15 0.55];
hsColor = [0.10 0.65 0.20];
toColor = [0.95 0.55 0.00];
axesColor = [0.98 0.98 0.98];
textColor = [0.12 0.12 0.12];
gridColor = [0.75 0.75 0.75];

qcFigure = figure( ...
    'Color', ...
    'w', ...
    'Name', ...
    'Zoomed GRF gait-event QC', ...
    'NumberTitle', ...
    'off', ...
    'Visible', ...
    figure_visibility_for_current_mode, ...
    'Position', ...
    [50 50 1500 900]);

qcLayout = tiledlayout( ...
    qcFigure, ...
    3, ...
    1, ...
    'TileSpacing', ...
    'compact', ...
    'Padding', ...
    'compact');

%% Right-foot panel

rightAxes = ...
    nexttile(qcLayout, 1);

plot( ...
    rightAxes, ...
    relativeTime, ...
    rightSignal, ...
    'Color', ...
    rightColor, ...
    'LineWidth', ...
    1.5);

hold(rightAxes, 'on');

yline( ...
    rightAxes, ...
    diagnostics.rightThresholdOn, ...
    '--', ...
    'Contact on', ...
    'Color', ...
    hsColor, ...
    'LineWidth', ...
    1.0);

yline( ...
    rightAxes, ...
    diagnostics.rightThresholdOff, ...
    ':', ...
    'Contact off', ...
    'Color', ...
    toColor, ...
    'LineWidth', ...
    1.0);

add_event_markers( ...
    rightAxes, ...
    relativeTime, ...
    rightSignal, ...
    eventSamples(eventTypes == "RHS"), ...
    'v', ...
    hsColor);

add_event_markers( ...
    rightAxes, ...
    relativeTime, ...
    rightSignal, ...
    eventSamples(eventTypes == "RTO"), ...
    '^', ...
    toColor);

format_qc_axes( ...
    rightAxes, ...
    axesColor, ...
    textColor, ...
    gridColor, ...
    zoomWindowSec);

set_zoom_y_limits( ...
    rightAxes, ...
    relativeTime, ...
    rightSignal, ...
    zoomWindowSec, ...
    [ ...
        diagnostics.rightThresholdOn, ...
        diagnostics.rightThresholdOff]);

ylabel(rightAxes, 'Right GRF');

title( ...
    rightAxes, ...
    'Right foot: RHS (green down) and RTO (orange up)');

%% Left-foot panel

leftAxes = ...
    nexttile(qcLayout, 2);

plot( ...
    leftAxes, ...
    relativeTime, ...
    leftSignal, ...
    'Color', ...
    leftColor, ...
    'LineWidth', ...
    1.5);

hold(leftAxes, 'on');

yline( ...
    leftAxes, ...
    diagnostics.leftThresholdOn, ...
    '--', ...
    'Contact on', ...
    'Color', ...
    hsColor, ...
    'LineWidth', ...
    1.0);

yline( ...
    leftAxes, ...
    diagnostics.leftThresholdOff, ...
    ':', ...
    'Contact off', ...
    'Color', ...
    toColor, ...
    'LineWidth', ...
    1.0);

add_event_markers( ...
    leftAxes, ...
    relativeTime, ...
    leftSignal, ...
    eventSamples(eventTypes == "LHS"), ...
    'v', ...
    hsColor);

add_event_markers( ...
    leftAxes, ...
    relativeTime, ...
    leftSignal, ...
    eventSamples(eventTypes == "LTO"), ...
    '^', ...
    toColor);

format_qc_axes( ...
    leftAxes, ...
    axesColor, ...
    textColor, ...
    gridColor, ...
    zoomWindowSec);

set_zoom_y_limits( ...
    leftAxes, ...
    relativeTime, ...
    leftSignal, ...
    zoomWindowSec, ...
    [ ...
        diagnostics.leftThresholdOn, ...
        diagnostics.leftThresholdOff]);

ylabel(leftAxes, 'Left GRF');

title( ...
    leftAxes, ...
    'Left foot: LHS (green down) and LTO (orange up)');

%% Combined panel

bothAxes = ...
    nexttile(qcLayout, 3);

plot( ...
    bothAxes, ...
    relativeTime, ...
    rightSignal, ...
    'Color', ...
    rightColor, ...
    'LineWidth', ...
    1.3, ...
    'DisplayName', ...
    'Right GRF');

hold(bothAxes, 'on');

plot( ...
    bothAxes, ...
    relativeTime, ...
    leftSignal, ...
    'Color', ...
    leftColor, ...
    'LineWidth', ...
    1.3, ...
    'DisplayName', ...
    'Left GRF');

add_event_markers( ...
    bothAxes, ...
    relativeTime, ...
    rightSignal, ...
    eventSamples(eventTypes == "RHS"), ...
    'v', ...
    hsColor, ...
    'RHS');

add_event_markers( ...
    bothAxes, ...
    relativeTime, ...
    leftSignal, ...
    eventSamples(eventTypes == "LHS"), ...
    'o', ...
    hsColor, ...
    'LHS');

format_qc_axes( ...
    bothAxes, ...
    axesColor, ...
    textColor, ...
    gridColor, ...
    zoomWindowSec);

set_zoom_y_limits( ...
    bothAxes, ...
    relativeTime, ...
    [rightSignal, leftSignal], ...
    zoomWindowSec, ...
    []);

xlabel( ...
    bothAxes, ...
    'Time from accepted walking-interval start (s)');

ylabel( ...
    bothAxes, ...
    'GRF above baseline');

title( ...
    bothAxes, ...
    'Both feet: heel-strike alternation');

legend( ...
    bothAxes, ...
    'Location', ...
    'eastoutside');

linkaxes( ...
    [rightAxes, leftAxes, bothAxes], ...
    'x');

sgtitle( ...
    qcLayout, ...
    sprintf( ...
        '%s | %s | segment %d | representative %.1f s QC window', ...
        char(subjectName), ...
        char(conditionName), ...
        segmentIndex, ...
        zoomEndSec - zoomStartSec), ...
    'Interpreter', ...
    'none', ...
    'Color', ...
    textColor);

end

function visibility = figure_visibility_for_current_mode

if strcmpi(strtrim( ...
        getenv('GRF_BATCH_UNATTENDED')), '1')
    visibility = 'off';
else
    visibility = 'on';
end
end

function markerHandle = ...
        add_event_markers( ...
            targetAxes, ...
            relativeTime, ...
            signal, ...
            eventSamples, ...
            markerShape, ...
            markerColor, ...
            displayName)

if nargin < 7
    displayName = '';
end

eventSamples = ...
    round(double(eventSamples(:)));

validSamples = ...
    eventSamples >= 1 & ...
    eventSamples <= numel(signal);

eventSamples = ...
    eventSamples(validSamples);

if isempty(eventSamples)

    markerHandle = ...
        gobjects(0);

    return;
end

markerHandle = plot( ...
    targetAxes, ...
    relativeTime(eventSamples), ...
    signal(eventSamples), ...
    markerShape, ...
    'LineStyle', ...
    'none', ...
    'Color', ...
    markerColor, ...
    'MarkerFaceColor', ...
    markerColor, ...
    'MarkerEdgeColor', ...
    [0.10 0.10 0.10], ...
    'MarkerSize', ...
    8, ...
    'LineWidth', ...
    0.8);

if ~isempty(displayName)

    markerHandle.DisplayName = ...
        displayName;

else

    markerHandle.HandleVisibility = ...
        'off';
end

end

function format_qc_axes( ...
        targetAxes, ...
        axesColor, ...
        textColor, ...
        gridColor, ...
        zoomWindowSec)

targetAxes.Color = ...
    axesColor;

targetAxes.XColor = ...
    textColor;

targetAxes.YColor = ...
    textColor;

targetAxes.GridColor = ...
    gridColor;

targetAxes.GridAlpha = ...
    0.45;

targetAxes.FontSize = ...
    11;

targetAxes.LineWidth = ...
    0.8;

grid(targetAxes, 'on');

xlim( ...
    targetAxes, ...
    zoomWindowSec);

end

function set_zoom_y_limits( ...
        targetAxes, ...
        relativeTime, ...
        signals, ...
        zoomWindowSec, ...
        additionalValues)

visibleSamples = ...
    relativeTime >= zoomWindowSec(1) & ...
    relativeTime <= zoomWindowSec(2);

visibleValues = ...
    double(signals(visibleSamples, :));

visibleValues = ...
    visibleValues(isfinite(visibleValues));

additionalValues = ...
    double(additionalValues(:));

additionalValues = ...
    additionalValues(isfinite(additionalValues));

allValues = [ ...
    visibleValues(:); ...
    additionalValues];

if isempty(allValues)
    return;
end

lowerLimit = ...
    min(0, min(allValues));

upperLimit = ...
    max(allValues);

if upperLimit <= lowerLimit

    upperLimit = ...
        lowerLimit + 1;
end

padding = ...
    0.08 * (upperLimit - lowerLimit);

ylim( ...
    targetAxes, ...
    [ ...
        lowerLimit - 0.25 * padding, ...
        upperLimit + padding]);

end

function [alignedEvents, ...
          canMerge, ...
          structureChanged, ...
          changeDescription] = ...
        align_existing_event_table( ...
            existingEvents, ...
            templateEvents)

alignedEvents = ...
    existingEvents;

canMerge = true;
structureChanged = false;
changeMessages = strings(0, 1);

expectedNames = ...
    string(templateEvents.Properties.VariableNames);

existingNames = ...
    string(alignedEvents.Properties.VariableNames);

%% Normalize case-only differences in column names

for iExpected = 1:numel(expectedNames)

    exactMatch = find( ...
        existingNames == expectedNames(iExpected));

    if ~isempty(exactMatch)
        continue;
    end

    caseInsensitiveMatch = find( ...
        strcmpi( ...
            existingNames, ...
            expectedNames(iExpected)));

    if numel(caseInsensitiveMatch) == 1

        alignedEvents.Properties.VariableNames{ ...
            caseInsensitiveMatch} = ...
            char(expectedNames(iExpected));

        existingNames(caseInsensitiveMatch) = ...
            expectedNames(iExpected);

        structureChanged = true;
    end
end

existingNames = ...
    string(alignedEvents.Properties.VariableNames);

missingNames = setdiff( ...
    expectedNames, ...
    existingNames, ...
    'stable');

extraNames = setdiff( ...
    existingNames, ...
    expectedNames, ...
    'stable');

if ~isempty(missingNames)

    structureChanged = true;

    changeMessages(end + 1) = ...
        "added missing columns: " + ...
        strjoin(missingNames, ", "); %#ok<AGROW>
end

if ~isempty(extraNames)

    structureChanged = true;

    changeMessages(end + 1) = ...
        "removed obsolete columns: " + ...
        strjoin(extraNames, ", "); %#ok<AGROW>
end

if ~ismember("XDFPath", existingNames)

    canMerge = false;

    changeMessages(end + 1) = ...
        "old CSV had no XDFPath column"; %#ok<AGROW>

    changeDescription = ...
        char(strjoin(changeMessages, "; "));

    return;
end

nExistingRows = ...
    height(alignedEvents);

%% Add missing columns with compatible data types

for iMissing = 1:numel(missingNames)

    variableName = ...
        char(missingNames(iMissing));

    templateColumn = ...
        templateEvents.(variableName);

    if isstring(templateColumn)

        alignedEvents.(variableName) = ...
            strings(nExistingRows, 1);

    elseif isnumeric(templateColumn)

        alignedEvents.(variableName) = ...
            nan(nExistingRows, 1);

    elseif islogical(templateColumn)

        alignedEvents.(variableName) = ...
            false(nExistingRows, 1);

    else

        canMerge = false;

        changeMessages(end + 1) = ...
            "unsupported missing column type: " + ...
            string(variableName); %#ok<AGROW>

        changeDescription = ...
            char(strjoin(changeMessages, "; "));

        return;
    end
end

%% Convert existing columns to current data types

for iExpected = 1:numel(expectedNames)

    variableName = ...
        char(expectedNames(iExpected));

    templateColumn = ...
        templateEvents.(variableName);

    existingColumn = ...
        alignedEvents.(variableName);

    if isstring(templateColumn)

        if ~isstring(existingColumn)
            structureChanged = true;
        end

        alignedEvents.(variableName) = ...
            string(existingColumn);

    elseif isnumeric(templateColumn)

        if isnumeric(existingColumn)

            if ~isa(existingColumn, 'double')
                structureChanged = true;
            end

            alignedEvents.(variableName) = ...
                double(existingColumn);

        else

            structureChanged = true;

            alignedEvents.(variableName) = ...
                str2double(string(existingColumn));
        end

    elseif islogical(templateColumn)

        if ~islogical(existingColumn)
            structureChanged = true;
        end

        alignedEvents.(variableName) = ...
            logical(existingColumn);
    end
end

alignedEvents = ...
    alignedEvents(:, cellstr(expectedNames));

if structureChanged && isempty(changeMessages)

    changeMessages = ...
        "normalized column names or data types";
end

changeDescription = ...
    char(strjoin(changeMessages, "; "));

end

function backupFile = ...
        make_csv_backup_path(sharedCSVFile)

[csvFolder, csvBaseName, csvExtension] = ...
    fileparts(sharedCSVFile);

timeStamp = char(datetime( ...
    'now', ...
    'Format', ...
    'yyyyMMdd_HHmmss'));

backupFile = fullfile( ...
    csvFolder, ...
    sprintf( ...
        '%s_backup_%s%s', ...
        csvBaseName, ...
        timeStamp, ...
        csvExtension));

backupIndex = 1;

while isfile(backupFile)

    backupFile = fullfile( ...
        csvFolder, ...
        sprintf( ...
            '%s_backup_%s_%02d%s', ...
            csvBaseName, ...
            timeStamp, ...
            backupIndex, ...
            csvExtension));

    backupIndex = ...
        backupIndex + 1;
end

end

