% GOAL
%   Map GRF-derived gait events onto real samples of the EEG stream from the
%   same source XDF without resampling the EEG.
% INPUT
%   GRF_BATCH_EVENT_FILE, GRF_BATCH_GRF_OUTPUT_FOLDER, and
%   GRF_BATCH_EEG_OUTPUT_FOLDER supplied internally by
%   step03_process_subject_grf_eeg.m.
% OUTPUT
%   *_EEG_500Hz_with_GRF_events.set
%   *_GRF_to_EEG_event_mapping.csv
%   *_EEG_timestamp_gaps.csv
% METHOD
%   Preserve the current real-timestamp mapping logic: detect EEG timestamp
%   gaps, map only to existing EEG samples, exclude events inside gaps, add
%   EEGLAB boundary events, and attach the project channel locations.

batchModeRequested = ~isempty(strtrim( ...
    getenv('GRF_BATCH_GRF_OUTPUT_FOLDER')));

processingVersion = ...
    "GRF_to_EEG_mapping_v2_provenance_2026-08-22";

if ~batchModeRequested
    clear;
    clc;
    close all;
end

%% Load project paths and Step 03 configuration

internalFolder = fileparts(mfilename('fullpath'));
scriptsRoot = fileparts(internalFolder);

addpath(scriptsRoot, '-begin');
addpath(fullfile(scriptsRoot, 'config'), '-begin');

P = project_paths();
cfg = config_step03_04_grf_processing();

grfSegmentationFolder = P.grfSegmentationFolder;
channelLocationFile = P.channelLocationFile;

batchGRFOutputFolder = strtrim( ...
    getenv('GRF_BATCH_GRF_OUTPUT_FOLDER'));

if ~isempty(batchGRFOutputFolder)
    grfSegmentationFolder = batchGRFOutputFolder;
end

if ~isfolder(grfSegmentationFolder)
    error('The GRF output folder does not exist:\n%s', ...
        grfSegmentationFolder);
end

if ~isfile(channelLocationFile)
    error('Cannot find channel-location file:\n%s', ...
        channelLocationFile);
end

batchEEGOutputFolder = strtrim( ...
    getenv('GRF_BATCH_EEG_OUTPUT_FOLDER'));

if ~isempty(batchEEGOutputFolder)
    eegEventOutputFolder = batchEEGOutputFolder;
else
    eegEventOutputFolder = P.eegWithGRFEventsFolder;
end

if ~isfolder(eegEventOutputFolder)
    mkdir(eegEventOutputFolder);
end

%% Mapping settings

expectedEEGStreamName = cfg.mapping.expectedEEGStreamName;
expectedEEGChannels = cfg.mapping.expectedEEGChannels;
expectedAuxiliaryLabels = cfg.mapping.expectedAuxiliaryLabels;
targetEEGSrate = cfg.mapping.targetEEGSrateHz;
maximumMappingErrorMs = cfg.mapping.maximumMappingErrorMs;
timestampGapFactor = cfg.mapping.timestampGapFactor;
minimumTimestampGapSec = cfg.mapping.minimumTimestampGapSec;

%% Select one saved per-XDF GRF event file

batchEventFile = strtrim( ...
    getenv('GRF_BATCH_EVENT_FILE'));

if ~isempty(batchEventFile)

    sourceEventFile = batchEventFile;

else

    eventFileFilter = fullfile( ...
        grfSegmentationFolder, ...
        '*.mat');

    [selectedFile, selectedFolder] = uigetfile( ...
        eventFileFilter, ...
        'Select one GRF gait-event MAT file');

    if isequal(selectedFile, 0)
        error('No GRF gait-event file was selected.');
    end

    sourceEventFile = fullfile( ...
        selectedFolder, ...
        selectedFile);
end

if ~isfile(sourceEventFile)
    error('Cannot find the GRF gait-event MAT file:\n%s', ...
        sourceEventFile);
end

sourceEventSignature = hipexo.file_signature(sourceEventFile);

loadedEvents = load(sourceEventFile);

if ~isfield(loadedEvents, 'allEventTable')
    error([ ...
        'The selected MAT file does not contain allEventTable:\n%s'], ...
        sourceEventFile);
end

allEventTable = loadedEvents.allEventTable;

requiredEventVariables = { ...
    'Subject', ...
    'Condition', ...
    'EventType', ...
    'Side', ...
    'SegmentIndex', ...
    'LSLTime', ...
    'XDFPath'};

if ~all(ismember( ...
        requiredEventVariables, ...
        allEventTable.Properties.VariableNames))

    error([ ...
        'The event table is missing one or more required variables:\n%s'], ...
        strjoin(requiredEventVariables, ', '));
end

if isempty(allEventTable)
    error('The selected event table is empty.');
end

eventTypes = string(allEventTable.EventType);
validEventTypes = ["RHS", "RTO", "LHS", "LTO"];

if any(~ismember(eventTypes, validEventTypes))
    error('The event table contains an unexpected EventType.');
end

xdfPaths = unique(string(allEventTable.XDFPath));
xdfPaths(strlength(xdfPaths) == 0) = [];

if numel(xdfPaths) ~= 1
    error([ ...
        'The selected event MAT must contain events from exactly one XDF.\n' ...
        'Number of unique XDF paths found: %d'], ...
        numel(xdfPaths));
end

xdfFile = xdfPaths(1);

if ~isfile(xdfFile)
    error('Cannot find the source XDF:\n%s', xdfFile);
end

sourceXDFSignature = hipexo.file_signature(xdfFile);

sourceMetadata = ...
    parse_xdf_source_metadata(xdfFile);


eventSubjectKeys = unique( ...
    canonical_subject_key_local(allEventTable.Subject));

eventConditions = unique( ...
    canonical_condition_local(allEventTable.Condition));

expectedSubjectKey = ...
    canonical_subject_key_local(sourceMetadata.SubjectLabel);

expectedCondition = ...
    canonical_condition_local(sourceMetadata.ConditionLabel);

if numel(eventSubjectKeys) ~= 1 || ...
        eventSubjectKeys(1) ~= expectedSubjectKey
    error([ ...
        'GRF event-table Subject does not match the source XDF filename.\n' ...
        'Event table: %s | XDF: %s'], ...
        strjoin(unique(string(allEventTable.Subject)), ', '), ...
        sourceMetadata.SubjectLabel);
end

if numel(eventConditions) ~= 1 || ...
        eventConditions(1) ~= expectedCondition
    error([ ...
        'GRF event-table Condition does not match the source XDF filename.\n' ...
        'Event table: %s -> %s | XDF: %s -> %s'], ...
        strjoin(unique(string(allEventTable.Condition)), ', '), ...
        strjoin(eventConditions, ', '), ...
        sourceMetadata.ConditionLabel, ...
        expectedCondition);
end

if ~ismember(sourceMetadata.RunNumber, [1 2])

    error([ ...
        'Only run-001 and run-002 may enter GRF-to-EEG mapping.\n' ...
        'Resolved run number: %g\nSource XDF:\n%s'], ...
        sourceMetadata.RunNumber, ...
        xdfFile);
end

if sourceMetadata.IsOldVersion

    error('Old XDF versions are not accepted:\n%s', ...
        xdfFile);
end

%% Load XDF and find the real EEG stream

fprintf('\n====================================================\n');
fprintf('MAP GRF EVENTS TO 500 HZ EEG\n');
fprintf('====================================================\n');
fprintf('Source event MAT:\n%s\n\n', sourceEventFile);
fprintf('Source XDF:\n%s\n\n', xdfFile);

[streams, ~] = load_xdf(char(xdfFile));

if isempty(streams)
    error('No streams were loaded from the XDF.');
end

[eegStreamIndex, streamSummary] = find_real_eeg_stream( ...
    streams, ...
    expectedEEGStreamName, ...
    expectedEEGChannels, ...
    targetEEGSrate);

disp(streamSummary);

EEGStream = streams{eegStreamIndex};
eegData = double(EEGStream.time_series);
eegTimeStamps = double(EEGStream.time_stamps(:)');

if size(eegData, 2) ~= numel(eegTimeStamps) && ...
        size(eegData, 1) == numel(eegTimeStamps)

    eegData = eegData';
end

if size(eegData, 2) ~= numel(eegTimeStamps)
    error([ ...
        'EEG data and EEG timestamps have different sample counts.\n' ...
        'EEG data size: %d x %d\n' ...
        'EEG timestamps: %d'], ...
        size(eegData, 1), ...
        size(eegData, 2), ...
        numel(eegTimeStamps));
end

%% Select the 64 EEG channels from the LiveAmp stream

if exist('eeglab', 'file') ~= 2
    error('Cannot find eeglab.m. Check eeglabFolder in project_paths.m.');
end

[ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab('nogui'); %#ok<ASGLU>

projectChanlocs = readlocs(channelLocationFile);

if numel(projectChanlocs) ~= expectedEEGChannels
    error([ ...
        'Expected %d channel locations, but chanlocs.ced contains %d.'], ...
        expectedEEGChannels, ...
        numel(projectChanlocs));
end

projectChannelLabels = ...
    string({projectChanlocs.labels})';

rawEEGChannelCount = size(eegData, 1);

rawEEGChannelLabels = get_stream_channel_labels( ...
    EEGStream, ...
    rawEEGChannelCount);

[selectedEEGChannelIndices, ...
 droppedEEGChannelIndices, ...
 channelSelectionMethod] = ...
    select_project_eeg_channels( ...
        rawEEGChannelLabels, ...
        projectChannelLabels, ...
        rawEEGChannelCount, ...
        expectedEEGChannels, ...
        expectedAuxiliaryLabels, ...
        expectedEEGStreamName);

eegData = eegData(selectedEEGChannelIndices, :);

selectedEEGChannelLabels = ...
    rawEEGChannelLabels(selectedEEGChannelIndices);

droppedEEGChannelLabels = ...
    rawEEGChannelLabels(droppedEEGChannelIndices);

if any(~isfinite(eegTimeStamps)) || ...
        any(diff(eegTimeStamps) <= 0)

    error('EEG timestamps must be finite and strictly increasing.');
end

measuredEEGSrate = 1 / median(diff(eegTimeStamps));
nominalEEGSrate = get_stream_nominal_srate(EEGStream);

if ~isfinite(nominalEEGSrate) || ...
        abs(nominalEEGSrate - targetEEGSrate) > 1

    error([ ...
        'The selected EEG stream is not a nominal 500 Hz stream.\n' ...
        'Nominal sampling rate: %.9g Hz'], ...
        nominalEEGSrate);
end

fprintf('Selected EEG stream: %s\n', ...
    get_stream_text_field(EEGStream, 'name'));

fprintf('Raw LiveAmp stream channels: %d\n', ...
    rawEEGChannelCount);

fprintf('Selected EEG channels: %d\n', ...
    size(eegData, 1));

fprintf('Channel-selection method: %s\n', ...
    channelSelectionMethod);

if ~isempty(droppedEEGChannelIndices)

    fprintf('Dropped auxiliary channel indices: %s\n', ...
        mat2str(droppedEEGChannelIndices'));

    if any(strlength(droppedEEGChannelLabels) > 0)

        fprintf('Dropped auxiliary channel labels: %s\n', ...
            strjoin(droppedEEGChannelLabels, ', '));
    end
end

fprintf('EEG samples: %d\n', ...
    size(eegData, 2));

fprintf('Nominal EEG rate: %.6f Hz\n', ...
    nominalEEGSrate);

fprintf('Measured timestamp rate: %.6f Hz\n', ...
    measuredEEGSrate);

fprintf('EEG LSL range: %.6f to %.6f s\n', ...
    eegTimeStamps(1), ...
    eegTimeStamps(end));

%% Detect real gaps in the EEG timestamp vector

eegTimestampDifferenceSec = ...
    diff(eegTimeStamps(:));

medianEEGSampleIntervalSec = ...
    median(eegTimestampDifferenceSec);

timestampGapThresholdSec = max( ...
    timestampGapFactor * medianEEGSampleIntervalSec, ...
    minimumTimestampGapSec);

gapBeforeSample = find( ...
    eegTimestampDifferenceSec > timestampGapThresholdSec);

gapAfterSample = ...
    gapBeforeSample + 1;

if isempty(gapBeforeSample)

    eegTimestampGapTable = table( ...
        'Size', ...
        [0 8], ...
        'VariableTypes', { ...
            'double', ...
            'double', ...
            'double', ...
            'double', ...
            'double', ...
            'double', ...
            'double', ...
            'double'}, ...
        'VariableNames', { ...
            'GapIndex', ...
            'SampleBeforeGap', ...
            'SampleAfterGap', ...
            'LSLBeforeGap', ...
            'LSLAfterGap', ...
            'TimestampJumpSec', ...
            'MissingDurationSec', ...
            'MissingSampleCount'});

else

    timestampJumpSec = ...
        eegTimestampDifferenceSec(gapBeforeSample);

    missingDurationSec = max( ...
        0, ...
        timestampJumpSec - medianEEGSampleIntervalSec);

    missingSampleCount = max( ...
        0, ...
        round(timestampJumpSec * targetEEGSrate) - 1);

    eegTimestampGapTable = table( ...
        (1:numel(gapBeforeSample))', ...
        double(gapBeforeSample(:)), ...
        double(gapAfterSample(:)), ...
        reshape( ...
            double(eegTimeStamps(gapBeforeSample)), ...
            [], ...
            1), ...
        reshape( ...
            double(eegTimeStamps(gapAfterSample)), ...
            [], ...
            1), ...
        double(timestampJumpSec(:)), ...
        double(missingDurationSec(:)), ...
        double(missingSampleCount(:)), ...
        'VariableNames', { ...
            'GapIndex', ...
            'SampleBeforeGap', ...
            'SampleAfterGap', ...
            'LSLBeforeGap', ...
            'LSLAfterGap', ...
            'TimestampJumpSec', ...
            'MissingDurationSec', ...
            'MissingSampleCount'});
end

fprintf('\nEEG timestamp-gap check:\n');

fprintf('Gap threshold: %.6f s\n', ...
    timestampGapThresholdSec);

fprintf('Detected gaps: %d\n', ...
    height(eegTimestampGapTable));

if ~isempty(eegTimestampGapTable)
    disp(eegTimestampGapTable);
end

%% Map each GRF event to a real EEG sample

allEventTable = ...
    sortrows(allEventTable, 'LSLTime');

eventTypes = ...
    string(allEventTable.EventType);

grfEventLSLTime = ...
    double(allEventTable.LSLTime);

insideEEGRange = ...
    grfEventLSLTime >= eegTimeStamps(1) & ...
    grfEventLSLTime <= eegTimeStamps(end);

if any(~insideEEGRange)

    outsideRows = allEventTable( ...
        ~insideEEGRange, ...
        {'EventType', 'LSLTime'});

    disp(outsideRows);

    error([ ...
        '%d GRF events are outside the EEG timestamp range.\n' ...
        'No EEG file was saved. Check the walking interval and source XDF.'], ...
        sum(~insideEEGRange));
end

nearestEEGSample = interp1( ...
    eegTimeStamps, ...
    1:numel(eegTimeStamps), ...
    grfEventLSLTime, ...
    'nearest');

nearestEEGSample = ...
    round(nearestEEGSample(:));

if any(~isfinite(nearestEEGSample)) || ...
        any(nearestEEGSample < 1) || ...
        any(nearestEEGSample > numel(eegTimeStamps))

    error('One or more GRF events could not be mapped to an EEG sample.');
end

nearestEEGLSLTime = ...
    eegTimeStamps(nearestEEGSample);

nearestEEGLSLTime = ...
    nearestEEGLSLTime(:);

nearestMappingErrorMs = ...
    1000 * (nearestEEGLSLTime - grfEventLSLTime);

eventInsideTimestampGap = ...
    false(height(allEventTable), 1);

eventTimestampGapIndex = ...
    nan(height(allEventTable), 1);

for iGap = 1:height(eegTimestampGapTable)

    currentEventsInsideGap = ...
        grfEventLSLTime > ...
            eegTimestampGapTable.LSLBeforeGap(iGap) & ...
        grfEventLSLTime < ...
            eegTimestampGapTable.LSLAfterGap(iGap);

    eventInsideTimestampGap = ...
        eventInsideTimestampGap | ...
        currentEventsInsideGap;

    eventTimestampGapIndex(currentEventsInsideGap) = ...
        eegTimestampGapTable.GapIndex(iGap);
end

unexplainedBadMapping = ...
    abs(nearestMappingErrorMs) > maximumMappingErrorMs & ...
    ~eventInsideTimestampGap;

if any(unexplainedBadMapping)

    badRows = find(unexplainedBadMapping);

    disp(table( ...
        eventTypes(badRows), ...
        grfEventLSLTime(badRows), ...
        nearestEEGSample(badRows), ...
        nearestEEGLSLTime(badRows), ...
        nearestMappingErrorMs(badRows), ...
        'VariableNames', { ...
            'EventType', ...
            'GRFEventLSLTime', ...
            'NearestEEGSample', ...
            'NearestEEGLSLTime', ...
            'NearestMappingErrorMs'}));

    error([ ...
        '%d event mappings exceed %.3f ms and are not explained ' ...
        'by a detected EEG timestamp gap.\n' ...
        'No EEG file was saved.'], ...
        numel(badRows), ...
        maximumMappingErrorMs);
end

mappingStatus = repmat( ...
    "mapped", ...
    height(allEventTable), ...
    1);

mappingStatus(eventInsideTimestampGap) = ...
    "excluded_no_EEG_sample_in_timestamp_gap";

eegSample = ...
    nan(height(allEventTable), 1);

matchedEEGLSLTime = ...
    nan(height(allEventTable), 1);

signedMappingErrorMs = ...
    nan(height(allEventTable), 1);

mappedEventMask = ...
    ~eventInsideTimestampGap;

eegSample(mappedEventMask) = ...
    nearestEEGSample(mappedEventMask);

matchedEEGLSLTime(mappedEventMask) = ...
    nearestEEGLSLTime(mappedEventMask);

signedMappingErrorMs(mappedEventMask) = ...
    nearestMappingErrorMs(mappedEventMask);

mappingTable = ...
    allEventTable;

mappingTable.MappingStatus = ...
    mappingStatus;

mappingTable.EEGTimestampGapIndex = ...
    eventTimestampGapIndex;

mappingTable.EEGSample = ...
    eegSample;

mappingTable.MatchedEEGLSLTime = ...
    matchedEEGLSLTime;

mappingTable.MappingErrorMs = ...
    signedMappingErrorMs;

mappingTable.NearestEEGSample = ...
    nearestEEGSample;

mappingTable.NearestEEGLSLTime = ...
    nearestEEGLSLTime;

mappingTable.NearestMappingErrorMs = ...
    nearestMappingErrorMs;

mappedEventTable = ...
    mappingTable(mappedEventMask, :);

excludedEventTable = ...
    mappingTable(eventInsideTimestampGap, :);

if isempty(mappedEventTable)

    error([ ...
        'All GRF events fall inside EEG timestamp gaps.\n' ...
        'No EEG file was saved.']);
end

mappedEEGSample = ...
    double(mappedEventTable.EEGSample);

duplicateEventSample = ...
    [false; diff(mappedEEGSample) == 0];

if any(duplicateEventSample)

    duplicateRows = find(duplicateEventSample);

    disp(table( ...
        string(mappedEventTable.EventType(duplicateRows)), ...
        mappedEEGSample(duplicateRows), ...
        double(mappedEventTable.LSLTime(duplicateRows)), ...
        'VariableNames', { ...
            'EventType', ...
            'EEGSample', ...
            'GRFEventLSLTime'}));

    error([ ...
        'Two or more mapped gait events use the same EEG sample.\n' ...
        'No EEG file was saved.']);
end

fprintf('\nGRF-to-EEG mapping status:\n');

fprintf('Original GRF events: %d\n', ...
    height(mappingTable));

fprintf('Successfully mapped events: %d\n', ...
    height(mappedEventTable));

fprintf('Excluded events inside EEG timestamp gaps: %d\n', ...
    height(excludedEventTable));

%% Construct the session EEG dataset

EEG = eeg_emptyset;

[~, xdfBaseName] = ...
    fileparts(char(xdfFile));

EEG.setname = [ ...
    xdfBaseName ...
    '_500Hz_with_GRF_events'];

EEG.data = single(eegData);
EEG.nbchan = size(eegData, 1);
EEG.trials = 1;
EEG.pnts = size(eegData, 2);

% The samples are not resampled.
% The nominal acquisition rate is retained.
EEG.srate = targetEEGSrate;
EEG.xmin = 0;
EEG.xmax = (EEG.pnts - 1) / EEG.srate;
EEG.times = (0:(EEG.pnts - 1)) / EEG.srate * 1000;

EEG.event = struct( ...
    'type', {}, ...
    'latency', {}, ...
    'duration', {}, ...
    'side', {}, ...
    'segment_index', {}, ...
    'lsl_time', {}, ...
    'matched_eeg_lsl_time', {}, ...
    'mapping_error_ms', {}, ...
    'mapping_status', {}, ...
    'gap_start_lsl_time', {}, ...
    'gap_end_lsl_time', {}, ...
    'subject_label', {}, ...
    'day_label', {}, ...
    'session_label', {}, ...
    'condition_label', {}, ...
    'task_label', {}, ...
    'run_number', {}, ...
    'source_xdf', {}, ...
    'source_recording', {});

%% Add successfully mapped gait events

for iEvent = 1:height(mappedEventTable)

    EEG.event(iEvent).type = ...
        char(string(mappedEventTable.EventType(iEvent)));

    EEG.event(iEvent).latency = ...
        double(mappedEventTable.EEGSample(iEvent));

    EEG.event(iEvent).duration = ...
        0;

    EEG.event(iEvent).side = ...
        char(string(mappedEventTable.Side(iEvent)));

    EEG.event(iEvent).segment_index = ...
        double(mappedEventTable.SegmentIndex(iEvent));

    EEG.event(iEvent).lsl_time = ...
        double(mappedEventTable.LSLTime(iEvent));

    EEG.event(iEvent).matched_eeg_lsl_time = ...
        double(mappedEventTable.MatchedEEGLSLTime(iEvent));

    EEG.event(iEvent).mapping_error_ms = ...
        double(mappedEventTable.MappingErrorMs(iEvent));

    EEG.event(iEvent).mapping_status = ...
        'mapped';

    EEG.event(iEvent).gap_start_lsl_time = ...
        NaN;

    EEG.event(iEvent).gap_end_lsl_time = ...
        NaN;

    EEG.event(iEvent).subject_label = ...
        char(sourceMetadata.SubjectLabel);

    EEG.event(iEvent).day_label = ...
        char(sourceMetadata.DayLabel);

    EEG.event(iEvent).session_label = ...
        char(sourceMetadata.SessionLabel);

    EEG.event(iEvent).condition_label = ...
        char(sourceMetadata.ConditionLabel);

    EEG.event(iEvent).task_label = ...
        char(sourceMetadata.TaskLabel);

    EEG.event(iEvent).run_number = ...
        sourceMetadata.RunNumber;

    EEG.event(iEvent).source_xdf = ...
        char(xdfFile);

    EEG.event(iEvent).source_recording = ...
        char(sourceMetadata.RecordingLabel);
end

%% Add boundary events for EEG timestamp gaps

% Missing EEG samples are not synthesized or interpolated.
for iGap = 1:height(eegTimestampGapTable)

    iEEGEvent = ...
        height(mappedEventTable) + iGap;

    EEG.event(iEEGEvent).type = ...
        'boundary';

    EEG.event(iEEGEvent).latency = ...
        eegTimestampGapTable.SampleBeforeGap(iGap) + 0.5;

    EEG.event(iEEGEvent).duration = ...
        eegTimestampGapTable.MissingSampleCount(iGap);

    EEG.event(iEEGEvent).side = ...
        '';

    EEG.event(iEEGEvent).segment_index = ...
        NaN;

    EEG.event(iEEGEvent).lsl_time = ...
        NaN;

    EEG.event(iEEGEvent).matched_eeg_lsl_time = ...
        NaN;

    EEG.event(iEEGEvent).mapping_error_ms = ...
        NaN;

    EEG.event(iEEGEvent).mapping_status = ...
        'EEG_timestamp_gap_boundary';

    EEG.event(iEEGEvent).gap_start_lsl_time = ...
        eegTimestampGapTable.LSLBeforeGap(iGap);

    EEG.event(iEEGEvent).gap_end_lsl_time = ...
        eegTimestampGapTable.LSLAfterGap(iGap);

    EEG.event(iEEGEvent).subject_label = ...
        char(sourceMetadata.SubjectLabel);

    EEG.event(iEEGEvent).day_label = ...
        char(sourceMetadata.DayLabel);

    EEG.event(iEEGEvent).session_label = ...
        char(sourceMetadata.SessionLabel);

    EEG.event(iEEGEvent).condition_label = ...
        char(sourceMetadata.ConditionLabel);

    EEG.event(iEEGEvent).task_label = ...
        char(sourceMetadata.TaskLabel);

    EEG.event(iEEGEvent).run_number = ...
        sourceMetadata.RunNumber;

    EEG.event(iEEGEvent).source_xdf = ...
        char(xdfFile);

    EEG.event(iEEGEvent).source_recording = ...
        char(sourceMetadata.RecordingLabel);
end

%% Sort gait and boundary events by EEG latency

if ~isempty(EEG.event)

    [~, eventSortOrder] = sort( ...
        double([EEG.event.latency]));

    EEG.event = ...
        EEG.event(eventSortOrder);
end

%% Save provenance and timestamp-gap information

EEG.subject = ...
    char(sourceMetadata.SubjectLabel);

EEG.condition = ...
    char(sourceMetadata.ConditionLabel);

EEG.etc.source_xdf = ...
    char(xdfFile);

EEG.etc.source_metadata = ...
    sourceMetadata;

EEG.etc.source_grf_event_file = ...
    sourceEventFile;

EEG.etc.eeg_stream_name = ...
    char(get_stream_text_field(EEGStream, 'name'));

EEG.etc.eeg_first_lsl_time = ...
    eegTimeStamps(1);

EEG.etc.eeg_last_lsl_time = ...
    eegTimeStamps(end);

EEG.etc.eeg_nominal_srate = ...
    nominalEEGSrate;

EEG.etc.eeg_measured_timestamp_srate = ...
    measuredEEGSrate;

EEG.etc.raw_eeg_stream_channel_count = ...
    rawEEGChannelCount;

EEG.etc.selected_eeg_stream_channel_indices = ...
    selectedEEGChannelIndices;

EEG.etc.selected_eeg_stream_channel_labels = ...
    selectedEEGChannelLabels;

EEG.etc.dropped_auxiliary_channel_indices = ...
    droppedEEGChannelIndices;

EEG.etc.dropped_auxiliary_channel_labels = ...
    droppedEEGChannelLabels;

EEG.etc.eeg_channel_selection_method = ...
    char(channelSelectionMethod);

EEG.etc.grf_to_eeg_mapping = ...
    mappingTable;

EEG.etc.eeg_timestamp_gaps = ...
    eegTimestampGapTable;

EEG.etc.excluded_grf_events_due_to_eeg_gaps = ...
    excludedEventTable;

EEG.etc.timestamp_gap_threshold_sec = ...
    timestampGapThresholdSec;

EEG.etc.grf_to_eeg_processing = struct( ...
    'version', char(processingVersion), ...
    'source_event_file', sourceEventFile, ...
    'source_event_signature', char(sourceEventSignature), ...
    'source_xdf', char(xdfFile), ...
    'source_xdf_signature', char(sourceXDFSignature), ...
    'maximum_mapping_error_ms', maximumMappingErrorMs, ...
    'timestamp_gap_factor', timestampGapFactor, ...
    'minimum_timestamp_gap_sec', minimumTimestampGapSec, ...
    'created_on', char(datetime( ...
        'now', 'Format', 'yyyy-MM-dd HH:mm:ss')));

%% Add project channel locations

EEG.chanlocs = ...
    projectChanlocs;

if numel(EEG.chanlocs) ~= EEG.nbchan

    error([ ...
        'Channel-location count does not match EEG.nbchan.\n' ...
        'Channel locations: %d\n' ...
        'EEG channels: %d'], ...
        numel(EEG.chanlocs), ...
        EEG.nbchan);
end

EEG = eeg_checkset(EEG);
EEG = eeg_checkset(EEG, 'eventconsistency');

%% Final QC summary

mappedEventCountTable = groupsummary( ...
    mappedEventTable, ...
    'EventType');

fprintf('\nSuccessfully mapped gait events by type:\n');

disp( ...
    mappedEventCountTable(:, ...
        {'EventType', 'GroupCount'}));

if ~isempty(excludedEventTable)

    excludedEventCountTable = groupsummary( ...
        excludedEventTable, ...
        'EventType');

    fprintf('\nEvents excluded because no EEG sample existed:\n');

    disp( ...
        excludedEventCountTable(:, ...
            {'EventType', 'GroupCount'}));
end

mappedAbsoluteMappingErrorMs = abs( ...
    double(mappedEventTable.MappingErrorMs));

fprintf('\nMapping error for successfully mapped events:\n');

fprintf('Median absolute error: %.6f ms\n', ...
    median(mappedAbsoluteMappingErrorMs));

fprintf('Maximum absolute error: %.6f ms\n', ...
    max(mappedAbsoluteMappingErrorMs));

fprintf('Original GRF event count: %d\n', ...
    height(mappingTable));

fprintf('Mapped gait-event count: %d\n', ...
    height(mappedEventTable));

fprintf('Excluded gait-event count: %d\n', ...
    height(excludedEventTable));

fprintf('EEG boundary-event count: %d\n', ...
    height(eegTimestampGapTable));

fprintf('EEG sampling rate saved in EEGLAB: %.6f Hz\n', ...
    EEG.srate);

fprintf('Total EEGLAB event count (mapped + boundary): %d\n', ...
    numel(EEG.event));

fprintf('Channel locations: %d / %d\n', ...
    numel(EEG.chanlocs), ...
    EEG.nbchan);

%% Save the session EEG and QC tables

outputSetName = [ ...
    xdfBaseName ...
    '_EEG_500Hz_with_GRF_events.set'];

mappingCSVName = [ ...
    xdfBaseName ...
    '_GRF_to_EEG_event_mapping.csv'];

mappingCSVFile = fullfile( ...
    eegEventOutputFolder, ...
    mappingCSVName);

gapCSVName = [ ...
    xdfBaseName ...
    '_EEG_timestamp_gaps.csv'];

gapCSVFile = fullfile( ...
    eegEventOutputFolder, ...
    gapCSVName);

writetable( ...
    mappingTable, ...
    mappingCSVFile);

writetable( ...
    eegTimestampGapTable, ...
    gapCSVFile);

EEG = pop_saveset( ...
    EEG, ...
    'filename', ...
    outputSetName, ...
    'filepath', ...
    eegEventOutputFolder, ...
    'savemode', ...
    'onefile');

%% Completion summary

fprintf('\n====================================================\n');
fprintf('GRF EVENTS MAPPED TO EEG SUCCESSFULLY\n');
fprintf('====================================================\n');

fprintf('Session EEG .set:\n%s\n', ...
    fullfile(eegEventOutputFolder, outputSetName));

fprintf('\nMapping CSV:\n%s\n', ...
    mappingCSVFile);

fprintf('\nEEG timestamp-gap CSV:\n%s\n', ...
    gapCSVFile);

fprintf('\nThe EEG remained at 500 Hz. No resampling was performed.\n');

fprintf([ ...
    'GRF events inside EEG timestamp gaps were excluded rather than ' ...
    'forced onto an unrelated EEG sample.\n']);

fprintf('EEGLAB boundary events were added at timestamp gaps.\n');

fprintf('No session concatenation or BeMoBIL processing was performed.\n');

%% Local helper functions

function metadata = ...
        parse_xdf_source_metadata(xdfFile)

[~, baseName, extension] = ...
    fileparts(char(xdfFile));

fullName = ...
    string([baseName extension]);

isOldVersion = ~isempty(regexpi( ...
    char(fullName), ...
    '_old\d*\.xdf$', ...
    'once'));

cleanBaseName = ...
    regexprep( ...
        string(baseName), ...
        '_old\d*$', ...
        '', ...
        'ignorecase');

token = ...
    regexp( ...
        char(cleanBaseName), ...
        ['^sub-(?<subject>.+?)_' ...
         '(?<day>day\d+)_' ...
         'ses-(?<session>.+?)_' ...
         'task-(?<task>.+?)_' ...
         'run-(?<run>\d+)_' ...
         'eeg$'], ...
        'names', ...
        'once');

if isempty(token)

    error([ ...
        'Could not parse subject/day/session/task/run metadata from:\n%s\n' ...
        'Expected a filename ending like ' ...
        '_day2_ses-Condition_task-Default_run-001_eeg.xdf.'], ...
        xdfFile);
end

runNumber = ...
    str2double(token.run);

if ~isfinite(runNumber)

    error('Invalid run number in XDF filename:\n%s', ...
        xdfFile);
end

metadata = struct();

metadata.SubjectLabel = ...
    "sub-" + string(token.subject);

metadata.DayLabel = ...
    string(token.day);

metadata.SessionLabel = ...
    "ses-" + string(token.session);

metadata.ConditionLabel = ...
    string(token.session);

metadata.TaskLabel = ...
    string(token.task);

metadata.RunNumber = ...
    runNumber;

metadata.RecordingLabel = ...
    metadata.SubjectLabel + "_" + ...
    metadata.DayLabel + "_" + ...
    metadata.SessionLabel + "_" + ...
    compose("run-%03d", runNumber);

metadata.IsOldVersion = ...
    isOldVersion;

metadata.XDFPath = ...
    string(xdfFile);
end

function [selectedIndex, streamSummary] = ...
        find_real_eeg_stream( ...
            streams, ...
            expectedName, ...
            expectedChannels, ...
            targetSrate)

nStreams = numel(streams);

streamIndex = ...
    (1:nStreams)';

streamName = ...
    strings(nStreams, 1);

streamType = ...
    strings(nStreams, 1);

nominalSrate = ...
    nan(nStreams, 1);

channelCount = ...
    nan(nStreams, 1);

sampleCount = ...
    nan(nStreams, 1);

for iStream = 1:nStreams

    currentStream = ...
        streams{iStream};

    streamName(iStream) = ...
        get_stream_text_field( ...
            currentStream, ...
            'name');

    streamType(iStream) = ...
        get_stream_text_field( ...
            currentStream, ...
            'type');

    nominalSrate(iStream) = ...
        get_stream_nominal_srate( ...
            currentStream);

    if isfield(currentStream, 'time_series') && ...
            isnumeric(currentStream.time_series)

        currentData = ...
            currentStream.time_series;

        currentTimestamps = ...
            currentStream.time_stamps;

        sampleCount(iStream) = ...
            numel(currentTimestamps);

        if size(currentData, 2) == sampleCount(iStream)

            channelCount(iStream) = ...
                size(currentData, 1);

        elseif size(currentData, 1) == sampleCount(iStream)

            channelCount(iStream) = ...
                size(currentData, 2);
        end
    end
end

streamSummary = table( ...
    streamIndex, ...
    streamName, ...
    streamType, ...
    nominalSrate, ...
    channelCount, ...
    sampleCount, ...
    'VariableNames', { ...
        'StreamIndex', ...
        'Name', ...
        'Type', ...
        'NominalSrate', ...
        'ChannelCount', ...
        'SampleCount'});

exactNameMatch = ...
    strcmpi(streamName, expectedName) & ...
    channelCount >= expectedChannels & ...
    channelCount <= expectedChannels + 16 & ...
    abs(nominalSrate - targetSrate) <= 1;

candidateIndices = ...
    find(exactNameMatch);

if isempty(candidateIndices)

    fallbackMatch = ...
        channelCount >= expectedChannels & ...
        channelCount <= expectedChannels + 16 & ...
        abs(nominalSrate - targetSrate) <= 1 & ...
        (contains(lower(streamType), 'eeg') | ...
         contains(lower(streamName), 'liveamp'));

    candidateIndices = ...
        find(fallbackMatch);
end

if numel(candidateIndices) ~= 1

    disp(streamSummary);

    error([ ...
        'Could not identify exactly one real LiveAmp 500 Hz EEG stream.\n' ...
        'Number of candidates: %d'], ...
        numel(candidateIndices));
end

selectedIndex = ...
    candidateIndices(1);

end

function [selectedIndices, droppedIndices, selectionMethod] = ...
        select_project_eeg_channels( ...
            rawLabels, ...
            projectLabels, ...
            rawChannelCount, ...
            expectedChannelCount, ...
            expectedAuxiliaryLabels, ...
            expectedStreamName)

selectedIndices = [];
droppedIndices = [];
selectionMethod = "";

rawLabels = ...
    string(rawLabels(:));

projectLabels = ...
    string(projectLabels(:));

expectedAuxiliaryLabels = ...
    string(expectedAuxiliaryLabels(:));

if numel(rawLabels) ~= rawChannelCount || ...
        any(strlength(strtrim(rawLabels)) == 0)

    error([ ...
        'The XDF EEG stream does not provide a complete channel-label ' ...
        'list. The ACC channels cannot be removed safely by label.']);
end

normalizedRawLabels = ...
    rawLabels;

streamPrefix = ...
    string(expectedStreamName) + "_";

hasStreamPrefix = startsWith( ...
    normalizedRawLabels, ...
    streamPrefix, ...
    'IgnoreCase', ...
    true);

normalizedRawLabels(hasStreamPrefix) = extractAfter( ...
    normalizedRawLabels(hasStreamPrefix), ...
    strlength(streamPrefix));

if rawChannelCount == expectedChannelCount + ...
        numel(expectedAuxiliaryLabels)

    auxiliaryIndices = nan( ...
        numel(expectedAuxiliaryLabels), ...
        1);

    for iAuxiliary = 1:numel(expectedAuxiliaryLabels)

        currentMatch = find(strcmpi( ...
            strtrim(normalizedRawLabels), ...
            strtrim(expectedAuxiliaryLabels(iAuxiliary))));

        if numel(currentMatch) ~= 1

            error([ ...
                'Expected exactly one %s channel in the 67-channel ' ...
                'LiveAmp stream, but found %d.'], ...
                expectedAuxiliaryLabels(iAuxiliary), ...
                numel(currentMatch));
        end

        auxiliaryIndices(iAuxiliary) = ...
            currentMatch;
    end

    if numel(unique(auxiliaryIndices)) ~= ...
            numel(expectedAuxiliaryLabels)

        error('The ACC channel-label matches are not unique.');
    end

    droppedIndices = ...
        auxiliaryIndices;

elseif rawChannelCount == expectedChannelCount

    droppedIndices = ...
        zeros(0, 1);

else

    error([ ...
        'Expected either %d EEG channels or %d channels ' ...
        '(64 EEG + ACC_X/ACC_Y/ACC_Z), but found %d.'], ...
        expectedChannelCount, ...
        expectedChannelCount + numel(expectedAuxiliaryLabels), ...
        rawChannelCount);
end

remainingIndices = setdiff( ...
    (1:rawChannelCount)', ...
    droppedIndices, ...
    'stable');

if numel(remainingIndices) ~= expectedChannelCount

    error([ ...
        'Removing ACC_X/ACC_Y/ACC_Z did not leave exactly %d EEG ' ...
        'channels. Remaining channels: %d'], ...
        expectedChannelCount, ...
        numel(remainingIndices));
end

if numel(projectLabels) ~= expectedChannelCount || ...
        any(strlength(strtrim(projectLabels)) == 0)

    error('chanlocs.ced does not contain 64 valid channel labels.');
end

matchedIndices = ...
    nan(expectedChannelCount, 1);

for iChannel = 1:expectedChannelCount

    currentMatch = remainingIndices(strcmpi( ...
        strtrim(normalizedRawLabels(remainingIndices)), ...
        strtrim(projectLabels(iChannel))));

    if numel(currentMatch) ~= 1

        error([ ...
            'Could not match chanlocs.ced channel %s uniquely in the ' ...
            'XDF EEG stream. Number of matches: %d'], ...
            projectLabels(iChannel), ...
            numel(currentMatch));
    end

    matchedIndices(iChannel) = ...
        currentMatch;
end

if numel(unique(matchedIndices)) ~= expectedChannelCount

    error('The 64 EEG channel-label matches are not unique.');
end

selectedIndices = ...
    matchedIndices;

if isempty(droppedIndices)

    selectionMethod = ...
        "matched_64_EEG_channels_to_chanlocs_labels";

else

    selectionMethod = ...
        "removed_ACC_X_ACC_Y_ACC_Z_then_matched_chanlocs_labels";
end

end

function channelLabels = ...
        get_stream_channel_labels( ...
            stream, ...
            channelCount)

channelLabels = ...
    strings(channelCount, 1);

if ~isfield(stream, 'info') || ...
        ~isfield(stream.info, 'desc')

    return;
end

description = ...
    stream.info.desc;

while iscell(description) && ...
        numel(description) == 1

    description = ...
        description{1};
end

if ~isstruct(description) || ...
        ~isfield(description, 'channels')

    return;
end

channelsNode = ...
    description.channels;

while iscell(channelsNode) && ...
        numel(channelsNode) == 1

    channelsNode = ...
        channelsNode{1};
end

if ~isstruct(channelsNode) || ...
        ~isfield(channelsNode, 'channel')

    return;
end

channelEntries = ...
    channelsNode.channel;

if iscell(channelEntries)

    numberOfEntries = min( ...
        channelCount, ...
        numel(channelEntries));

    for iChannel = 1:numberOfEntries

        channelLabels(iChannel) = ...
            get_channel_entry_label( ...
                channelEntries{iChannel});
    end

elseif isstruct(channelEntries)

    numberOfEntries = min( ...
        channelCount, ...
        numel(channelEntries));

    for iChannel = 1:numberOfEntries

        channelLabels(iChannel) = ...
            get_channel_entry_label( ...
                channelEntries(iChannel));
    end
end

end

function channelLabel = ...
        get_channel_entry_label(channelEntry)

channelLabel = "";

while iscell(channelEntry) && ...
        numel(channelEntry) == 1

    channelEntry = ...
        channelEntry{1};
end

if ~isstruct(channelEntry) || ...
        ~isfield(channelEntry, 'label')

    return;
end

rawLabel = ...
    channelEntry.label;

while iscell(rawLabel) && ...
        ~isempty(rawLabel)

    rawLabel = ...
        rawLabel{1};
end

if isempty(rawLabel)

    return;
end

channelLabel = ...
    string(rawLabel);

channelLabel = ...
    channelLabel(1);

end

function nominalSrate = ...
        get_stream_nominal_srate(stream)

nominalSrate = ...
    NaN;

if ~isfield(stream, 'info') || ...
        ~isfield(stream.info, 'nominal_srate')

    return;
end

rawValue = ...
    stream.info.nominal_srate;

while iscell(rawValue) && ...
        ~isempty(rawValue)

    rawValue = ...
        rawValue{1};
end

if isnumeric(rawValue)

    nominalSrate = ...
        double(rawValue(1));

else

    nominalSrate = ...
        str2double(string(rawValue));
end

end

function textValue = ...
        get_stream_text_field( ...
            stream, ...
            fieldName)

textValue = "";

if ~isfield(stream, 'info') || ...
        ~isfield(stream.info, fieldName)

    return;
end

rawValue = ...
    stream.info.(fieldName);

while iscell(rawValue) && ...
        ~isempty(rawValue)

    rawValue = ...
        rawValue{1};
end

if isempty(rawValue)

    return;
end

textValue = ...
    string(rawValue);

textValue = ...
    textValue(1);

end

function conditions = canonical_condition_local(values)

values = string(values(:));
conditions = strings(size(values));

for valueIndex = 1:numel(values)

    key = lower(char(values(valueIndex)));
    key = regexprep(key, '[^a-z0-9]', '');

    if contains(key, 'noexo') && contains(key, 'pre')
        conditions(valueIndex) = "NoExoPre";

    elseif contains(key, 'noexo') && contains(key, 'post')
        conditions(valueIndex) = "NoExoPost";

    elseif contains(key, 'aquaplus') || contains(key, 'aquaextra')
        conditions(valueIndex) = "AquaPlus";

    elseif contains(key, 'transparent') || contains(key, 'exooff')
        conditions(valueIndex) = "Transparent";

    elseif contains(key, 'sport')
        conditions(valueIndex) = "Sport";

    elseif contains(key, 'boost')
        conditions(valueIndex) = "Boost";

    elseif contains(key, 'aqua')
        conditions(valueIndex) = "Aqua";

    elseif contains(key, 'eco') || strcmp(key, 'exo') || ...
            ~isempty(regexp(key, 'exo\d*(on)?$', 'once'))
        conditions(valueIndex) = "Exo";

    else
        error('Cannot canonicalize condition label: %s', ...
            char(values(valueIndex)));
    end
end

end


function keys = canonical_label_key_local(values)

keys = lower( ...
    regexprep( ...
        strtrim(string(values(:))), ...
        '[^a-zA-Z0-9]', ...
        ''));

if any(strlength(keys) == 0)
    error('A required subject/condition label is empty.');
end

end

function keys = canonical_subject_key_local(values)

keys = canonical_label_key_local(values);
keys = regexprep(keys, '^sub', '');

end

