% GOAL
%   Map GRF-derived gait events onto the corresponding BIDS-derived EEGLAB
%   recording using the original XDF EEG timestamps as LSL timing provenance.
%
% INPUT
%   batchEventFile          Per-recording GRF gait-event MAT.
%   batchBidsEEGLABSet      Run-separated BIDS-derived EEGLAB dataset.
%   batchOutputStem         Canonical BIDS entity stem.
%   batchCanonicalSubject   Canonical SubjectID from Step 02 (sub-XX).
%   batchOriginalSubject    Original acquisition identity for provenance.
%   batchGRFOutputFolder    Subject GRF output folder.
%   batchEEGOutputFolder    Subject EEG-with-GRF-events output folder.
%
% APPROACH
%   1. Treat Step 02 SubjectID as the authoritative analysis identity.
%   2. Cross-check canonical/original identity across the event MAT, XDF,
%      import-table row, and BIDS-derived EEG before normalizing labels.
%   3. Verify source condition/run metadata and exact XDF/BIDS sample identity.
%   4. Map GRF event LSL times to real EEG samples without resampling.
%   5. Exclude events inside genuine EEG timestamp gaps and add boundaries.
%   6. Save the mapped EEG plus mapping/timestamp-gap audit tables.
%
% OUTPUT
%   *_desc-grfevents_eeg.set
%   *_desc-grfeventmapping_events.csv
%   *_desc-eegtimestampgaps_events.csv
%
% USED BY
%   step04_process_subject_grf_eeg.m

function step04_map_grf_events_to_eeg_internal( ...
        batchEventFile, batchBidsEEGLABSet, batchOutputStem, ...
        batchCanonicalSubject, batchOriginalSubject, ...
        batchGRFOutputFolder, batchEEGOutputFolder)
% GOAL
%   Map GRF-derived gait events onto one explicitly supplied run-separated
%   EEGLAB recording created FROM BIDS in Step 02B.
%
% INPUT
%   batchEventFile          GRF gait-event MAT for this recording.
%   batchBidsEEGLABSet      Canonical BIDS-derived, unresampled EEGLAB set.
%   batchOutputStem         Canonical BIDS entity stem for derivative names.
%   batchCanonicalSubject   Canonical participant identity, e.g. sub-01.
%   batchOriginalSubject    Original acquisition identity for provenance only.
%   batchGRFOutputFolder    GRF/event output folder.
%   batchEEGOutputFolder    Mapped EEG output folder.
%
% METHOD
%   BIDS-derived EEGLAB supplies all EEG amplitudes. Source XDF supplies only
%   the original LSL EEG timestamps required for GRF-to-EEG alignment. Paths
%   and identities are explicit function arguments; no environment-variable
%   worker state is used.

if nargin < 1, batchEventFile = ""; end
if nargin < 2, batchBidsEEGLABSet = ""; end
if nargin < 3, batchOutputStem = ""; end
if nargin < 4, batchCanonicalSubject = ""; end
if nargin < 5, batchOriginalSubject = ""; end
if nargin < 6, batchGRFOutputFolder = ""; end
if nargin < 7, batchEEGOutputFolder = ""; end

batchEventFile = char(strtrim(string(batchEventFile)));
batchBidsEEGLABSet = char(strtrim(string(batchBidsEEGLABSet)));
batchOutputStem = char(strtrim(string(batchOutputStem)));
batchCanonicalSubject = char(strtrim(string(batchCanonicalSubject)));
batchOriginalSubject = char(strtrim(string(batchOriginalSubject)));
batchGRFOutputFolder = char(strtrim(string(batchGRFOutputFolder)));
batchEEGOutputFolder = char(strtrim(string(batchEEGOutputFolder)));
batchModeRequested = ~isempty(batchEventFile) || ~isempty(batchBidsEEGLABSet) || ...
    ~isempty(batchGRFOutputFolder) || ~isempty(batchEEGOutputFolder);

processingVersion = ...
    "GRF_to_BIDS_EEGLAB_mapping_v6_retained_samples";

if ~batchModeRequested
    clc;
    close all;
end

%% Load project paths and Step 03 configuration

scriptsRoot = hipexo.project_root();
addpath(scriptsRoot, '-begin');
addpath(fullfile(scriptsRoot, 'config'), '-begin');

P = project_paths();
cfg = config_step03_04_grf_processing();
eegQC = config_step01_02_xdf_import();

grfSegmentationFolder = P.grfSegmentationFolder;
channelLocationFile = P.channelLocationFile;

if ~isempty(batchGRFOutputFolder)
    grfSegmentationFolder = batchGRFOutputFolder;
end

if ~isfolder(grfSegmentationFolder)
    error('The GRF output folder does not exist:\n%s', ...
        grfSegmentationFolder);
end

if ~isfile(channelLocationFile)
    error('Cannot find channel-location file:\n%s', ...
        channelLocationFile);
end

if isempty(batchBidsEEGLABSet) || ~isfile(batchBidsEEGLABSet)
    error(['Step 04 requires a valid run-separated BIDS-derived EEGLAB set.\n' ...
        'Input BIDS-derived EEGLAB set: %s'], batchBidsEEGLABSet);
end

sourceBidsEEGLABSet = string(batchBidsEEGLABSet);
sourceBidsEEGLABSignature = hipexo.eeglab_dataset_signature(char(sourceBidsEEGLABSet));

if isempty(batchOutputStem)
    [~, rawStem] = fileparts(batchBidsEEGLABSet);
    batchOutputStem = regexprep(rawStem, '_desc-bidsraw_eeg$', '');
end

if ~isempty(batchEEGOutputFolder)
    eegEventOutputFolder = batchEEGOutputFolder;
else
    eegEventOutputFolder = P.eegWithGRFEventsFolder;
end

if ~isfolder(eegEventOutputFolder)
    mkdir(eegEventOutputFolder);
end

%% Mapping settings

expectedEEGStreamName = cfg.mapping.expectedEEGStreamName;
expectedEEGChannels = cfg.mapping.expectedEEGChannels;
expectedAuxiliaryLabels = cfg.mapping.expectedAuxiliaryLabels;
targetEEGSrate = cfg.mapping.targetEEGSrateHz;
maximumMappingErrorMs = cfg.mapping.maximumMappingErrorMs;
timestampGapFactor = cfg.mapping.timestampGapFactor;
minimumTimestampGapSec = cfg.mapping.minimumTimestampGapSec;

%% Select one saved per-XDF GRF event file

if ~isempty(batchEventFile)

    sourceEventFile = batchEventFile;

else

    eventFileFilter = fullfile( ...
        grfSegmentationFolder, ...
        '*.mat');

    [selectedFile, selectedFolder] = uigetfile( ...
        eventFileFilter, ...
        'Select one GRF gait-event MAT file');

    if isequal(selectedFile, 0)
        error('No GRF gait-event file was selected.');
    end

    sourceEventFile = fullfile( ...
        selectedFolder, ...
        selectedFile);
end

if ~isfile(sourceEventFile)
    error('Cannot find the GRF gait-event MAT file:\n%s', ...
        sourceEventFile);
end

sourceEventSignature = hipexo.file_metadata_signature(sourceEventFile);

loadedEvents = load(sourceEventFile);

if ~isfield(loadedEvents, 'allEventTable')
    error([ ...
        'The selected MAT file does not contain allEventTable:\n%s'], ...
        sourceEventFile);
end

allEventTable = loadedEvents.allEventTable;

requiredEventVariables = { ...
    'Subject', ...
    'Condition', ...
    'EventType', ...
    'Side', ...
    'SegmentIndex', ...
    'LSLTime', ...
    'XDFPath'};

if ~all(ismember( ...
        requiredEventVariables, ...
        allEventTable.Properties.VariableNames))

    error([ ...
        'The event table is missing one or more required variables:\n%s'], ...
        strjoin(requiredEventVariables, ', '));
end

if isempty(allEventTable)
    error('The selected event table is empty.');
end

eventTypes = string(allEventTable.EventType);
validEventTypes = ["RHS", "RTO", "LHS", "LTO"];

if any(~ismember(eventTypes, validEventTypes))
    error('The event table contains an unexpected EventType.');
end

xdfPaths = unique(string(allEventTable.XDFPath));
xdfPaths(strlength(xdfPaths) == 0) = [];

if numel(xdfPaths) ~= 1
    error([ ...
        'The selected event MAT must contain events from exactly one XDF.\n' ...
        'Number of unique XDF paths found: %d'], ...
        numel(xdfPaths));
end

xdfFile = xdfPaths(1);

if ~isfile(xdfFile)
    error('Cannot find the source XDF:\n%s', xdfFile);
end

sourceXDFSignature = hipexo.file_metadata_signature(xdfFile);

sourceMetadata = ...
    parse_xdf_source_metadata(xdfFile);

canonicalSubject = ...
    strtrim(string(batchCanonicalSubject));

originalSubject = ...
    strtrim(string(batchOriginalSubject));

if ismissing(canonicalSubject) || ...
        strlength(canonicalSubject) == 0

    error('Canonical participant identity is missing for GRF-to-EEG mapping.');
end

if isempty(regexp( ...
        char(canonicalSubject), ...
        '^sub-[0-9]+$', ...
        'once'))

    error([ ...
        'Invalid canonical participant identity: %s\n' ...
        'Expected the Step 02 SubjectID format sub-XX.'], ...
        canonicalSubject);
end

if ismissing(originalSubject) || ...
        strlength(originalSubject) == 0

    error('Original participant identity is missing for GRF-to-EEG mapping.');
end

eventSubjectValues = ...
    unique(strtrim(string(allEventTable.Subject)));

eventSubjectValues( ...
    ismissing(eventSubjectValues) | ...
    strlength(eventSubjectValues) == 0) = [];

if numel(eventSubjectValues) ~= 1

    error([ ...
        'GRF event table must contain exactly one non-empty Subject label. ' ...
        'Found: %s'], ...
        strjoin(eventSubjectValues, ', '));
end

eventSubjectKey = ...
    subject_identity_key_local(eventSubjectValues(1));

if eventSubjectKey ~= subject_identity_key_local(canonicalSubject) && ...
        eventSubjectKey ~= subject_identity_key_local(originalSubject)

    error([ ...
        'GRF event-table Subject belongs to a different participant.\n' ...
        'Event table: %s | Canonical: %s | Original: %s'], ...
        eventSubjectValues(1), ...
        canonicalSubject, ...
        originalSubject);
end

% Step 02 is the authoritative participant-identity source. Older GRF
% event MAT files may contain the legacy raw-XDF label (for example
% Pilot2_3). Normalize the in-memory event table to the canonical sub-XX
% identity before mapping; the original XDF identity remains available
% separately in provenance metadata.
allEventTable.Subject(:) = canonicalSubject;

eventConditions = unique( ...
    canonical_condition_local(allEventTable.Condition));

expectedCondition = ...
    canonical_condition_local(sourceMetadata.ConditionLabel);

if numel(eventConditions) ~= 1 || ...
        eventConditions(1) ~= expectedCondition
    error([ ...
        'GRF event-table Condition does not match the source XDF filename.\n' ...
        'Event table: %s -> %s | XDF: %s -> %s'], ...
        strjoin(unique(string(allEventTable.Condition)), ', '), ...
        strjoin(eventConditions, ', '), ...
        sourceMetadata.ConditionLabel, ...
        expectedCondition);
end

if ~isfinite(sourceMetadata.RunNumber) || ...
        sourceMetadata.RunNumber < 1 || ...
        sourceMetadata.RunNumber ~= round(sourceMetadata.RunNumber)

    error([ ...
        'The source recording has an invalid run number.\n' ...
        'Resolved run number: %g\nSource XDF:\n%s'], ...
        sourceMetadata.RunNumber, ...
        xdfFile);
end

if sourceMetadata.IsOldVersion

    error('Old XDF versions are not accepted:\n%s', ...
        xdfFile);
end

canonicalRecordingLabel = ...
    string(batchOutputStem);

%% Load XDF and find the real EEG stream

fprintf('\n====================================================\n');
fprintf('MAP GRF EVENTS TO BIDS-DERIVED EEG\n');
fprintf('====================================================\n');
fprintf('Source event MAT:\n%s\n\n', sourceEventFile);
fprintf('Source XDF (timing provenance only):\n%s\n\n', xdfFile);
fprintf('Source BIDS-derived EEGLAB signal:\n%s\n\n', sourceBidsEEGLABSet);

[streams, ~] = load_xdf(char(xdfFile));

if isempty(streams)
    error('No streams were loaded from the XDF.');
end

[eegStreamIndex, streamSummary] = find_real_eeg_stream( ...
    streams, ...
    expectedEEGStreamName, ...
    expectedEEGChannels, ...
    targetEEGSrate);

disp(streamSummary);

EEGStream = streams{eegStreamIndex};
eegTimeStamps = double(EEGStream.time_stamps(:)');

if isempty(eegTimeStamps)
    error('The source XDF EEG stream has no LSL timestamps.');
end

% Do NOT use EEGStream.time_series for downstream EEG amplitudes. The XDF is
% retained here solely because it contains the original LSL clock needed to
% align the GRF events with the BIDS-derived recording.
xdfEEGSampleCount = numel(eegTimeStamps);

%% Load canonical BIDS-derived EEGLAB signal and select project EEG channels

if exist('eeglab', 'file') ~= 2
    error('Cannot find eeglab.m. Check eeglabFolder in project_paths.m.');
end

[ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab('nogui'); %#ok<ASGLU>

[sourceBidsFolder, sourceBidsFile, sourceBidsExt] = ...
    fileparts(char(sourceBidsEEGLABSet));
BIDS_EEG = pop_loadset('filename', [sourceBidsFile sourceBidsExt], ...
    'filepath', sourceBidsFolder);

if ~isfield(BIDS_EEG, 'etc') || ...
        ~isfield(BIDS_EEG.etc, 'hipexo_canonical_subject_id') || ...
        ~isfield(BIDS_EEG.etc, 'hipexo_original_subject_id')

    error([ ...
        'The BIDS-derived EEGLAB dataset lacks Step 02B participant ' ...
        'identity metadata. Re-run Step 02B for this recording.']);
end

bidsCanonicalSubject = ...
    strtrim(string(BIDS_EEG.etc.hipexo_canonical_subject_id));

bidsOriginalSubject = ...
    strtrim(string(BIDS_EEG.etc.hipexo_original_subject_id));

% Step 02 binds the current acquisition folder to a canonical participant.
% Filenames can retain an earlier acquisition label. Verify the exact XDF
% path and signature saved by Step 02B before accepting that binding.
if ~isfield(BIDS_EEG.etc, 'hipexo_source_xdf') || ...
        ~isfield(BIDS_EEG.etc, 'hipexo_source_xdf_signature_at_bids_export') || ...
        ~strcmpi(strrep(strtrim(string(BIDS_EEG.etc.hipexo_source_xdf)), '\', '/'), ...
            strrep(strtrim(string(xdfFile)), '\', '/')) || ...
        string(BIDS_EEG.etc.hipexo_source_xdf_signature_at_bids_export) ~= ...
            string(sourceXDFSignature)
    error('BIDS EEG and GRF events are not bound to the same current source XDF.');
end

if ~strcmpi(bidsCanonicalSubject, canonicalSubject) || ...
        subject_identity_key_local(bidsOriginalSubject) ~= ...
        subject_identity_key_local(originalSubject)

    error([ ...
        'BIDS-derived EEG participant identity does not match the ' ...
        'current import-table row.\n' ...
        'Expected: %s / %s | BIDS EEG: %s / %s'], ...
        canonicalSubject, ...
        originalSubject, ...
        bidsCanonicalSubject, ...
        bidsOriginalSubject);
end

bidsDatasetSubject = "";

if isfield(BIDS_EEG, 'subject')
    bidsDatasetSubject = strtrim(string(BIDS_EEG.subject));
end

if ~isscalar(bidsDatasetSubject) || ...
        ~strcmpi(bidsDatasetSubject, canonicalSubject)

    error([ ...
        'BIDS-derived EEG.subject does not match canonical SubjectID.\n' ...
        'Expected: %s | BIDS EEG.subject: %s'], ...
        canonicalSubject, ...
        strjoin(bidsDatasetSubject, ', '));
end

if double(BIDS_EEG.pnts) ~= xdfEEGSampleCount || ...
        size(BIDS_EEG.data, 2) ~= xdfEEGSampleCount

    error([ ...
        'BIDS-derived EEG and XDF LSL timestamp vectors differ in sample count.\n' ...
        'BIDS-derived EEG.pnts: %d\n' ...
        'BIDS-derived data samples: %d\n' ...
        'XDF EEG timestamps: %d\n' ...
        'No mapping is allowed because sample identity is not one-to-one.'], ...
        double(BIDS_EEG.pnts), ...
        size(BIDS_EEG.data, 2), ...
        xdfEEGSampleCount);
end

% IMPORTANT:
% The BrainVision header written during BIDS conversion may contain an
% effective sampling rate inferred from the XDF timing (for example
% 499.9x Hz) even though the LiveAmp stream is nominally 500 Hz. That is
% NOT evidence that samples were resampled. The scientifically relevant
% no-resampling gate here is one-to-one sample identity, verified above.
bidsHeaderSrate = double(BIDS_EEG.srate);

if ~isscalar(bidsHeaderSrate) || ...
        ~isfinite(bidsHeaderSrate) || ...
        bidsHeaderSrate <= 0

    error('The BIDS-derived EEGLAB dataset has an invalid sampling rate.');
end

if isfield(BIDS_EEG, 'etc') && ...
        isfield(BIDS_EEG.etc, 'hipexo_bids_to_eeglab_no_resampling') && ...
        ~logical(BIDS_EEG.etc.hipexo_bids_to_eeglab_no_resampling)

    error([ ...
        'Step 02B provenance reports that the BIDS-derived EEGLAB ' ...
        'recording was resampled. Step 03 requires sample identity ' ...
        'with the source XDF.']);
end

projectChanlocs = readlocs(channelLocationFile);
if numel(projectChanlocs) ~= expectedEEGChannels
    error('Expected %d project channel locations, found %d.', ...
        expectedEEGChannels, numel(projectChanlocs));
end
projectChannelLabels = string({projectChanlocs.labels})';

rawEEGChannelCount = double(BIDS_EEG.nbchan);
if isempty(BIDS_EEG.chanlocs) || numel(BIDS_EEG.chanlocs) ~= rawEEGChannelCount
    error('BIDS-derived EEGLAB dataset lacks a complete channel-label list.');
end
rawEEGChannelLabels = string({BIDS_EEG.chanlocs.labels})';

[selectedEEGChannelIndices, droppedEEGChannelIndices, channelSelectionMethod] = ...
    select_project_eeg_channels( ...
        rawEEGChannelLabels, projectChannelLabels, rawEEGChannelCount, ...
        expectedEEGChannels, expectedAuxiliaryLabels, expectedEEGStreamName);

% Recheck the same source sample ranges as Step 01 before slicing amplitudes.
[retainedRanges, segmentAudit, checkedTimeStamps] = ...
    hipexo.check_eeg_segments(EEGStream, eegQC, xdfFile);
if isempty(retainedRanges)
    error('No continuous EEG segment passes the current Step 01 QC: %s', ...
        segmentAudit.status);
end
retainedIndex = cell(size(retainedRanges, 1), 1);
for k = 1:size(retainedRanges, 1)
    retainedIndex{k} = retainedRanges(k, 1):retainedRanges(k, 2);
end
retainedIndex = [retainedIndex{:}];
eegTimeStamps = checkedTimeStamps(retainedIndex);
eegData = double(BIDS_EEG.data(selectedEEGChannelIndices, retainedIndex));
retainedJoinSamples = cumsum(retainedRanges(:, 2) - retainedRanges(:, 1) + 1);
retainedJoinSamples = retainedJoinSamples(1:end-1);
retainedJoinSamples = retainedJoinSamples(:);
selectedEEGChannelLabels = rawEEGChannelLabels(selectedEEGChannelIndices);
droppedEEGChannelLabels = rawEEGChannelLabels(droppedEEGChannelIndices);
originalBidsEvents = BIDS_EEG.event;

if any(~isfinite(eegTimeStamps)) || ...
        any(diff(eegTimeStamps) <= 0)

    error('EEG timestamps must be finite and strictly increasing.');
end

measuredEEGSrate = 1 / median(diff(eegTimeStamps));
nominalEEGSrate = get_stream_nominal_srate(EEGStream);

if ~isfinite(nominalEEGSrate) || ...
        abs(nominalEEGSrate - targetEEGSrate) > 1

    error([ ...
        'The selected EEG stream does not match the configured nominal rate.\n' ...
        'Configured rate: %.9g Hz\n' ...
        'XDF nominal rate: %.9g Hz'], ...
        targetEEGSrate, ...
        nominalEEGSrate);
end

fprintf('XDF timing stream: %s\n', ...
    get_stream_text_field(EEGStream, 'name'));
fprintf('EEG amplitude source: BIDS-derived EEGLAB set\n');

fprintf('BIDS-derived raw channels: %d\n', ...
    rawEEGChannelCount);

fprintf('Selected EEG channels: %d\n', ...
    size(eegData, 1));

fprintf('Channel-selection method: %s\n', ...
    channelSelectionMethod);

if ~isempty(droppedEEGChannelIndices)

    fprintf('Dropped auxiliary channel indices: %s\n', ...
        mat2str(droppedEEGChannelIndices'));

    if any(strlength(droppedEEGChannelLabels) > 0)

        fprintf('Dropped auxiliary channel labels: %s\n', ...
            strjoin(droppedEEGChannelLabels, ', '));
    end
end

fprintf('EEG samples: %d\n', ...
    size(eegData, 2));

fprintf('Nominal XDF EEG rate: %.6f Hz\n', ...
    nominalEEGSrate);

fprintf('Measured XDF timestamp rate: %.6f Hz\n', ...
    measuredEEGSrate);

fprintf('BIDS/BrainVision header rate: %.6f Hz\n', ...
    bidsHeaderSrate);

fprintf([ ...
    'Output EEGLAB nominal rate: %.6f Hz ' ...
    '(sample data are not resampled)\n'], ...
    targetEEGSrate);

fprintf('EEG LSL range: %.6f to %.6f s\n', ...
    eegTimeStamps(1), ...
    eegTimeStamps(end));

%% Detect real gaps in the EEG timestamp vector

eegTimestampDifferenceSec = ...
    diff(eegTimeStamps(:));

medianEEGSampleIntervalSec = ...
    median(eegTimestampDifferenceSec);

timestampGapThresholdSec = max( ...
    timestampGapFactor * medianEEGSampleIntervalSec, ...
    minimumTimestampGapSec);

gapBeforeSample = unique([find( ...
    eegTimestampDifferenceSec > timestampGapThresholdSec); retainedJoinSamples]);

gapAfterSample = ...
    gapBeforeSample + 1;

if isempty(gapBeforeSample)

    eegTimestampGapTable = table( ...
        'Size', ...
        [0 8], ...
        'VariableTypes', { ...
            'double', ...
            'double', ...
            'double', ...
            'double', ...
            'double', ...
            'double', ...
            'double', ...
            'double'}, ...
        'VariableNames', { ...
            'GapIndex', ...
            'SampleBeforeGap', ...
            'SampleAfterGap', ...
            'LSLBeforeGap', ...
            'LSLAfterGap', ...
            'TimestampJumpSec', ...
            'MissingDurationSec', ...
            'MissingSampleCount'});

else

    timestampJumpSec = ...
        eegTimestampDifferenceSec(gapBeforeSample);

    missingDurationSec = max( ...
        0, ...
        timestampJumpSec - medianEEGSampleIntervalSec);

    missingSampleCount = max( ...
        0, ...
        round(timestampJumpSec * targetEEGSrate) - 1);

    eegTimestampGapTable = table( ...
        (1:numel(gapBeforeSample))', ...
        double(gapBeforeSample(:)), ...
        double(gapAfterSample(:)), ...
        reshape( ...
            double(eegTimeStamps(gapBeforeSample)), ...
            [], ...
            1), ...
        reshape( ...
            double(eegTimeStamps(gapAfterSample)), ...
            [], ...
            1), ...
        double(timestampJumpSec(:)), ...
        double(missingDurationSec(:)), ...
        double(missingSampleCount(:)), ...
        'VariableNames', { ...
            'GapIndex', ...
            'SampleBeforeGap', ...
            'SampleAfterGap', ...
            'LSLBeforeGap', ...
            'LSLAfterGap', ...
            'TimestampJumpSec', ...
            'MissingDurationSec', ...
            'MissingSampleCount'});
end

fprintf('\nEEG timestamp-gap check:\n');

fprintf('Gap threshold: %.6f s\n', ...
    timestampGapThresholdSec);

fprintf('Detected gaps: %d\n', ...
    height(eegTimestampGapTable));

if ~isempty(eegTimestampGapTable)
    disp(eegTimestampGapTable);
end

%% Map each GRF event to a real EEG sample

allEventTable = ...
    sortrows(allEventTable, 'LSLTime');

eventTypes = ...
    string(allEventTable.EventType);

grfEventLSLTime = ...
    double(allEventTable.LSLTime);

insideEEGRange = ...
    grfEventLSLTime >= eegTimeStamps(1) & ...
    grfEventLSLTime <= eegTimeStamps(end);

% GRF may start earlier or finish later than retained EEG. Such events
% stay in the mapping audit with no EEG latency and cannot enter analysis.
nearestEEGSample = nan(height(allEventTable), 1);
nearestEEGSample(insideEEGRange) = round(interp1( ...
    eegTimeStamps, 1:numel(eegTimeStamps), ...
    grfEventLSLTime(insideEEGRange), 'nearest'));
if any(~isfinite(nearestEEGSample(insideEEGRange)))
    error('A GRF event inside the EEG range could not be mapped.');
end
nearestEEGLSLTime = nan(height(allEventTable), 1);
nearestEEGLSLTime(insideEEGRange) = eegTimeStamps(nearestEEGSample(insideEEGRange));

nearestMappingErrorMs = ...
    1000 * (nearestEEGLSLTime - grfEventLSLTime);

eventInsideTimestampGap = ...
    false(height(allEventTable), 1);

eventTimestampGapIndex = ...
    nan(height(allEventTable), 1);

for iGap = 1:height(eegTimestampGapTable)

    currentEventsInsideGap = ...
        grfEventLSLTime > ...
            eegTimestampGapTable.LSLBeforeGap(iGap) & ...
        grfEventLSLTime < ...
            eegTimestampGapTable.LSLAfterGap(iGap);

    eventInsideTimestampGap = ...
        eventInsideTimestampGap | ...
        currentEventsInsideGap;

    eventTimestampGapIndex(currentEventsInsideGap) = ...
        eegTimestampGapTable.GapIndex(iGap);
end

unexplainedBadMapping = ...
    abs(nearestMappingErrorMs) > maximumMappingErrorMs & ...
    ~eventInsideTimestampGap & insideEEGRange;

if any(unexplainedBadMapping)

    badRows = find(unexplainedBadMapping);

    disp(table( ...
        eventTypes(badRows), ...
        grfEventLSLTime(badRows), ...
        nearestEEGSample(badRows), ...
        nearestEEGLSLTime(badRows), ...
        nearestMappingErrorMs(badRows), ...
        'VariableNames', { ...
            'EventType', ...
            'GRFEventLSLTime', ...
            'NearestEEGSample', ...
            'NearestEEGLSLTime', ...
            'NearestMappingErrorMs'}));

    error([ ...
        '%d event mappings exceed %.3f ms and are not explained ' ...
        'by a detected EEG timestamp gap.\n' ...
        'No EEG file was saved.'], ...
        numel(badRows), ...
        maximumMappingErrorMs);
end

mappingStatus = repmat( ...
    "mapped", ...
    height(allEventTable), ...
    1);

mappingStatus(eventInsideTimestampGap) = ...
    "excluded_no_EEG_sample_in_timestamp_gap";
mappingStatus(~insideEEGRange) = "excluded_outside_retained_EEG_range";

eegSample = ...
    nan(height(allEventTable), 1);

matchedEEGLSLTime = ...
    nan(height(allEventTable), 1);

signedMappingErrorMs = ...
    nan(height(allEventTable), 1);

mappedEventMask = ...
    insideEEGRange & ~eventInsideTimestampGap;

eegSample(mappedEventMask) = ...
    nearestEEGSample(mappedEventMask);

matchedEEGLSLTime(mappedEventMask) = ...
    nearestEEGLSLTime(mappedEventMask);

signedMappingErrorMs(mappedEventMask) = ...
    nearestMappingErrorMs(mappedEventMask);

mappingTable = allEventTable;
mappingTable.CanonicalSubjectID = repmat(canonicalSubject, height(mappingTable), 1);
mappingTable.OriginalSubjectID = repmat(originalSubject, height(mappingTable), 1);
mappingTable.SourceBidsEEGLABSet = repmat(sourceBidsEEGLABSet, height(mappingTable), 1);

mappingTable.MappingStatus = ...
    mappingStatus;
mappingTable.SourceXDFEEGSample = nan(height(mappingTable), 1);
mappingTable.SourceXDFEEGSample(mappedEventMask) = ...
    retainedIndex(eegSample(mappedEventMask));

mappingTable.EEGTimestampGapIndex = ...
    eventTimestampGapIndex;

mappingTable.EEGSample = ...
    eegSample;

mappingTable.MatchedEEGLSLTime = ...
    matchedEEGLSLTime;

mappingTable.MappingErrorMs = ...
    signedMappingErrorMs;

mappingTable.NearestEEGSample = ...
    nearestEEGSample;

mappingTable.NearestEEGLSLTime = ...
    nearestEEGLSLTime;

mappingTable.NearestMappingErrorMs = ...
    nearestMappingErrorMs;

mappedEventTable = ...
    mappingTable(mappedEventMask, :);

excludedEventTable = ...
    mappingTable(~mappedEventMask, :);

if isempty(mappedEventTable)

    error([ ...
        'No GRF gait events overlap retained EEG samples.\n' ...
        'No EEG file was saved.']);
end

mappedEEGSample = ...
    double(mappedEventTable.EEGSample);

duplicateEventSample = ...
    [false; diff(mappedEEGSample) == 0];

if any(duplicateEventSample)

    duplicateRows = find(duplicateEventSample);

    disp(table( ...
        string(mappedEventTable.EventType(duplicateRows)), ...
        mappedEEGSample(duplicateRows), ...
        double(mappedEventTable.LSLTime(duplicateRows)), ...
        'VariableNames', { ...
            'EventType', ...
            'EEGSample', ...
            'GRFEventLSLTime'}));

    error([ ...
        'Two or more mapped gait events use the same EEG sample.\n' ...
        'No EEG file was saved.']);
end

fprintf('\nGRF-to-EEG mapping status:\n');

fprintf('Original GRF events: %d\n', ...
    height(mappingTable));

fprintf('Successfully mapped events: %d\n', ...
    height(mappedEventTable));

fprintf('Events excluded outside retained EEG or inside gaps: %d\n', ...
    height(excludedEventTable));

%% Construct the session EEG dataset

EEG = BIDS_EEG;
EEG.etc.hipexo_original_bids_events = originalBidsEvents;
EEG.urevent = [];
EEG.event = struct([]);
EEG.setname = [batchOutputStem '_desc-grfevents_eeg'];
EEG.data = single(eegData);
EEG.nbchan = size(eegData, 1);
EEG.trials = 1;
EEG.pnts = size(eegData, 2);

% Retain the audited source sample ranges without changing their values.
% Rejected ranges are omitted; no interpolation or sample insertion is used.
%
% Step 02B may encode an effective BrainVision header rate (for example
% 499.9x Hz). After exact XDF/BIDS sample-count identity has been verified,
% the analysis copy is assigned the protocol nominal rate so all runs share
% the same native-rate EEGLAB time base for later concatenation.
EEG.srate = targetEEGSrate;
EEG.xmin = 0;
EEG.xmax = (EEG.pnts - 1) / EEG.srate;
EEG.times = (0:(EEG.pnts - 1)) / EEG.srate * 1000;

EEG.event = struct( ...
    'type', {}, ...
    'latency', {}, ...
    'duration', {}, ...
    'side', {}, ...
    'segment_index', {}, ...
    'lsl_time', {}, ...
    'matched_eeg_lsl_time', {}, ...
    'mapping_error_ms', {}, ...
    'mapping_status', {}, ...
    'gap_start_lsl_time', {}, ...
    'gap_end_lsl_time', {}, ...
    'subject_label', {}, ...
    'session_label', {}, ...
    'condition_label', {}, ...
    'task_label', {}, ...
    'run_number', {}, ...
    'source_xdf', {}, ...
    'source_recording', {});

%% Add successfully mapped gait events

for iEvent = 1:height(mappedEventTable)

    EEG.event(iEvent).type = ...
        char(string(mappedEventTable.EventType(iEvent)));

    EEG.event(iEvent).latency = ...
        double(mappedEventTable.EEGSample(iEvent));

    EEG.event(iEvent).duration = ...
        0;

    EEG.event(iEvent).side = ...
        char(string(mappedEventTable.Side(iEvent)));

    EEG.event(iEvent).segment_index = ...
        double(mappedEventTable.SegmentIndex(iEvent));

    EEG.event(iEvent).lsl_time = ...
        double(mappedEventTable.LSLTime(iEvent));

    EEG.event(iEvent).matched_eeg_lsl_time = ...
        double(mappedEventTable.MatchedEEGLSLTime(iEvent));

    EEG.event(iEvent).mapping_error_ms = ...
        double(mappedEventTable.MappingErrorMs(iEvent));

    EEG.event(iEvent).mapping_status = ...
        'mapped';

    EEG.event(iEvent).gap_start_lsl_time = ...
        NaN;

    EEG.event(iEvent).gap_end_lsl_time = ...
        NaN;

    EEG.event(iEvent).subject_label = ...
        char(canonicalSubject);

    EEG.event(iEvent).session_label = ...
        char(sourceMetadata.SessionLabel);

    EEG.event(iEvent).condition_label = ...
        char(sourceMetadata.ConditionLabel);

    EEG.event(iEvent).task_label = ...
        char(sourceMetadata.TaskLabel);

    EEG.event(iEvent).run_number = ...
        sourceMetadata.RunNumber;

    EEG.event(iEvent).source_xdf = ...
        char(xdfFile);

    EEG.event(iEvent).source_recording = ...
        char(canonicalRecordingLabel);
end

%% Add boundary events for EEG timestamp gaps and retained-segment joins
% EEGLAB represents discontinuities with boundary events between samples:
% https://eeglab.org/tutorials/ConceptsGuide/Data_Structures.html#event-boundaries

% Missing EEG samples are not synthesized or interpolated.
for iGap = 1:height(eegTimestampGapTable)

    iEEGEvent = ...
        height(mappedEventTable) + iGap;

    EEG.event(iEEGEvent).type = ...
        'boundary';

    EEG.event(iEEGEvent).latency = ...
        eegTimestampGapTable.SampleBeforeGap(iGap) + 0.5;

    EEG.event(iEEGEvent).duration = ...
        eegTimestampGapTable.MissingSampleCount(iGap);

    EEG.event(iEEGEvent).side = ...
        '';

    EEG.event(iEEGEvent).segment_index = ...
        NaN;

    EEG.event(iEEGEvent).lsl_time = ...
        NaN;

    EEG.event(iEEGEvent).matched_eeg_lsl_time = ...
        NaN;

    EEG.event(iEEGEvent).mapping_error_ms = ...
        NaN;

    EEG.event(iEEGEvent).mapping_status = ...
        'EEG_timestamp_gap_boundary';

    EEG.event(iEEGEvent).gap_start_lsl_time = ...
        eegTimestampGapTable.LSLBeforeGap(iGap);

    EEG.event(iEEGEvent).gap_end_lsl_time = ...
        eegTimestampGapTable.LSLAfterGap(iGap);

    EEG.event(iEEGEvent).subject_label = ...
        char(canonicalSubject);

    EEG.event(iEEGEvent).session_label = ...
        char(sourceMetadata.SessionLabel);

    EEG.event(iEEGEvent).condition_label = ...
        char(sourceMetadata.ConditionLabel);

    EEG.event(iEEGEvent).task_label = ...
        char(sourceMetadata.TaskLabel);

    EEG.event(iEEGEvent).run_number = ...
        sourceMetadata.RunNumber;

    EEG.event(iEEGEvent).source_xdf = ...
        char(xdfFile);

    EEG.event(iEEGEvent).source_recording = ...
        char(canonicalRecordingLabel);
end

%% Sort gait and boundary events by EEG latency

if ~isempty(EEG.event)

    [~, eventSortOrder] = sort( ...
        double([EEG.event.latency]));

    EEG.event = ...
        EEG.event(eventSortOrder);
end

%% Save provenance and timestamp-gap information

EEG.subject = char(canonicalSubject);

EEG.condition = ...
    char(sourceMetadata.ConditionLabel);

EEG.etc.source_xdf = ...
    char(xdfFile);

EEG.etc.source_bids_eeg_set = char(sourceBidsEEGLABSet);
EEG.etc.source_bids_eeg_set_signature = char(sourceBidsEEGLABSignature);
EEG.etc.canonical_subject_id = char(canonicalSubject);
EEG.etc.original_subject_id = char(originalSubject);
EEG.etc.data_lineage = [ ...
    'XDF -> BIDS -> run-separated EEGLAB -> GRF-event mapping; ' ...
    'XDF EEG amplitudes not used; BIDS sample values retained exactly; ' ...
    'analysis srate normalized to the protocol nominal rate after ' ...
    'sample-count identity verification'];

analysisSourceMetadata = sourceMetadata;
analysisSourceMetadata.OriginalSubjectLabel = string(sourceMetadata.SubjectLabel);
analysisSourceMetadata.SubjectLabel = canonicalSubject;
analysisSourceMetadata.RecordingLabel = canonicalRecordingLabel;

EEG.etc.source_metadata = analysisSourceMetadata;
EEG.etc.original_source_metadata = sourceMetadata;

EEG.etc.source_grf_event_file = ...
    sourceEventFile;

EEG.etc.eeg_stream_name = ...
    char(get_stream_text_field(EEGStream, 'name'));

EEG.etc.eeg_first_lsl_time = ...
    eegTimeStamps(1);

EEG.etc.eeg_last_lsl_time = ...
    eegTimeStamps(end);

EEG.etc.eeg_source_sample_count = xdfEEGSampleCount;
EEG.etc.eeg_retained_source_sample_ranges = retainedRanges;
EEG.etc.eeg_segment_audit = segmentAudit;

EEG.etc.eeg_nominal_srate = ...
    nominalEEGSrate;

EEG.etc.eeg_measured_timestamp_srate = ...
    measuredEEGSrate;

EEG.etc.bids_header_srate = ...
    bidsHeaderSrate;

EEG.etc.analysis_output_srate = ...
    targetEEGSrate;

EEG.etc.sample_identity_verified = ...
    true;

EEG.etc.sample_values_resampled = ...
    false;

EEG.etc.sampling_rate_policy = ...
    ['Retained BIDS sample values are unchanged. Source sample ranges ' ...
     'and XDF segment timestamps define the event mapping. Disjoint ' ...
     'ranges are separated by boundary events at the protocol nominal rate.'];

EEG.etc.raw_eeg_stream_channel_count = ...
    rawEEGChannelCount;

EEG.etc.selected_eeg_stream_channel_indices = ...
    selectedEEGChannelIndices;

EEG.etc.selected_eeg_stream_channel_labels = ...
    selectedEEGChannelLabels;

EEG.etc.dropped_auxiliary_channel_indices = ...
    droppedEEGChannelIndices;

EEG.etc.dropped_auxiliary_channel_labels = ...
    droppedEEGChannelLabels;

EEG.etc.eeg_channel_selection_method = ...
    char(channelSelectionMethod);

EEG.etc.grf_to_eeg_mapping = ...
    mappingTable;

EEG.etc.eeg_timestamp_gaps = ...
    eegTimestampGapTable;

EEG.etc.excluded_grf_events_due_to_eeg_gaps = ...
    mappingTable(eventInsideTimestampGap, :);
EEG.etc.excluded_grf_events_outside_eeg = mappingTable(~insideEEGRange, :);

EEG.etc.timestamp_gap_threshold_sec = ...
    timestampGapThresholdSec;

EEG.etc.grf_to_eeg_processing = struct( ...
    'version', char(processingVersion), ...
    'source_event_file', sourceEventFile, ...
    'source_event_signature', char(sourceEventSignature), ...
    'source_xdf', char(xdfFile), ...
    'source_xdf_signature', char(sourceXDFSignature), ...
    'source_bids_eeg_set', char(sourceBidsEEGLABSet), ...
    'source_bids_eeg_set_signature', char(sourceBidsEEGLABSignature), ...
    'mapping_parameters', cfg.mapping, ...
    'channel_location_signature', char(hipexo.file_metadata_signature(P.channelLocationFile)), ...
    'eeg_qc_parameters', struct('eeg', eegQC.eeg, 'timestamp', eegQC.timestamp), ...
    'eeg_segment_code_signature', char(hipexo.content_signature( ...
        fileread(which('hipexo.check_eeg_segments')))), ...
    'retained_source_sample_ranges', retainedRanges, ...
    'canonical_subject_id', char(canonicalSubject), ...
    'original_subject_id', char(originalSubject), ...
    'xdf_role', 'LSL_timing_and_GRF_only', ...
    'eeg_signal_role', 'BIDS_derived_EEGLAB_only', ...
    'sample_count_identity_verified', true, ...
    'sample_values_resampled', false, ...
    'bids_header_srate_hz', bidsHeaderSrate, ...
    'xdf_nominal_srate_hz', nominalEEGSrate, ...
    'xdf_measured_timestamp_srate_hz', measuredEEGSrate, ...
    'output_nominal_srate_hz', targetEEGSrate, ...
    'rate_policy', ...
        ['BIDS-derived sample values retained; output EEGLAB srate ' ...
         'normalized to protocol nominal rate only after exact sample ' ...
         'identity validation.'], ...
    'maximum_mapping_error_ms', maximumMappingErrorMs, ...
    'timestamp_gap_factor', timestampGapFactor, ...
    'minimum_timestamp_gap_sec', minimumTimestampGapSec, ...
    'created_on', char(datetime( ...
        'now', 'Format', 'yyyy-MM-dd HH:mm:ss')));

%% Add project channel locations

EEG.chanlocs = ...
    projectChanlocs;

if numel(EEG.chanlocs) ~= EEG.nbchan

    error([ ...
        'Channel-location count does not match EEG.nbchan.\n' ...
        'Channel locations: %d\n' ...
        'EEG channels: %d'], ...
        numel(EEG.chanlocs), ...
        EEG.nbchan);
end

EEG = eeg_checkset(EEG);
EEG = eeg_checkset(EEG, 'eventconsistency');

%% Final QC summary

mappedEventCountTable = groupsummary( ...
    mappedEventTable, ...
    'EventType');

fprintf('\nSuccessfully mapped gait events by type:\n');

disp( ...
    mappedEventCountTable(:, ...
        {'EventType', 'GroupCount'}));

if ~isempty(excludedEventTable)

    excludedEventCountTable = groupsummary( ...
        excludedEventTable, ...
        'EventType');

    fprintf('\nEvents excluded because no EEG sample existed:\n');

    disp( ...
        excludedEventCountTable(:, ...
            {'EventType', 'GroupCount'}));
end

mappedAbsoluteMappingErrorMs = abs( ...
    double(mappedEventTable.MappingErrorMs));

fprintf('\nMapping error for successfully mapped events:\n');

fprintf('Median absolute error: %.6f ms\n', ...
    median(mappedAbsoluteMappingErrorMs));

fprintf('Maximum absolute error: %.6f ms\n', ...
    max(mappedAbsoluteMappingErrorMs));

fprintf('Original GRF event count: %d\n', ...
    height(mappingTable));

fprintf('Mapped gait-event count: %d\n', ...
    height(mappedEventTable));

fprintf('Excluded gait-event count: %d\n', ...
    height(excludedEventTable));

fprintf('EEG boundary-event count: %d\n', ...
    height(eegTimestampGapTable));

fprintf('EEG sampling rate saved in EEGLAB: %.6f Hz\n', ...
    EEG.srate);

fprintf('Total EEGLAB event count (mapped + boundary): %d\n', ...
    numel(EEG.event));

fprintf('Channel locations: %d / %d\n', ...
    numel(EEG.chanlocs), ...
    EEG.nbchan);

%% Save the session EEG and QC tables

outputSetName = [batchOutputStem '_desc-grfevents_eeg.set'];

mappingCSVName = [batchOutputStem '_desc-grfeventmapping_events.csv'];

mappingCSVFile = fullfile( ...
    eegEventOutputFolder, ...
    mappingCSVName);

gapCSVName = [batchOutputStem '_desc-eegtimestampgaps_events.csv'];

gapCSVFile = fullfile( ...
    eegEventOutputFolder, ...
    gapCSVName);

writetable( ...
    mappingTable, ...
    mappingCSVFile);

writetable( ...
    eegTimestampGapTable, ...
    gapCSVFile);

EEG = pop_saveset( ...
    EEG, ...
    'filename', ...
    outputSetName, ...
    'filepath', ...
    eegEventOutputFolder, ...
    'savemode', ...
    'onefile');

%% Completion summary

fprintf('\n====================================================\n');
fprintf('GRF EVENTS MAPPED TO EEG SUCCESSFULLY\n');
fprintf('====================================================\n');

fprintf('Session EEG .set:\n%s\n', ...
    fullfile(eegEventOutputFolder, outputSetName));

fprintf('\nMapping CSV:\n%s\n', ...
    mappingCSVFile);

fprintf('\nEEG timestamp-gap CSV:\n%s\n', ...
    gapCSVFile);

fprintf([ ...
    '\nEEG sample values were not resampled. The saved analysis copy ' ...
    'uses the protocol nominal sampling rate of %.6f Hz.\n'], ...
    targetEEGSrate);

fprintf([ ...
    'GRF events inside EEG timestamp gaps were excluded rather than ' ...
    'forced onto an unrelated EEG sample.\n']);

fprintf('EEGLAB boundaries mark timestamp gaps and retained-segment joins.\n');

fprintf('No session concatenation or BeMoBIL processing was performed.\n');

end

%% Local helper functions

function metadata = ...
        parse_xdf_source_metadata(xdfFile)

[~, baseName, extension] = ...
    fileparts(char(xdfFile));

fullName = ...
    string([baseName extension]);

isOldVersion = ~isempty(regexpi( ...
    char(fullName), ...
    '_old\d*\.xdf$', ...
    'once'));

cleanBaseName = ...
    regexprep( ...
        string(baseName), ...
        '_old\d*$', ...
        '', ...
        'ignorecase');

token = ...
    regexpi( ...
        char(cleanBaseName), ...
        ['^sub-(?<subject>.+?)_' ...
         '(?:day\d+_)?' ...
         'ses-(?<session>.+?)_' ...
         'task-(?<task>.+?)_' ...
         'run-(?<run>\d+)_' ...
         'eeg$'], ...
        'names', ...
        'once');

if isempty(token)

    error([ ...
        'Could not parse subject/session/task/run metadata from:\n%s\n' ...
        'Expected a filename ending like ' ...
        '_ses-Condition_task-Default_run-001_eeg.xdf.'], ...
        xdfFile);
end

runNumber = ...
    str2double(token.run);

if ~isfinite(runNumber)

    error('Invalid run number in XDF filename:\n%s', ...
        xdfFile);
end

metadata = struct();

metadata.SubjectLabel = ...
    "sub-" + string(token.subject);


metadata.SessionLabel = ...
    "ses-" + string(token.session);

metadata.ConditionLabel = ...
    string(token.session);

metadata.TaskLabel = ...
    string(token.task);

metadata.RunNumber = ...
    runNumber;

metadata.RecordingLabel = ...
    metadata.SubjectLabel + "_" + ...
    metadata.SessionLabel + "_" + ...
    compose("run-%03d", runNumber);

metadata.IsOldVersion = ...
    isOldVersion;

metadata.XDFPath = ...
    string(xdfFile);
end

function [selectedIndex, streamSummary] = ...
        find_real_eeg_stream( ...
            streams, ...
            expectedName, ...
            expectedChannels, ...
            targetSrate)

nStreams = numel(streams);

streamIndex = ...
    (1:nStreams)';

streamName = ...
    strings(nStreams, 1);

streamType = ...
    strings(nStreams, 1);

nominalSrate = ...
    nan(nStreams, 1);

channelCount = ...
    nan(nStreams, 1);

sampleCount = ...
    nan(nStreams, 1);

for iStream = 1:nStreams

    currentStream = ...
        streams{iStream};

    streamName(iStream) = ...
        get_stream_text_field( ...
            currentStream, ...
            'name');

    streamType(iStream) = ...
        get_stream_text_field( ...
            currentStream, ...
            'type');

    nominalSrate(iStream) = ...
        get_stream_nominal_srate( ...
            currentStream);

    if isfield(currentStream, 'time_series') && ...
            isnumeric(currentStream.time_series)

        currentData = ...
            currentStream.time_series;

        currentTimestamps = ...
            currentStream.time_stamps;

        sampleCount(iStream) = ...
            numel(currentTimestamps);

        if size(currentData, 2) == sampleCount(iStream)

            channelCount(iStream) = ...
                size(currentData, 1);

        elseif size(currentData, 1) == sampleCount(iStream)

            channelCount(iStream) = ...
                size(currentData, 2);
        end
    end
end

streamSummary = table( ...
    streamIndex, ...
    streamName, ...
    streamType, ...
    nominalSrate, ...
    channelCount, ...
    sampleCount, ...
    'VariableNames', { ...
        'StreamIndex', ...
        'Name', ...
        'Type', ...
        'NominalSrate', ...
        'ChannelCount', ...
        'SampleCount'});

exactNameMatch = ...
    strcmpi(streamName, expectedName) & ...
    channelCount >= expectedChannels & ...
    channelCount <= expectedChannels + 16 & ...
    abs(nominalSrate - targetSrate) <= 1;

candidateIndices = ...
    find(exactNameMatch);

if isempty(candidateIndices)

    fallbackMatch = ...
        channelCount >= expectedChannels & ...
        channelCount <= expectedChannels + 16 & ...
        abs(nominalSrate - targetSrate) <= 1 & ...
        (contains(lower(streamType), 'eeg') | ...
         contains(lower(streamName), 'liveamp'));

    candidateIndices = ...
        find(fallbackMatch);
end

if numel(candidateIndices) ~= 1

    disp(streamSummary);

    error([ ...
        'Could not identify exactly one real EEG stream near %.9g Hz.\n' ...
        'Number of candidates: %d'], ...
        targetSrate, ...
        numel(candidateIndices));
end

selectedIndex = ...
    candidateIndices(1);

end

function [selectedIndices, droppedIndices, selectionMethod] = ...
        select_project_eeg_channels( ...
            rawLabels, ...
            projectLabels, ...
            rawChannelCount, ...
            expectedChannelCount, ...
            expectedAuxiliaryLabels, ...
            expectedStreamName)

selectedIndices = [];
droppedIndices = [];
selectionMethod = "";

rawLabels = ...
    string(rawLabels(:));

projectLabels = ...
    string(projectLabels(:));

expectedAuxiliaryLabels = ...
    string(expectedAuxiliaryLabels(:));

if numel(rawLabels) ~= rawChannelCount || ...
        any(strlength(strtrim(rawLabels)) == 0)

    error([ ...
        'The BIDS-derived EEG recording does not provide a complete channel-label ' ...
        'list. The ACC channels cannot be removed safely by label.']);
end

normalizedRawLabels = ...
    rawLabels;

streamPrefix = ...
    string(expectedStreamName) + "_";

hasStreamPrefix = startsWith( ...
    normalizedRawLabels, ...
    streamPrefix, ...
    'IgnoreCase', ...
    true);

normalizedRawLabels(hasStreamPrefix) = extractAfter( ...
    normalizedRawLabels(hasStreamPrefix), ...
    strlength(streamPrefix));

if rawChannelCount == expectedChannelCount + ...
        numel(expectedAuxiliaryLabels)

    auxiliaryIndices = nan( ...
        numel(expectedAuxiliaryLabels), ...
        1);

    for iAuxiliary = 1:numel(expectedAuxiliaryLabels)

        currentMatch = find(strcmpi( ...
            strtrim(normalizedRawLabels), ...
            strtrim(expectedAuxiliaryLabels(iAuxiliary))));

        if numel(currentMatch) ~= 1

            error([ ...
                'Expected exactly one %s channel in the 67-channel ' ...
                'LiveAmp stream, but found %d.'], ...
                expectedAuxiliaryLabels(iAuxiliary), ...
                numel(currentMatch));
        end

        auxiliaryIndices(iAuxiliary) = ...
            currentMatch;
    end

    if numel(unique(auxiliaryIndices)) ~= ...
            numel(expectedAuxiliaryLabels)

        error('The ACC channel-label matches are not unique.');
    end

    droppedIndices = ...
        auxiliaryIndices;

elseif rawChannelCount == expectedChannelCount

    droppedIndices = ...
        zeros(0, 1);

else

    error([ ...
        'Expected either %d EEG channels or %d channels ' ...
        '(64 EEG + ACC_X/ACC_Y/ACC_Z), but found %d.'], ...
        expectedChannelCount, ...
        expectedChannelCount + numel(expectedAuxiliaryLabels), ...
        rawChannelCount);
end

remainingIndices = setdiff( ...
    (1:rawChannelCount)', ...
    droppedIndices, ...
    'stable');

if numel(remainingIndices) ~= expectedChannelCount

    error([ ...
        'Removing ACC_X/ACC_Y/ACC_Z did not leave exactly %d EEG ' ...
        'channels. Remaining channels: %d'], ...
        expectedChannelCount, ...
        numel(remainingIndices));
end

if numel(projectLabels) ~= expectedChannelCount || ...
        any(strlength(strtrim(projectLabels)) == 0)

    error('chanlocs.ced does not contain 64 valid channel labels.');
end

matchedIndices = ...
    nan(expectedChannelCount, 1);

for iChannel = 1:expectedChannelCount

    currentMatch = remainingIndices(strcmpi( ...
        strtrim(normalizedRawLabels(remainingIndices)), ...
        strtrim(projectLabels(iChannel))));

    if numel(currentMatch) ~= 1

        error([ ...
            'Could not match chanlocs.ced channel %s uniquely in the ' ...
            'BIDS-derived EEG recording. Number of matches: %d'], ...
            projectLabels(iChannel), ...
            numel(currentMatch));
    end

    matchedIndices(iChannel) = ...
        currentMatch;
end

if numel(unique(matchedIndices)) ~= expectedChannelCount

    error('The 64 EEG channel-label matches are not unique.');
end

selectedIndices = ...
    matchedIndices;

if isempty(droppedIndices)

    selectionMethod = ...
        "matched_64_EEG_channels_to_chanlocs_labels";

else

    selectionMethod = ...
        "removed_ACC_X_ACC_Y_ACC_Z_then_matched_chanlocs_labels";
end

end

function channelLabels = ...
        get_stream_channel_labels( ...
            stream, ...
            channelCount)

channelLabels = ...
    strings(channelCount, 1);

if ~isfield(stream, 'info') || ...
        ~isfield(stream.info, 'desc')

    return;
end

description = ...
    stream.info.desc;

while iscell(description) && ...
        numel(description) == 1

    description = ...
        description{1};
end

if ~isstruct(description) || ...
        ~isfield(description, 'channels')

    return;
end

channelsNode = ...
    description.channels;

while iscell(channelsNode) && ...
        numel(channelsNode) == 1

    channelsNode = ...
        channelsNode{1};
end

if ~isstruct(channelsNode) || ...
        ~isfield(channelsNode, 'channel')

    return;
end

channelEntries = ...
    channelsNode.channel;

if iscell(channelEntries)

    numberOfEntries = min( ...
        channelCount, ...
        numel(channelEntries));

    for iChannel = 1:numberOfEntries

        channelLabels(iChannel) = ...
            get_channel_entry_label( ...
                channelEntries{iChannel});
    end

elseif isstruct(channelEntries)

    numberOfEntries = min( ...
        channelCount, ...
        numel(channelEntries));

    for iChannel = 1:numberOfEntries

        channelLabels(iChannel) = ...
            get_channel_entry_label( ...
                channelEntries(iChannel));
    end
end

end

function channelLabel = ...
        get_channel_entry_label(channelEntry)

channelLabel = "";

while iscell(channelEntry) && ...
        numel(channelEntry) == 1

    channelEntry = ...
        channelEntry{1};
end

if ~isstruct(channelEntry) || ...
        ~isfield(channelEntry, 'label')

    return;
end

rawLabel = ...
    channelEntry.label;

while iscell(rawLabel) && ...
        ~isempty(rawLabel)

    rawLabel = ...
        rawLabel{1};
end

if isempty(rawLabel)

    return;
end

channelLabel = ...
    string(rawLabel);

channelLabel = ...
    channelLabel(1);

end

function nominalSrate = ...
        get_stream_nominal_srate(stream)

nominalSrate = ...
    NaN;

if ~isfield(stream, 'info') || ...
        ~isfield(stream.info, 'nominal_srate')

    return;
end

rawValue = ...
    stream.info.nominal_srate;

while iscell(rawValue) && ...
        ~isempty(rawValue)

    rawValue = ...
        rawValue{1};
end

if isnumeric(rawValue)

    nominalSrate = ...
        double(rawValue(1));

else

    nominalSrate = ...
        str2double(string(rawValue));
end

end

function textValue = ...
        get_stream_text_field( ...
            stream, ...
            fieldName)

textValue = "";

if ~isfield(stream, 'info') || ...
        ~isfield(stream.info, fieldName)

    return;
end

rawValue = ...
    stream.info.(fieldName);

while iscell(rawValue) && ...
        ~isempty(rawValue)

    rawValue = ...
        rawValue{1};
end

if isempty(rawValue)

    return;
end

textValue = ...
    string(rawValue);

textValue = ...
    textValue(1);

end

function conditions = canonical_condition_local(values)

values = string(values(:));
conditions = strings(size(values));

for valueIndex = 1:numel(values)

    key = lower(char(values(valueIndex)));
    key = regexprep(key, '[^a-z0-9]', '');

    if contains(key, 'noexo') && contains(key, 'pre')
        conditions(valueIndex) = "NoExoPre";

    elseif contains(key, 'noexo') && contains(key, 'post')
        conditions(valueIndex) = "NoExoPost";

    elseif contains(key, 'aquaplus') || contains(key, 'aquaextra')
        conditions(valueIndex) = "AquaPlus";

    elseif contains(key, 'transparent') || contains(key, 'exooff')
        conditions(valueIndex) = "Transparent";

    elseif contains(key, 'sport')
        conditions(valueIndex) = "Sport";

    elseif contains(key, 'boost')
        conditions(valueIndex) = "Boost";

    elseif contains(key, 'aqua')
        conditions(valueIndex) = "Aqua";

    elseif contains(key, 'eco') || strcmp(key, 'exo') || ...
            ~isempty(regexp(key, 'exo\d*(on)?$', 'once'))
        conditions(valueIndex) = "Exo";

    else
        error('Cannot canonicalize condition label: %s', ...
            char(values(valueIndex)));
    end
end

end

function key = subject_identity_key_local(value)

value = strtrim(string(value));

if ~isscalar(value) || ismissing(value) || strlength(value) == 0
    error('Participant identity must be one non-empty text value.');
end

key = lower(value);
key = regexprep(key, '^sub-', '');
key = regexprep(key, '^p(?=\d)', 'pilot');
key = regexprep(key, '[^a-z0-9]', '');

if strlength(key) == 0
    error('Participant identity cannot be normalized: %s', value);
end

end
