% Goal:
% 1. Read bemobil_import_table.csv generated by import_table.m and updated by bemobil_import.m.
% 2. Load usable raw EEGLAB .set files from RawSetPath.
% 3. Run basic BeMoBIL EEG preprocessing.
% 4. Event-based trimming is intentionally disabled.
% 5. Skip AMICA in this script.
%
% Current workflow:
%   1) check_eeg_streams.m
%   2) import_table.m
%   3) bemobil_import.m
%   4) this preprocessing script
%
% Table-driven control:
%   DoImport = 1
%       Controls XDF -> BIDS -> raw EEGLAB import.
%
%   RecommendedDoPreprocess = 1
%       Generated by bemobil_import.m.
%       One row per usable raw .set file is recommended for preprocessing.
%
%   DoPreprocess = 1
%       Controls which raw .set files are actually preprocessed by this script.
%
% Important:
%   This script must NOT use DoImport directly for preprocessing.
%   DoImport is run-level.
%   Preprocessing is raw-set-level.
%   It uses RawSetPath from bemobil_import_table.csv.


clear; clc; close all;

% Keep figures hidden during batch preprocessing.
set(0, 'DefaultFigureVisible', 'off');
set(groot, 'DefaultFigureVisible', 'off');

%% ========================================================================
%  LOAD CENTRAL PATHS
%  ========================================================================

run(fullfile(fileparts(mfilename('fullpath')), 'paths.m'));

if ~exist(mappingFile, 'file')
    error('Import table not found:\n%s\nPlease run import_table.m and bemobil_import_resample_merge.m first.', mappingFile);
end

%% ========================================================================
%  PROCESSING SETTINGS
%  ========================================================================

% If true:
%   DoPreprocess will be overwritten from RecommendedDoPreprocess.
%
% Recommended for the first run after a new import/audit.
%
% Later, if you want to manually edit DoPreprocess in the CSV,
% set this to false.
reset_DoPreprocess_from_Recommended = true;

% Recompute BeMoBIL preprocessing output.
force_recompute = 1;

%% ========================================================================
%  INITIALIZE EEGLAB
%  ========================================================================

if ~exist('ALLCOM', 'var')
    eeglab nogui;
end

hide_all_figures();

%% ========================================================================
%  INITIALIZE FIELDTRIP
%  ========================================================================

global ft_default
ft_default.toolbox.signal = 'matlab';
ft_default.toolbox.stats  = 'matlab';
ft_default.toolbox.image  = 'matlab';

ft_defaults;

hide_all_figures();

fprintf('Using EEGLAB from:\n%s\n', which('eeglab'));
fprintf('Using ft_defaults from:\n%s\n', which('ft_defaults'));
fprintf('Using load_xdf from:\n%s\n', which('load_xdf'));

if isempty(which('load_xdf'))
    error('load_xdf was not found. Please check FieldTrip external/xdf path.');
end

if isempty(which('clean_data_with_zapline_plus_eeglab_wrapper'))
    error('zapline-plus was not found. Please install it via EEGLAB extension manager.');
else
    fprintf('Using zapline-plus from:\n%s\n', which('clean_data_with_zapline_plus_eeglab_wrapper'));
end

hide_all_figures();

%% ========================================================================
%  LOAD BEMOBIL CONFIGURATION
%  ========================================================================

run(fullfile(scriptsFolder, 'bemobil_config_.m'));

% Keep one clean base config.
% This is important because channels_to_remove will be adjusted per file.
base_bemobil_config = bemobil_config;

hide_all_figures();

%% ========================================================================
%  READ IMPORT TABLE
%  ========================================================================

optsImport = detectImportOptions(mappingFile, ...
    'FileType', 'text', ...
    'Delimiter', ',', ...
    'VariableNamingRule', 'preserve');

sourceMap = readtable(mappingFile, optsImport);

fprintf('\nLoaded import table:\n%s\n', mappingFile);
fprintf('Rows in import table: %d\n', height(sourceMap));

%% ========================================================================
%  CHECK REQUIRED COLUMNS
%  ========================================================================

requiredColumns = { ...
    'DoImport', ...
    'XdfPath', ...
    'FileName', ...
    'BidsSubject', ...
    'BidsSession', ...
    'RawSetPath', ...
    'RawSetStatus', ...
    'RecommendedDoPreprocess' ...
};

for c = 1:length(requiredColumns)
    if ~ismember(requiredColumns{c}, sourceMap.Properties.VariableNames)
        error(['Import table is missing required column: %s\n' ...
               'Please run bemobil_import_resample_merge.m first, because it writes RawSetPath, RawSetStatus, and RecommendedDoPreprocess.'], ...
               requiredColumns{c});
    end
end

%% ========================================================================
%  NORMALIZE IMPORTANT COLUMNS
%  ========================================================================

sourceMap = ensure_numeric_column(sourceMap, 'DoImport');
sourceMap = ensure_numeric_column(sourceMap, 'BidsSubject');
sourceMap = ensure_numeric_column(sourceMap, 'RecommendedDoPreprocess');

sourceMap.XdfPath = string(sourceMap.XdfPath);
sourceMap.FileName = string(sourceMap.FileName);
sourceMap.BidsSession = string(sourceMap.BidsSession);
sourceMap.RawSetPath = string(sourceMap.RawSetPath);
sourceMap.RawSetStatus = string(sourceMap.RawSetStatus);

sourceMap.XdfPath(ismissing(sourceMap.XdfPath)) = "";
sourceMap.FileName(ismissing(sourceMap.FileName)) = "";
sourceMap.BidsSession(ismissing(sourceMap.BidsSession)) = "";
sourceMap.RawSetPath(ismissing(sourceMap.RawSetPath)) = "";
sourceMap.RawSetStatus(ismissing(sourceMap.RawSetStatus)) = "";

if ismember('EEGStreamName', sourceMap.Properties.VariableNames)
    sourceMap.EEGStreamName = string(sourceMap.EEGStreamName);
    sourceMap.EEGStreamName(ismissing(sourceMap.EEGStreamName)) = "";
end

if ismember('RunNumber', sourceMap.Properties.VariableNames)
    sourceMap = ensure_numeric_column(sourceMap, 'RunNumber');
else
    sourceMap.RunNumber = nan(height(sourceMap), 1);
end

%% ========================================================================
%  CREATE OR RESET DOPREPROCESS
%  ========================================================================

if ~ismember('DoPreprocess', sourceMap.Properties.VariableNames)

    sourceMap.DoPreprocess = sourceMap.RecommendedDoPreprocess;

    writetable(sourceMap, mappingFile);

    fprintf('\nDoPreprocess column was not found.\n');
    fprintf('Created DoPreprocess from RecommendedDoPreprocess and saved it to:\n%s\n', mappingFile);

else

    sourceMap = ensure_numeric_column(sourceMap, 'DoPreprocess');

    if reset_DoPreprocess_from_Recommended

        sourceMap.DoPreprocess = sourceMap.RecommendedDoPreprocess;

        writetable(sourceMap, mappingFile);

        fprintf('\nDoPreprocess column already existed.\n');
        fprintf('Reset DoPreprocess from RecommendedDoPreprocess because reset_DoPreprocess_from_Recommended = true.\n');
        fprintf('Updated import table saved to:\n%s\n', mappingFile);

    else

        fprintf('\nDoPreprocess column already existed.\n');
        fprintf('Using existing DoPreprocess values because reset_DoPreprocess_from_Recommended = false.\n');

    end

end

%% ========================================================================
%  SELECT ROWS TO PROCESS
%  ========================================================================

sourceMap = ensure_numeric_column(sourceMap, 'DoPreprocess');

candidateRows = find(sourceMap.DoPreprocess == 1);

if isempty(candidateRows)
    error('No rows with DoPreprocess = 1 found in bemobil_import_table.csv.');
end

% Only process rows that have an OK raw set status and a non-empty RawSetPath.
hasRawPath = strlength(strtrim(sourceMap.RawSetPath)) > 0;
hasOKRawSet = startsWith(sourceMap.RawSetStatus, "OK_");

validRows = candidateRows(hasRawPath(candidateRows) & hasOKRawSet(candidateRows));

if isempty(validRows)

    fprintf('\nRows with DoPreprocess = 1 exist, but none have OK RawSetStatus and non-empty RawSetPath.\n');
    fprintf('Problem rows:\n');
    disp(sourceMap(candidateRows, {'FileName', 'BidsSubject', 'BidsSession', ...
                                   'DoImport', 'DoPreprocess', ...
                                   'RawSetStatus', 'RawSetPath'}));

    error('No valid rows for preprocessing.');

end

% Safety: avoid processing the same RawSetPath more than once.
rawPathsForValidRows = sourceMap.RawSetPath(validRows);
[~, uniqueIdx] = unique(rawPathsForValidRows, 'stable');
rowsToProcess = validRows(uniqueIdx);

fprintf('\n============================================================\n');
fprintf('BASIC EEG PREPROCESSING STARTED\n');
fprintf('============================================================\n');
fprintf('Selection mode: table-driven raw-set-level preprocessing\n');
fprintf('Rows with DoPreprocess = 1: %d\n', length(candidateRows));
fprintf('Rows with OK RawSetStatus and RawSetPath: %d\n', length(validRows));
fprintf('Unique raw .set files to preprocess: %d\n', length(rowsToProcess));
fprintf('Import table:\n%s\n', mappingFile);
fprintf('============================================================\n\n');

fprintf('Rows selected for preprocessing:\n');
disp(sourceMap(rowsToProcess, {'FileName', 'BidsSubject', 'BidsSession', ...
                               'RawSetStatus', 'RawSetPath'}));

hide_all_figures();

%% ========================================================================
%  PROCESSING LOOP
%  ========================================================================

for r = 1:length(rowsToProcess)

    hide_all_figures();

    rowIdx = rowsToProcess(r);

    % Reset config for each file.
    bemobil_config = base_bemobil_config;

    %% --------------------------------------------------------------------
    %  READ LABELS FROM IMPORT TABLE
    %  --------------------------------------------------------------------

    bidsSubject = sourceMap.BidsSubject(rowIdx);
    bidsSession = char(sourceMap.BidsSession(rowIdx));

    originalXDFName = char(sourceMap.FileName(rowIdx));
    originalXDFPath = char(sourceMap.XdfPath(rowIdx));

    rawSetStatus = char(sourceMap.RawSetStatus(rowIdx));
    importedSetPath = char(sourceMap.RawSetPath(rowIdx));

    if isnan(bidsSubject)

        warning('Invalid BidsSubject in row %d. Skipping this row.', rowIdx);

        sourceMap = update_mapping_status( ...
            sourceMap, rowIdx, ...
            "PreprocessingStatus", "failed_invalid_bids_subject", ...
            "PreprocessingNotes", "BidsSubject is NaN or invalid." ...
        );

        sourceMap = ensure_string_column(sourceMap, 'PreprocessingDate');
        sourceMap.PreprocessingDate(rowIdx) = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

        writetable(sourceMap, mappingFile);
        continue;

    end

    if strlength(strtrim(string(importedSetPath))) == 0

        warning('RawSetPath is empty in row %d. Skipping this row.', rowIdx);

        sourceMap = update_mapping_status( ...
            sourceMap, rowIdx, ...
            "PreprocessingStatus", "failed_empty_raw_set_path", ...
            "PreprocessingNotes", "RawSetPath is empty." ...
        );

        sourceMap = ensure_string_column(sourceMap, 'PreprocessingDate');
        sourceMap.PreprocessingDate(rowIdx) = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

        writetable(sourceMap, mappingFile);
        continue;

    end

    if ~startsWith(string(rawSetStatus), "OK_")

        warning('RawSetStatus is not OK in row %d. Skipping this row. Status: %s', rowIdx, rawSetStatus);

        sourceMap = update_mapping_status( ...
            sourceMap, rowIdx, ...
            "PreprocessingStatus", "failed_raw_set_status_not_ok", ...
            "PreprocessingNotes", "RawSetStatus is not OK." ...
        );

        sourceMap = ensure_string_column(sourceMap, 'PreprocessingDate');
        sourceMap.PreprocessingDate(rowIdx) = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

        writetable(sourceMap, mappingFile);
        continue;

    end

    %% --------------------------------------------------------------------
    %  PROCESSING LABEL
    %  --------------------------------------------------------------------

    % This label is used for preprocessing output.
    % It must be unique per final raw set/session.
    %
    % Example:
    %   BidsSession:
    %       Pilot2p3day2sesNoExoPost
    %
    %   ProcessingSubjectLabel:
    %       Pilot2p3day2sesNoExoPost
    %
    %   ProcessingSubjectFolder:
    %       sub-Pilot2p3day2sesNoExoPost

    processingSubjectLabel = char(make_bids_label(string(bidsSession)));
    processingSubjectFolder = [bemobil_config.filename_prefix processingSubjectLabel];

    fprintf('\n\n============================================================\n');
    fprintf('PROCESSING RAW SET %d / %d\n', r, length(rowsToProcess));
    fprintf('============================================================\n');
    fprintf('Table row: %d\n', rowIdx);
    fprintf('Original XDF name:\n%s\n\n', originalXDFName);
    fprintf('Original XDF path:\n%s\n\n', originalXDFPath);
    fprintf('Imported BIDS subject:\nsub-%d\n', bidsSubject);
    fprintf('Imported BIDS session:\n%s\n', bidsSession);
    fprintf('RawSetStatus:\n%s\n', rawSetStatus);
    fprintf('RawSetPath:\n%s\n', importedSetPath);
    fprintf('Processing label:\n%s\n', processingSubjectLabel);
    fprintf('Processing folder:\n%s\n', processingSubjectFolder);
    fprintf('============================================================\n\n');

    %% --------------------------------------------------------------------
    %  RESOLVE IMPORTED EEGLAB FILE PATH FROM RAWSETPATH
    %  --------------------------------------------------------------------

    if ~exist(importedSetPath, 'file')

        warning('Imported EEGLAB .set file does not exist. Skipping this row:\n%s', importedSetPath);

        sourceMap = update_mapping_status( ...
            sourceMap, rowIdx, ...
            "PreprocessingStatus", "failed_imported_set_not_found", ...
            "PreprocessingNotes", "RawSetPath points to a .set file that does not exist." ...
        );

        sourceMap = ensure_string_column(sourceMap, 'ImportedSetPath');
        sourceMap = ensure_string_column(sourceMap, 'PreprocessingDate');

        sourceMap.ImportedSetPath(rowIdx) = string(importedSetPath);
        sourceMap.PreprocessingDate(rowIdx) = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

        writetable(sourceMap, mappingFile);

        continue;

    end

    [input_filepath, input_name, input_ext] = fileparts(importedSetPath);
    input_filename = [input_name input_ext];

    fprintf('Imported EEGLAB file resolved from RawSetPath:\n');
    fprintf('  input_filepath = %s\n', input_filepath);
    fprintf('  input_filename = %s\n', input_filename);

    %% --------------------------------------------------------------------
    %  PREPARE EXPECTED OUTPUT PATH
    %  --------------------------------------------------------------------

    preprocessedFolder = fullfile( ...
        bemobil_config.study_folder, ...
        bemobil_config.EEG_preprocessing_data_folder, ...
        processingSubjectFolder ...
    );

    preprocessedSetPath = fullfile( ...
        preprocessedFolder, ...
        [processingSubjectFolder '_' bemobil_config.preprocessed_filename] ...
    );

    singleSubjectFolder = fullfile( ...
        bemobil_config.study_folder, ...
        bemobil_config.single_subject_analysis_folder, ...
        processingSubjectFolder ...
    );

    if ~exist(singleSubjectFolder, 'dir')
        mkdir(singleSubjectFolder);
    end

    %% --------------------------------------------------------------------
    %  UPDATE TABLE BEFORE PROCESSING
    %  --------------------------------------------------------------------

    sourceMap = ensure_string_column(sourceMap, 'ProcessingSubjectLabel');
    sourceMap = ensure_string_column(sourceMap, 'ProcessingSubjectFolder');
    sourceMap = ensure_string_column(sourceMap, 'ImportedSetPath');
    sourceMap = ensure_string_column(sourceMap, 'PreprocessedSetPath');
    sourceMap = ensure_string_column(sourceMap, 'PreprocessingStatus');
    sourceMap = ensure_string_column(sourceMap, 'PreprocessingDate');
    sourceMap = ensure_string_column(sourceMap, 'PreprocessingNotes');

    sourceMap.ProcessingSubjectLabel(rowIdx) = string(processingSubjectLabel);
    sourceMap.ProcessingSubjectFolder(rowIdx) = string(processingSubjectFolder);
    sourceMap.ImportedSetPath(rowIdx) = string(importedSetPath);
    sourceMap.PreprocessedSetPath(rowIdx) = string(preprocessedSetPath);
    sourceMap.PreprocessingStatus(rowIdx) = "running";
    sourceMap.PreprocessingDate(rowIdx) = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));
    sourceMap.PreprocessingNotes(rowIdx) = "";

    writetable(sourceMap, mappingFile);

    %% --------------------------------------------------------------------
    %  EEGLAB MEMORY/SAVE OPTIONS
    %  --------------------------------------------------------------------

    try
        pop_editoptions( ...
            'option_saveversion6', 0, ...
            'option_single', 0, ...
            'option_memmapdata', 0, ...
            'option_savetwofiles', 1, ...
            'option_storedisk', 0);
    catch
        warning('Could NOT edit EEGLAB memory options.');
    end

    hide_all_figures();

    %% --------------------------------------------------------------------
    %  RESET EEGLAB VARIABLES FOR THIS FILE
    %  --------------------------------------------------------------------

    STUDY = [];
    CURRENTSTUDY = 0;
    ALLEEG = [];
    CURRENTSET = [];
    EEG = [];
    EEG_interp_avref = [];
    EEG_single_subject_final = [];

    %% --------------------------------------------------------------------
    %  LOAD IMPORTED EEGLAB .SET FILE
    %  --------------------------------------------------------------------

    fprintf('\nLoading imported EEGLAB file:\n%s\nfrom:\n%s\n', input_filename, input_filepath);

    EEG = pop_loadset( ...
        'filename', input_filename, ...
        'filepath', input_filepath ...
    );

    EEG = eeg_checkset(EEG);

    hide_all_figures();

    %% --------------------------------------------------------------------
    %  STORE SOURCE INFORMATION INSIDE EEG.ETC
    %  --------------------------------------------------------------------

    EEG.etc.source_original_xdf_name = originalXDFName;
    EEG.etc.source_original_xdf_path = originalXDFPath;
    EEG.etc.real_bids_subject = bidsSubject;
    EEG.etc.session_label = bidsSession;
    EEG.etc.processing_subject_label = processingSubjectLabel;
    EEG.etc.raw_set_status = rawSetStatus;
    EEG.etc.raw_set_path = importedSetPath;

    if ismember('EEGStreamName', sourceMap.Properties.VariableNames)
        EEG.etc.source_eeg_stream_name = char(sourceMap.EEGStreamName(rowIdx));
    end

    if ismember('RunNumber', sourceMap.Properties.VariableNames)
        EEG.etc.source_run_number = sourceMap.RunNumber(rowIdx);
    end

    %% --------------------------------------------------------------------
    %  CHECK AND FILTER CHANNELS_TO_REMOVE
    %  --------------------------------------------------------------------

    all_labels = {EEG.chanlocs.labels};

    disp('All channel labels in current EEG:');
    disp(all_labels');

    if isfield(bemobil_config, 'channels_to_remove') && ~isempty(bemobil_config.channels_to_remove)

        original_remove_list = bemobil_config.channels_to_remove;

        existing_remove_list = original_remove_list( ...
            ismember(original_remove_list, all_labels) ...
        );

        missing_remove_list = setdiff(original_remove_list, all_labels);

        disp('Requested channels to remove:');
        disp(original_remove_list');

        disp('Actually existing channels to remove:');
        disp(existing_remove_list');

        disp('Requested but missing channels, will be ignored:');
        disp(missing_remove_list');

        bemobil_config.channels_to_remove = existing_remove_list;

    else

        disp('No channels_to_remove specified.');

    end

    fprintf('\nLoaded EEG information:\n');
    fprintf('Channels: %d\n', EEG.nbchan);
    fprintf('Sampling rate: %.2f Hz\n', EEG.srate);
    fprintf('Samples: %d\n', EEG.pnts);
    fprintf('Duration: %.2f seconds\n', EEG.pnts / EEG.srate);
    fprintf('Events: %d\n', length(EEG.event));

    %% --------------------------------------------------------------------
    %  EVENT-BASED TRIMMING IS INTENTIONALLY DISABLED
    %  --------------------------------------------------------------------

    nEventsBeforePreprocessing = numel(EEG.event);

    fprintf('\nEvent-based trimming is intentionally disabled in this script.\n');
    fprintf('Using the whole EEG recording for preprocessing.\n');
    fprintf('Number of events currently in EEG.event: %d\n', nEventsBeforePreprocessing);

    EEG.etc.event_based_trimming_disabled = true;
    EEG.etc.event_based_trimming_note = ...
        'Whole recording was used. EEG.event was not used for trimming in this preprocessing script.';
    EEG.etc.n_events_before_preprocessing = nEventsBeforePreprocessing;

    hide_all_figures();

    %% --------------------------------------------------------------------
    %  BASIC EEG PREPROCESSING
    %  --------------------------------------------------------------------

    try

        hide_all_figures();

        [ALLEEG, EEG_preprocessed, CURRENTSET] = bemobil_process_all_EEG_preprocessing( ...
            processingSubjectLabel, ...
            bemobil_config, ...
            ALLEEG, ...
            EEG, ...
            CURRENTSET, ...
            force_recompute);

        hide_all_figures();

    catch ME

        hide_all_figures();

        warning('Preprocessing failed for table row %d:\n%s', rowIdx, ME.message);

        sourceMap = update_mapping_status( ...
            sourceMap, rowIdx, ...
            "PreprocessingStatus", "failed", ...
            "PreprocessingNotes", string(ME.message) ...
        );

        sourceMap = ensure_string_column(sourceMap, 'PreprocessingDate');
        sourceMap.PreprocessingDate(rowIdx) = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

        writetable(sourceMap, mappingFile);

        continue;

    end

    %% --------------------------------------------------------------------
    %  CHECK OUTPUT AND UPDATE TABLE
    %  --------------------------------------------------------------------

    if exist(preprocessedSetPath, 'file')

        sourceMap.PreprocessingStatus(rowIdx) = "completed";
        sourceMap.PreprocessingNotes(rowIdx) = "";

    else

        sourceMap.PreprocessingStatus(rowIdx) = "finished_but_output_file_not_found";
        sourceMap.PreprocessingNotes(rowIdx) = "BeMoBIL finished, but expected preprocessed .set was not found. Check output folders.";

    end

    sourceMap.PreprocessingDate(rowIdx) = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

    writetable(sourceMap, mappingFile);

    hide_all_figures();

    fprintf('\n============================================================\n');
    fprintf('BASIC EEG PREPROCESSING FINISHED FOR THIS RAW SET\n');
    fprintf('============================================================\n');
    fprintf('Expected preprocessed file:\n%s\n', preprocessedSetPath);
    fprintf('Import table updated:\n%s\n', mappingFile);
    fprintf('AMICA is intentionally skipped in this script.\n');

end

hide_all_figures();

%% ========================================================================
%  FINAL REPORT
%  ========================================================================

fprintf('\n\n============================================================\n');
fprintf('ALL SELECTED BASIC EEG PREPROCESSING FINISHED\n');
fprintf('============================================================\n');
fprintf('Import table:\n%s\n', mappingFile);

optsFinal = detectImportOptions(mappingFile, ...
    'FileType', 'text', ...
    'Delimiter', ',', ...
    'VariableNamingRule', 'preserve');

sourceMapFinal = readtable(mappingFile, optsFinal);

if ismember('PreprocessingStatus', sourceMapFinal.Properties.VariableNames)

    sourceMapFinal.PreprocessingStatus = string(sourceMapFinal.PreprocessingStatus);
    sourceMapFinal.PreprocessingStatus(ismissing(sourceMapFinal.PreprocessingStatus)) = "";

    fprintf('\nPreprocessing status summary:\n');

    statusNonEmpty = sourceMapFinal.PreprocessingStatus(strlength(sourceMapFinal.PreprocessingStatus) > 0);
    uniqueStatus = unique(statusNonEmpty, 'stable');

    if isempty(uniqueStatus)
        fprintf('  No preprocessing status entries found.\n');
    else
        for k = 1:numel(uniqueStatus)
            thisStatus = uniqueStatus(k);
            n = sum(statusNonEmpty == thisStatus);
            fprintf('  %-45s %d\n', thisStatus, n);
        end
    end

end

hide_all_figures();

fprintf('\nDone.\n');

%% ========================================================================
%  HELPER FUNCTIONS
%  ========================================================================

function hide_all_figures()

    try
        set(0, 'DefaultFigureVisible', 'off');
        set(groot, 'DefaultFigureVisible', 'off');
    catch
    end

    try
        figs = findall(0, 'Type', 'figure');

        if ~isempty(figs)
            set(figs, 'Visible', 'off');
            close(figs);
        end

    catch
        try
            close all force;
        catch
        end
    end

end

function y = to_numeric_column(x)

    if isnumeric(x)
        y = x;
    elseif islogical(x)
        y = double(x);
    else
        y = str2double(string(x));
    end

end

function label = make_bids_label(x)

    label = char(x);

    % Remove underscores and other non-alphanumeric characters.
    % BIDS labels should be letters/numbers only.
    label = regexprep(label, '[^A-Za-z0-9]', '');

    label = string(label);

end

function T = ensure_string_column(T, columnName)

    if ~ismember(columnName, T.Properties.VariableNames)
        T.(columnName) = strings(height(T), 1);
    else
        if ~isstring(T.(columnName))
            T.(columnName) = string(T.(columnName));
        end

        T.(columnName)(ismissing(T.(columnName))) = "";
    end

end

function T = ensure_numeric_column(T, columnName)

    if ~ismember(columnName, T.Properties.VariableNames)
        error('Table is missing required column: %s', columnName);
    end

    if isnumeric(T.(columnName))
        return;
    elseif islogical(T.(columnName))
        T.(columnName) = double(T.(columnName));
    else
        T.(columnName) = str2double(string(T.(columnName)));
    end

end

function T = update_mapping_status(T, rowIdx, statusColumn, statusValue, notesColumn, notesValue)

    T = ensure_string_column(T, char(statusColumn));
    T = ensure_string_column(T, char(notesColumn));

    T.(char(statusColumn))(rowIdx) = string(statusValue);
    T.(char(notesColumn))(rowIdx) = string(notesValue);

end