% Goal:
% 1. Read bemobil_import_table.csv generated by import_table.m.
% 2. Load imported EEGLAB .set files from 2_raw-EEGLAB.
% 3. Run basic BeMoBIL EEG preprocessing.
% 4. Skip event-based trimming because EEG.event is empty.
% 5. Skip AMICA in this script.
%
% Current workflow:
%   1) check_eeg_streams.m
%   2) import_table.m
%   3) bemobil_import.m
%   4) this preprocessing script
%
% Table-driven control:
%   DoImport = 1       -> this row was selected for import
%   DoPreprocess = 1  -> this row will be preprocessed
%
% If DoPreprocess does not exist, this script creates it from DoImport.

clear; clc; close all;

%% Load central paths

run(fullfile(fileparts(mfilename('fullpath')), 'paths.m'));

if ~exist(mappingFile, 'file')
    error('Import table not found:\n%s\nPlease run import_table.m and bemobil_import.m first.', mappingFile);
end

%% Processing settings

% Completely table-driven:
% The script will process rows with DoPreprocess = 1.
%
% First run:
%   If DoPreprocess does not exist, it will be created from DoImport.
%
% Later:
%   You can manually edit DoPreprocess in bemobil_import_table.csv:
%       1 = preprocess this row
%       0 = skip this row

force_recompute = 1;

%% Initialize EEGLAB

if ~exist('ALLCOM', 'var')
    eeglab;
end

%% Initialize FieldTrip

global ft_default
ft_default.toolbox.signal = 'matlab';
ft_default.toolbox.stats  = 'matlab';
ft_default.toolbox.image  = 'matlab';

ft_defaults;

fprintf('Using EEGLAB from:\n%s\n', which('eeglab'));
fprintf('Using ft_defaults from:\n%s\n', which('ft_defaults'));
fprintf('Using load_xdf from:\n%s\n', which('load_xdf'));

if isempty(which('load_xdf'))
    error('load_xdf was not found. Please check FieldTrip external/xdf path.');
end

if isempty(which('clean_data_with_zapline_plus_eeglab_wrapper'))
    error('zapline-plus was not found. Please install it via EEGLAB extension manager.');
else
    fprintf('Using zapline-plus from:\n%s\n', which('clean_data_with_zapline_plus_eeglab_wrapper'));
end

%% Load BeMoBIL configuration

run(fullfile(scriptsFolder, 'bemobil_config_.m'));

% Keep one clean base config.
% This is important because channels_to_remove will be adjusted per file.
base_bemobil_config = bemobil_config;

%% Read import table

optsImport = detectImportOptions(mappingFile, ...
    'FileType', 'text', ...
    'Delimiter', ',', ...
    'VariableNamingRule', 'preserve');

sourceMap = readtable(mappingFile, optsImport);

%% Check required columns

requiredColumns = { ...
    'DoImport', ...
    'XdfPath', ...
    'FileName', ...
    'BidsSubject', ...
    'BidsSession' ...
};

for c = 1:length(requiredColumns)
    if ~ismember(requiredColumns{c}, sourceMap.Properties.VariableNames)
        error('Import table is missing required column: %s', requiredColumns{c});
    end
end

%% Normalize important columns

sourceMap = ensure_numeric_column(sourceMap, 'DoImport');
sourceMap = ensure_numeric_column(sourceMap, 'BidsSubject');

sourceMap.XdfPath = string(sourceMap.XdfPath);
sourceMap.FileName = string(sourceMap.FileName);
sourceMap.BidsSession = string(sourceMap.BidsSession);

if ismember('EEGStreamName', sourceMap.Properties.VariableNames)
    sourceMap.EEGStreamName = string(sourceMap.EEGStreamName);
end

%% Create or read DoPreprocess

if ~ismember('DoPreprocess', sourceMap.Properties.VariableNames)

    % First time running this script:
    % create DoPreprocess from DoImport.
    %
    % So all rows that were imported will also be selected for preprocessing
    % by default.
    sourceMap.DoPreprocess = sourceMap.DoImport;

    writetable(sourceMap, mappingFile);

    fprintf('\nDoPreprocess column was not found.\n');
    fprintf('Created DoPreprocess from DoImport and saved it to:\n%s\n', mappingFile);

else

    sourceMap = ensure_numeric_column(sourceMap, 'DoPreprocess');

end

%% Select rows from table

rowsToProcess = find(sourceMap.DoPreprocess == 1);

if isempty(rowsToProcess)
    error('No rows with DoPreprocess = 1 found in bemobil_import_table.csv.');
end

fprintf('\n============================================================\n');
fprintf('BASIC EEG PREPROCESSING STARTED\n');
fprintf('============================================================\n');
fprintf('Selection mode: table-driven\n');
fprintf('Rows with DoPreprocess = 1: %d\n', length(rowsToProcess));
fprintf('Import table:\n%s\n', mappingFile);
fprintf('============================================================\n\n');

%% Processing loop

for r = 1:length(rowsToProcess)

    rowIdx = rowsToProcess(r);

    % Reset config for each file
    bemobil_config = base_bemobil_config;

    %% Read labels from import table

    bidsSubject = sourceMap.BidsSubject(rowIdx);        % example: 1
    bidsSession = char(sourceMap.BidsSession(rowIdx));  % example: Pilot2p1day2sesExo1Sport

    originalXDFName = char(sourceMap.FileName(rowIdx));
    originalXDFPath = char(sourceMap.XdfPath(rowIdx));

    if isnan(bidsSubject)
        warning('Invalid BidsSubject in row %d. Skipping this row.', rowIdx);

        sourceMap = update_mapping_status( ...
            sourceMap, rowIdx, ...
            "PreprocessingStatus", "failed_invalid_bids_subject", ...
            "PreprocessingNotes", "BidsSubject is NaN or invalid." ...
        );

        sourceMap = ensure_string_column(sourceMap, 'PreprocessingDate');
        sourceMap.PreprocessingDate(rowIdx) = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

        writetable(sourceMap, mappingFile);
        continue;
    end

    % This label is used for preprocessing output.
    % It must be unique per file/session, otherwise different sessions overwrite each other.
    %
    % Example:
    %   Pilot2p1day2sesExo1Sport
    processingSubjectLabel = char(make_bids_label(string(bidsSession)));

    % Example:
    %   sub-Pilot2p1day2sesExo1Sport
    processingSubjectFolder = [bemobil_config.filename_prefix processingSubjectLabel];

    fprintf('\n\n============================================================\n');
    fprintf('PROCESSING FILE %d / %d\n', r, length(rowsToProcess));
    fprintf('============================================================\n');
    fprintf('Table row: %d\n', rowIdx);
    fprintf('Original XDF name:\n%s\n\n', originalXDFName);
    fprintf('Original XDF path:\n%s\n\n', originalXDFPath);
    fprintf('Imported BIDS subject:\nsub-%d\n', bidsSubject);
    fprintf('Imported BIDS session:\n%s\n', bidsSession);
    fprintf('Processing label:\n%s\n', processingSubjectLabel);
    fprintf('Processing folder:\n%s\n', processingSubjectFolder);
    fprintf('============================================================\n\n');

    %% Resolve imported EEGLAB file path

    % bemobil_import.m / bemobil_bids2set generated files like:
    %
    %   output_data\2_raw-EEGLAB\sub-1\
    %       sub-1_Pilot2p1day2sesExo1Sport_EEG.set
    %
    % Notice:
    %   The EEGLAB raw folder uses sub-1, not sub-01.

    importedSubjectFolder = sprintf('%s%d', bemobil_config.filename_prefix, bidsSubject);

    input_filepath = fullfile( ...
        bemobil_config.study_folder, ...
        bemobil_config.raw_EEGLAB_data_folder, ...
        importedSubjectFolder ...
    );

    input_filename = sprintf('%s_%s_EEG.set', importedSubjectFolder, bidsSession);

    importedSetPath = fullfile(input_filepath, input_filename);

    fprintf('Expected imported EEGLAB file:\n%s\n', importedSetPath);

    if ~exist(importedSetPath, 'file')

        warning('Imported EEGLAB .set file does not exist. Skipping this row:\n%s', importedSetPath);

        sourceMap = update_mapping_status( ...
            sourceMap, rowIdx, ...
            "PreprocessingStatus", "failed_imported_set_not_found", ...
            "PreprocessingNotes", "Imported .set file was not found." ...
        );

        sourceMap = ensure_string_column(sourceMap, 'ImportedSetPath');
        sourceMap = ensure_string_column(sourceMap, 'PreprocessingDate');

        sourceMap.ImportedSetPath(rowIdx) = string(importedSetPath);
        sourceMap.PreprocessingDate(rowIdx) = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

        writetable(sourceMap, mappingFile);

        continue;

    end

    %% Prepare expected output path

    preprocessedFolder = fullfile( ...
        bemobil_config.study_folder, ...
        bemobil_config.EEG_preprocessing_data_folder, ...
        processingSubjectFolder ...
    );

    preprocessedSetPath = fullfile( ...
        preprocessedFolder, ...
        [processingSubjectFolder '_' bemobil_config.preprocessed_filename] ...
    );

    singleSubjectFolder = fullfile( ...
        bemobil_config.study_folder, ...
        bemobil_config.single_subject_analysis_folder, ...
        processingSubjectFolder ...
    );

    if ~exist(singleSubjectFolder, 'dir')
        mkdir(singleSubjectFolder);
    end

    %% Update table before processing

    sourceMap = ensure_string_column(sourceMap, 'ProcessingSubjectLabel');
    sourceMap = ensure_string_column(sourceMap, 'ProcessingSubjectFolder');
    sourceMap = ensure_string_column(sourceMap, 'ImportedSetPath');
    sourceMap = ensure_string_column(sourceMap, 'PreprocessedSetPath');
    sourceMap = ensure_string_column(sourceMap, 'PreprocessingStatus');
    sourceMap = ensure_string_column(sourceMap, 'PreprocessingDate');
    sourceMap = ensure_string_column(sourceMap, 'PreprocessingNotes');

    sourceMap.ProcessingSubjectLabel(rowIdx) = string(processingSubjectLabel);
    sourceMap.ProcessingSubjectFolder(rowIdx) = string(processingSubjectFolder);
    sourceMap.ImportedSetPath(rowIdx) = string(importedSetPath);
    sourceMap.PreprocessedSetPath(rowIdx) = string(preprocessedSetPath);
    sourceMap.PreprocessingStatus(rowIdx) = "running";
    sourceMap.PreprocessingDate(rowIdx) = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));
    sourceMap.PreprocessingNotes(rowIdx) = "";

    writetable(sourceMap, mappingFile);

    %% EEGLAB memory/save options

    try
        pop_editoptions( ...
            'option_saveversion6', 0, ...
            'option_single', 0, ...
            'option_memmapdata', 0, ...
            'option_savetwofiles', 1, ...
            'option_storedisk', 0);
    catch
        warning('Could NOT edit EEGLAB memory options.');
    end

    %% Reset EEGLAB variables for this file

    STUDY = [];
    CURRENTSTUDY = 0;
    ALLEEG = [];
    CURRENTSET = [];
    EEG = [];
    EEG_interp_avref = [];
    EEG_single_subject_final = [];

    %% Load imported EEGLAB .set file

    fprintf('\nLoading imported EEGLAB file:\n%s\nfrom:\n%s\n', input_filename, input_filepath);

    EEG = pop_loadset( ...
        'filename', input_filename, ...
        'filepath', input_filepath ...
    );

    EEG = eeg_checkset(EEG);

    %% Store source information inside EEG.etc

    EEG.etc.source_original_xdf_name = originalXDFName;
    EEG.etc.source_original_xdf_path = originalXDFPath;
    EEG.etc.real_bids_subject = bidsSubject;
    EEG.etc.session_label = bidsSession;
    EEG.etc.processing_subject_label = processingSubjectLabel;

    if ismember('EEGStreamName', sourceMap.Properties.VariableNames)
        EEG.etc.source_eeg_stream_name = char(sourceMap.EEGStreamName(rowIdx));
    end

    %% Check and filter channels_to_remove

    all_labels = {EEG.chanlocs.labels};

    disp('All channel labels in current EEG:');
    disp(all_labels');

    if isfield(bemobil_config, 'channels_to_remove') && ~isempty(bemobil_config.channels_to_remove)

        original_remove_list = bemobil_config.channels_to_remove;

        existing_remove_list = original_remove_list( ...
            ismember(original_remove_list, all_labels) ...
        );

        missing_remove_list = setdiff(original_remove_list, all_labels);

        disp('Requested channels to remove:');
        disp(original_remove_list');

        disp('Actually existing channels to remove:');
        disp(existing_remove_list');

        disp('Requested but missing channels, will be ignored:');
        disp(missing_remove_list');

        bemobil_config.channels_to_remove = existing_remove_list;

    else

        disp('No channels_to_remove specified.');

    end

    fprintf('\nLoaded EEG information:\n');
    fprintf('Channels: %d\n', EEG.nbchan);
    fprintf('Sampling rate: %.2f Hz\n', EEG.srate);
    fprintf('Samples: %d\n', EEG.pnts);
    fprintf('Duration: %.2f seconds\n', EEG.pnts / EEG.srate);
    fprintf('Events: %d\n', length(EEG.event));

    %% Skip event-based trimming

    disp('Skipping event-based trimming because EEG.event is empty.');
    disp('Using the whole EEG recording for this preprocessing test.');

    %% Basic EEG preprocessing

    try

        [ALLEEG, EEG_preprocessed, CURRENTSET] = bemobil_process_all_EEG_preprocessing( ...
            processingSubjectLabel, ...
            bemobil_config, ...
            ALLEEG, ...
            EEG, ...
            CURRENTSET, ...
            force_recompute);

    catch ME

        warning('Preprocessing failed for table row %d:\n%s', rowIdx, ME.message);

        sourceMap = update_mapping_status( ...
            sourceMap, rowIdx, ...
            "PreprocessingStatus", "failed", ...
            "PreprocessingNotes", string(ME.message) ...
        );

        sourceMap = ensure_string_column(sourceMap, 'PreprocessingDate');
        sourceMap.PreprocessingDate(rowIdx) = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

        writetable(sourceMap, mappingFile);

        continue;

    end

    %% Check output and update table

    if exist(preprocessedSetPath, 'file')

        sourceMap.PreprocessingStatus(rowIdx) = "completed";
        sourceMap.PreprocessingNotes(rowIdx) = "";

    else

        sourceMap.PreprocessingStatus(rowIdx) = "finished_but_output_file_not_found";
        sourceMap.PreprocessingNotes(rowIdx) = "BeMoBIL finished, but expected preprocessed .set was not found. Check output folders.";

    end

    sourceMap.PreprocessingDate(rowIdx) = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

    writetable(sourceMap, mappingFile);

    fprintf('\n============================================================\n');
    fprintf('BASIC EEG PREPROCESSING FINISHED FOR THIS FILE\n');
    fprintf('============================================================\n');
    fprintf('Expected preprocessed file:\n%s\n', preprocessedSetPath);
    fprintf('Import table updated:\n%s\n', mappingFile);
    fprintf('AMICA is intentionally skipped in this script.\n');

end

fprintf('\n\n============================================================\n');
fprintf('ALL SELECTED BASIC EEG PREPROCESSING FINISHED\n');
fprintf('============================================================\n');
fprintf('Import table:\n%s\n', mappingFile);
fprintf('Done.\n');

%% Helper functions

function y = to_numeric_column(x)

    if isnumeric(x)
        y = x;
    elseif islogical(x)
        y = double(x);
    else
        y = str2double(string(x));
    end

end

function label = make_bids_label(x)

    label = char(x);

    % Remove underscores and other non-alphanumeric characters.
    % BIDS labels should be letters/numbers only.
    label = regexprep(label, '[^A-Za-z0-9]', '');

    label = string(label);

end

function T = ensure_string_column(T, columnName)

    if ~ismember(columnName, T.Properties.VariableNames)
        T.(columnName) = strings(height(T), 1);
    else
        if ~isstring(T.(columnName))
            T.(columnName) = string(T.(columnName));
        end
    end

end

function T = ensure_numeric_column(T, columnName)

    if ~ismember(columnName, T.Properties.VariableNames)
        error('Table is missing required column: %s', columnName);
    end

    if isnumeric(T.(columnName))
        return;
    elseif islogical(T.(columnName))
        T.(columnName) = double(T.(columnName));
    else
        T.(columnName) = str2double(string(T.(columnName)));
    end

end

function T = update_mapping_status(T, rowIdx, statusColumn, statusValue, notesColumn, notesValue)

    T = ensure_string_column(T, char(statusColumn));
    T = ensure_string_column(T, char(notesColumn));

    T.(char(statusColumn))(rowIdx) = string(statusValue);
    T.(char(notesColumn))(rowIdx) = string(notesValue);

end