%% build_k06_curated_STUDY.m
%
% Goal:
% 1. Load the original K=6 spatially clustered Yes-only STUDY.
% 2. Read the completed member-level QC table.
% 3. Create a conservative CORE STUDY containing ReviewerDecision = Keep.
% 4. Create an INCLUSIVE STUDY containing Keep + NeedsDiscussion.
% 5. Verify every cluster membership against the QC table.
% 6. Export membership and coverage reports.
% 7. Support Keep, NeedsDiscussion, Reassign, and ClusterOutlier decisions.
%
% This script does NOT:
% - rerun ICA;
% - rerun preclustering;
% - rerun k-means;
% - modify the original .set datasets;
% - overwrite the original K=6 STUDY.

clear;
clc;
close all;

%% Paths

scriptFolder = fileparts(mfilename('fullpath'));
run(fullfile(scriptFolder, 'paths.m'));

outputDataFolder = outputFolder;

sourceStudyFolder = fullfile( ...
    outputDataFolder, ...
    '9_group-STUDY', ...
    'spatial_clustering_k06');

sourceStudyFilename = ...
    'HipExo_manual_IC_Yes_only_spatial_clustered_k06.study';

qcFolder = fullfile( ...
    outputDataFolder, ...
    '10_cluster-member-QC', ...
    'k06');

qcFilename = ...
    'HipExo_K06_member_QC_review_updated_v5.csv';

% Frozen current-analysis integrity checks. Set
% enforceFrozenReviewCounts=false only when intentionally building a new
% review version with documented counts.
enforceFrozenReviewCounts = true;
expectedSourceMemberCount = 62;
expectedKeepCount = 52;
expectedNeedsDiscussionCount = 10;
expectedReassignCount = 0;
expectedClusterOutlierCount = 0;
expectedChildClusterIndices = 2:7;

curatedOutputFolder = fullfile( ...
    outputDataFolder, ...
    '11_curated-STUDY_k06');

sourceStudyPath = fullfile(sourceStudyFolder, sourceStudyFilename);
qcPath = fullfile(qcFolder, qcFilename);

if ~isfolder(curatedOutputFolder)
    mkdir(curatedOutputFolder);
end

%% Start EEGLAB

addpath(eeglabFolder);

if isempty(which('eeglab'))
    error('EEGLAB was not found: %s', eeglabFolder);
end

[ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab('nogui');

%% Check input files

if ~isfile(sourceStudyPath)
    error('Source K=6 STUDY was not found:\n%s', sourceStudyPath);
end

if ~isfile(qcPath)
    error([ ...
        'Completed QC CSV was not found:\n%s\n\n' ...
        'Place HipExo_K06_member_QC_review_updated_v5.csv in:\n%s'], ...
        qcPath, qcFolder);
end

fprintf('\n============================================================\n');
fprintf('K=6 CURATED STUDY CREATION STARTED\n');
fprintf('============================================================\n');
fprintf('Source STUDY:\n%s\n\n', sourceStudyPath);
fprintf('QC table:\n%s\n\n', qcPath);
fprintf('Output folder:\n%s\n', curatedOutputFolder);
fprintf('============================================================\n\n');

%% Read completed member-level QC table

qc = readtable( ...
    qcPath, ...
    'TextType', 'string', ...
    'VariableNamingRule', 'preserve');

requiredVariables = [ ...
    "ClusterIndex", ...
    "ClusterName", ...
    "DatasetIndex", ...
    "Subject", ...
    "Condition", ...
    "Session", ...
    "DatasetFilename", ...
    "IC", ...
    "ReviewerDecision"];

missingVariables = setdiff(requiredVariables, string(qc.Properties.VariableNames));

if ~isempty(missingVariables)
    error( ...
        'QC table is missing required columns: %s', ...
        strjoin(missingVariables, ', '));
end

qc.ReviewerDecision = strtrim(string(qc.ReviewerDecision));
qc.ClusterName = string(qc.ClusterName);
qc.Subject = string(qc.Subject);
qc.Condition = string(qc.Condition);
qc.DatasetFilename = string(qc.DatasetFilename);

if ~ismember('TargetCluster', qc.Properties.VariableNames)
    qc.TargetCluster = strings(height(qc), 1);
end

allowedDecisions = [ ...
    "Keep", ...
    "NeedsDiscussion", ...
    "Reassign", ...
    "ClusterOutlier"];

unknownDecisionRows = ~ismember(qc.ReviewerDecision, allowedDecisions);

if any(unknownDecisionRows)
    badDecisions = unique(qc.ReviewerDecision(unknownDecisionRows));

    error( ...
        'Unexpected ReviewerDecision values were found: %s', ...
        strjoin(badDecisions, ', '));
end

nKeep = sum(qc.ReviewerDecision == "Keep");
nNeedsDiscussion = sum(qc.ReviewerDecision == "NeedsDiscussion");
nReassign = sum(qc.ReviewerDecision == "Reassign");
nClusterOutlier = sum(qc.ReviewerDecision == "ClusterOutlier");

fprintf('QC rows: %d\n', height(qc));
fprintf('Keep: %d\n', nKeep);
fprintf('NeedsDiscussion: %d\n\n', nNeedsDiscussion);
fprintf('Reassign: %d\n', nReassign);
fprintf('ClusterOutlier: %d\n\n', nClusterOutlier);

if enforceFrozenReviewCounts
    if height(qc) ~= expectedSourceMemberCount || ...
            nKeep ~= expectedKeepCount || ...
            nNeedsDiscussion ~= expectedNeedsDiscussionCount || ...
            nReassign ~= expectedReassignCount || ...
            nClusterOutlier ~= expectedClusterOutlierCount

        error([ ...
            'Frozen QC integrity check failed.\n' ...
            'Expected rows/Keep/NeedsDiscussion/Reassign/ClusterOutlier: ' ...
            '%d/%d/%d/%d/%d\n' ...
            'Found: %d/%d/%d/%d/%d'], ...
            expectedSourceMemberCount, ...
            expectedKeepCount, ...
            expectedNeedsDiscussionCount, ...
            expectedReassignCount, ...
            expectedClusterOutlierCount, ...
            height(qc), nKeep, nNeedsDiscussion, ...
            nReassign, nClusterOutlier);
    end
end

%% Load original K=6 STUDY and all referenced datasets

[STUDY_SOURCE, ALLEEG] = pop_loadstudy( ...
    'filename', sourceStudyFilename, ...
    'filepath', sourceStudyFolder);

fprintf('Loaded source STUDY:\n');
fprintf('  Datasets: %d\n', numel(STUDY_SOURCE.datasetinfo));
fprintf('  STUDY clusters: %d\n\n', numel(STUDY_SOURCE.cluster));

%% Verify that the QC table belongs to this exact STUDY

verify_qc_against_source_study_local( ...
    STUDY_SOURCE, ...
    qc, ...
    expectedChildClusterIndices, ...
    expectedSourceMemberCount);

fprintf('QC table matches the original K=6 STUDY membership.\n\n');

%% Build CORE and INCLUSIVE membership tables

resolvedQC = resolve_review_decisions_local( ...
    qc, ...
    STUDY_SOURCE, ...
    expectedChildClusterIndices);

coreMembers = resolvedQC( ...
    ismember(resolvedQC.ReviewerDecision, ["Keep", "Reassign"]), :);

inclusiveMembers = resolvedQC( ...
    ismember(resolvedQC.ReviewerDecision, ...
        ["Keep", "NeedsDiscussion", "Reassign"]), :);

coreMembers = sortrows( ...
    coreMembers, ...
    {'ClusterIndex', 'DatasetIndex', 'IC'});

inclusiveMembers = sortrows( ...
    inclusiveMembers, ...
    {'ClusterIndex', 'DatasetIndex', 'IC'});

%% Create CORE STUDY

coreStudyFilename = ...
    'HipExo_manual_IC_Yes_only_spatial_clustered_k06_CORE.study';

STUDY_CORE = create_curated_study_local( ...
    STUDY_SOURCE, ...
    coreMembers, ...
    "CORE", ...
    qcFilename, ...
    coreStudyFilename, ...
    curatedOutputFolder, ...
    expectedChildClusterIndices, ...
    file_signature_local(qcPath));

verify_curated_study_local( ...
    STUDY_CORE, coreMembers, "CORE", expectedChildClusterIndices);

[STUDY_CORE, ALLEEG] = pop_savestudy( ...
    STUDY_CORE, ...
    ALLEEG, ...
    'filename', coreStudyFilename, ...
    'filepath', curatedOutputFolder, ...
    'resavedatasets', 'off');

fprintf('CORE STUDY saved:\n%s\n\n', ...
    fullfile(curatedOutputFolder, coreStudyFilename));

%% Create INCLUSIVE STUDY

inclusiveStudyFilename = ...
    'HipExo_manual_IC_Yes_only_spatial_clustered_k06_INCLUSIVE.study';

STUDY_INCLUSIVE = create_curated_study_local( ...
    STUDY_SOURCE, ...
    inclusiveMembers, ...
    "INCLUSIVE", ...
    qcFilename, ...
    inclusiveStudyFilename, ...
    curatedOutputFolder, ...
    expectedChildClusterIndices, ...
    file_signature_local(qcPath));

verify_curated_study_local( ...
    STUDY_INCLUSIVE, ...
    inclusiveMembers, ...
    "INCLUSIVE", ...
    expectedChildClusterIndices);

[STUDY_INCLUSIVE, ALLEEG] = pop_savestudy( ...
    STUDY_INCLUSIVE, ...
    ALLEEG, ...
    'filename', inclusiveStudyFilename, ...
    'filepath', curatedOutputFolder, ...
    'resavedatasets', 'off');

fprintf('INCLUSIVE STUDY saved:\n%s\n\n', ...
    fullfile(curatedOutputFolder, inclusiveStudyFilename));

%% Reload saved STUDY files and verify again

[STUDY_CORE_RELOADED, ~] = pop_loadstudy( ...
    'filename', coreStudyFilename, ...
    'filepath', curatedOutputFolder);

verify_curated_study_local( ...
    STUDY_CORE_RELOADED, ...
    coreMembers, ...
    "CORE reloaded", ...
    expectedChildClusterIndices);

[STUDY_INCLUSIVE_RELOADED, ~] = pop_loadstudy( ...
    'filename', inclusiveStudyFilename, ...
    'filepath', curatedOutputFolder);

verify_curated_study_local( ...
    STUDY_INCLUSIVE_RELOADED, ...
    inclusiveMembers, ...
    "INCLUSIVE reloaded", ...
    expectedChildClusterIndices);

fprintf('Both saved STUDY files passed reload verification.\n\n');

%% Build coverage reports

[ ...
    coreClusterSummary, ...
    coreSubjectCoverage, ...
    coreConditionCoverage, ...
    coreSubjectConditionCoverage, ...
    coreDuplicateDatasetMembers ...
] = build_coverage_tables_local(coreMembers);

[ ...
    inclusiveClusterSummary, ...
    inclusiveSubjectCoverage, ...
    inclusiveConditionCoverage, ...
    inclusiveSubjectConditionCoverage, ...
    inclusiveDuplicateDatasetMembers ...
] = build_coverage_tables_local(inclusiveMembers);

differenceMembers = inclusiveMembers( ...
    inclusiveMembers.ReviewerDecision == "NeedsDiscussion", :);

reassignedMembers = resolvedQC( ...
    resolvedQC.ReviewerDecision == "Reassign", :);

excludedClusterOutliers = resolvedQC( ...
    resolvedQC.ReviewerDecision == "ClusterOutlier", :);

%% Write separate CSV reports

writetable( ...
    resolvedQC, ...
    fullfile(curatedOutputFolder, 'HipExo_k06_resolved_review_decisions.csv'));

writetable( ...
    coreMembers, ...
    fullfile(curatedOutputFolder, 'HipExo_k06_CORE_membership.csv'));

writetable( ...
    inclusiveMembers, ...
    fullfile(curatedOutputFolder, 'HipExo_k06_INCLUSIVE_membership.csv'));

writetable( ...
    differenceMembers, ...
    fullfile( ...
        curatedOutputFolder, ...
        'HipExo_k06_CORE_vs_INCLUSIVE_difference.csv'));

writetable( ...
    reassignedMembers, ...
    fullfile(curatedOutputFolder, 'HipExo_k06_reassigned_members.csv'));

writetable( ...
    excludedClusterOutliers, ...
    fullfile(curatedOutputFolder, 'HipExo_k06_excluded_cluster_outliers.csv'));

writetable( ...
    coreClusterSummary, ...
    fullfile(curatedOutputFolder, 'HipExo_k06_CORE_cluster_summary.csv'));

writetable( ...
    coreSubjectCoverage, ...
    fullfile(curatedOutputFolder, 'HipExo_k06_CORE_subject_coverage.csv'));

writetable( ...
    coreConditionCoverage, ...
    fullfile(curatedOutputFolder, 'HipExo_k06_CORE_condition_coverage.csv'));

writetable( ...
    coreSubjectConditionCoverage, ...
    fullfile( ...
        curatedOutputFolder, ...
        'HipExo_k06_CORE_subject_condition_coverage.csv'));

writetable( ...
    coreDuplicateDatasetMembers, ...
    fullfile( ...
        curatedOutputFolder, ...
        'HipExo_k06_CORE_same_dataset_multiple_ICs.csv'));

writetable( ...
    inclusiveClusterSummary, ...
    fullfile( ...
        curatedOutputFolder, ...
        'HipExo_k06_INCLUSIVE_cluster_summary.csv'));

writetable( ...
    inclusiveSubjectCoverage, ...
    fullfile( ...
        curatedOutputFolder, ...
        'HipExo_k06_INCLUSIVE_subject_coverage.csv'));

writetable( ...
    inclusiveConditionCoverage, ...
    fullfile( ...
        curatedOutputFolder, ...
        'HipExo_k06_INCLUSIVE_condition_coverage.csv'));

writetable( ...
    inclusiveSubjectConditionCoverage, ...
    fullfile( ...
        curatedOutputFolder, ...
        'HipExo_k06_INCLUSIVE_subject_condition_coverage.csv'));

writetable( ...
    inclusiveDuplicateDatasetMembers, ...
    fullfile( ...
        curatedOutputFolder, ...
        'HipExo_k06_INCLUSIVE_same_dataset_multiple_ICs.csv'));

%% Write one Excel workbook containing all reports

coverageWorkbook = fullfile( ...
    curatedOutputFolder, ...
    'HipExo_k06_curated_coverage_report.xlsx');

if isfile(coverageWorkbook)
    delete(coverageWorkbook);
end

writetable(coreMembers, coverageWorkbook, ...
    'Sheet', 'CORE_Members');

writetable(coreClusterSummary, coverageWorkbook, ...
    'Sheet', 'CORE_ClusterSummary');

writetable(coreSubjectCoverage, coverageWorkbook, ...
    'Sheet', 'CORE_SubjectCoverage');

writetable(coreConditionCoverage, coverageWorkbook, ...
    'Sheet', 'CORE_ConditionCoverage');

writetable(coreSubjectConditionCoverage, coverageWorkbook, ...
    'Sheet', 'CORE_SubjCond');

writetable(coreDuplicateDatasetMembers, coverageWorkbook, ...
    'Sheet', 'CORE_MultipleICs');

writetable(inclusiveMembers, coverageWorkbook, ...
    'Sheet', 'INCLUSIVE_Members');

writetable(inclusiveClusterSummary, coverageWorkbook, ...
    'Sheet', 'INCL_ClusterSummary');

writetable(inclusiveSubjectCoverage, coverageWorkbook, ...
    'Sheet', 'INCL_SubjectCoverage');

writetable(inclusiveConditionCoverage, coverageWorkbook, ...
    'Sheet', 'INCL_ConditionCoverage');

writetable(inclusiveSubjectConditionCoverage, coverageWorkbook, ...
    'Sheet', 'INCL_SubjCond');

writetable(inclusiveDuplicateDatasetMembers, coverageWorkbook, ...
    'Sheet', 'INCL_MultipleICs');

writetable(differenceMembers, coverageWorkbook, ...
    'Sheet', 'NeedsDiscussion');

writetable(reassignedMembers, coverageWorkbook, ...
    'Sheet', 'Reassigned');

writetable(excludedClusterOutliers, coverageWorkbook, ...
    'Sheet', 'ClusterOutliers');

%% Preserve a copy of the QC source table

copyfile( ...
    qcPath, ...
    fullfile(curatedOutputFolder, qcFilename), ...
    'f');

%% Display summaries

fprintf('\n============================================================\n');
fprintf('K=6 CURATED STUDY CREATION COMPLETED\n');
fprintf('============================================================\n');
fprintf('CORE:\n');
fprintf('  IC members: %d\n', height(coreMembers));
fprintf('  Datasets represented: %d\n', ...
    numel(unique(coreMembers.DatasetIndex)));
fprintf('  Subjects represented: %d\n\n', ...
    numel(unique(coreMembers.Subject)));

fprintf('INCLUSIVE:\n');
fprintf('  IC members: %d\n', height(inclusiveMembers));
fprintf('  Datasets represented: %d\n', ...
    numel(unique(inclusiveMembers.DatasetIndex)));
fprintf('  Subjects represented: %d\n\n', ...
    numel(unique(inclusiveMembers.Subject)));

fprintf('Output folder:\n%s\n\n', curatedOutputFolder);
fprintf('Main files:\n');
fprintf('  %s\n', coreStudyFilename);
fprintf('  %s\n', inclusiveStudyFilename);
fprintf('  HipExo_k06_curated_coverage_report.xlsx\n');
fprintf('============================================================\n\n');

disp('CORE cluster summary:');
disp(coreClusterSummary);

disp('INCLUSIVE cluster summary:');
disp(inclusiveClusterSummary);

% Leave the conservative STUDY in the MATLAB workspace.
STUDY = STUDY_CORE_RELOADED;
CURRENTSTUDY = 1;

fprintf([ ...
    '\nThe conservative CORE STUDY is now stored in variable STUDY.\n' ...
    'To open the cluster editor later, use:\n\n' ...
    '    pop_clustedit(STUDY, ALLEEG);\n\n']);

%% Local functions

function verify_qc_against_source_study_local( ...
    STUDY, qc, expectedChildClusterIndices, expectedMemberCount)

    actualChildClusterIndices = 2:numel(STUDY.cluster);

    if ~isequal(actualChildClusterIndices, expectedChildClusterIndices)
        error(['Source STUDY child cluster indices do not match the frozen ' ...
            'K=6 definition. Expected %s, found %s.'], ...
            mat2str(expectedChildClusterIndices), ...
            mat2str(actualChildClusterIndices));
    end

    if height(qc) ~= expectedMemberCount
        error('Expected %d source QC members, but found %d.', ...
            expectedMemberCount, height(qc));
    end

    clusterIndices = unique(double(qc.ClusterIndex(:)))';

    if ~isequal(clusterIndices, expectedChildClusterIndices)
        error(['QC table must contain every source child cluster exactly. ' ...
            'Expected %s, found %s.'], ...
            mat2str(expectedChildClusterIndices), ...
            mat2str(clusterIndices));
    end

    allKeys = string(qc.DatasetIndex) + "_" + string(qc.IC);

    if numel(unique(allKeys)) ~= numel(allKeys)
        duplicateKeys = allKeys( ...
            duplicated_rows_local(allKeys));

        error( ...
            'The QC table contains duplicate DatasetIndex-IC pairs: %s', ...
            strjoin(unique(duplicateKeys), ', '));
    end

    for rowIndex = 1:height(qc)

        datasetIndex = double(qc.DatasetIndex(rowIndex));
        icIndex = double(qc.IC(rowIndex));
        clusterIndex = double(qc.ClusterIndex(rowIndex));

        if datasetIndex < 1 || ...
                datasetIndex > numel(STUDY.datasetinfo)

            error( ...
                'Invalid DatasetIndex %d in QC row %d.', ...
                datasetIndex, rowIndex);
        end

        expectedFilename = string( ...
            STUDY.datasetinfo(datasetIndex).filename);

        qcFilename = string(qc.DatasetFilename(rowIndex));

        if expectedFilename ~= qcFilename
            error([ ...
                'Dataset filename mismatch in QC row %d.\n' ...
                'STUDY: %s\nQC: %s'], ...
                rowIndex, expectedFilename, qcFilename);
        end

        expectedSubject = string( ...
            STUDY.datasetinfo(datasetIndex).subject);
        expectedCondition = string( ...
            STUDY.datasetinfo(datasetIndex).condition);

        if expectedSubject ~= string(qc.Subject(rowIndex)) || ...
                expectedCondition ~= string(qc.Condition(rowIndex))

            error(['Subject/condition mismatch in QC row %d for dataset %d.'], ...
                rowIndex, datasetIndex);
        end

        expectedClusterName = string(STUDY.cluster(clusterIndex).name);

        if expectedClusterName ~= string(qc.ClusterName(rowIndex))
            error(['Cluster name mismatch in QC row %d. STUDY: %s; QC: %s'], ...
                rowIndex, expectedClusterName, ...
                string(qc.ClusterName(rowIndex)));
        end

        [clusterSets, clusterComps] = flatten_cluster_members_local( ...
            STUDY.cluster(clusterIndex).sets, ...
            STUDY.cluster(clusterIndex).comps);

        isMember = any( ...
            clusterSets == datasetIndex & ...
            clusterComps == icIndex);

        if ~isMember
            error([ ...
                'QC row %d is not present in source cluster %d: ' ...
                'Dataset %d, IC %d.'], ...
                rowIndex, ...
                clusterIndex, ...
                datasetIndex, ...
                icIndex);
        end
    end

    sourceUnion = zeros(0, 2);

    for clusterIndex = expectedChildClusterIndices

        qcRows = qc(double(qc.ClusterIndex) == clusterIndex, :);

        expectedPairs = sortrows( ...
            [double(qcRows.DatasetIndex), double(qcRows.IC)], ...
            [1 2]);

        [actualSets, actualComps] = flatten_cluster_members_local( ...
            STUDY.cluster(clusterIndex).sets, ...
            STUDY.cluster(clusterIndex).comps);

        actualPairs = sortrows( ...
            [actualSets, actualComps], [1 2]);

        if ~isequal(expectedPairs, actualPairs)
            error( ...
                'QC membership does not exactly match source cluster %d.', ...
                clusterIndex);
        end


        sourceUnion = [sourceUnion; actualPairs]; %#ok<AGROW>
    end

    sourceUnion = sortrows(sourceUnion, [1 2]);

    if size(unique(sourceUnion, 'rows'), 1) ~= size(sourceUnion, 1)
        error(['The source STUDY assigns at least one DatasetIndex-IC pair ' ...
            'to more than one child cluster.']);
    end

    [parentSets, parentComps] = flatten_cluster_members_local( ...
        STUDY.cluster(1).sets, STUDY.cluster(1).comps);
    parentPairs = sortrows([parentSets, parentComps], [1 2]);

    if ~isequal(sourceUnion, parentPairs)
        error(['Source ParentCluster membership is not exactly the union ' ...
            'of child clusters %s.'], ...
            mat2str(expectedChildClusterIndices));
    end
end

function resolvedQC = resolve_review_decisions_local( ...
    qc, STUDY, expectedChildClusterIndices)

    resolvedQC = qc;
    resolvedQC.OriginalClusterIndex = double(qc.ClusterIndex);
    resolvedQC.OriginalClusterName = string(qc.ClusterName);

    targetClusters = normalize_numeric_local(qc.TargetCluster);
    resolvedQC.ResolvedClusterIndex = double(qc.ClusterIndex);
    resolvedQC.ResolutionNote = strings(height(qc), 1);

    for rowIndex = 1:height(qc)
        decision = string(qc.ReviewerDecision(rowIndex));
        originalCluster = double(qc.ClusterIndex(rowIndex));

        if decision == "Reassign"
            targetCluster = targetClusters(rowIndex);

            if ~isfinite(targetCluster) || ...
                    targetCluster ~= round(targetCluster) || ...
                    ~ismember(targetCluster, expectedChildClusterIndices)

                error(['QC row %d is Reassign but TargetCluster is not a ' ...
                    'valid child cluster in %s.'], ...
                    rowIndex, mat2str(expectedChildClusterIndices));
            end

            if targetCluster == originalCluster
                error(['QC row %d is Reassign, but TargetCluster equals the ' ...
                    'original cluster %d. Use Keep instead.'], ...
                    rowIndex, originalCluster);
            end

            resolvedQC.ClusterIndex(rowIndex) = targetCluster;
            resolvedQC.ClusterName(rowIndex) = ...
                string(STUDY.cluster(targetCluster).name);
            resolvedQC.ResolvedClusterIndex(rowIndex) = targetCluster;
            resolvedQC.ResolutionNote(rowIndex) = ...
                "Reassigned from cluster " + string(originalCluster) + ...
                " to cluster " + string(targetCluster);

        else
            if isfinite(targetClusters(rowIndex))
                error(['QC row %d has ReviewerDecision=%s but also contains ' ...
                    'TargetCluster=%g. Clear TargetCluster or use Reassign.'], ...
                    rowIndex, decision, targetClusters(rowIndex));
            end

            if decision == "ClusterOutlier"
                resolvedQC.ResolutionNote(rowIndex) = ...
                    "Excluded from CORE and INCLUSIVE";
            else
                resolvedQC.ResolutionNote(rowIndex) = ...
                    "Original automatic cluster retained";
            end
        end
    end

end

function STUDY = create_curated_study_local( ...
        STUDY_SOURCE, ...
        members, ...
        versionName, ...
        qcFilename, ...
        outputFilename, ...
        outputFolder, ...
        expectedChildClusterIndices, ...
        qcSignature)

    STUDY = STUDY_SOURCE;

    clusterIndices = unique(double(members.ClusterIndex(:)))';

    if any(~ismember(clusterIndices, expectedChildClusterIndices))
        error('Curated members contain an unexpected child cluster index.');
    end

    % Remove cached cluster-level measure fields whose membership-dependent
    % values may no longer be valid.
    staleFields = { ...
        'erptimes', ...
        'erpdata', ...
        'specfreqs', ...
        'specdata', ...
        'erspdata', ...
        'ersptimes', ...
        'erspfreqs', ...
        'erspdatatrials', ...
        'erspsubjinds', ...
        'erspbase', ...
        'ersptrialinfo', ...
        'itcdata', ...
        'itcfreqs', ...
        'itctimes', ...
        'erpimdata', ...
        'erpimevents', ...
        'erpimtrials', ...
        'erpimtimes'};

    for fieldIndex = 1:numel(staleFields)
        if isfield(STUDY.cluster, staleFields{fieldIndex})
            STUDY.cluster = rmfield( ...
                STUDY.cluster, ...
                staleFields{fieldIndex});
        end
    end

    % Clear every expected child cluster first. This prevents an omitted
    % cluster from silently retaining automatic K-means members.
    for clusterIndex = expectedChildClusterIndices

        STUDY.cluster(clusterIndex).sets = [];
        STUDY.cluster(clusterIndex).comps = [];

        if isfield(STUDY.cluster, 'preclust')
            STUDY.cluster(clusterIndex).preclust = [];
        end
    end

    % Rebuild every child cluster from the resolved review table.
    for clusterIndex = expectedChildClusterIndices

        clusterRows = members( ...
            double(members.ClusterIndex) == clusterIndex, :);

        STUDY.cluster(clusterIndex).sets = ...
            double(clusterRows.DatasetIndex(:))';

        STUDY.cluster(clusterIndex).comps = ...
            double(clusterRows.IC(:))';

    end

    % Update ParentCluster 1 to contain exactly the union of curated members.
    parentRows = sortrows( ...
        members, ...
        {'DatasetIndex', 'IC'});

    STUDY.cluster(1).sets = ...
        double(parentRows.DatasetIndex(:))';

    STUDY.cluster(1).comps = ...
        double(parentRows.IC(:))';

    if isfield(STUDY.cluster, 'preclust')
        STUDY.cluster(1).preclust = [];
    end

    if ~isfield(STUDY, 'etc') || ~isstruct(STUDY.etc)
        STUDY.etc = struct();
    end

    STUDY.etc.manual_cluster_qc = struct();
    STUDY.etc.manual_cluster_qc.version = char(versionName);
    STUDY.etc.manual_cluster_qc.source_qc_csv = qcFilename;
    STUDY.etc.manual_cluster_qc.source_qc_signature = char(qcSignature);
    STUDY.etc.manual_cluster_qc.created = ...
        datestr(now, 30);
    STUDY.etc.manual_cluster_qc.member_count = ...
        height(members);
    STUDY.etc.manual_cluster_qc.cluster_indices = ...
        expectedChildClusterIndices;
    STUDY.etc.manual_cluster_qc.reassigned_member_count = ...
        sum(string(members.ReviewerDecision) == "Reassign");

    STUDY.name = sprintf( ...
        '%s | K=6 %s', ...
        STUDY_SOURCE.name, ...
        versionName);

    STUDY.notes = sprintf([ ...
        '%s\n\n' ...
        'Manual K=6 member-level QC version: %s\n' ...
        'Source QC table: %s\n' ...
        'Included members: %d\n' ...
        'Original datasets were not modified.\n'], ...
        char(string(STUDY_SOURCE.notes)), ...
        versionName, ...
        qcFilename, ...
        height(members));

    STUDY.filename = outputFilename;
    STUDY.filepath = outputFolder;
    STUDY.saved = 'no';
end

function verify_curated_study_local( ...
    STUDY, members, label, expectedChildClusterIndices)

    memberKeys = ...
        string(members.DatasetIndex) + "_" + string(members.IC);

    if numel(unique(memberKeys)) ~= height(members)
        error( ...
            '%s contains duplicate DatasetIndex-IC membership rows.', ...
            label);
    end

    clusterIndices = unique(double(members.ClusterIndex(:)))';

    if any(~ismember(clusterIndices, expectedChildClusterIndices))
        error('%s contains an unexpected child cluster index.', label);
    end

    actualChildClusterIndices = 2:numel(STUDY.cluster);

    if ~isequal(actualChildClusterIndices, expectedChildClusterIndices)
        error('%s has unexpected STUDY child cluster indices.', label);
    end

    totalChildMembers = 0;
    childUnion = zeros(0, 2);

    for clusterIndex = expectedChildClusterIndices

        rows = members( ...
            double(members.ClusterIndex) == clusterIndex, :);

        expectedPairs = sortrows( ...
            [double(rows.DatasetIndex), double(rows.IC)], ...
            [1 2]);

        [actualSets, actualComps] = flatten_cluster_members_local( ...
            STUDY.cluster(clusterIndex).sets, ...
            STUDY.cluster(clusterIndex).comps);

        actualPairs = sortrows( ...
            [actualSets, actualComps], [1 2]);

        if ~isequal(expectedPairs, actualPairs)
            error( ...
                '%s verification failed for cluster %d.', ...
                label, clusterIndex);
        end

        totalChildMembers = totalChildMembers + size(actualPairs, 1);
        childUnion = [childUnion; actualPairs]; %#ok<AGROW>
    end

    childUnion = sortrows(childUnion, [1 2]);

    if size(unique(childUnion, 'rows'), 1) ~= size(childUnion, 1)
        error('%s assigns a DatasetIndex-IC pair to multiple clusters.', ...
            label);
    end

    parentExpected = sortrows( ...
        [double(members.DatasetIndex), double(members.IC)], ...
        [1 2]);

    [parentSets, parentComps] = flatten_cluster_members_local( ...
        STUDY.cluster(1).sets, STUDY.cluster(1).comps);
    parentActual = sortrows([parentSets, parentComps], [1 2]);

    if ~isequal(parentExpected, parentActual)
        error( ...
            '%s ParentCluster membership verification failed.', ...
            label);
    end

    if totalChildMembers ~= height(members)
        error( ...
            '%s child-cluster member count is inconsistent.', ...
            label);
    end

    if ~isequal(childUnion, parentActual)
        error('%s child-cluster union does not equal ParentCluster.', label);
    end

    fprintf( ...
        ['%s verification passed: %d members; every cluster %s was ' ...
        'checked, including empty clusters.\n'], ...
        label, ...
        height(members), ...
        mat2str(expectedChildClusterIndices));
end

function [ ...
        clusterSummary, ...
        subjectCoverage, ...
        conditionCoverage, ...
        subjectConditionCoverage, ...
        duplicateDatasetMembers ...
    ] = build_coverage_tables_local(members)

    clusterIndices = unique(double(members.ClusterIndex(:)))';

    clusterSummary = table();
    subjectCoverage = table();
    conditionCoverage = table();
    subjectConditionCoverage = table();
    duplicateDatasetMembers = table();

    for clusterIndex = clusterIndices

        clusterRows = members( ...
            double(members.ClusterIndex) == clusterIndex, :);

        clusterName = string(clusterRows.ClusterName(1));

        subjectValues = unique( ...
            string(clusterRows.Subject), ...
            'stable');

        conditionValues = unique( ...
            string(clusterRows.Condition), ...
            'stable');

        subjectCountParts = strings(numel(subjectValues), 1);

        for subjectIndex = 1:numel(subjectValues)

            currentSubject = subjectValues(subjectIndex);

            subjectRows = clusterRows( ...
                string(clusterRows.Subject) == currentSubject, :);

            subjectCountParts(subjectIndex) = sprintf( ...
                '%s:%d', ...
                char(currentSubject), ...
                height(subjectRows));

            newSubjectRow = table( ...
                clusterIndex, ...
                clusterName, ...
                currentSubject, ...
                height(subjectRows), ...
                numel(unique(subjectRows.DatasetIndex)), ...
                numel(unique(string(subjectRows.Condition))), ...
                'VariableNames', { ...
                    'ClusterIndex', ...
                    'ClusterName', ...
                    'Subject', ...
                    'N_IC', ...
                    'N_Datasets', ...
                    'N_Conditions'});

            if isempty(subjectCoverage)
                subjectCoverage = newSubjectRow;
            else
                subjectCoverage = [ ...
                    subjectCoverage; ...
                    newSubjectRow]; %#ok<AGROW>
            end
        end

        conditionCountParts = strings(numel(conditionValues), 1);

        for conditionIndex = 1:numel(conditionValues)

            currentCondition = conditionValues(conditionIndex);

            conditionRows = clusterRows( ...
                string(clusterRows.Condition) == currentCondition, :);

            conditionCountParts(conditionIndex) = sprintf( ...
                '%s:%d', ...
                char(currentCondition), ...
                height(conditionRows));

            newConditionRow = table( ...
                clusterIndex, ...
                clusterName, ...
                currentCondition, ...
                height(conditionRows), ...
                numel(unique(conditionRows.DatasetIndex)), ...
                numel(unique(string(conditionRows.Subject))), ...
                'VariableNames', { ...
                    'ClusterIndex', ...
                    'ClusterName', ...
                    'Condition', ...
                    'N_IC', ...
                    'N_Datasets', ...
                    'N_Subjects'});

            if isempty(conditionCoverage)
                conditionCoverage = newConditionRow;
            else
                conditionCoverage = [ ...
                    conditionCoverage; ...
                    newConditionRow]; %#ok<AGROW>
            end
        end

        for subjectIndex = 1:numel(subjectValues)

            currentSubject = subjectValues(subjectIndex);

            for conditionIndex = 1:numel(conditionValues)

                currentCondition = conditionValues(conditionIndex);

                rows = clusterRows( ...
                    string(clusterRows.Subject) == currentSubject & ...
                    string(clusterRows.Condition) == currentCondition, :);

                if isempty(rows)
                    continue;
                end

                newSubjectConditionRow = table( ...
                    clusterIndex, ...
                    clusterName, ...
                    currentSubject, ...
                    currentCondition, ...
                    height(rows), ...
                    numel(unique(rows.DatasetIndex)), ...
                    'VariableNames', { ...
                        'ClusterIndex', ...
                        'ClusterName', ...
                        'Subject', ...
                        'Condition', ...
                        'N_IC', ...
                        'N_Datasets'});

                if isempty(subjectConditionCoverage)
                    subjectConditionCoverage = newSubjectConditionRow;
                else
                    subjectConditionCoverage = [ ...
                        subjectConditionCoverage; ...
                        newSubjectConditionRow]; %#ok<AGROW>
                end
            end
        end

        uniqueDatasets = unique(clusterRows.DatasetIndex);

        for datasetIndex = reshape(uniqueDatasets, 1, [])

            datasetRows = clusterRows( ...
                clusterRows.DatasetIndex == datasetIndex, :);

            if height(datasetRows) <= 1
                continue;
            end

            icList = strjoin( ...
                string(sort(double(datasetRows.IC))), ...
                ', ');

            newDuplicateRow = table( ...
                clusterIndex, ...
                clusterName, ...
                double(datasetIndex), ...
                string(datasetRows.Subject(1)), ...
                string(datasetRows.Condition(1)), ...
                double(datasetRows.Session(1)), ...
                height(datasetRows), ...
                icList, ...
                'VariableNames', { ...
                    'ClusterIndex', ...
                    'ClusterName', ...
                    'DatasetIndex', ...
                    'Subject', ...
                    'Condition', ...
                    'Session', ...
                    'N_IC', ...
                    'IC_List'});

            if isempty(duplicateDatasetMembers)
                duplicateDatasetMembers = newDuplicateRow;
            else
                duplicateDatasetMembers = [ ...
                    duplicateDatasetMembers; ...
                    newDuplicateRow]; %#ok<AGROW>
            end
        end

        newClusterSummaryRow = table( ...
            clusterIndex, ...
            clusterName, ...
            height(clusterRows), ...
            numel(unique(clusterRows.DatasetIndex)), ...
            numel(subjectValues), ...
            numel(conditionValues), ...
            sum(clusterRows.ReviewerDecision == "Keep"), ...
            sum(clusterRows.ReviewerDecision == "NeedsDiscussion"), ...
            sum(clusterRows.ReviewerDecision == "Reassign"), ...
            strjoin(subjectCountParts, '; '), ...
            strjoin(conditionCountParts, '; '), ...
            'VariableNames', { ...
                'ClusterIndex', ...
                'ClusterName', ...
                'N_IC', ...
                'N_Datasets', ...
                'N_Subjects', ...
                'N_Conditions', ...
                'N_Keep', ...
                'N_NeedsDiscussion', ...
                'N_Reassign', ...
                'SubjectCounts', ...
                'ConditionCounts'});

        if isempty(clusterSummary)
            clusterSummary = newClusterSummaryRow;
        else
            clusterSummary = [ ...
                clusterSummary; ...
                newClusterSummaryRow]; %#ok<AGROW>
        end
    end
end

function duplicateMask = duplicated_rows_local(values)

    [~, firstIndex] = unique(values, 'stable');

    duplicateMask = true(size(values));
    duplicateMask(firstIndex) = false;
end

function [setVector, compVector] = ...
        flatten_cluster_members_local(setsValue, compsValue)

    setVector = zeros(0, 1);
    compVector = zeros(0, 1);

    if isnumeric(setsValue) && isnumeric(compsValue)
        setsFlat = double(setsValue(:));
        compsFlat = double(compsValue(:));
        n = min(numel(setsFlat), numel(compsFlat));
        setsFlat = setsFlat(1:n);
        compsFlat = compsFlat(1:n);

        valid = isfinite(setsFlat) & setsFlat > 0 & ...
            isfinite(compsFlat) & compsFlat > 0;

        setVector = setsFlat(valid);
        compVector = compsFlat(valid);
        return;
    end

    if iscell(setsValue) && iscell(compsValue)
        nCells = min(numel(setsValue), numel(compsValue));

        for cellIndex = 1:nCells
            currentSets = double(setsValue{cellIndex}(:));
            currentComps = double(compsValue{cellIndex}(:));

            if isempty(currentSets) || isempty(currentComps)
                continue;
            end

            if isscalar(currentSets) && numel(currentComps) > 1
                currentSets = repmat(currentSets, size(currentComps));
            elseif isscalar(currentComps) && numel(currentSets) > 1
                currentComps = repmat(currentComps, size(currentSets));
            end

            n = min(numel(currentSets), numel(currentComps));
            currentSets = currentSets(1:n);
            currentComps = currentComps(1:n);

            valid = isfinite(currentSets) & currentSets > 0 & ...
                isfinite(currentComps) & currentComps > 0;

            setVector = [setVector; currentSets(valid)]; %#ok<AGROW>
            compVector = [compVector; currentComps(valid)]; %#ok<AGROW>
        end
        return;
    end

    if isempty(setsValue) && isempty(compsValue)
        return;
    end

    error('Unsupported STUDY cluster sets/comps representation.');
end

function values = normalize_numeric_local(values)

    if isnumeric(values)
        values = double(values);
    elseif islogical(values)
        values = double(values);
    else
        textValues = strtrim(string(values));
        textValues(ismissing(textValues)) = "";
        values = str2double(textValues);
    end

    values = double(values(:));
end

function signature = file_signature_local(filePath)

    filePath = string(filePath);

    if exist(filePath, 'file') ~= 2
        error('Cannot create a signature for a missing file: %s', filePath);
    end

    info = dir(filePath);
    signature = string(info.bytes) + "|" + ...
        compose('%.15g', info.datenum);
end
