% Goal:
% Create a BeMoBIL import table from:
%   output_data/xdf_file_stream_summary.csv
%   output_data/xdf_stream_detail_table.csv
%
% Output:
%   output_data/bemobil_import_table.csv
%
% Naming rule:
%   Raw:
%       Sub-P2_1 / day2 / data / ses-Exo1_sport / eeg / xxx.xdf
%
%   BeMoBIL/BIDS:
%       sub-01 / ses-Pilot2p1day2sesExo1Sport / eeg / ...
%
% Important:
%   This script does NOT load XDF files again.
%   It only reads the CSV tables generated by check_eeg_streams.m.
%
% Run order:
%   1) check_eeg_streams
%   2) import_table
%   3) bemobil_import

clear; clc;

%% Load central paths

run(fullfile(fileparts(mfilename('fullpath')), 'paths.m'));

if ~exist(summaryFile, 'file')
    error('File summary table not found:\n%s\nRun check_eeg_streams.m first.', summaryFile);
end

if ~exist(detailFile, 'file')
    error('Stream detail table not found:\n%s\nRun check_eeg_streams.m first.', detailFile);
end

%% Read CSV tables manually
% Do NOT use readtable here.
% MATLAB may wrongly split Windows paths like E:\master_thesis\... into columns.

fileSummary  = read_xdf_file_summary_csv(summaryFile);
streamDetail = read_xdf_stream_detail_csv(detailFile);

fprintf('Loaded file summary table: %d rows\n', height(fileSummary));
fprintf('Loaded stream detail table: %d rows\n', height(streamDetail));

fprintf('\nFile summary column names:\n');
disp(fileSummary.Properties.VariableNames');

fprintf('\nStream detail column names:\n');
disp(streamDetail.Properties.VariableNames');

%% Convert important columns

fileIndex = to_numeric_column(fileSummary.FileIndex);
hasEEG    = to_logical_column(fileSummary.HasRealEEG);

detailFileIndex = to_numeric_column(streamDetail.FileIndex);
detailIsRealEEG = to_logical_column(streamDetail.IsRealEEG);

%% Prepare output arrays

DoImport          = [];
XdfPath           = strings(0, 1);
FileName          = strings(0, 1);
RawSubjectFolder  = strings(0, 1);
RawDayFolder      = strings(0, 1);
RawSessionFolder  = strings(0, 1);
BidsSubject       = [];
BidsSession       = strings(0, 1);
Task              = strings(0, 1);
RunNumber         = strings(0, 1);
ExtraTag          = strings(0, 1);
EEGStreamName     = strings(0, 1);
NominalSrate      = strings(0, 1);
ChannelCount      = strings(0, 1);

%% Build import table from EEG files only

eegRows = find(hasEEG);

fprintf('\nFound %d files with real EEG in summary table.\n', numel(eegRows));

for k = 1:numel(eegRows)

    r = eegRows(k);

    thisFileIndex = fileIndex(r);
    thisFileName  = string(fileSummary.FileName(r));
    thisFullPath  = string(fileSummary.FullPath(r));

    xdfPathChar = char(thisFullPath);

    %% Parse raw folder information from full path
    % Example path:
    % E:\...\raw_data_PilotTest2\Sub-P2_1\day2\data\ses-Exo1_sport\eeg\xxx.xdf

    pathTok = regexp(xdfPathChar, ...
        '[\\/](?<rawSubject>Sub-P\d+_\d+)[\\/](?<rawDay>day\d+)[\\/]data[\\/](?<rawSession>ses-[^\\/]+)[\\/]eeg[\\/]', ...
        'names', 'once');

    if isempty(pathTok)
        warning('Could not parse raw path. Skipping:\n%s', xdfPathChar);
        continue;
    end

    rawSubject = string(pathTok.rawSubject);
    rawDay     = string(pathTok.rawDay);
    rawSession = string(pathTok.rawSession);

    %% Parse pilot number and subject number from Sub-P2_1

    subjTok = regexp(char(rawSubject), ...
        'Sub-P(?<pilot>\d+)_(?<subject>\d+)', ...
        'names', 'once');

    if isempty(subjTok)
        warning('Could not parse subject folder. Skipping:\n%s', rawSubject);
        continue;
    end

    pilotNumber = subjTok.pilot;
    subjectNumber = str2double(subjTok.subject);

    if isnan(subjectNumber)
        warning('Invalid subject number. Skipping:\n%s', rawSubject);
        continue;
    end

    %% Create BIDS subject and session labels

    % Keep original simple subject numbering:
    %   Sub-P2_1 -> subject 1
    %   Sub-P2_3 -> subject 3
    bidsSubject = subjectNumber;

    % Put raw source information into session label:
    %   Sub-P2_1 + day2 + ses-Exo1_sport
    %   -> Pilot2p1day2sesExo1Sport
    %
    % Use "p" instead of "-" or "_" to keep the BIDS label safe.
    pilotLabel = "Pilot" + string(pilotNumber) + "p" + string(subjectNumber);
    sessionLabel = pilotLabel + rawDay + make_bids_label(rawSession);

    %% Parse task from file name

    taskTok = regexp(char(thisFileName), ...
        '_task-(?<task>[A-Za-z0-9]+)', ...
        'names', 'once');

    if isempty(taskTok)
        taskLabel = "Default";
    else
        taskLabel = string(taskTok.task);
    end

    %% Parse run number from file name

    runTok = regexp(char(thisFileName), ...
        '_run-(?<run>\d+)', ...
        'names', 'once');

    if isempty(runTok)
        runLabel = "";
    else
        runLabel = string(runTok.run);
    end

    %% Find the real EEG stream for this file

    streamRows = find(detailFileIndex == thisFileIndex & detailIsRealEEG);

    if isempty(streamRows)
        % Fallback: match by full path.
        streamRows = find(streamDetail.FullPath == thisFullPath & detailIsRealEEG);
    end

    if isempty(streamRows)
        warning('No real EEG stream found in detail table. Skipping:\n%s', thisFullPath);
        continue;
    end

    firstStreamRow = streamRows(1);

    eegStream = string(streamDetail.StreamName(firstStreamRow));
    srate     = string(streamDetail.NominalSrate(firstStreamRow));
    nChan     = string(streamDetail.ChannelCount(firstStreamRow));

    %% Decide whether to import by default

    % Keep old files in the table, but do not import them by default.
    isOldFile = ~isempty(regexpi(char(thisFullPath), 'old\d*', 'once'));

    if isOldFile
        doImportFlag = 0;
        extraTag = "old_file_default_skip";
    else
        doImportFlag = 1;
        extraTag = "";
    end

    %% Append one row

    DoImport(end+1, 1)         = doImportFlag;
    XdfPath(end+1, 1)          = thisFullPath;
    FileName(end+1, 1)         = thisFileName;
    RawSubjectFolder(end+1, 1) = rawSubject;
    RawDayFolder(end+1, 1)     = rawDay;
    RawSessionFolder(end+1, 1) = rawSession;
    BidsSubject(end+1, 1)      = bidsSubject;
    BidsSession(end+1, 1)      = sessionLabel;
    Task(end+1, 1)             = taskLabel;
    RunNumber(end+1, 1)        = runLabel;
    ExtraTag(end+1, 1)         = extraTag;
    EEGStreamName(end+1, 1)    = eegStream;
    NominalSrate(end+1, 1)     = srate;
    ChannelCount(end+1, 1)     = nChan;

end

%% Create and save import table

importTable = table( ...
    DoImport, ...
    XdfPath, ...
    FileName, ...
    RawSubjectFolder, ...
    RawDayFolder, ...
    RawSessionFolder, ...
    BidsSubject, ...
    BidsSession, ...
    Task, ...
    RunNumber, ...
    ExtraTag, ...
    EEGStreamName, ...
    NominalSrate, ...
    ChannelCount);

writetable(importTable, importTableFile);

fprintf('\n============================================================\n');
fprintf('IMPORT TABLE CREATED\n');
fprintf('============================================================\n');

fprintf('Saved to:\n%s\n', importTableFile);

fprintf('\nTotal EEG rows in import table: %d\n', height(importTable));
fprintf('Rows with DoImport = 1: %d\n', sum(importTable.DoImport == 1));
fprintf('Rows with DoImport = 0: %d\n', sum(importTable.DoImport == 0));

fprintf('\nPreview:\n');
disp(importTable(1:min(10, height(importTable)), :));

%% Helper functions

function T = read_xdf_file_summary_csv(filename)
    % Expected header:
    % FileIndex,FileName,FullPath,AllStreams,HasRealEEG

    lines = splitlines(string(fileread(filename)));
    lines = lines(strlength(strtrim(lines)) > 0);

    if numel(lines) < 2
        error('CSV file is empty or has no data rows:\n%s', filename);
    end

    dataLines = lines(2:end);

    FileIndex  = [];
    FileName   = strings(0, 1);
    FullPath   = strings(0, 1);
    AllStreams = strings(0, 1);
    HasRealEEG = strings(0, 1);

    for i = 1:numel(dataLines)

        parts = strsplit(char(dataLines(i)), ',', 'CollapseDelimiters', false);

        if numel(parts) < 5
            warning('Skipping malformed summary line %d:\n%s', i + 1, dataLines(i));
            continue;
        end

        % First three fields are fixed.
        thisFileIndex = str2double(parts{1});
        thisFileName  = string(parts{2});
        thisFullPath  = string(parts{3});

        % Last field is HasRealEEG.
        thisHasEEG = string(parts{end});

        % Middle fields are AllStreams.
        % Usually this is only one field, but this protects against commas in messages.
        middleParts = parts(4:end-1);
        thisAllStreams = string(strjoin(middleParts, ','));

        FileIndex(end+1, 1)  = thisFileIndex;
        FileName(end+1, 1)   = thisFileName;
        FullPath(end+1, 1)   = thisFullPath;
        AllStreams(end+1, 1) = thisAllStreams;
        HasRealEEG(end+1, 1) = thisHasEEG;

    end

    T = table(FileIndex, FileName, FullPath, AllStreams, HasRealEEG);
end

function T = read_xdf_stream_detail_csv(filename)
    % Expected header:
    % FileIndex,FileName,FullPath,StreamIndex,StreamName,StreamType,NominalSrate,ChannelCount,IsRealEEG

    lines = splitlines(string(fileread(filename)));
    lines = lines(strlength(strtrim(lines)) > 0);

    if numel(lines) < 2
        error('CSV file is empty or has no data rows:\n%s', filename);
    end

    dataLines = lines(2:end);

    FileIndex    = [];
    FileName     = strings(0, 1);
    FullPath     = strings(0, 1);
    StreamIndex  = [];
    StreamName   = strings(0, 1);
    StreamType   = strings(0, 1);
    NominalSrate = strings(0, 1);
    ChannelCount = strings(0, 1);
    IsRealEEG    = strings(0, 1);

    for i = 1:numel(dataLines)

        parts = strsplit(char(dataLines(i)), ',', 'CollapseDelimiters', false);

        if numel(parts) < 9
            warning('Skipping malformed detail line %d:\n%s', i + 1, dataLines(i));
            continue;
        end

        % In normal generated files there are exactly 9 fields.
        % If there are more than 9, join the extra middle fields into StreamName.
        thisFileIndex   = str2double(parts{1});
        thisFileName    = string(parts{2});
        thisFullPath    = string(parts{3});
        thisStreamIndex = str2double(parts{4});

        if numel(parts) == 9
            thisStreamName   = string(parts{5});
            thisStreamType   = string(parts{6});
            thisNominalSrate = string(parts{7});
            thisChannelCount = string(parts{8});
            thisIsRealEEG    = string(parts{9});
        else
            % Last four fields are fixed.
            thisStreamType   = string(parts{end-3});
            thisNominalSrate = string(parts{end-2});
            thisChannelCount = string(parts{end-1});
            thisIsRealEEG    = string(parts{end});

            % Everything between StreamIndex and StreamType is StreamName.
            thisStreamName = string(strjoin(parts(5:end-4), ','));
        end

        FileIndex(end+1, 1)    = thisFileIndex;
        FileName(end+1, 1)     = thisFileName;
        FullPath(end+1, 1)     = thisFullPath;
        StreamIndex(end+1, 1)  = thisStreamIndex;
        StreamName(end+1, 1)   = thisStreamName;
        StreamType(end+1, 1)   = thisStreamType;
        NominalSrate(end+1, 1) = thisNominalSrate;
        ChannelCount(end+1, 1) = thisChannelCount;
        IsRealEEG(end+1, 1)    = thisIsRealEEG;

    end

    T = table(FileIndex, FileName, FullPath, StreamIndex, StreamName, ...
              StreamType, NominalSrate, ChannelCount, IsRealEEG);
end

function y = to_numeric_column(x)

    if isnumeric(x)
        y = x;
    elseif islogical(x)
        y = double(x);
    else
        y = str2double(string(x));
    end

end

function y = to_logical_column(x)

    if islogical(x)
        y = x;
        return;
    end

    if isnumeric(x)
        y = x ~= 0;
        return;
    end

    x = lower(strtrim(string(x)));

    y = x == "true" | x == "1" | x == "yes";

end

function label = make_bids_label(rawLabel)

    % Convert:
    %   ses-Exo1_sport       -> sesExo1Sport
    %   ses-Exo1_transportant -> sesExo1Transportant
    %
    % No hyphen, no underscore.

    rawLabel = char(rawLabel);

    parts = regexp(rawLabel, '[A-Za-z0-9]+', 'match');

    if isempty(parts)
        label = "unknown";
        return;
    end

    label = string(parts{1});

    for i = 2:numel(parts)

        p = string(parts{i});

        if strlength(p) == 0
            continue;
        end

        firstChar = upper(extractBetween(p, 1, 1));
        restChars = extractAfter(p, 1);

        label = label + firstChar + restChars;

    end

end