% Goal:
% Create a BeMoBIL import table from:
%   output_data/xdf_file_stream_summary.csv
%   output_data/xdf_stream_detail_table.csv
%
% Output:
%   output_data/bemobil_import_table.csv
%
% Important:
%   It reads the CSV tables generated by check_eeg_streams.m.
%   It keeps all files with real EEG streams in the table.
%   It sets DoImport = 1 only for usable EEG files.
%   Bad EEG files remain in the table with DoImport = 0 and QC reason.
%
% Run order:
%   1) check_eeg_streams.m
%   2) import_table.m
%   3) bemobil_import.m

clear; clc;

%% Load central paths

run(fullfile(fileparts(mfilename('fullpath')), 'paths.m'));

if ~exist(summaryFile, 'file')
    error('File summary table not found:\n%s\nRun check_eeg_streams.m first.', summaryFile);
end

if ~exist(detailFile, 'file')
    error('Stream detail table not found:\n%s\nRun check_eeg_streams.m first.', detailFile);
end

%% Read CSV tables

optsSummary = detectImportOptions(summaryFile, ...
    'FileType', 'text', ...
    'Delimiter', ',', ...
    'VariableNamingRule', 'preserve');

optsDetail = detectImportOptions(detailFile, ...
    'FileType', 'text', ...
    'Delimiter', ',', ...
    'VariableNamingRule', 'preserve');

fileSummary  = readtable(summaryFile, optsSummary);
streamDetail = readtable(detailFile, optsDetail);

fprintf('Loaded file summary table: %d rows\n', height(fileSummary));
fprintf('Loaded stream detail table: %d rows\n', height(streamDetail));

fprintf('\nFile summary column names:\n');
disp(fileSummary.Properties.VariableNames');

fprintf('\nStream detail column names:\n');
disp(streamDetail.Properties.VariableNames');

%% Make sure required columns exist

requiredSummaryColumns = {'FileIndex', 'FileName', 'FullPath', 'HasRealEEG'};
requiredDetailColumns = {'FileIndex', 'FileName', 'FullPath', 'StreamIndex', ...
                         'StreamName', 'StreamType', 'NominalSrate', ...
                         'ChannelCount', 'IsRealEEG'};

check_required_columns(fileSummary, requiredSummaryColumns, 'file summary table');
check_required_columns(streamDetail, requiredDetailColumns, 'stream detail table');

%% Convert important columns

fileSummary.FileIndex = to_numeric_column(fileSummary.FileIndex);
streamDetail.FileIndex = to_numeric_column(streamDetail.FileIndex);
streamDetail.StreamIndex = to_numeric_column(streamDetail.StreamIndex);

fileSummary.HasRealEEG = to_logical_column(fileSummary.HasRealEEG);
streamDetail.IsRealEEG = to_logical_column(streamDetail.IsRealEEG);

if ismember('HasUsableEEG', fileSummary.Properties.VariableNames)
    fileSummary.HasUsableEEG = to_logical_column(fileSummary.HasUsableEEG);
else
    warning('HasUsableEEG column not found. Falling back to HasRealEEG.');
    fileSummary.HasUsableEEG = fileSummary.HasRealEEG;
end

if ismember('IsUsableEEG', streamDetail.Properties.VariableNames)
    streamDetail.IsUsableEEG = to_logical_column(streamDetail.IsUsableEEG);
else
    warning('IsUsableEEG column not found. Falling back to IsRealEEG.');
    streamDetail.IsUsableEEG = streamDetail.IsRealEEG;
end

%% Convert text columns

fileSummary.FileName = string(fileSummary.FileName);
fileSummary.FullPath = string(fileSummary.FullPath);

streamDetail.FileName = string(streamDetail.FileName);
streamDetail.FullPath = string(streamDetail.FullPath);
streamDetail.StreamName = string(streamDetail.StreamName);
streamDetail.StreamType = string(streamDetail.StreamType);
streamDetail.NominalSrate = string(streamDetail.NominalSrate);
streamDetail.ChannelCount = string(streamDetail.ChannelCount);

if ismember('EEGQualityStatus', streamDetail.Properties.VariableNames)
    streamDetail.EEGQualityStatus = string(streamDetail.EEGQualityStatus);
else
    streamDetail.EEGQualityStatus = strings(height(streamDetail), 1);
end

if ismember('EEGQualityReason', streamDetail.Properties.VariableNames)
    streamDetail.EEGQualityReason = string(streamDetail.EEGQualityReason);
else
    streamDetail.EEGQualityReason = strings(height(streamDetail), 1);
end

%% Prepare output arrays

DoImport          = [];
XdfPath           = strings(0, 1);
FileName          = strings(0, 1);
RawSubjectFolder  = strings(0, 1);
RawDayFolder      = strings(0, 1);
RawSessionFolder  = strings(0, 1);
BidsSubject       = [];
BidsSession       = strings(0, 1);
Task              = strings(0, 1);
RunNumber         = strings(0, 1);
ExtraTag          = strings(0, 1);
EEGStreamName     = strings(0, 1);
NominalSrate      = strings(0, 1);
ChannelCount      = strings(0, 1);

HasUsableEEG      = [];
SelectedStreamIndex = [];
EEGQualityStatus  = strings(0, 1);
EEGQualityReason  = strings(0, 1);
DurationSec       = [];
EffectiveSrate    = [];
MaxDtSec          = [];
NDataSamples      = [];
NTimeStamps       = [];

%% Build import table from files with real EEG streams

eegRows = find(fileSummary.HasRealEEG);

fprintf('\nFound %d files with real EEG streams in summary table.\n', numel(eegRows));

for k = 1:numel(eegRows)

    r = eegRows(k);

    thisFileIndex = fileSummary.FileIndex(r);
    thisFileName  = string(fileSummary.FileName(r));
    thisFullPath  = string(fileSummary.FullPath(r));
    thisHasUsableEEG = logical(fileSummary.HasUsableEEG(r));

    xdfPathChar = char(thisFullPath);

    %% Parse raw folder information from full path
    % Example path:
    % E:\...\raw_data_PilotTest2\Sub-P2_1\day2\data\ses-Exo1_sport\eeg\xxx.xdf

    pathTok = regexp(xdfPathChar, ...
        '[\\/](?<rawSubject>Sub-P\d+_\d+)[\\/](?<rawDay>day\d+)[\\/]data[\\/](?<rawSession>ses-[^\\/]+)[\\/]eeg[\\/]', ...
        'names', 'once');

    if isempty(pathTok)
        warning('Could not parse raw path. Skipping:\n%s', xdfPathChar);
        continue;
    end

    rawSubject = string(pathTok.rawSubject);
    rawDay     = string(pathTok.rawDay);
    rawSession = string(pathTok.rawSession);

    %% Parse pilot number and subject number from Sub-P2_1

    subjTok = regexp(char(rawSubject), ...
        'Sub-P(?<pilot>\d+)_(?<subject>\d+)', ...
        'names', 'once');

    if isempty(subjTok)
        warning('Could not parse subject folder. Skipping:\n%s', rawSubject);
        continue;
    end

    pilotNumber = subjTok.pilot;
    subjectNumber = str2double(subjTok.subject);

    if isnan(subjectNumber)
        warning('Invalid subject number. Skipping:\n%s', rawSubject);
        continue;
    end

    %% Create BIDS subject and session labels

    % Keep original simple subject numbering:
    %   Sub-P2_1 -> subject 1
    %   Sub-P2_3 -> subject 3
    bidsSubject = subjectNumber;

    % Put raw source information into session label:
    %   Sub-P2_1 + day2 + ses-Exo1_sport
    %   -> Pilot2p1day2sesExo1Sport
    %
    % Important:
    %   Do NOT add Run001 / Run002 into BidsSession.
    %   RunNumber is stored separately and passed to bemobil_xdf2bids as config.run.
    pilotLabel = "Pilot" + string(pilotNumber) + "p" + string(subjectNumber);
    sessionLabel = pilotLabel + rawDay + make_bids_label(rawSession);

    %% Parse task from file name

    taskTok = regexp(char(thisFileName), ...
        '_task-(?<task>[A-Za-z0-9]+)', ...
        'names', 'once');

    if isempty(taskTok)
        taskLabel = "Default";
    else
        taskLabel = string(taskTok.task);
    end

    %% Parse run number from file name

    runTok = regexp(char(thisFileName), ...
        '_run-(?<run>\d+)', ...
        'names', 'once');

    if isempty(runTok)
        runLabel = "";
    else
        runLabel = string(runTok.run);
    end

    %% Find selected EEG stream for this file

    usableStreamRows = find(streamDetail.FileIndex == thisFileIndex & ...
                            streamDetail.IsRealEEG & ...
                            streamDetail.IsUsableEEG);

    realStreamRows = find(streamDetail.FileIndex == thisFileIndex & ...
                          streamDetail.IsRealEEG);

    if ~isempty(usableStreamRows)
        selectedStreamRow = usableStreamRows(1);
    elseif ~isempty(realStreamRows)
        selectedStreamRow = realStreamRows(1);
    else
        warning('No real EEG stream found in detail table. Skipping:\n%s', thisFullPath);
        continue;
    end

    eegStream = string(streamDetail.StreamName(selectedStreamRow));
    srate     = string(streamDetail.NominalSrate(selectedStreamRow));
    nChan     = string(streamDetail.ChannelCount(selectedStreamRow));

    selectedStreamIndex = streamDetail.StreamIndex(selectedStreamRow);

    if ismember('DurationSec', streamDetail.Properties.VariableNames)
        thisDurationSec = to_scalar_double(streamDetail.DurationSec(selectedStreamRow));
    else
        thisDurationSec = NaN;
    end

    if ismember('EffectiveSrate', streamDetail.Properties.VariableNames)
        thisEffectiveSrate = to_scalar_double(streamDetail.EffectiveSrate(selectedStreamRow));
    else
        thisEffectiveSrate = NaN;
    end

    if ismember('MaxDtSec', streamDetail.Properties.VariableNames)
        thisMaxDtSec = to_scalar_double(streamDetail.MaxDtSec(selectedStreamRow));
    else
        thisMaxDtSec = NaN;
    end

    if ismember('NDataSamples', streamDetail.Properties.VariableNames)
        thisNDataSamples = to_scalar_double(streamDetail.NDataSamples(selectedStreamRow));
    else
        thisNDataSamples = NaN;
    end

    if ismember('NTimeStamps', streamDetail.Properties.VariableNames)
        thisNTimeStamps = to_scalar_double(streamDetail.NTimeStamps(selectedStreamRow));
    else
        thisNTimeStamps = NaN;
    end

    thisQualityStatus = string(streamDetail.EEGQualityStatus(selectedStreamRow));
    thisQualityReason = string(streamDetail.EEGQualityReason(selectedStreamRow));

    if strlength(thisQualityStatus) == 0
        if thisHasUsableEEG
            thisQualityStatus = "OK";
            thisQualityReason = "usable_eeg_stream_found";
        else
            thisQualityStatus = "BAD_unknown";
            thisQualityReason = "no_usable_eeg_stream_found";
        end
    end

    %% Decide whether to import by default

    % Keep old files in the table, but do not import them by default.
    isOldFile = ~isempty(regexpi(char(thisFullPath), 'old\d*', 'once'));

    if isOldFile

        doImportFlag = 0;

        if strlength(thisQualityStatus) > 0
            extraTag = "old_file_default_skip;" + thisQualityStatus;
        else
            extraTag = "old_file_default_skip";
        end

    elseif ~thisHasUsableEEG

        doImportFlag = 0;
        extraTag = thisQualityStatus;

    else

        doImportFlag = 1;

        if startsWith(thisQualityStatus, "WARNING")
            extraTag = thisQualityStatus;
        else
            extraTag = "";
        end

    end

    %% Append one row

    DoImport(end+1, 1)            = doImportFlag;
    XdfPath(end+1, 1)             = thisFullPath;
    FileName(end+1, 1)            = thisFileName;
    RawSubjectFolder(end+1, 1)    = rawSubject;
    RawDayFolder(end+1, 1)        = rawDay;
    RawSessionFolder(end+1, 1)    = rawSession;
    BidsSubject(end+1, 1)         = bidsSubject;
    BidsSession(end+1, 1)         = sessionLabel;
    Task(end+1, 1)                = taskLabel;
    RunNumber(end+1, 1)           = runLabel;
    ExtraTag(end+1, 1)            = extraTag;
    EEGStreamName(end+1, 1)       = eegStream;
    NominalSrate(end+1, 1)        = srate;
    ChannelCount(end+1, 1)        = nChan;

    HasUsableEEG(end+1, 1)        = thisHasUsableEEG;
    SelectedStreamIndex(end+1, 1) = selectedStreamIndex;
    EEGQualityStatus(end+1, 1)    = thisQualityStatus;
    EEGQualityReason(end+1, 1)    = thisQualityReason;
    DurationSec(end+1, 1)         = thisDurationSec;
    EffectiveSrate(end+1, 1)      = thisEffectiveSrate;
    MaxDtSec(end+1, 1)            = thisMaxDtSec;
    NDataSamples(end+1, 1)        = thisNDataSamples;
    NTimeStamps(end+1, 1)         = thisNTimeStamps;

end

%% Create and save import table

importTable = table( ...
    DoImport, ...
    XdfPath, ...
    FileName, ...
    RawSubjectFolder, ...
    RawDayFolder, ...
    RawSessionFolder, ...
    BidsSubject, ...
    BidsSession, ...
    Task, ...
    RunNumber, ...
    ExtraTag, ...
    EEGStreamName, ...
    NominalSrate, ...
    ChannelCount, ...
    HasUsableEEG, ...
    SelectedStreamIndex, ...
    EEGQualityStatus, ...
    EEGQualityReason, ...
    DurationSec, ...
    EffectiveSrate, ...
    MaxDtSec, ...
    NDataSamples, ...
    NTimeStamps);

writetable(importTable, importTableFile);

%% Final report

fprintf('\n============================================================\n');
fprintf('IMPORT TABLE CREATED\n');
fprintf('============================================================\n');

fprintf('Saved to:\n%s\n', importTableFile);

fprintf('\nTotal EEG rows in import table: %d\n', height(importTable));
fprintf('Rows with DoImport = 1: %d\n', sum(importTable.DoImport == 1));
fprintf('Rows with DoImport = 0: %d\n', sum(importTable.DoImport == 0));

fprintf('\nDoImport = 0 reasons:\n');

skipRows = importTable.DoImport == 0;

if any(skipRows)

    skipStatus = importTable.EEGQualityStatus(skipRows);
    uniqueStatus = unique(skipStatus, 'stable');

    for k = 1:numel(uniqueStatus)
        thisStatus = uniqueStatus(k);
        n = sum(skipStatus == thisStatus);
        fprintf('  %-40s %d\n', thisStatus, n);
    end

    fprintf('\nSkipped EEG rows:\n');
    disp(importTable(skipRows, { ...
        'FileName', 'BidsSubject', 'BidsSession', 'RunNumber', ...
        'ExtraTag', 'EEGQualityStatus', 'EEGQualityReason', ...
        'DurationSec', 'EffectiveSrate', 'MaxDtSec', ...
        'NDataSamples', 'NTimeStamps'}));

else

    fprintf('  None.\n');

end

fprintf('\nPreview:\n');
disp(importTable(1:min(10, height(importTable)), :));

fprintf('\nDone.\n');

%% Helper functions

function check_required_columns(T, requiredColumns, tableName)

    for i = 1:numel(requiredColumns)
        if ~ismember(requiredColumns{i}, T.Properties.VariableNames)
            error('Required column "%s" not found in %s.', requiredColumns{i}, tableName);
        end
    end

end

function y = to_numeric_column(x)

    if isnumeric(x)
        y = double(x);
    elseif islogical(x)
        y = double(x);
    else
        y = str2double(string(x));
    end

end

function y = to_logical_column(x)

    if islogical(x)
        y = x;
        return;
    end

    if isnumeric(x)
        y = x ~= 0;
        return;
    end

    x = lower(strtrim(string(x)));

    y = x == "true" | x == "1" | x == "yes";

end

function y = to_scalar_double(x)

    if isnumeric(x)
        y = double(x);
    elseif islogical(x)
        y = double(x);
    else
        y = str2double(string(x));
    end

    if numel(y) > 1
        y = y(1);
    end

end

function label = make_bids_label(rawLabel)

    % Convert:
    %   ses-Exo1_sport        -> sesExo1Sport
    %   ses-Exo1_transportant -> sesExo1Transportant
    %
    % No hyphen, no underscore.

    rawLabel = char(rawLabel);

    parts = regexp(rawLabel, '[A-Za-z0-9]+', 'match');

    if isempty(parts)
        label = "unknown";
        return;
    end

    label = string(parts{1});

    for i = 2:numel(parts)

        p = string(parts{i});

        if strlength(p) == 0
            continue;
        end

        firstChar = upper(extractBetween(p, 1, 1));
        restChars = extractAfter(p, 1);

        label = label + firstChar + restChars;

    end

end