% Goal:
% Create a BeMoBIL import table from:
%   output_data/xdf_file_stream_summary.csv
%   output_data/xdf_stream_detail_table.csv
%
% Output:
%   output_data/bemobil_import_table.csv
%
% Important:
%   It reads the CSV tables generated by check_eeg_streams.m.
%   It keeps all files with real EEG streams in the table.
%   It sets DoImport = 1 only for usable EEG files.
%   Bad EEG files remain in the table with DoImport = 0 and QC reason.
%
% Run order:
%   1) check_eeg_streams.m
%   2) import_table.m
%   3) bemobil_import.m

clear; clc;

expectedEEGStreamName = "LiveAmpSN-102108-1139";

%% Load central paths

run(fullfile(fileparts(mfilename('fullpath')), 'paths.m'));

if ~exist(summaryFile, 'file')
    error('File summary table not found:\n%s\nRun check_eeg_streams.m first.', summaryFile);
end

if ~exist(detailFile, 'file')
    error('Stream detail table not found:\n%s\nRun check_eeg_streams.m first.', detailFile);
end

%% Read CSV tables

optsSummary = detectImportOptions(summaryFile, ...
    'FileType', 'text', ...
    'Delimiter', ',', ...
    'VariableNamingRule', 'preserve');

optsDetail = detectImportOptions(detailFile, ...
    'FileType', 'text', ...
    'Delimiter', ',', ...
    'VariableNamingRule', 'preserve');

fileSummary  = readtable(summaryFile, optsSummary);
streamDetail = readtable(detailFile, optsDetail);

fprintf('Loaded file summary table: %d rows\n', height(fileSummary));
fprintf('Loaded stream detail table: %d rows\n', height(streamDetail));

fprintf('\nFile summary column names:\n');
disp(fileSummary.Properties.VariableNames');

fprintf('\nStream detail column names:\n');
disp(streamDetail.Properties.VariableNames');

%% Make sure required columns exist

requiredSummaryColumns = {'FileIndex', 'FileName', 'FullPath', ...
                          'HasRealEEG', 'HasUsableEEG'};
requiredDetailColumns = {'FileIndex', 'FileName', 'FullPath', 'StreamIndex', ...
                         'StreamName', 'StreamType', 'NominalSrate', ...
                         'ChannelCount', 'IsRealEEG', 'IsUsableEEG'};

check_required_columns(fileSummary, requiredSummaryColumns, 'file summary table');
check_required_columns(streamDetail, requiredDetailColumns, 'stream detail table');

%% Convert important columns

fileSummary.FileIndex = to_numeric_column(fileSummary.FileIndex);
streamDetail.FileIndex = to_numeric_column(streamDetail.FileIndex);
streamDetail.StreamIndex = to_numeric_column(streamDetail.StreamIndex);

fileSummary.HasRealEEG   = to_logical_column(fileSummary.HasRealEEG);
fileSummary.HasUsableEEG = to_logical_column(fileSummary.HasUsableEEG);
streamDetail.IsRealEEG   = to_logical_column(streamDetail.IsRealEEG);
streamDetail.IsUsableEEG = to_logical_column(streamDetail.IsUsableEEG);

%% Convert text columns

fileSummary.FileName = string(fileSummary.FileName);
fileSummary.FullPath = string(fileSummary.FullPath);

streamDetail.FileName = string(streamDetail.FileName);
streamDetail.FullPath = string(streamDetail.FullPath);
streamDetail.StreamName = string(streamDetail.StreamName);
streamDetail.StreamType = string(streamDetail.StreamType);
streamDetail.NominalSrate = string(streamDetail.NominalSrate);
streamDetail.ChannelCount = string(streamDetail.ChannelCount);

if ismember('EEGQualityStatus', streamDetail.Properties.VariableNames)
    streamDetail.EEGQualityStatus = string(streamDetail.EEGQualityStatus);
else
    streamDetail.EEGQualityStatus = strings(height(streamDetail), 1);
end

if ismember('EEGQualityReason', streamDetail.Properties.VariableNames)
    streamDetail.EEGQualityReason = string(streamDetail.EEGQualityReason);
else
    streamDetail.EEGQualityReason = strings(height(streamDetail), 1);
end

%% Prepare output arrays

DoImport          = [];
XdfPath           = strings(0, 1);
FileName          = strings(0, 1);
RawSubjectFolder  = strings(0, 1);
RawDayFolder      = strings(0, 1);
RawSessionFolder  = strings(0, 1);
BidsSubject       = [];
BidsSession       = strings(0, 1);
Task              = strings(0, 1);
RunNumber         = strings(0, 1);
ExtraTag          = strings(0, 1);
EEGStreamName     = strings(0, 1);
NominalSrate      = strings(0, 1);
ChannelCount      = strings(0, 1);

HasUsableEEG      = [];
SelectedStreamIndex = [];
EEGQualityStatus  = strings(0, 1);
EEGQualityReason  = strings(0, 1);
DurationSec       = [];
EffectiveSrate    = [];
MaxDtSec          = [];
NDataSamples      = [];
NTimeStamps       = [];

%% Build import table from files with real EEG streams

eegRows = find(fileSummary.HasRealEEG);

fprintf('\nFound %d files with real EEG streams in summary table.\n', numel(eegRows));

for k = 1:numel(eegRows)

    r = eegRows(k);

    thisFileIndex = fileSummary.FileIndex(r);
    thisFileName  = string(fileSummary.FileName(r));
    thisFullPath  = string(fileSummary.FullPath(r));
    thisHasUsableEEG = logical(fileSummary.HasUsableEEG(r));

    xdfPathChar = char(thisFullPath);

    %% Parse raw folder information from full path
    % Example path:
    % E:\...\raw_data_PilotTest2\Sub-P2_1\day2\data\ses-Exo1_sport\eeg\xxx.xdf

    pathTok = regexp(xdfPathChar, ...
        '[\\/](?<rawSubject>Sub-P\d+_\d+)[\\/](?<rawDay>day\d+)[\\/]data[\\/](?<rawSession>ses-[^\\/]+)[\\/]eeg[\\/]', ...
        'names', 'once');

    if isempty(pathTok)
        error(['Could not parse a real-EEG XDF path:\n%s\n' ...
            'No import table was written. Fix the path schema or update the path regexp explicitly.'], ...
            xdfPathChar);
    end

    rawSubject = string(pathTok.rawSubject);
    rawDay     = string(pathTok.rawDay);
    rawSession = string(pathTok.rawSession);

    %% Parse pilot number and subject number from Sub-P2_1

    subjTok = regexp(char(rawSubject), ...
        'Sub-P(?<pilot>\d+)_(?<subject>\d+)', ...
        'names', 'once');

    if isempty(subjTok)
        error('Could not parse subject folder for a real-EEG XDF: %s', rawSubject);
    end

    pilotNumber = subjTok.pilot;
    subjectNumber = str2double(subjTok.subject);

    if isnan(subjectNumber)
        error('Invalid subject number for a real-EEG XDF: %s', rawSubject);
    end

    %% Create BIDS subject and session labels

    % Keep original simple subject numbering:
    %   Sub-P2_1 -> subject 1
    %   Sub-P2_3 -> subject 3
    bidsSubject = subjectNumber;

    % Put raw source information into session label:
    %   Sub-P2_1 + day2 + ses-Exo1_sport
    %   -> Pilot2p1day2sesExo1Sport
    %
    % Important:
    %   Do NOT add Run001 / Run002 into BidsSession.
    %   RunNumber is stored separately and passed to bemobil_xdf2bids as config.run.
    pilotLabel = "Pilot" + string(pilotNumber) + "p" + string(subjectNumber);
    sessionLabel = pilotLabel + rawDay + make_bids_label(rawSession);

    %% Parse task from file name

    taskTok = regexp(char(thisFileName), ...
        '_task-(?<task>[A-Za-z0-9]+)', ...
        'names', 'once');

    if isempty(taskTok)
        taskLabel = "Default";
    else
        taskLabel = string(taskTok.task);
    end

    %% Parse run number from file name

    runTok = regexp(char(thisFileName), ...
        '_run-(?<run>\d+)', ...
        'names', 'once');

    if isempty(runTok)
        runLabel = "";
    else
        runLabel = string(runTok.run);
    end

    %% Find selected EEG stream for this file

    usableStreamRows = find(streamDetail.FileIndex == thisFileIndex & ...
                            streamDetail.IsRealEEG & ...
                            streamDetail.IsUsableEEG);

    realStreamRows = find(streamDetail.FileIndex == thisFileIndex & ...
                          streamDetail.IsRealEEG);

    exactUsableRows = usableStreamRows( ...
        streamDetail.StreamName(usableStreamRows) == expectedEEGStreamName);

    if ~isempty(exactUsableRows)
        selectedStreamRow = exactUsableRows(1);
    elseif ~isempty(usableStreamRows)
        selectedStreamRow = usableStreamRows(1);
    elseif ~isempty(realStreamRows)
        selectedStreamRow = realStreamRows(1);
    else
        warning('No real EEG stream found in detail table. Skipping:\n%s', thisFullPath);
        continue;
    end

    eegStream = string(streamDetail.StreamName(selectedStreamRow));
    srate     = string(streamDetail.NominalSrate(selectedStreamRow));
    nChan     = string(streamDetail.ChannelCount(selectedStreamRow));

    selectedStreamIndex = streamDetail.StreamIndex(selectedStreamRow);

    if ismember('DurationSec', streamDetail.Properties.VariableNames)
        thisDurationSec = to_scalar_double(streamDetail.DurationSec(selectedStreamRow));
    else
        thisDurationSec = NaN;
    end

    if ismember('EffectiveSrate', streamDetail.Properties.VariableNames)
        thisEffectiveSrate = to_scalar_double(streamDetail.EffectiveSrate(selectedStreamRow));
    else
        thisEffectiveSrate = NaN;
    end

    if ismember('MaxDtSec', streamDetail.Properties.VariableNames)
        thisMaxDtSec = to_scalar_double(streamDetail.MaxDtSec(selectedStreamRow));
    else
        thisMaxDtSec = NaN;
    end

    if ismember('NDataSamples', streamDetail.Properties.VariableNames)
        thisNDataSamples = to_scalar_double(streamDetail.NDataSamples(selectedStreamRow));
    else
        thisNDataSamples = NaN;
    end

    if ismember('NTimeStamps', streamDetail.Properties.VariableNames)
        thisNTimeStamps = to_scalar_double(streamDetail.NTimeStamps(selectedStreamRow));
    else
        thisNTimeStamps = NaN;
    end

    thisQualityStatus = string(streamDetail.EEGQualityStatus(selectedStreamRow));
    thisQualityReason = string(streamDetail.EEGQualityReason(selectedStreamRow));

    if strlength(thisQualityStatus) == 0
        if thisHasUsableEEG
            thisQualityStatus = "OK";
            thisQualityReason = "usable_eeg_stream_found";
        else
            thisQualityStatus = "BAD_unknown";
            thisQualityReason = "no_usable_eeg_stream_found";
        end
    end

    %% Decide whether to import by default

    % Keep old/backup files in the table, but do not import them by default.
    % Match only a filename suffix such as _old.xdf, _old1.xdf, _old2.xdf.
    % Do not inspect the whole path, because a parent folder could contain
    % the word "old" without the XDF itself being an old backup.
    isOldFile = ~isempty(regexpi(char(thisFileName), '_old\d*\.xdf$', 'once'));

    if isOldFile

        doImportFlag = 0;

        if strlength(thisQualityStatus) > 0
            extraTag = "old_file_default_skip;" + thisQualityStatus;
        else
            extraTag = "old_file_default_skip";
        end

    elseif eegStream ~= expectedEEGStreamName

        doImportFlag = 0;
        extraTag = "unexpected_eeg_stream_default_skip;" + thisQualityStatus;

    elseif ~thisHasUsableEEG

        doImportFlag = 0;
        extraTag = thisQualityStatus;

    else

        doImportFlag = 1;

        if startsWith(thisQualityStatus, "WARNING")
            extraTag = thisQualityStatus;
        else
            extraTag = "";
        end

    end

    %% Append one row

    DoImport(end+1, 1)            = doImportFlag;
    XdfPath(end+1, 1)             = thisFullPath;
    FileName(end+1, 1)            = thisFileName;
    RawSubjectFolder(end+1, 1)    = rawSubject;
    RawDayFolder(end+1, 1)        = rawDay;
    RawSessionFolder(end+1, 1)    = rawSession;
    BidsSubject(end+1, 1)         = bidsSubject;
    BidsSession(end+1, 1)         = sessionLabel;
    Task(end+1, 1)                = taskLabel;
    RunNumber(end+1, 1)           = runLabel;
    ExtraTag(end+1, 1)            = extraTag;
    EEGStreamName(end+1, 1)       = eegStream;
    NominalSrate(end+1, 1)        = srate;
    ChannelCount(end+1, 1)        = nChan;

    HasUsableEEG(end+1, 1)        = thisHasUsableEEG;
    SelectedStreamIndex(end+1, 1) = selectedStreamIndex;
    EEGQualityStatus(end+1, 1)    = thisQualityStatus;
    EEGQualityReason(end+1, 1)    = thisQualityReason;
    DurationSec(end+1, 1)         = thisDurationSec;
    EffectiveSrate(end+1, 1)      = thisEffectiveSrate;
    MaxDtSec(end+1, 1)            = thisMaxDtSec;
    NDataSamples(end+1, 1)        = thisNDataSamples;
    NTimeStamps(end+1, 1)         = thisNTimeStamps;

end

%% Create and save import table

importTable = table( ...
    DoImport, ...
    XdfPath, ...
    FileName, ...
    RawSubjectFolder, ...
    RawDayFolder, ...
    RawSessionFolder, ...
    BidsSubject, ...
    BidsSession, ...
    Task, ...
    RunNumber, ...
    ExtraTag, ...
    EEGStreamName, ...
    NominalSrate, ...
    ChannelCount, ...
    HasUsableEEG, ...
    SelectedStreamIndex, ...
    EEGQualityStatus, ...
    EEGQualityReason, ...
    DurationSec, ...
    EffectiveSrate, ...
    MaxDtSec, ...
    NDataSamples, ...
    NTimeStamps);

% Keep the QC-derived recommendation separate from the editable DoImport flag.
importTable.RecommendedDoImport = importTable.DoImport;

% Preserve manual and downstream columns only when the source-row signature
% is unchanged. Changed rows deliberately lose downstream status so stale
% preprocessing/AMICA outputs cannot be trusted silently.
importTable = preserve_existing_columns(importTable, importTableFile);

% A duplicate BIDS run key is dangerous only when more than one row is
% actually enabled for import. Disabled old/backup rows may share the same
% parsed key and should remain visible without disabling the valid row.
importTable = disable_duplicate_bids_keys(importTable);

writetable(importTable, importTableFile);

%% Final report

fprintf('\n============================================================\n');
fprintf('IMPORT TABLE CREATED\n');
fprintf('============================================================\n');

fprintf('Saved to:\n%s\n', importTableFile);

fprintf('\nTotal EEG rows in import table: %d\n', height(importTable));
fprintf('Rows with DoImport = 1: %d\n', sum(importTable.DoImport == 1));
fprintf('Rows with DoImport = 0: %d\n', sum(importTable.DoImport == 0));

fprintf('\nDoImport = 0 reasons:\n');

skipRows = importTable.DoImport == 0;

if any(skipRows)

    skipStatus = importTable.EEGQualityStatus(skipRows);
    uniqueStatus = unique(skipStatus, 'stable');

    for k = 1:numel(uniqueStatus)
        thisStatus = uniqueStatus(k);
        n = sum(skipStatus == thisStatus);
        fprintf('  %-40s %d\n', thisStatus, n);
    end

    fprintf('\nSkipped EEG rows:\n');
    disp(importTable(skipRows, { ...
        'FileName', 'BidsSubject', 'BidsSession', 'RunNumber', ...
        'ExtraTag', 'EEGQualityStatus', 'EEGQualityReason', ...
        'DurationSec', 'EffectiveSrate', 'MaxDtSec', ...
        'NDataSamples', 'NTimeStamps'}));

else

    fprintf('  None.\n');

end

fprintf('\nPreview:\n');
disp(importTable(1:min(10, height(importTable)), :));

fprintf('\nDone.\n');

%% Helper functions

function check_required_columns(T, requiredColumns, tableName)

    for i = 1:numel(requiredColumns)
        if ~ismember(requiredColumns{i}, T.Properties.VariableNames)
            error('Required column "%s" not found in %s.', requiredColumns{i}, tableName);
        end
    end

end

function y = to_numeric_column(x)

    if isnumeric(x)
        y = double(x);
    elseif islogical(x)
        y = double(x);
    else
        y = str2double(string(x));
    end

end

function y = to_logical_column(x)

    if islogical(x)
        y = x;
        return;
    end

    if isnumeric(x)
        y = x ~= 0;
        return;
    end

    x = lower(strtrim(string(x)));

    y = x == "true" | x == "1" | x == "yes";

end

function y = to_scalar_double(x)

    if isnumeric(x)
        y = double(x);
    elseif islogical(x)
        y = double(x);
    else
        y = str2double(string(x));
    end

    if numel(y) > 1
        y = y(1);
    end

end

function label = make_bids_label(rawLabel)

    % Convert:
    %   ses-Exo1_sport        -> sesExo1Sport
    %   ses-Exo1_transportant -> sesExo1Transportant
    %
    % No hyphen, no underscore.

    rawLabel = char(rawLabel);

    parts = regexp(rawLabel, '[A-Za-z0-9]+', 'match');

    if isempty(parts)
        label = "unknown";
        return;
    end

    label = string(parts{1});

    for i = 2:numel(parts)

        p = string(parts{i});

        if strlength(p) == 0
            continue;
        end

        firstChar = upper(extractBetween(p, 1, 1));
        restChars = extractAfter(p, 1);

        label = label + firstChar + restChars;

    end

end

function T = disable_duplicate_bids_keys(T)

    % Only enabled rows can overwrite one another during XDF -> BIDS import.
    % A disabled _old*.xdf row is allowed to share the same parsed BIDS key
    % with the current file because it will not be passed to bemobil_xdf2bids.
    T.DoImport = to_numeric_column(T.DoImport);

    if ismember('RecommendedDoImport', T.Properties.VariableNames)
        T.RecommendedDoImport = to_numeric_column(T.RecommendedDoImport);
    end

    enabledRows = find(T.DoImport == 1);

    if numel(enabledRows) < 2
        return;
    end

    runText = string(T.RunNumber(enabledRows));
    runText(ismissing(runText)) = "";

    keys = string(T.BidsSubject(enabledRows)) + "|" + ...
           string(T.BidsSession(enabledRows)) + "|" + ...
           string(T.Task(enabledRows)) + "|" + runText;

    [uniqueKeys, ~, groupIndex] = unique(keys, 'stable');
    counts = accumarray(groupIndex, 1);
    duplicateGroups = find(counts > 1);

    if isempty(duplicateGroups)
        return;
    end

    warning(['Duplicate ENABLED BIDS subject/session/task/run keys found. ' ...
             'Only the conflicting enabled rows were set to DoImport = 0.']);

    for k = 1:numel(duplicateGroups)

        rows = enabledRows(groupIndex == duplicateGroups(k));

        T.DoImport(rows) = 0;

        if ismember('RecommendedDoImport', T.Properties.VariableNames)
            T.RecommendedDoImport(rows) = 0;
        end

        T.EEGQualityStatus(rows) = "BAD_duplicate_enabled_bids_key";
        T.EEGQualityReason(rows) = ...
            "multiple_enabled_XDF_files_map_to_the_same_BIDS_subject_session_task_run";
        T.ExtraTag(rows) = "duplicate_enabled_bids_key_default_skip";

        fprintf('Duplicate enabled key: %s\n', uniqueKeys(duplicateGroups(k)));
        disp(T(rows, {'FileName', 'XdfPath', 'BidsSubject', ...
                      'BidsSession', 'Task', 'RunNumber', 'DoImport'}));

    end

end

function newT = preserve_existing_columns(newT, tableFile)

    if ~exist(tableFile, 'file')
        return;
    end

    try
        opts = detectImportOptions(tableFile, 'FileType', 'text', 'Delimiter', ',', ...
            'VariableNamingRule', 'preserve');
        oldT = readtable(tableFile, opts);
    catch ME
        warning('Could not read the previous import table. Existing manual columns were not preserved: %s', ME.message);
        return;
    end

    if ~ismember('XdfPath', oldT.Properties.VariableNames)
        warning('Previous import table has no XdfPath column. Existing columns were not preserved.');
        return;
    end

    oldT.XdfPath = string(oldT.XdfPath);
    newT.XdfPath = string(newT.XdfPath);

    oldExtra = setdiff(oldT.Properties.VariableNames, newT.Properties.VariableNames, 'stable');
    columnsToPreserve = [{'DoImport'}, oldExtra];

    for c = 1:numel(columnsToPreserve)
        name = columnsToPreserve{c};
        if ~ismember(name, oldT.Properties.VariableNames)
            continue;
        end
        if ~ismember(name, newT.Properties.VariableNames)
            newT.(name) = make_missing_column_like(oldT.(name), height(newT));
        end
    end

    preservedRows = 0;
    invalidatedRows = 0;

    for r = 1:height(newT)
        oldRow = find(oldT.XdfPath == newT.XdfPath(r), 1, 'first');
        if isempty(oldRow)
            continue;
        end

        if source_signature_matches(oldT, oldRow, newT, r)
            for c = 1:numel(columnsToPreserve)
                name = columnsToPreserve{c};
                if ismember(name, oldT.Properties.VariableNames)

                    if strcmp(name, 'DoImport')

                        % Never enable a row that is currently not recommended.
                        if newT.RecommendedDoImport(r) ~= 1
                            continue;
                        end

                        % Earlier versions automatically set all rows in a
                        % duplicate group to DoImport = 0. Do not preserve that
                        % obsolete automatic decision; let the current QC logic
                        % restore the valid non-old row to DoImport = 1.
                        if was_auto_disabled_duplicate(oldT, oldRow)
                            continue;
                        end

                    end

                    newT.(name)(r,:) = oldT.(name)(oldRow,:);

                end
            end
            preservedRows = preservedRows + 1;
        else
            invalidatedRows = invalidatedRows + 1;
        end
    end

    fprintf('Preserved manual/downstream columns for %d unchanged XDF rows.\n', preservedRows);
    fprintf('Invalidated downstream columns for %d changed XDF rows.\n', invalidatedRows);

end

function tf = was_auto_disabled_duplicate(T, row)

    tf = false;

    if ismember('ExtraTag', T.Properties.VariableNames)
        tag = string(T.ExtraTag(row));
        tag(ismissing(tag)) = "";

        if contains(tag, "duplicate_bids_key_default_skip") || ...
                contains(tag, "duplicate_enabled_bids_key_default_skip")
            tf = true;
            return;
        end
    end

    if ismember('EEGQualityStatus', T.Properties.VariableNames)
        status = string(T.EEGQualityStatus(row));
        status(ismissing(status)) = "";

        if status == "BAD_duplicate_bids_key" || ...
                status == "BAD_duplicate_enabled_bids_key"
            tf = true;
        end
    end

end

function tf = source_signature_matches(oldT, oldRow, newT, newRow)

    tf = true;
    fields = {'BidsSubject', 'BidsSession', 'Task', 'RunNumber', ...
              'NDataSamples', 'NTimeStamps', 'DurationSec', 'EffectiveSrate'};

    for i = 1:numel(fields)
        name = fields{i};
        if ~ismember(name, oldT.Properties.VariableNames) || ...
                ~ismember(name, newT.Properties.VariableNames)
            tf = false;
            return;
        end

        a = string(oldT.(name)(oldRow));
        b = string(newT.(name)(newRow));

        if ismember(name, {'DurationSec', 'EffectiveSrate'})
            av = str2double(a);
            bv = str2double(b);
            if ~(isfinite(av) && isfinite(bv) && abs(av - bv) <= 1e-6)
                tf = false;
                return;
            end
        elseif ~isequaln(a, b)
            tf = false;
            return;
        end
    end

end

function out = make_missing_column_like(example, nRows)

    if isstring(example)
        out = strings(nRows, size(example, 2));
    elseif islogical(example)
        out = false(nRows, size(example, 2));
    elseif isnumeric(example)
        out = nan(nRows, size(example, 2));
    elseif isdatetime(example)
        out = NaT(nRows, size(example, 2));
    elseif iscell(example)
        out = cell(nRows, size(example, 2));
    elseif iscategorical(example)
        out = repmat(categorical(missing), nRows, size(example, 2));
    else
        out = strings(nRows, size(example, 2));
    end

end
