%% run_k06_CORE_pilot_PSD.m
%
% PURPOSE
% -------
% Compute a pilot continuous-EEG PSD prototype from the manually curated
% K=6 CORE STUDY.
%
% This script:
% 1. Loads the CORE STUDY and the 52-member CORE membership table.
% 2. Computes Welch PSD from each retained IC activation.
% 3. Resolves ICA scale indeterminacy by multiplying each activation by the
%    RMS of its scalp projection map before PSD estimation.
% 4. Never concatenates data across EEGLAB boundary events.
% 5. Averages multiple ICs in the same Dataset x Cluster in LINEAR power.
% 6. Exports theta, mu, beta, low-beta and high-beta band power.
% 7. Creates subject-level and cluster-level QC summaries and figures.
%
% IMPORTANT INTERPRETATION
% ------------------------
% This is a PILOT / METHOD-VALIDATION analysis only.
% - Original session labels are preserved.
% - No Assistive/Resistive/Transparent mapping is assumed.
% - No condition statistics are performed.
% - No gait-event alignment is performed.
% - Final PSD must be rerun after all participants and the final STUDY are
%   available.
%
% The script does NOT modify:
% - EEG.data
% - ICA decompositions
% - the CORE STUDY
% - cluster membership
%
% OUTPUT
% ------
% output_data/13_pilot-PSD-k06-CORE/
%   HipExo_k06_CORE_IC_level_bandpower.csv
%   HipExo_k06_CORE_dataset_cluster_bandpower.csv
%   HipExo_k06_CORE_dataset_cluster_PSD_long.csv
%   HipExo_k06_CORE_subject_cluster_bandpower_QC.csv
%   HipExo_k06_CORE_subject_cluster_PSD_long_QC.csv
%   HipExo_k06_CORE_cluster_PSD_QC_summary.csv
%   HipExo_k06_CORE_pilot_PSD_results.mat
%   HipExo_k06_CORE_pilot_PSD_settings.txt
%   figures/*.png

clear;
clc;
close all;

%% ========================================================================
%  PATHS
%  ========================================================================

projectFolder = ...
    '/Users/dydan/master_thesis/HipExo-EEG-Study/eeg_preprocessing';

eeglabFolder = ...
    '/Users/dydan/master_thesis/eeglab2026.0.0';

outputDataFolder = fullfile(projectFolder, 'output_data');

coreStudyFolder = fullfile( ...
    outputDataFolder, ...
    '11_curated-STUDY_k06');

coreStudyFilename = ...
    'HipExo_manual_IC_Yes_only_spatial_clustered_k06_CORE.study';

coreMembershipFilename = ...
    'HipExo_k06_CORE_membership.csv';

resultFolder = fullfile( ...
    outputDataFolder, ...
    '13_pilot-PSD-k06-CORE');

figureFolder = fullfile(resultFolder, 'figures');

if ~isfolder(resultFolder)
    mkdir(resultFolder);
end

if ~isfolder(figureFolder)
    mkdir(figureFolder);
end

coreStudyPath = fullfile(coreStudyFolder, coreStudyFilename);
coreMembershipPath = fullfile( ...
    coreStudyFolder, ...
    coreMembershipFilename);

if ~isfile(coreStudyPath)
    error('CORE STUDY was not found:\n%s', coreStudyPath);
end

if ~isfile(coreMembershipPath)
    error('CORE membership CSV was not found:\n%s', ...
        coreMembershipPath);
end

%% ========================================================================
%  PSD SETTINGS
%  ========================================================================

% Four-second windows provide approximately 0.25-Hz frequency resolution
% at 250 Hz when nfft = 1024.
windowLengthSec = 4.0;

% Consecutive Welch windows overlap by 50%.
overlapFraction = 0.50;

% Remove this amount from both sides of every continuous segment.
% This reduces edge effects around dataset boundaries and rejected portions.
edgeTrimSec = 2.0;

% Analyze all usable continuous data. Set a finite number such as 180 to
% use at most the first 180 usable seconds from each dataset.
maxUsableDurationSec = Inf;

% Minimum number of valid Welch windows required for an IC.
minimumWelchWindows = 20;

% Frequency range exported in the long-format PSD tables.
exportFrequencyRangeHz = [1 40];

% Frequency range used as the denominator for relative band power.
relativePowerReferenceHz = [3 30];

% Non-overlapping analysis bands:
% theta:     4 <= f < 8 Hz  (corresponds to nominal 4-7 Hz)
% mu:        8 <= f < 13 Hz
% beta:     13 <= f <= 30 Hz
% low beta: 13 <= f < 20 Hz
% high beta:20 <= f <= 30 Hz
thetaBandHz = [4 8];
muBandHz = [8 13];
betaBandHz = [13 30];
lowBetaBandHz = [13 20];
highBetaBandHz = [20 30];

%% ========================================================================
%  START EEGLAB
%  ========================================================================

addpath(eeglabFolder);

if isempty(which('eeglab'))
    error('EEGLAB was not found:\n%s', eeglabFolder);
end

[ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab('nogui'); %#ok<ASGLU>

fprintf('\n============================================================\n');
fprintf('K=6 CORE PILOT PSD ANALYSIS\n');
fprintf('============================================================\n');
fprintf('CORE STUDY:\n%s\n\n', coreStudyPath);
fprintf('CORE membership:\n%s\n\n', coreMembershipPath);
fprintf('Output folder:\n%s\n', resultFolder);
fprintf('============================================================\n\n');

%% ========================================================================
%  LOAD CORE STUDY AND MEMBERSHIP
%  ========================================================================

[STUDY, ALLEEG] = pop_loadstudy( ...
    'filename', coreStudyFilename, ...
    'filepath', coreStudyFolder);

membership = readtable( ...
    coreMembershipPath, ...
    'TextType', 'string', ...
    'VariableNamingRule', 'preserve');

requiredColumns = [ ...
    "ClusterIndex", ...
    "ClusterName", ...
    "DatasetIndex", ...
    "Subject", ...
    "Condition", ...
    "Session", ...
    "DatasetFilename", ...
    "IC", ...
    "ReviewerDecision"];

missingColumns = setdiff( ...
    requiredColumns, ...
    string(membership.Properties.VariableNames));

if ~isempty(missingColumns)
    error('Membership table is missing columns: %s', ...
        strjoin(missingColumns, ', '));
end

membership.ReviewerDecision = ...
    strtrim(string(membership.ReviewerDecision));

if any(membership.ReviewerDecision ~= "Keep")
    error([ ...
        'The CORE membership file contains a row whose ' ...
        'ReviewerDecision is not Keep.']);
end

membership = sortrows( ...
    membership, ...
    {'DatasetIndex', 'ClusterIndex', 'IC'});

verify_membership_against_study_local(STUDY, membership);

nMembers = height(membership);

fprintf('Verified CORE membership: %d ICs.\n', nMembers);
fprintf('Datasets represented: %d\n', ...
    numel(unique(membership.DatasetIndex)));
fprintf('Clusters represented: %d\n\n', ...
    numel(unique(membership.ClusterIndex)));

%% ========================================================================
%  COMPUTE IC-LEVEL PSD
%  ========================================================================

% The frequency vector is initialized using the first successfully analyzed
% IC. All datasets are expected to have the same post-processing sampling
% rate. If a minor difference occurs, PSD is interpolated to the first
% frequency grid.

frequencyHz = [];
icPsdLinear = [];
icWelchWindows = zeros(nMembers, 1);
icAnalyzedDurationSec = zeros(nMembers, 1);
icContinuousSegmentCount = zeros(nMembers, 1);
icSamplingRate = zeros(nMembers, 1);
icScalpMapRmsScale = nan(nMembers, 1);

% Band metrics at IC level.
icThetaPowerDb = nan(nMembers, 1);
icMuPowerDb = nan(nMembers, 1);
icBetaPowerDb = nan(nMembers, 1);
icLowBetaPowerDb = nan(nMembers, 1);
icHighBetaPowerDb = nan(nMembers, 1);

icThetaRelativePct = nan(nMembers, 1);
icMuRelativePct = nan(nMembers, 1);
icBetaRelativePct = nan(nMembers, 1);
icLowBetaRelativePct = nan(nMembers, 1);
icHighBetaRelativePct = nan(nMembers, 1);

icMuPeakFrequencyHz = nan(nMembers, 1);
icMuPeakPsdDb = nan(nMembers, 1);

currentDatasetIndex = NaN;
currentEEG = [];

for memberIndex = 1:nMembers

    datasetIndex = double(membership.DatasetIndex(memberIndex));
    componentIndex = double(membership.IC(memberIndex));

    if datasetIndex ~= currentDatasetIndex

        currentEEG = load_full_study_dataset_local( ...
            STUDY, ...
            ALLEEG, ...
            datasetIndex);

        currentDatasetIndex = datasetIndex;

        expectedFilename = ...
            string(membership.DatasetFilename(memberIndex));

        if string(currentEEG.filename) ~= expectedFilename
            error([ ...
                'Dataset filename mismatch for DatasetIndex %d.\n' ...
                'Membership: %s\nLoaded: %s'], ...
                datasetIndex, ...
                expectedFilename, ...
                string(currentEEG.filename));
        end

        fprintf('\nDataset %02d/%02d: %s\n', ...
            datasetIndex, ...
            numel(STUDY.datasetinfo), ...
            currentEEG.filename);
        fprintf('  Subject: %s | Condition: %s\n', ...
            membership.Subject(memberIndex), ...
            membership.Condition(memberIndex));
        fprintf('  Sampling rate: %.6f Hz | Samples: %d\n', ...
            currentEEG.srate, ...
            currentEEG.pnts);
    end

    if isempty(currentEEG.icaweights) || ...
            isempty(currentEEG.icasphere)
        error('Dataset %d has no ICA decomposition.', datasetIndex);
    end

    if componentIndex < 1 || ...
            componentIndex > size(currentEEG.icaweights, 1)
        error([ ...
            'Invalid IC %d for DatasetIndex %d. The dataset contains ' ...
            '%d ICA components.'], ...
            componentIndex, ...
            datasetIndex, ...
            size(currentEEG.icaweights, 1));
    end

    icActivation = compute_single_ic_activation_local( ...
        currentEEG, ...
        componentIndex);

    [ ...
        icActivation, ...
        scalpMapRmsScale ...
    ] = normalize_ic_activation_scale_local( ...
        currentEEG, ...
        componentIndex, ...
        icActivation);

    icScalpMapRmsScale(memberIndex) = scalpMapRmsScale;

    windowSamples = round(windowLengthSec * currentEEG.srate);

    continuousSegments = get_continuous_segments_local( ...
        currentEEG, ...
        edgeTrimSec, ...
        windowSamples, ...
        maxUsableDurationSec);

    [ ...
        memberPsdLinear, ...
        memberFrequencyHz, ...
        nWelchWindows, ...
        analyzedDurationSec ...
    ] = compute_welch_psd_across_segments_local( ...
        icActivation, ...
        continuousSegments, ...
        currentEEG.srate, ...
        windowLengthSec, ...
        overlapFraction);

    if nWelchWindows < minimumWelchWindows
        error([ ...
            'Dataset %d IC %d produced only %d valid Welch windows. ' ...
            'Minimum required: %d.'], ...
            datasetIndex, ...
            componentIndex, ...
            nWelchWindows, ...
            minimumWelchWindows);
    end

    if isempty(frequencyHz)

        exportMask = ...
            memberFrequencyHz >= exportFrequencyRangeHz(1) & ...
            memberFrequencyHz <= exportFrequencyRangeHz(2);

        frequencyHz = memberFrequencyHz(exportMask);
        icPsdLinear = nan(nMembers, numel(frequencyHz));

    else

        exportMask = ...
            memberFrequencyHz >= exportFrequencyRangeHz(1) & ...
            memberFrequencyHz <= exportFrequencyRangeHz(2);
    end

    memberFrequencyExport = memberFrequencyHz(exportMask);
    memberPsdExport = memberPsdLinear(exportMask);

    if numel(memberFrequencyExport) ~= numel(frequencyHz) || ...
            max(abs(memberFrequencyExport - frequencyHz)) > 1e-8

        memberPsdExport = interp1( ...
            memberFrequencyExport, ...
            memberPsdExport, ...
            frequencyHz, ...
            'linear', ...
            NaN);
    end

    icPsdLinear(memberIndex, :) = memberPsdExport;

    icWelchWindows(memberIndex) = nWelchWindows;
    icAnalyzedDurationSec(memberIndex) = analyzedDurationSec;
    icContinuousSegmentCount(memberIndex) = ...
        size(continuousSegments, 1);
    icSamplingRate(memberIndex) = currentEEG.srate;

    metrics = compute_band_metrics_local( ...
        frequencyHz, ...
        memberPsdExport, ...
        relativePowerReferenceHz, ...
        thetaBandHz, ...
        muBandHz, ...
        betaBandHz, ...
        lowBetaBandHz, ...
        highBetaBandHz);

    icThetaPowerDb(memberIndex) = metrics.ThetaPowerDb;
    icMuPowerDb(memberIndex) = metrics.MuPowerDb;
    icBetaPowerDb(memberIndex) = metrics.BetaPowerDb;
    icLowBetaPowerDb(memberIndex) = metrics.LowBetaPowerDb;
    icHighBetaPowerDb(memberIndex) = metrics.HighBetaPowerDb;

    icThetaRelativePct(memberIndex) = metrics.ThetaRelativePct;
    icMuRelativePct(memberIndex) = metrics.MuRelativePct;
    icBetaRelativePct(memberIndex) = metrics.BetaRelativePct;
    icLowBetaRelativePct(memberIndex) = ...
        metrics.LowBetaRelativePct;
    icHighBetaRelativePct(memberIndex) = ...
        metrics.HighBetaRelativePct;

    icMuPeakFrequencyHz(memberIndex) = metrics.MuPeakFrequencyHz;
    icMuPeakPsdDb(memberIndex) = metrics.MuPeakPsdDb;

    fprintf([ ...
        '  Cls %d | IC %d | %.1f s | %d windows | ' ...
        'theta %.2f dB | mu %.2f dB | beta %.2f dB\n'], ...
        double(membership.ClusterIndex(memberIndex)), ...
        componentIndex, ...
        analyzedDurationSec, ...
        nWelchWindows, ...
        metrics.ThetaPowerDb, ...
        metrics.MuPowerDb, ...
        metrics.BetaPowerDb);
end

%% ========================================================================
%  IC-LEVEL OUTPUT TABLE
%  ========================================================================

icBandpowerTable = membership(:, { ...
    'ClusterIndex', ...
    'ClusterName', ...
    'DatasetIndex', ...
    'Subject', ...
    'Condition', ...
    'Session', ...
    'DatasetFilename', ...
    'IC'});

icBandpowerTable.SamplingRate_Hz = icSamplingRate;
icBandpowerTable.ScalpMapRMSScale = icScalpMapRmsScale;
icBandpowerTable.AnalyzedDuration_s = icAnalyzedDurationSec;
icBandpowerTable.ContinuousSegments = ...
    icContinuousSegmentCount;
icBandpowerTable.WelchWindows = icWelchWindows;

icBandpowerTable.Theta_4to7_dB_uV2 = icThetaPowerDb;
icBandpowerTable.Mu_8to13_dB_uV2 = icMuPowerDb;
icBandpowerTable.Beta_13to30_dB_uV2 = icBetaPowerDb;
icBandpowerTable.LowBeta_13to20_dB_uV2 = ...
    icLowBetaPowerDb;
icBandpowerTable.HighBeta_20to30_dB_uV2 = ...
    icHighBetaPowerDb;

icBandpowerTable.ThetaRelative_3to30_pct = ...
    icThetaRelativePct;
icBandpowerTable.MuRelative_3to30_pct = ...
    icMuRelativePct;
icBandpowerTable.BetaRelative_3to30_pct = ...
    icBetaRelativePct;
icBandpowerTable.LowBetaRelative_3to30_pct = ...
    icLowBetaRelativePct;
icBandpowerTable.HighBetaRelative_3to30_pct = ...
    icHighBetaRelativePct;

icBandpowerTable.MuPeakFrequency_Hz = ...
    icMuPeakFrequencyHz;
icBandpowerTable.MuPeakPSD_dB_uV2_per_Hz = ...
    icMuPeakPsdDb;

writetable( ...
    icBandpowerTable, ...
    fullfile( ...
        resultFolder, ...
        'HipExo_k06_CORE_IC_level_bandpower.csv'));

%% ========================================================================
%  DATASET x CLUSTER AGGREGATION
%  ========================================================================

% Multiple ICs from the same dataset and cluster are averaged here in
% LINEAR PSD. They are not treated as independent observations.

datasetClusterKeys = unique( ...
    [ ...
        double(membership.DatasetIndex), ...
        double(membership.ClusterIndex) ...
    ], ...
    'rows', ...
    'stable');

nDatasetClusterRows = size(datasetClusterKeys, 1);
datasetClusterPsdLinear = nan( ...
    nDatasetClusterRows, ...
    numel(frequencyHz));

datasetClusterBandRows = cell(nDatasetClusterRows, 26);

for rowIndex = 1:nDatasetClusterRows

    datasetIndex = datasetClusterKeys(rowIndex, 1);
    clusterIndex = datasetClusterKeys(rowIndex, 2);

    memberMask = ...
        double(membership.DatasetIndex) == datasetIndex & ...
        double(membership.ClusterIndex) == clusterIndex;

    sourceRows = find(memberMask);

    aggregatedPsd = mean( ...
        icPsdLinear(memberMask, :), ...
        1, ...
        'omitnan');

    datasetClusterPsdLinear(rowIndex, :) = aggregatedPsd;

    metrics = compute_band_metrics_local( ...
        frequencyHz, ...
        aggregatedPsd, ...
        relativePowerReferenceHz, ...
        thetaBandHz, ...
        muBandHz, ...
        betaBandHz, ...
        lowBetaBandHz, ...
        highBetaBandHz);

    datasetClusterBandRows(rowIndex, :) = { ...
        clusterIndex, ...
        membership.ClusterName(sourceRows(1)), ...
        datasetIndex, ...
        membership.Subject(sourceRows(1)), ...
        membership.Condition(sourceRows(1)), ...
        double(membership.Session(sourceRows(1))), ...
        membership.DatasetFilename(sourceRows(1)), ...
        numel(sourceRows), ...
        strjoin(string(sort(double(membership.IC(sourceRows)))), ', '), ...
        mean(icAnalyzedDurationSec(sourceRows), 'omitnan'), ...
        sum(icWelchWindows(sourceRows)), ...
        metrics.ThetaPowerDb, ...
        metrics.MuPowerDb, ...
        metrics.BetaPowerDb, ...
        metrics.LowBetaPowerDb, ...
        metrics.HighBetaPowerDb, ...
        metrics.ThetaRelativePct, ...
        metrics.MuRelativePct, ...
        metrics.BetaRelativePct, ...
        metrics.LowBetaRelativePct, ...
        metrics.HighBetaRelativePct, ...
        metrics.MuPeakFrequencyHz, ...
        metrics.MuPeakPsdDb, ...
        "Average of IC PSDs in linear power", ...
        "Original session label; no experimental mapping applied", ...
        "Pilot QC only" ...
    };
end

datasetClusterBandpowerTable = cell2table( ...
    datasetClusterBandRows, ...
    'VariableNames', { ...
        'ClusterIndex', ...
        'ClusterName', ...
        'DatasetIndex', ...
        'Subject', ...
        'OriginalCondition', ...
        'Session', ...
        'DatasetFilename', ...
        'N_IC_Averaged', ...
        'IC_List', ...
        'MeanAnalyzedDuration_s', ...
        'TotalICWelchWindows', ...
        'Theta_4to7_dB_uV2', ...
        'Mu_8to13_dB_uV2', ...
        'Beta_13to30_dB_uV2', ...
        'LowBeta_13to20_dB_uV2', ...
        'HighBeta_20to30_dB_uV2', ...
        'ThetaRelative_3to30_pct', ...
        'MuRelative_3to30_pct', ...
        'BetaRelative_3to30_pct', ...
        'LowBetaRelative_3to30_pct', ...
        'HighBetaRelative_3to30_pct', ...
        'MuPeakFrequency_Hz', ...
        'MuPeakPSD_dB_uV2_per_Hz', ...
        'ICAggregation', ...
        'ConditionHandling', ...
        'AnalysisStatus'});

writetable( ...
    datasetClusterBandpowerTable, ...
    fullfile( ...
        resultFolder, ...
        'HipExo_k06_CORE_dataset_cluster_bandpower.csv'));

datasetClusterPsdLongTable = build_psd_long_table_local( ...
    datasetClusterBandpowerTable(:, { ...
        'ClusterIndex', ...
        'ClusterName', ...
        'DatasetIndex', ...
        'Subject', ...
        'OriginalCondition', ...
        'Session', ...
        'DatasetFilename', ...
        'N_IC_Averaged'}), ...
    frequencyHz, ...
    datasetClusterPsdLinear);

writetable( ...
    datasetClusterPsdLongTable, ...
    fullfile( ...
        resultFolder, ...
        'HipExo_k06_CORE_dataset_cluster_PSD_long.csv'));

%% ========================================================================
%  SUBJECT x CLUSTER QC AGGREGATION
%  ========================================================================

% For visualization only, sessions are first averaged within each
% Subject x Cluster. This prevents a subject with more retained sessions
% from dominating the cluster QC mean.
%
% These rows are NOT condition-comparison results.

subjectStrings = string( ...
    datasetClusterBandpowerTable.Subject);

subjectClusterKeyStrings = ...
    subjectStrings + "__" + ...
    string(datasetClusterBandpowerTable.ClusterIndex);

[uniqueSubjectClusterKeys, firstKeyRows] = unique( ...
    subjectClusterKeyStrings, ...
    'stable');

nSubjectClusterRows = numel(uniqueSubjectClusterKeys);
subjectClusterPsdLinear = nan( ...
    nSubjectClusterRows, ...
    numel(frequencyHz));

subjectClusterBandRows = cell( ...
    nSubjectClusterRows, ...
    21);

for rowIndex = 1:nSubjectClusterRows

    key = uniqueSubjectClusterKeys(rowIndex);
    sourceMask = subjectClusterKeyStrings == key;
    sourceRows = find(sourceMask);
    firstRow = firstKeyRows(rowIndex);

    aggregatedPsd = mean( ...
        datasetClusterPsdLinear(sourceMask, :), ...
        1, ...
        'omitnan');

    subjectClusterPsdLinear(rowIndex, :) = ...
        aggregatedPsd;

    metrics = compute_band_metrics_local( ...
        frequencyHz, ...
        aggregatedPsd, ...
        relativePowerReferenceHz, ...
        thetaBandHz, ...
        muBandHz, ...
        betaBandHz, ...
        lowBetaBandHz, ...
        highBetaBandHz);

    subjectClusterBandRows(rowIndex, :) = { ...
        datasetClusterBandpowerTable.ClusterIndex(firstRow), ...
        datasetClusterBandpowerTable.ClusterName(firstRow), ...
        datasetClusterBandpowerTable.Subject(firstRow), ...
        sum(sourceMask), ...
        strjoin( ...
            string(datasetClusterBandpowerTable.OriginalCondition(sourceRows)), ...
            ' | '), ...
        metrics.ThetaPowerDb, ...
        metrics.MuPowerDb, ...
        metrics.BetaPowerDb, ...
        metrics.LowBetaPowerDb, ...
        metrics.HighBetaPowerDb, ...
        metrics.ThetaRelativePct, ...
        metrics.MuRelativePct, ...
        metrics.BetaRelativePct, ...
        metrics.LowBetaRelativePct, ...
        metrics.HighBetaRelativePct, ...
        metrics.MuPeakFrequencyHz, ...
        metrics.MuPeakPsdDb, ...
        "Equal average across available original sessions", ...
        "No condition inference", ...
        "Subject-level cluster QC", ...
        "Pilot only" ...
    };
end

subjectClusterBandpowerTable = cell2table( ...
    subjectClusterBandRows, ...
    'VariableNames', { ...
        'ClusterIndex', ...
        'ClusterName', ...
        'Subject', ...
        'N_DatasetClusterRows', ...
        'OriginalConditionsIncluded', ...
        'Theta_4to7_dB_uV2', ...
        'Mu_8to13_dB_uV2', ...
        'Beta_13to30_dB_uV2', ...
        'LowBeta_13to20_dB_uV2', ...
        'HighBeta_20to30_dB_uV2', ...
        'ThetaRelative_3to30_pct', ...
        'MuRelative_3to30_pct', ...
        'BetaRelative_3to30_pct', ...
        'LowBetaRelative_3to30_pct', ...
        'HighBetaRelative_3to30_pct', ...
        'MuPeakFrequency_Hz', ...
        'MuPeakPSD_dB_uV2_per_Hz', ...
        'SessionAggregation', ...
        'ConditionHandling', ...
        'AnalysisLevel', ...
        'AnalysisStatus'});

writetable( ...
    subjectClusterBandpowerTable, ...
    fullfile( ...
        resultFolder, ...
        'HipExo_k06_CORE_subject_cluster_bandpower_QC.csv'));

subjectClusterPsdLongTable = build_psd_long_table_local( ...
    subjectClusterBandpowerTable(:, { ...
        'ClusterIndex', ...
        'ClusterName', ...
        'Subject', ...
        'N_DatasetClusterRows'}), ...
    frequencyHz, ...
    subjectClusterPsdLinear);

writetable( ...
    subjectClusterPsdLongTable, ...
    fullfile( ...
        resultFolder, ...
        'HipExo_k06_CORE_subject_cluster_PSD_long_QC.csv'));

%% ========================================================================
%  CLUSTER-LEVEL EQUAL-SUBJECT QC SUMMARY AND FIGURES
%  ========================================================================

clusterIndices = unique( ...
    double(subjectClusterBandpowerTable.ClusterIndex), ...
    'stable');

clusterSummaryRows = cell(numel(clusterIndices), 24);

for clusterCounter = 1:numel(clusterIndices)

    clusterIndex = clusterIndices(clusterCounter);

    subjectMask = ...
        double(subjectClusterBandpowerTable.ClusterIndex) == ...
        clusterIndex;

    sourceRows = find(subjectMask);

    equalSubjectMeanPsd = mean( ...
        subjectClusterPsdLinear(subjectMask, :), ...
        1, ...
        'omitnan');

    metrics = compute_band_metrics_local( ...
        frequencyHz, ...
        equalSubjectMeanPsd, ...
        relativePowerReferenceHz, ...
        thetaBandHz, ...
        muBandHz, ...
        betaBandHz, ...
        lowBetaBandHz, ...
        highBetaBandHz);

    clusterDatasetMask = ...
        double(datasetClusterBandpowerTable.ClusterIndex) == ...
        clusterIndex;

    clusterIcMask = ...
        double(membership.ClusterIndex) == ...
        clusterIndex;

    subjects = string( ...
        subjectClusterBandpowerTable.Subject(subjectMask));

    clusterSummaryRows(clusterCounter, :) = { ...
        clusterIndex, ...
        subjectClusterBandpowerTable.ClusterName(sourceRows(1)), ...
        sum(clusterIcMask), ...
        sum(clusterDatasetMask), ...
        sum(subjectMask), ...
        strjoin(subjects, ', '), ...
        metrics.ThetaPowerDb, ...
        metrics.MuPowerDb, ...
        metrics.BetaPowerDb, ...
        metrics.LowBetaPowerDb, ...
        metrics.HighBetaPowerDb, ...
        metrics.ThetaRelativePct, ...
        metrics.MuRelativePct, ...
        metrics.BetaRelativePct, ...
        metrics.LowBetaRelativePct, ...
        metrics.HighBetaRelativePct, ...
        metrics.MuPeakFrequencyHz, ...
        metrics.MuPeakPsdDb, ...
        "Equal-subject mean", ...
        "Sessions averaged within subject before cluster mean", ...
        "No condition statistics", ...
        "No gait-event alignment", ...
        "Pilot method validation", ...
        "Do not interpret as final group result" ...
    };

    create_cluster_qc_figure_local( ...
        frequencyHz, ...
        subjectClusterPsdLinear(subjectMask, :), ...
        subjects, ...
        clusterIndex, ...
        subjectClusterBandpowerTable.ClusterName(sourceRows(1)), ...
        figureFolder);
end

clusterSummaryTable = cell2table( ...
    clusterSummaryRows, ...
    'VariableNames', { ...
        'ClusterIndex', ...
        'ClusterName', ...
        'N_IC', ...
        'N_DatasetClusterRows', ...
        'N_Subjects', ...
        'Subjects', ...
        'Theta_4to7_dB_uV2', ...
        'Mu_8to13_dB_uV2', ...
        'Beta_13to30_dB_uV2', ...
        'LowBeta_13to20_dB_uV2', ...
        'HighBeta_20to30_dB_uV2', ...
        'ThetaRelative_3to30_pct', ...
        'MuRelative_3to30_pct', ...
        'BetaRelative_3to30_pct', ...
        'LowBetaRelative_3to30_pct', ...
        'HighBetaRelative_3to30_pct', ...
        'MuPeakFrequency_Hz', ...
        'MuPeakPSD_dB_uV2_per_Hz', ...
        'SubjectWeighting', ...
        'WithinSubjectAggregation', ...
        'ConditionStatistics', ...
        'GaitAlignment', ...
        'AnalysisStatus', ...
        'InterpretationWarning'});

writetable( ...
    clusterSummaryTable, ...
    fullfile( ...
        resultFolder, ...
        'HipExo_k06_CORE_cluster_PSD_QC_summary.csv'));

%% ========================================================================
%  SAVE MAT FILE AND SETTINGS
%  ========================================================================

save( ...
    fullfile( ...
        resultFolder, ...
        'HipExo_k06_CORE_pilot_PSD_results.mat'), ...
    'STUDY', ...
    'membership', ...
    'frequencyHz', ...
    'icPsdLinear', ...
    'icBandpowerTable', ...
    'datasetClusterPsdLinear', ...
    'datasetClusterBandpowerTable', ...
    'datasetClusterPsdLongTable', ...
    'subjectClusterPsdLinear', ...
    'subjectClusterBandpowerTable', ...
    'subjectClusterPsdLongTable', ...
    'clusterSummaryTable', ...
    'windowLengthSec', ...
    'overlapFraction', ...
    'edgeTrimSec', ...
    'maxUsableDurationSec', ...
    'minimumWelchWindows', ...
    'exportFrequencyRangeHz', ...
    'relativePowerReferenceHz', ...
    'thetaBandHz', ...
    'muBandHz', ...
    'betaBandHz', ...
    'lowBetaBandHz', ...
    'highBetaBandHz', ...
    '-v7.3');

write_settings_file_local( ...
    fullfile( ...
        resultFolder, ...
        'HipExo_k06_CORE_pilot_PSD_settings.txt'), ...
    coreStudyPath, ...
    coreMembershipPath, ...
    windowLengthSec, ...
    overlapFraction, ...
    edgeTrimSec, ...
    maxUsableDurationSec, ...
    minimumWelchWindows, ...
    exportFrequencyRangeHz, ...
    relativePowerReferenceHz, ...
    thetaBandHz, ...
    muBandHz, ...
    betaBandHz, ...
    lowBetaBandHz, ...
    highBetaBandHz);

%% ========================================================================
%  FINAL DISPLAY
%  ========================================================================

fprintf('\n============================================================\n');
fprintf('K=6 CORE PILOT PSD ANALYSIS COMPLETED\n');
fprintf('============================================================\n');
fprintf('IC-level rows: %d\n', height(icBandpowerTable));
fprintf('Dataset x Cluster rows: %d\n', ...
    height(datasetClusterBandpowerTable));
fprintf('Subject x Cluster QC rows: %d\n', ...
    height(subjectClusterBandpowerTable));
fprintf('Clusters summarized: %d\n\n', ...
    height(clusterSummaryTable));

fprintf('Output folder:\n%s\n\n', resultFolder);

fprintf('Primary pilot-QC outputs:\n');
fprintf('  HipExo_k06_CORE_dataset_cluster_bandpower.csv\n');
fprintf('  HipExo_k06_CORE_dataset_cluster_PSD_long.csv\n');
fprintf('  HipExo_k06_CORE_cluster_PSD_QC_summary.csv\n');
fprintf('  figures/\n');
fprintf('============================================================\n\n');

disp('Cluster-level equal-subject PSD QC summary:');
disp(clusterSummaryTable);

%% ========================================================================
%  LOCAL FUNCTIONS
%  ========================================================================

function verify_membership_against_study_local(STUDY, membership)

    memberKeys = ...
        string(membership.DatasetIndex) + "_" + ...
        string(membership.IC);

    if numel(unique(memberKeys)) ~= height(membership)
        error('Membership contains duplicate DatasetIndex-IC pairs.');
    end

    clusterIndices = unique( ...
        double(membership.ClusterIndex), ...
        'stable');

    for clusterIndex = reshape(clusterIndices, 1, [])

        rows = membership( ...
            double(membership.ClusterIndex) == clusterIndex, :);

        expectedPairs = sortrows( ...
            [ ...
                double(rows.DatasetIndex), ...
                double(rows.IC) ...
            ], ...
            [1 2]);

        actualPairs = sortrows( ...
            [ ...
                double(STUDY.cluster(clusterIndex).sets(:)), ...
                double(STUDY.cluster(clusterIndex).comps(:)) ...
            ], ...
            [1 2]);

        if ~isequal(expectedPairs, actualPairs)
            error([ ...
                'Membership CSV does not match CORE STUDY ' ...
                'cluster %d.'], ...
                clusterIndex);
        end
    end
end

function EEG = load_full_study_dataset_local( ...
        STUDY, ...
        ALLEEG, ...
        datasetIndex)

    expectedFilename = string( ...
        STUDY.datasetinfo(datasetIndex).filename);

    EEG = [];

    if datasetIndex <= numel(ALLEEG)

        candidate = ALLEEG(datasetIndex);

        if string(candidate.filename) == expectedFilename
            EEG = candidate;
        end
    end

    dataAreLoaded = ...
        ~isempty(EEG) && ...
        isnumeric(EEG.data) && ...
        ~isempty(EEG.data);

    if dataAreLoaded
        return;
    end

    datasetFilepath = string( ...
        STUDY.datasetinfo(datasetIndex).filepath);

    if datasetFilepath == ""
        error('Dataset %d has an empty filepath in STUDY.', ...
            datasetIndex);
    end

    fullDatasetPath = fullfile( ...
        datasetFilepath, ...
        expectedFilename);

    if ~isfile(fullDatasetPath)
        error('Dataset file was not found:\n%s', ...
            fullDatasetPath);
    end

    EEG = pop_loadset( ...
        'filename', char(expectedFilename), ...
        'filepath', char(datasetFilepath), ...
        'loadmode', 'all');

    EEG = eeg_checkset(EEG);
end

function activation = compute_single_ic_activation_local( ...
        EEG, ...
        componentIndex)

    data = double(reshape( ...
        EEG.data, ...
        EEG.nbchan, ...
        []));

    if isempty(EEG.icachansind)

        nIcaChannels = size(EEG.icasphere, 2);

        if nIcaChannels > size(data, 1)
            error('ICA channel count exceeds EEG channel count.');
        end

        icaChannelIndices = 1:nIcaChannels;

    else

        icaChannelIndices = double(EEG.icachansind(:))';
    end

    if any(icaChannelIndices < 1) || ...
            any(icaChannelIndices > size(data, 1))
        error('EEG.icachansind contains invalid channel indices.');
    end

    unmixingRow = ...
        double(EEG.icaweights(componentIndex, :)) * ...
        double(EEG.icasphere);

    activation = unmixingRow * ...
        data(icaChannelIndices, :);

    activation = double(activation(:)');
end

function [normalizedActivation, scalpMapRmsScale] = ...
        normalize_ic_activation_scale_local( ...
            EEG, ...
            componentIndex, ...
            activation)

    if isempty(EEG.icawinv)
        error('EEG.icawinv is empty; IC scale normalization is impossible.');
    end

    if componentIndex > size(EEG.icawinv, 2)
        error('IC %d exceeds EEG.icawinv column count.', componentIndex);
    end

    scalpMap = double(EEG.icawinv(:, componentIndex));

    validValues = scalpMap(isfinite(scalpMap));

    if isempty(validValues)
        error('IC %d scalp map contains no finite values.', componentIndex);
    end

    scalpMapRmsScale = sqrt(mean(validValues .^ 2));

    if ~isfinite(scalpMapRmsScale) || scalpMapRmsScale <= 0
        error('IC %d has an invalid scalp-map RMS scale.', componentIndex);
    end

    % ICA has an arbitrary component scaling: multiplying an activation by
    % c and dividing its scalp map by c leaves the sensor projection
    % unchanged. Multiplying the activation by RMS(icawinv(:,IC)) produces
    % a scale-invariant activation whose magnitude represents the RMS
    % sensor-space projection of that IC.
    normalizedActivation = ...
        double(activation) * scalpMapRmsScale;
end

function segments = get_continuous_segments_local( ...
        EEG, ...
        edgeTrimSec, ...
        minimumSegmentSamples, ...
        maxUsableDurationSec)

    nSamples = EEG.pnts * EEG.trials;

    boundaryLatencies = [];

    for eventIndex = 1:numel(EEG.event)

        eventType = EEG.event(eventIndex).type;

        while iscell(eventType) && numel(eventType) == 1
            eventType = eventType{1};
        end

        isBoundary = false;

        if ischar(eventType) || isstring(eventType)
            isBoundary = strcmpi( ...
                strtrim(string(eventType)), ...
                "boundary");
        end

        if ~isBoundary
            continue;
        end

        latency = double(EEG.event(eventIndex).latency);

        if isfinite(latency)
            boundaryLatencies(end+1) = latency; %#ok<AGROW>
        end
    end

    if isempty(boundaryLatencies)

        rawSegments = [1 nSamples];

    else

        splitSamples = unique( ...
            floor(boundaryLatencies));

        splitSamples = splitSamples( ...
            splitSamples >= 1 & ...
            splitSamples < nSamples);

        rawSegments = [ ...
            [1; splitSamples(:) + 1], ...
            [splitSamples(:); nSamples] ...
        ];
    end

    trimSamples = round(edgeTrimSec * EEG.srate);

    rawSegments(:, 1) = ...
        rawSegments(:, 1) + trimSamples;

    rawSegments(:, 2) = ...
        rawSegments(:, 2) - trimSamples;

    segmentLengths = ...
        rawSegments(:, 2) - ...
        rawSegments(:, 1) + 1;

    rawSegments = rawSegments( ...
        segmentLengths >= minimumSegmentSamples, :);

    if isempty(rawSegments)
        error([ ...
            'No continuous segment remains after boundary splitting ' ...
            'and edge trimming.']);
    end

    if isinf(maxUsableDurationSec)
        segments = rawSegments;
        return;
    end

    maximumSamples = round( ...
        maxUsableDurationSec * EEG.srate);

    segments = zeros(0, 2);
    usedSamples = 0;

    for segmentIndex = 1:size(rawSegments, 1)

        if usedSamples >= maximumSamples
            break;
        end

        startSample = rawSegments(segmentIndex, 1);
        endSample = rawSegments(segmentIndex, 2);

        availableSamples = ...
            endSample - startSample + 1;

        remainingSamples = ...
            maximumSamples - usedSamples;

        takeSamples = min( ...
            availableSamples, ...
            remainingSamples);

        if takeSamples < minimumSegmentSamples
            continue;
        end

        segments(end+1, :) = [ ... %#ok<AGROW>
            startSample, ...
            startSample + takeSamples - 1];

        usedSamples = usedSamples + takeSamples;
    end

    if isempty(segments)
        error('No segment satisfies maxUsableDurationSec.');
    end
end

function [ ...
        psdLinear, ...
        frequencyHz, ...
        numberOfWindows, ...
        analyzedDurationSec ...
    ] = compute_welch_psd_across_segments_local( ...
        signal, ...
        segments, ...
        samplingRate, ...
        windowLengthSec, ...
        overlapFraction)

    windowSamples = round( ...
        windowLengthSec * samplingRate);

    overlapSamples = round( ...
        overlapFraction * windowSamples);

    stepSamples = windowSamples - overlapSamples;

    if windowSamples < 4
        error('Welch window is too short.');
    end

    if stepSamples < 1
        error('Welch overlap leaves a non-positive step size.');
    end

    nfft = 2 ^ nextpow2(windowSamples);

    sampleIndex = (0:windowSamples-1)';

    if windowSamples == 1
        analysisWindow = 1;
    else
        analysisWindow = ...
            0.5 - ...
            0.5 * cos( ...
                2 * pi * sampleIndex / ...
                (windowSamples - 1));
    end

    windowEnergy = sum(analysisWindow .^ 2);

    positiveFrequencyCount = ...
        floor(nfft / 2) + 1;

    psdSum = zeros( ...
        positiveFrequencyCount, ...
        1);

    numberOfWindows = 0;
    analyzedSampleCount = 0;

    signal = double(signal(:));

    for segmentIndex = 1:size(segments, 1)

        startSample = segments(segmentIndex, 1);
        endSample = segments(segmentIndex, 2);

        segment = signal(startSample:endSample);
        segmentLength = numel(segment);

        frameStarts = ...
            1:stepSamples:(segmentLength - windowSamples + 1);

        for frameStart = frameStarts

            frame = segment( ...
                frameStart: ...
                frameStart + windowSamples - 1);

            if any(~isfinite(frame))
                continue;
            end

            frame = detrend(frame, 'linear');
            frame = frame .* analysisWindow;

            spectrum = fft(frame, nfft);

            twoSidedPsd = ...
                abs(spectrum) .^ 2 ./ ...
                (samplingRate * windowEnergy);

            oneSidedPsd = ...
                twoSidedPsd(1:positiveFrequencyCount);

            if rem(nfft, 2) == 0

                if numel(oneSidedPsd) > 2
                    oneSidedPsd(2:end-1) = ...
                        2 * oneSidedPsd(2:end-1);
                end

            else

                if numel(oneSidedPsd) > 1
                    oneSidedPsd(2:end) = ...
                        2 * oneSidedPsd(2:end);
                end
            end

            psdSum = psdSum + oneSidedPsd;
            numberOfWindows = numberOfWindows + 1;
        end

        analyzedSampleCount = ...
            analyzedSampleCount + segmentLength;
    end

    if numberOfWindows == 0
        error('No valid Welch windows were produced.');
    end

    psdLinear = ...
        psdSum ./ numberOfWindows;

    frequencyHz = ...
        (0:positiveFrequencyCount-1)' * ...
        samplingRate / nfft;

    analyzedDurationSec = ...
        analyzedSampleCount / samplingRate;
end

function metrics = compute_band_metrics_local( ...
        frequencyHz, ...
        psdLinear, ...
        referenceBandHz, ...
        thetaBandHz, ...
        muBandHz, ...
        betaBandHz, ...
        lowBetaBandHz, ...
        highBetaBandHz)

    frequencyHz = double(frequencyHz(:));
    psdLinear = double(psdLinear(:));

    referencePower = integrate_band_local( ...
        frequencyHz, ...
        psdLinear, ...
        referenceBandHz, ...
        true);

    thetaPower = integrate_band_local( ...
        frequencyHz, ...
        psdLinear, ...
        thetaBandHz, ...
        false);

    muPower = integrate_band_local( ...
        frequencyHz, ...
        psdLinear, ...
        muBandHz, ...
        false);

    betaPower = integrate_band_local( ...
        frequencyHz, ...
        psdLinear, ...
        betaBandHz, ...
        true);

    lowBetaPower = integrate_band_local( ...
        frequencyHz, ...
        psdLinear, ...
        lowBetaBandHz, ...
        false);

    highBetaPower = integrate_band_local( ...
        frequencyHz, ...
        psdLinear, ...
        highBetaBandHz, ...
        true);

    metrics = struct();

    metrics.ThetaPowerDb = safe_db_local(thetaPower);
    metrics.MuPowerDb = safe_db_local(muPower);
    metrics.BetaPowerDb = safe_db_local(betaPower);
    metrics.LowBetaPowerDb = safe_db_local(lowBetaPower);
    metrics.HighBetaPowerDb = safe_db_local(highBetaPower);

    metrics.ThetaRelativePct = ...
        safe_relative_percent_local( ...
            thetaPower, referencePower);

    metrics.MuRelativePct = ...
        safe_relative_percent_local( ...
            muPower, referencePower);

    metrics.BetaRelativePct = ...
        safe_relative_percent_local( ...
            betaPower, referencePower);

    metrics.LowBetaRelativePct = ...
        safe_relative_percent_local( ...
            lowBetaPower, referencePower);

    metrics.HighBetaRelativePct = ...
        safe_relative_percent_local( ...
            highBetaPower, referencePower);

    muMask = ...
        frequencyHz >= muBandHz(1) & ...
        frequencyHz < muBandHz(2) & ...
        isfinite(psdLinear);

    if any(muMask)

        muFrequencies = frequencyHz(muMask);
        muPsd = psdLinear(muMask);

        [peakPower, peakIndex] = max(muPsd);

        metrics.MuPeakFrequencyHz = ...
            muFrequencies(peakIndex);

        metrics.MuPeakPsdDb = ...
            safe_db_local(peakPower);

    else

        metrics.MuPeakFrequencyHz = NaN;
        metrics.MuPeakPsdDb = NaN;
    end
end

function bandPower = integrate_band_local( ...
        frequencyHz, ...
        psdLinear, ...
        bandHz, ...
        includeUpperBoundary)

    if includeUpperBoundary

        mask = ...
            frequencyHz >= bandHz(1) & ...
            frequencyHz <= bandHz(2);

    else

        mask = ...
            frequencyHz >= bandHz(1) & ...
            frequencyHz < bandHz(2);
    end

    mask = mask & ...
        isfinite(psdLinear);

    if sum(mask) < 2
        bandPower = NaN;
        return;
    end

    bandPower = trapz( ...
        frequencyHz(mask), ...
        psdLinear(mask));
end

function valueDb = safe_db_local(valueLinear)

    if ~isfinite(valueLinear) || ...
            valueLinear <= 0

        valueDb = NaN;

    else

        valueDb = 10 * log10(valueLinear);
    end
end

function relativePercent = safe_relative_percent_local( ...
        bandPower, ...
        referencePower)

    if ~isfinite(bandPower) || ...
            ~isfinite(referencePower) || ...
            referencePower <= 0

        relativePercent = NaN;

    else

        relativePercent = ...
            100 * bandPower / referencePower;
    end
end

function longTable = build_psd_long_table_local( ...
        metadataTable, ...
        frequencyHz, ...
        psdLinearMatrix)

    nRows = height(metadataTable);
    nFrequencies = numel(frequencyHz);

    repeatedMetadata = metadataTable( ...
        repelem((1:nRows)', nFrequencies), :);

    repeatedMetadata.Frequency_Hz = repmat( ...
        frequencyHz(:), ...
        nRows, ...
        1);

    repeatedMetadata.PSD_uV2_per_Hz = reshape( ...
        psdLinearMatrix', ...
        [], ...
        1);

    repeatedMetadata.PSD_dB_uV2_per_Hz = ...
        10 * log10( ...
            repeatedMetadata.PSD_uV2_per_Hz);

    longTable = repeatedMetadata;
end

function create_cluster_qc_figure_local( ...
        frequencyHz, ...
        subjectPsdLinear, ...
        subjects, ...
        clusterIndex, ...
        clusterName, ...
        figureFolder)

    figureHandle = figure( ...
        'Visible', 'off', ...
        'Color', 'w', ...
        'Position', [100 100 1150 720]);

    hold on;

    lineHandles = gobjects(size(subjectPsdLinear, 1) + 1, 1);
    legendLabels = strings(size(subjectPsdLinear, 1) + 1, 1);

    for subjectIndex = 1:size(subjectPsdLinear, 1)

        lineHandles(subjectIndex) = plot( ...
            frequencyHz, ...
            10 * log10(subjectPsdLinear(subjectIndex, :)), ...
            'LineWidth', 1.25);

        legendLabels(subjectIndex) = ...
            subjects(subjectIndex);
    end

    equalSubjectMeanPsd = mean( ...
        subjectPsdLinear, ...
        1, ...
        'omitnan');

    lineHandles(end) = plot( ...
        frequencyHz, ...
        10 * log10(equalSubjectMeanPsd), ...
        'k-', ...
        'LineWidth', 2.75);

    legendLabels(end) = "Equal-subject mean";

    xlim([3 30]);

    xlabel('Frequency (Hz)');
    ylabel('PSD (dB \muV^2/Hz)');

    title(sprintf( ...
        'Cls %d (%s): pilot continuous PSD QC', ...
        clusterIndex, ...
        clusterName), ...
        'Interpreter', 'none');

    grid on;
    box on;

    xline(4, ':');
    xline(8, ':');
    xline(13, ':');
    xline(30, ':');

    legend( ...
        lineHandles, ...
        legendLabels, ...
        'Location', 'best', ...
        'Interpreter', 'none');

    annotation( ...
        figureHandle, ...
        'textbox', ...
        [0.13 0.01 0.74 0.06], ...
        'String', ...
        ['Pilot QC only: sessions were averaged within subject; ' ...
         'no condition mapping and no gait-event alignment.'], ...
        'EdgeColor', 'none', ...
        'HorizontalAlignment', 'center');

    outputPath = fullfile( ...
        figureFolder, ...
        sprintf( ...
            'Cls_%02d_subject_mean_continuous_PSD_QC.png', ...
            clusterIndex));

    exportgraphics( ...
        figureHandle, ...
        outputPath, ...
        'Resolution', 180);

    close(figureHandle);
end

function write_settings_file_local( ...
        outputPath, ...
        coreStudyPath, ...
        coreMembershipPath, ...
        windowLengthSec, ...
        overlapFraction, ...
        edgeTrimSec, ...
        maxUsableDurationSec, ...
        minimumWelchWindows, ...
        exportFrequencyRangeHz, ...
        relativePowerReferenceHz, ...
        thetaBandHz, ...
        muBandHz, ...
        betaBandHz, ...
        lowBetaBandHz, ...
        highBetaBandHz)

    fileId = fopen(outputPath, 'w');

    if fileId < 0
        error('Could not create settings file:\n%s', ...
            outputPath);
    end

    cleanupObject = onCleanup(@() fclose(fileId)); %#ok<NASGU>

    fprintf(fileId, 'HipExo K=6 CORE pilot continuous PSD\n');
    fprintf(fileId, '====================================\n\n');

    fprintf(fileId, 'CORE STUDY:\n%s\n\n', coreStudyPath);
    fprintf(fileId, 'CORE membership:\n%s\n\n', ...
        coreMembershipPath);

    fprintf(fileId, 'Purpose: pilot method validation only\n');
    fprintf(fileId, 'Condition mapping: not applied\n');
    fprintf(fileId, 'Condition statistics: not performed\n');
    fprintf(fileId, 'Gait-event alignment: not performed\n');
    fprintf(fileId, ...
        ['IC scale normalization: activation multiplied by ' ...
         'RMS(icawinv(:,IC)) before PSD\n\n']);

    fprintf(fileId, 'Window length: %.3f s\n', ...
        windowLengthSec);
    fprintf(fileId, 'Overlap: %.1f %%\n', ...
        100 * overlapFraction);
    fprintf(fileId, 'Edge trim per segment: %.3f s\n', ...
        edgeTrimSec);

    if isinf(maxUsableDurationSec)

        fprintf(fileId, ...
            'Maximum usable duration: all available data\n');

    else

        fprintf(fileId, ...
            'Maximum usable duration: %.3f s\n', ...
            maxUsableDurationSec);
    end

    fprintf(fileId, 'Minimum Welch windows: %d\n', ...
        minimumWelchWindows);

    fprintf(fileId, 'Exported PSD range: %.3f-%.3f Hz\n', ...
        exportFrequencyRangeHz(1), ...
        exportFrequencyRangeHz(2));

    fprintf(fileId, ...
        'Relative-power reference: %.3f-%.3f Hz\n', ...
        relativePowerReferenceHz(1), ...
        relativePowerReferenceHz(2));

    fprintf(fileId, 'Theta: %.3f <= f < %.3f Hz\n', ...
        thetaBandHz(1), ...
        thetaBandHz(2));

    fprintf(fileId, 'Mu: %.3f <= f < %.3f Hz\n', ...
        muBandHz(1), ...
        muBandHz(2));

    fprintf(fileId, 'Beta: %.3f <= f <= %.3f Hz\n', ...
        betaBandHz(1), ...
        betaBandHz(2));

    fprintf(fileId, 'Low beta: %.3f <= f < %.3f Hz\n', ...
        lowBetaBandHz(1), ...
        lowBetaBandHz(2));

    fprintf(fileId, 'High beta: %.3f <= f <= %.3f Hz\n', ...
        highBetaBandHz(1), ...
        highBetaBandHz(2));

    fprintf(fileId, '\nAggregation rules:\n');
    fprintf(fileId, ...
        ['1. Multiple ICs in one Dataset x Cluster are averaged ' ...
         'in linear PSD.\n']);
    fprintf(fileId, ...
        ['2. Subject x Cluster QC averages available original ' ...
         'sessions equally.\n']);
    fprintf(fileId, ...
        ['3. Cluster QC averages subjects equally.\n']);
    fprintf(fileId, ...
        ['4. Subject/cluster QC rows are descriptive only and ' ...
         'must not be used as final condition results.\n']);
end
