function cfg = config_step12_14_clustering_roi_ersp()

% GOAL
%   Define parameters for repeated IC clustering around fixed ROI targets,
%   ROI-specific cluster QC, and gait-cycle time-warped ERSP analysis.
%
% METHOD
%   Store clustering parameters, fixed ROI targets, ROI-cluster QC settings,
%   ERSP settings, and output names in one configuration.

%% Step 12 - repeated clustering

cfg.clustering.processingVersion = ...
    "RHS_ROI_repeated_clustering";

cfg.clustering.numberOfClusters = 15;
cfg.clustering.numberOfRepetitions = 1000;
cfg.clustering.outlierSigma = 3;
cfg.clustering.randomSeed = 20260816;

cfg.clustering.forceRecomputeMeasureFiles = false;
cfg.clustering.forceRecomputePrecluster = false;
cfg.clustering.forceRecomputeSolutions = false;

% ROI candidate policy: within each repeated-clustering solution, evaluate
% only the regular cluster whose dipole centroid is nearest to the fixed ROI;
% then rank those per-solution candidates using the configured quality metrics.
cfg.clustering.roiCandidatePolicy = ...
    "nearest_centroid_per_solution";

%% Step 12 - preclustering features

cfg.clustering.weights.dipoles = 3;
cfg.clustering.weights.scalp = 1;
cfg.clustering.weights.spec = 1;
cfg.clustering.weights.erp = 0;
cfg.clustering.weights.ersp = 0;

cfg.clustering.frequencyRangeHz = [3 45];
cfg.clustering.timeWindowMs = [];

% BeMoBIL ROI quality dimensions:
%   1 subjects
%   2 ICs / subjects
%   3 normalized spread
%   4 mean RV
%   5 distance from ROI
%   6 Mahalanobis distance
cfg.clustering.qualityMeasureWeights = ...
    [3 -1 -1 -1 -2 -1];

%% Fixed ROI targets
%
% Identity fields are deliberately separated:
%   ROIID             stable analysis-target ID used downstream
%   OriginalClusterID provenance from the exploratory cluster that defined it
%   ROIName           anatomical label only
%   MNI_X/Y/Z         fixed target coordinate used by repeated clustering

cfg.roi.coordinateSpace = ...
    "MNI";

% Fixed targets were derived from the current five-subject exploratory
% clustering and then adjusted locally in BioImage Suite MNI<->TAL to obtain
% the recorded Brodmann-area labels. C03 (Left-SecVisual, BA18) is excluded
% because it is a visual-area cluster rather than a target walking ROI.
cfg.roi.provenance = struct( ...
    'coordinateSource', 'Adjusted MNI targets derived from current project exploratory clusters identified by OriginalClusterID', ...
    'atlasAnnotationSource', 'BioImage Suite MNI<->TAL');

cfg.roi.table = table( ...
    [ ...
        "ROI01"; ...
        "ROI02"; ...
        "ROI03"; ...
        "ROI04"; ...
        "ROI05"], ...
    [ ...
        "C04"; ...
        "C05"; ...
        "C10"; ...
        "C12"; ...
        "C15"], ...
    [ ...
        "Left_AngGyrus_BA39"; ...
        "Right_VisMotor_BA7"; ...
        "Left_PrimSensor_BA1"; ...
        "Right_PrimMotor_BA4"; ...
        "Right_PreMot_SuppMot_BA6"], ...
    [-39; 24; -24; 36; 1], ...
    [-55; -62; -30; -17; -22], ...
    [19; 42; 54; 45; 64], ...
    [true; true; true; true; true], ...
    'VariableNames', { ...
        'ROIID', ...
        'OriginalClusterID', ...
        'ROIName', ...
        'MNI_X', ...
        'MNI_Y', ...
        'MNI_Z', ...
        'Enabled'});

%% Step 12 - paths / filenames

cfg.clustering.rhsRootFolderName = ...
    '9_RHS-ERSP-run-separated';

cfg.clustering.inputStudyFolderName = ...
    '02_RHS-epoched-STUDY';

cfg.clustering.inputStudyFilename = ...
    'HipExo_RHS_epoched_run_separated.study';

cfg.clustering.outputFolderName = ...
    '03_ROI-repeated-clustering';

cfg.clustering.preclusterFolderName = ...
    '00_preclustered_STUDY';

cfg.clustering.solutionFolderName = ...
    '01_shared_clustering_solutions';

cfg.clustering.roiStudyFolderName = ...
    '02_ROI_STUDY_files';

cfg.clustering.preclusterFilename = ...
    'HipExo_RHS_epoched_bemobil_preclustered.study';

%% Step 13 - ROI-specific cluster QC

cfg.roiClusterQC.processingVersion = ...
    "RHS_ROI_CLUSTER_QC_DESCRIPTIVE_METRICS";

cfg.roiClusterQC.topSolutionCount = 10;
cfg.roiClusterQC.frequencyRangeHz = [3 45];

% Current study rule for subject representation.
% 0.80 means that the selected ROI-specific cluster must contain ICs from
% at least 80% of the subjects represented in the ROI STUDY, following the
% supervisor-approved rule for the current larger subject set.
cfg.roiClusterQC.minimumSubjectCoverageFraction = 0.80;

% No automatic numeric cutoffs are applied to centroid distance, dipole
% spread, dipole RV, subject balance, scalp correlation, or repeated-solution
% Jaccard. These are retained as descriptive QC metrics for manual review.

cfg.roiClusterQC.qcFolderName = ...
    '03_ROI_cluster_QC';

cfg.roiClusterQC.reviewWorkbookName = ...
    'RHS_ROI_cluster_QC_review.xlsx';

cfg.roiClusterQC.reviewSheetName = ...
    'ROI_Cluster_Review';

cfg.roiClusterQC.summaryCSVName = ...
    'ROI_cluster_QC_summary.csv';

cfg.roiClusterQC.overviewFigureName = ...
    'ROI_cluster_QC_overview.png';

cfg.roiClusterQC.overlapFigureName = ...
    'ROI_cluster_QC_pairwise_overlap.png';

cfg.roiClusterQC.runInfoName = ...
    'ROI_cluster_QC_run_info.mat';

%% Step 14 - gait-cycle ERSP

cfg.ersp.processingVersion = ...
    "RHS_ROI_timewarped_ERSP_COMMON_BASELINE_LOWEST_IC";

cfg.ersp.forceRecomputeERSP = false;

cfg.ersp.frequencyRangeHz = [3 45];
cfg.ersp.waveletCycles = [3 0.8];
cfg.ersp.numberOfFrequencies = 100;
cfg.ersp.numberOfTimePoints = 200;
cfg.ersp.paddingRatio = 2;

cfg.ersp.baselineNormalization = 'off';
cfg.ersp.trialBaselineMode = 'full';

conditions = config_analysis_conditions();

cfg.ersp.conditionOrder = conditions.Code';
cfg.ersp.conditionDisplayLabels = conditions.Display';

cfg.ersp.gaitEventNames = ...
    ["RHS", "LTO", "LHS", "RTO", "RHS"];

% Core descriptive EEG endpoints: Mu (8-13 Hz) and Beta (13-30 Hz)
% by gait phase, as motivated by Morteza_Khosrotabar_ICNR2026_HipExoskeleton.
% The paper also proposes frontal theta; it is not an implemented endpoint here.
% Formal Assistive/Resistive contrasts require the experimental mode mapping.
% Band-by-gait-phase descriptive summaries.
% These frequency bands are scientific analysis definitions, not QC cutoffs.

cfg.ersp.summaryBandNames = ...
    ["Mu", "Beta"];

cfg.ersp.summaryBandRangesHz = [ ...
     8 13; ...
    13 30];

cfg.ersp.gaitPhaseNames = [ ...
    "RHS_to_LTO", ...
    "LTO_to_LHS", ...
    "LHS_to_RTO", ...
    "RTO_to_RHS"];

cfg.ersp.gaitPhaseDisplayLabels = [ ...
    "RHS-LTO", ...
    "LTO-LHS", ...
    "LHS-RTO", ...
    "RTO-RHS"];

cfg.ersp.outputFolderName = ...
    '04_timewarped_ERSP';

cfg.ersp.selectionSnapshotName = ...
    'ERSP_eligible_ROI_clusters.csv';

cfg.ersp.runInfoName = ...
    'ROI_timewarped_ERSP_run_info.mat';

cfg.ersp.figureFolderName = ...
    'figures';

cfg.ersp.matrixFolderName = ...
    'matrices';

cfg.ersp.bandPhaseFolderName = ...
    'band_phase_summary';

cfg.ersp.bandPhaseGroupSummaryName = ...
    'ROI_band_phase_ERSP_group_summary.csv';

cfg.ersp.bandPhaseSubjectSummaryName = ...
    'ROI_band_phase_ERSP_subject_summary.csv';

cfg.ersp.requiredClusterDecision = ...
    "KEEP";

cfg.ersp.requiredManualQCValue = ...
    "PASS";

end
