function cfg = config_step10_rhs_timewarp()
% GOAL
%   Define RHS-to-RHS epoching, gait-cycle QC, and make_timewarp settings.
% METHOD
%   Store analysis parameters, condition labels, and output names here.
%   Dataset identities and IC selections are read from the current manual IC review and subject-level processing table.

%% Processing identity

cfg.processingVersion = ...
    "RHS_epoch_timewarp_dynamic";

%% Recompute / AMICA overlap policy

cfg.forceRecompute = false;

cfg.amicaBadSamplePolicy = ...
    "annotate_only";

%% Scientific input requirement

cfg.expectedSamplingRateHz = ...
    500;

%% Epoch / gait landmarks

cfg.epochLimitsSec = ...
    [-1 2.5];

cfg.timewarpEventOrder = { ...
    'RHS', ...
    'LTO', ...
    'LHS', ...
    'RTO', ...
    'RHS'};

cfg.baselineLatencyMs = ...
    0;

%% make_timewarp outlier rules

cfg.maxSTDForAbsolute = ...
    3;

cfg.maxSTDForRelative = ...
    3;

cfg.minimumEpochsForTimewarp = ...
    3;

cfg.lowEpochWarningThreshold = ...
    20;

%% Condition order

cfg.conditionOrder = [ ...
    "NoExoPre", ...
    "AquaPlus", ...
    "Aqua", ...
    "Transparent", ...
    "Exo", ...
    "Sport", ...
    "Boost", ...
    "NoExoPost"];

cfg.conditionDisplayOrder = [ ...
    "NoExoPre", ...
    "AquaPlus", ...
    "Aqua", ...
    "Transparent (ExoOff)", ...
    "Exo", ...
    "Sport", ...
    "Boost", ...
    "NoExoPost"];

%% Input / output names

cfg.rhsRootFolderName = ...
    '9_RHS-ERSP-run-separated';

cfg.epochedSetFolderName = ...
    '01_RHS-epoched-sets';

cfg.manifestFileName = ...
    '01_RHS_epoch_manifest.csv';

cfg.qcFileName = ...
    '01_RHS_epoch_QC.csv';

cfg.recommendedCycleRelativePath = fullfile( ...
    'grf_quality_check', ...
    'GRF_RHS_timewarp_cycles_recommended_all_subjects.csv');

end
