function cfg = config_step12_14_clustering_roi_ersp()
% GOAL
%   Define parameters for repeated IC clustering around fixed ROI targets,
%   ROI-specific cluster QC, and gait-cycle time-warped ERSP analysis.
%
% METHOD
%   Store clustering parameters, fixed ROI targets, ROI-cluster QC settings,
%   ERSP settings, and output names in one configuration.

%% Step 12 - repeated clustering

cfg.clustering.processingVersion = ...
    "RHS_ROI_repeated_clustering";

cfg.clustering.numberOfClusters = 6;
cfg.clustering.numberOfRepetitions = 100;
cfg.clustering.outlierSigma = 3;
cfg.clustering.randomSeed = 20260816;

cfg.clustering.forceRecomputeMeasureFiles = false;
cfg.clustering.forceRecomputePrecluster = false;
cfg.clustering.forceRecomputeSolutions = false;

cfg.clustering.recoverSolutionBankWithoutProvenance = true;

%% Step 12 - preclustering features

cfg.clustering.weights.dipoles = 3;
cfg.clustering.weights.scalp = 1;
cfg.clustering.weights.spec = 1;
cfg.clustering.weights.erp = 0;
cfg.clustering.weights.ersp = 0;

cfg.clustering.frequencyRangeHz = [3 45];
cfg.clustering.timeWindowMs = [];

% BeMoBIL ROI quality dimensions:
%   1 subjects
%   2 ICs / subjects
%   3 normalized spread
%   4 mean RV
%   5 distance from ROI
%   6 Mahalanobis distance
cfg.clustering.qualityMeasureWeights = ...
    [3 -1 -1 -1 -2 -1];

%% Fixed ROI targets
%
% Identity fields are deliberately separated:
%   ROIID             stable analysis-target ID used downstream
%   OriginalClusterID provenance from the exploratory cluster that defined it
%   ROIName           anatomical label only
%   MNI_X/Y/Z         fixed target coordinate used by repeated clustering

cfg.roi.coordinateSpace = ...
    "MNI";

cfg.roi.table = table( ...
    [ ...
        "ROI01"; ...
        "ROI02"; ...
        "ROI03"; ...
        "ROI04"; ...
        "ROI05"; ...
        "ROI06"], ...
    [ ...
        "C02"; ...
        "C03"; ...
        "C04"; ...
        "C05"; ...
        "C09"; ...
        "C12"], ...
    [ ...
        "Right_PreMot_SuppMot_BA6"; ...
        "Right_VisMotor_BA7"; ...
        "Left_PrimMotor_BA4"; ...
        "Left_Agranular_Retrolimbic_BA30"; ...
        "Left_Frontal_Eye_Fields_BA8"; ...
        "Right_VisMotor_BA7"], ...
    [41; 2; -17; -23; -12; 34], ...
    [-6; -51; -27; -51; 33; -43], ...
    [40; 50; 57; 8; 33; 54], ...
    [true; true; true; true; true; true], ...
    'VariableNames', { ...
        'ROIID', ...
        'OriginalClusterID', ...
        'ROIName', ...
        'MNI_X', ...
        'MNI_Y', ...
        'MNI_Z', ...
        'Enabled'});

%% Step 12 - paths / filenames

cfg.clustering.rhsRootFolderName = ...
    '9_RHS-ERSP-run-separated';

cfg.clustering.inputStudyFolderName = ...
    '02_RHS-epoched-STUDY';

cfg.clustering.inputStudyFilename = ...
    'HipExo_RHS_epoched_run_separated.study';

cfg.clustering.outputFolderName = ...
    '03_ROI-repeated-clustering';

cfg.clustering.preclusterFolderName = ...
    '00_preclustered_STUDY';

cfg.clustering.solutionFolderName = ...
    '01_shared_clustering_solutions';

cfg.clustering.roiStudyFolderName = ...
    '02_ROI_STUDY_files';

cfg.clustering.preclusterFilename = ...
    'HipExo_RHS_epoched_bemobil_preclustered.study';

%% Step 13 - ROI-specific cluster QC

cfg.roiClusterQC.processingVersion = ...
    "RHS_ROI_CLUSTER_QC_DESCRIPTIVE_METRICS";

cfg.roiClusterQC.topSolutionCount = 10;
cfg.roiClusterQC.frequencyRangeHz = [3 45];

% Current study rule for subject representation.
% 1.00 means that the selected ROI-specific cluster must contain ICs from
% every subject represented in the ROI STUDY. If the study design later
% adopts a different preregistered/supervisor-approved coverage rule, change
% this value explicitly rather than introducing ad-hoc balance thresholds.
cfg.roiClusterQC.minimumSubjectCoverageFraction = 1.00;

% No automatic numeric cutoffs are applied to centroid distance, dipole
% spread, dipole RV, subject balance, scalp correlation, or repeated-solution
% Jaccard. These are retained as descriptive QC metrics for manual review.

cfg.roiClusterQC.qcFolderName = ...
    '03_ROI_cluster_QC';

cfg.roiClusterQC.reviewWorkbookName = ...
    'RHS_ROI_cluster_QC_review.xlsx';

cfg.roiClusterQC.reviewSheetName = ...
    'ROI_Cluster_Review';

cfg.roiClusterQC.overviewFigureName = ...
    'ROI_cluster_QC_overview.png';

cfg.roiClusterQC.overlapFigureName = ...
    'ROI_cluster_QC_pairwise_overlap.png';

cfg.roiClusterQC.runInfoName = ...
    'ROI_cluster_QC_run_info.mat';

%% Step 14 - gait-cycle ERSP

cfg.ersp.processingVersion = ...
    "RHS_ROI_timewarped_ERSP_MEMBERWISE_BAND_PHASE";

cfg.ersp.buildTag = ...
    "ERSP_MEMBERWISE_GAIT_DB_BAND_PHASE";

cfg.ersp.forceRecomputeERSP = false;

cfg.ersp.frequencyRangeHz = [3 45];
cfg.ersp.waveletCycles = [3 0.8];
cfg.ersp.numberOfFrequencies = 100;
cfg.ersp.numberOfTimePoints = 200;
cfg.ersp.paddingRatio = 2;

cfg.ersp.timewarpRoundingMs = 50;

cfg.ersp.conditionOrder = [ ...
    "NoExoPre", ...
    "AquaPlus", ...
    "Aqua", ...
    "Transparent", ...
    "Exo", ...
    "Sport", ...
    "Boost", ...
    "NoExoPost"];

cfg.ersp.conditionDisplayLabels = [ ...
    "NoExoPre", ...
    "AquaPlus", ...
    "Aqua", ...
    "Transparent (ExoOff)", ...
    "Exo", ...
    "Sport", ...
    "Boost", ...
    "NoExoPost"];

cfg.ersp.gaitEventNames = ...
    ["RHS", "LTO", "LHS", "RTO", "RHS"];

% Band-by-gait-phase descriptive summaries.
% These frequency bands are scientific analysis definitions, not QC cutoffs.
cfg.ersp.summaryBandNames = ...
    ["Mu", "Beta"];

cfg.ersp.summaryBandRangesHz = [ ...
     8 13; ...
    13 30];

cfg.ersp.gaitPhaseNames = [ ...
    "RHS_to_LTO", ...
    "LTO_to_LHS", ...
    "LHS_to_RTO", ...
    "RTO_to_RHS"];

cfg.ersp.gaitPhaseDisplayLabels = [ ...
    "RHS-LTO", ...
    "LTO-LHS", ...
    "LHS-RTO", ...
    "RTO-RHS"];

cfg.ersp.outputFolderName = ...
    '04_timewarped_ERSP';

cfg.ersp.selectionSnapshotName = ...
    'ERSP_eligible_ROI_clusters.csv';

cfg.ersp.runInfoName = ...
    'ROI_timewarped_ERSP_run_info.mat';

cfg.ersp.figureFolderName = ...
    'figures';

cfg.ersp.matrixFolderName = ...
    'matrices';

cfg.ersp.bandPhaseFolderName = ...
    'band_phase_summary';

cfg.ersp.bandPhaseGroupSummaryName = ...
    'ROI_band_phase_ERSP_group_summary.csv';

cfg.ersp.bandPhaseSubjectSummaryName = ...
    'ROI_band_phase_ERSP_subject_summary.csv';

cfg.ersp.requiredClusterDecision = ...
    "KEEP";

cfg.ersp.requiredManualQCValue = ...
    "PASS";

end