function conditions = config_analysis_conditions()
% GOAL
%   Define the recorded pilot condition codes and their display order.
% INPUT
%   None. Physical run numbers remain the recorded run_number metadata.
% APPROACH
%   Retain existing pilot labels and aliases. The uploaded research-direction
%   paper does not specify which device modes are maximum assistance or
%   resistance; no such mapping is inferred here.
% OUTPUT
%   One ordered condition table used by Steps10, 11, 14 and 15.
% USED BY
%   The analysis configuration functions and hipexo.canonical_condition.
conditions = table( ...
    ["NoExoPre"; "AquaPlus"; "Aqua"; "Transparent"; ...
     "Exo"; "Sport"; "Boost"; "NoExoPost"], ...
    ["NoExoPre"; "AquaPlus"; "Aqua"; "Transparent (ExoOff)"; ...
     "Exo"; "Sport"; "Boost"; "NoExoPost"], ...
    ["noexo.*pre|pre.*noexo"; "aquaplus|aquaextra"; "aqua"; ...
     "transparent|exooff"; "eco|exo\d*(on)?$"; "sport"; "boost"; ...
     "noexo.*post|post.*noexo"], ...
    [1; 3; 7; 4; 8; 5; 6; 2], ...
    'VariableNames', {'Code', 'Display', 'Pattern', 'MatchPriority'});
end
