function P = project_paths()
% GOAL
%   Define all machine- and project-level paths used by the HipExo-EEG
%   pipeline from one central location.
% METHOD
%   Resolve the active scripts root from this file location, derive all
%   project paths, validate important locations, and add only active
%   code/dependencies to the MATLAB path.

%% USER SETTINGS
% Only this section should normally need editing when the project moves.

P.projectRoot = ...
    'E:\master_thesis\HipExo-EEG-Study_1';

P.eeglabFolder = ...
    'D:\eeglab_current\eeglab2026.0.0';

P.fieldtripFolder = fullfile( ...
    P.projectRoot, ...
    'fieldtrip-20260601');

P.amicaTempFolder = ...
    'E:\master_thesis\amica_tmp';

%% PROJECT STRUCTURE

P.projectFolder = fullfile( ...
    P.projectRoot, ...
    'EEG_preprocessing_Yadan');

P.rawDataFolder = fullfile( ...
    P.projectFolder, ...
    'PilotTest2');

P.bemobilFolder = fullfile( ...
    P.projectFolder, ...
    'BeMoBIL');

P.outputFolder = fullfile( ...
    P.projectFolder, ...
    'output_data_29082026');

%% CODE STRUCTURE
% project_paths.m must live inside the config/ folder of the active
% scripts package. The parent scripts-folder name is intentionally unrestricted
% so frozen and refactored packages can be tested side by side.

P.configFolder = fileparts(mfilename('fullpath'));
P.scriptsFolder = fileparts(P.configFolder);

[~, configFolderName] = fileparts(P.configFolder);

assert(strcmpi(configFolderName, 'config'), ...
    ['project_paths.m must be inside an active scripts-root/config folder.\n' ...
     'Detected config folder:\n%s'], ...
    P.configFolder);

P.runFolder = fullfile(P.scriptsFolder, 'run');
P.hipexoPackageFolder = fullfile(P.scriptsFolder, '+hipexo');
P.compatibilityFolder = fullfile(P.scriptsFolder, 'compatibility');
P.externalReferenceFolder = fullfile(P.scriptsFolder, 'external_reference');
P.archiveObsoleteFolder = fullfile(P.scriptsFolder, 'archive_obsolete');
P.docsFolder = fullfile(P.scriptsFolder, 'docs');
P.personalToolsFolder = fullfile(P.scriptsFolder, 'personal_tools');
P.testsFolder = fullfile(P.scriptsFolder, 'tests');

%% GAIT-EVENT AND CHANNEL-LOCATION PATHS

P.gaitEventFolder = fullfile( ...
    P.projectRoot, ...
    'stage1_per_condition', ...
    'gait-event-detection');

P.channelLocationFile = fullfile( ...
    P.gaitEventFolder, ...
    'chanlocs.ced');

% Compatibility fallback for the alternative project layout.
if ~isfile(P.channelLocationFile)

    alternativeGaitEventFolder = fullfile( ...
        P.projectFolder, ...
        'stage1_per_condition', ...
        'gait-event-detection');

    alternativeChannelLocationFile = fullfile( ...
        alternativeGaitEventFolder, ...
        'chanlocs.ced');

    if isfile(alternativeChannelLocationFile)
        P.gaitEventFolder = alternativeGaitEventFolder;
        P.channelLocationFile = alternativeChannelLocationFile;
    end
end

%% FIELDTRIP XDF LOADER

P.xdfLoaderFolder = fullfile( ...
    P.fieldtripFolder, ...
    'external', ...
    'xdf');

%% COMMON PIPELINE OUTPUTS

% Stream inspection.
P.summaryFile = fullfile( ...
    P.outputFolder, ...
    'xdf_file_stream_summary.csv');

P.detailFile = fullfile( ...
    P.outputFolder, ...
    'xdf_stream_detail_table.csv');

% Import control.
P.importTableFile = fullfile( ...
    P.outputFolder, ...
    'bemobil_import_table.csv');

P.mappingFile = P.importTableFile;

P.importLogFile = fullfile( ...
    P.outputFolder, ...
    'bemobil_xdf2bids_import_log.csv');

% GRF and mapped EEG.
P.grfSegmentationFolder = fullfile( ...
    P.outputFolder, ...
    'GRF_segmentation_output');

P.eegWithGRFEventsFolder = fullfile( ...
    P.outputFolder, ...
    'EEG_with_GRF_events');

% Subject-level EEG.
P.subjectLevelEEGFolder = fullfile( ...
    P.outputFolder, ...
    '2_raw-EEGLAB', ...
    'subject-level');

P.subjectLevelEEGTableFile = fullfile( ...
    P.subjectLevelEEGFolder, ...
    'subject_level_EEG_table.csv');

%% VALIDATE REQUIRED LOCATIONS

requiredFolders = { ...
    P.projectRoot, ...
    P.projectFolder, ...
    P.rawDataFolder, ...
    P.bemobilFolder, ...
    P.eeglabFolder, ...
    P.fieldtripFolder, ...
    P.scriptsFolder};

requiredFolderNames = { ...
    'projectRoot', ...
    'projectFolder', ...
    'rawDataFolder', ...
    'bemobilFolder', ...
    'eeglabFolder', ...
    'fieldtripFolder', ...
    'scriptsFolder'};

for i = 1:numel(requiredFolders)
    if ~isfolder(requiredFolders{i})
        warning('HipExo:MissingFolder', ...
            '%s does not exist:\n%s', ...
            requiredFolderNames{i}, ...
            requiredFolders{i});
    end
end

if ~isfile(P.channelLocationFile)
    warning('HipExo:MissingChannelLocations', ...
        'Channel-location file was not found:\n%s', ...
        P.channelLocationFile);
end

if ~isfolder(P.amicaTempFolder)
    warning('HipExo:MissingAMICATemp', ...
        'AMICA temporary folder does not exist:\n%s', ...
        P.amicaTempFolder);
end

%% ADD ACTIVE CODE AND DEPENDENCIES TO MATLAB PATH
% Do NOT add archive_obsolete, external_reference, personal_tools, or tests.

addpath(P.scriptsFolder, '-begin');

if isfolder(P.configFolder)
    addpath(P.configFolder, '-begin');
end

if isfolder(P.runFolder)
    addpath(P.runFolder, '-begin');
end

if isfolder(P.eeglabFolder)
    addpath(P.eeglabFolder);
end

if isfolder(P.bemobilFolder)
    addpath(genpath(P.bemobilFolder));
end

if isfolder(P.fieldtripFolder)
    addpath(P.fieldtripFolder);
end

if isfolder(P.xdfLoaderFolder)
    addpath(P.xdfLoaderFolder);
end

%% ENSURE CORE OUTPUT FOLDER EXISTS

if ~isfolder(P.outputFolder)
    mkdir(P.outputFolder);
end

end
