% GOAL
%   Extract the GRF stream from one batch-selected XDF and define accepted
%   walking intervals before gait-event detection.
%
% INPUT
%   GRF_BATCH_XDF_FILE and GRF_BATCH_GRF_OUTPUT_FOLDER supplied internally
%   by step03_process_subject_grf_eeg.m.
%
% OUTPUT
%   *_GRF_stream.mat
%   *_GRF_segmentation_QC.png
%
% METHOD
%   Preserve the current working marker-first/GRF-activity segmentation
%   logic. This is an internal Step 03 worker and is not run manually.

batchModeRequested = ~isempty(strtrim( ...
    getenv('GRF_BATCH_GRF_OUTPUT_FOLDER')));

batchUnattended = strcmpi(strtrim( ...
    getenv('GRF_BATCH_UNATTENDED')), '1');

processingVersion = ...
    "GRF_extraction_v2_strict_markers_2026-08-22";

figureVisibility = 'on';

if batchUnattended
    figureVisibility = 'off';
end

if ~batchModeRequested
    clear;
    clc;
    close all;
end

%% Load project paths and Step 03 configuration

internalFolder = fileparts(mfilename('fullpath'));
scriptsRoot = fileparts(internalFolder);

addpath(scriptsRoot, '-begin');
addpath(fullfile(scriptsRoot, 'config'), '-begin');

P = project_paths();
cfg = config_step03_04_grf_processing();

projectOutputFolder = P.outputFolder;
grfOutputFolder = P.grfSegmentationFolder;

%% Resolve batch output folder

batchGRFOutputFolder = strtrim( ...
    getenv('GRF_BATCH_GRF_OUTPUT_FOLDER'));

if ~isempty(batchGRFOutputFolder)
    grfOutputFolder = batchGRFOutputFolder;
end

if ~isfolder(projectOutputFolder)
    mkdir(projectOutputFolder);
end

if ~isfolder(grfOutputFolder)
    mkdir(grfOutputFolder);
end

fprintf('Project output folder:\n%s\n', projectOutputFolder);
fprintf('GRF output folder:\n%s\n\n', grfOutputFolder);

%% Initialize load_xdf

if exist('load_xdf', 'file') ~= 2

    if isfield(P, 'fieldtripFolder') && ...
            isfolder(P.fieldtripFolder)

        addpath(P.fieldtripFolder);

        if exist('ft_defaults', 'file') == 2
            ft_defaults;
        end
    end
end

% Search FieldTrip without adding all subfolders.
if exist('load_xdf', 'file') ~= 2 && ...
        isfield(P, 'fieldtripFolder') && ...
        isfolder(P.fieldtripFolder)

    xdfLoader = dir(fullfile( ...
        P.fieldtripFolder, ...
        '**', ...
        'load_xdf.m'));

    if ~isempty(xdfLoader)
        addpath(xdfLoader(1).folder);
    end
end

% Fallback: search EEGLAB plugins.
if exist('load_xdf', 'file') ~= 2 && ...
        isfield(P, 'eeglabFolder') && ...
        isfolder(P.eeglabFolder)

    xdfLoader = dir(fullfile( ...
        P.eeglabFolder, ...
        '**', ...
        'load_xdf.m'));

    if ~isempty(xdfLoader)
        addpath(xdfLoader(1).folder);
    end
end

if exist('load_xdf', 'file') ~= 2
    error([ ...
        'load_xdf.m could not be found using the folders ' ...
        'defined in project_paths.m.']);
end

fprintf('Using XDF loader:\n%s\n\n', ...
    which('load_xdf'));

%% Segmentation settings

segmentationMode = cfg.segmentation.mode;
excludedMarkerWords = cfg.segmentation.excludedMarkerWords;

%% Select one XDF

batchXDFFile = strtrim( ...
    getenv('GRF_BATCH_XDF_FILE'));

if ~isempty(batchXDFFile)

    xdfFile = batchXDFFile;

else

    [selectedFile, selectedFolder] = uigetfile( ...
        {'*.xdf', 'XDF files (*.xdf)'}, ...
        'Select one XDF file');

    if isequal(selectedFile, 0)
        error('No XDF file was selected.');
    end

    xdfFile = fullfile(selectedFolder, selectedFile);
end

if ~isfile(xdfFile)
    error('Selected XDF file does not exist:\n%s', ...
        xdfFile);
end

sourceXDFSignature = hipexo.file_signature(xdfFile);

[~, xdfBaseName] = fileparts(xdfFile);

safeBaseName = regexprep( ...
    xdfBaseName, ...
    '[^a-zA-Z0-9_-]', ...
    '_');

fprintf('\n====================================================\n');
fprintf('GRF EXTRACTION AND SEGMENTATION\n');
fprintf('====================================================\n');
fprintf('Selected XDF:\n%s\n\n', xdfFile);

%% Load XDF

streams = load_xdf(xdfFile);

if isempty(streams)
    error('No streams were found in the selected XDF.');
end

nStreams = numel(streams);

streamNames = strings(nStreams, 1);
streamTypes = strings(nStreams, 1);
streamRates = nan(nStreams, 1);
streamChannels = nan(nStreams, 1);

for iStream = 1:nStreams

    streamNames(iStream) = get_info_text( ...
        streams{iStream}, ...
        'name');

    streamTypes(iStream) = get_info_text( ...
        streams{iStream}, ...
        'type');

    streamRates(iStream) = str2double( ...
        get_info_text( ...
            streams{iStream}, ...
            'nominal_srate'));

    streamChannels(iStream) = str2double( ...
        get_info_text( ...
            streams{iStream}, ...
            'channel_count'));
end

streamSummary = table( ...
    (1:nStreams)', ...
    streamNames, ...
    streamTypes, ...
    streamRates, ...
    streamChannels, ...
    'VariableNames', { ...
        'StreamIndex', ...
        'StreamName', ...
        'StreamType', ...
        'NominalSrate', ...
        'ChannelCount'});

disp(streamSummary);

%% Find GRF force stream

isMarkerStream = ...
    contains(upper(streamNames), "MARKER") | ...
    contains(upper(streamTypes), "MARKER");

isGRFStream = ...
    strcmpi(strtrim(streamNames), "GRF") | ...
    contains(upper(streamTypes), "FORCE");

grfCandidates = find( ...
    isGRFStream & ...
    ~isMarkerStream);

if isempty(grfCandidates)
    error([ ...
        'No GRF force stream was found.\n' ...
        'Expected stream name "GRF" or type "Force".']);
end

if numel(grfCandidates) > 1

    fprintf('Possible GRF streams:\n');
    disp(streamSummary(grfCandidates, :));

    error('More than one possible GRF stream was found.');
end

grfIndex = grfCandidates(1);
grfStream = streams{grfIndex};

grfData = double(grfStream.time_series);
grfTimeStamps = double( ...
    grfStream.time_stamps(:)');

% Standard XDF orientation is channels x samples.
if size(grfData, 2) ~= numel(grfTimeStamps) && ...
        size(grfData, 1) == numel(grfTimeStamps)

    grfData = grfData';
end

if size(grfData, 2) ~= numel(grfTimeStamps)
    error([ ...
        'GRF data and timestamp sizes do not match.\n' ...
        'Data size: %d x %d\n' ...
        'Timestamps: %d'], ...
        size(grfData, 1), ...
        size(grfData, 2), ...
        numel(grfTimeStamps));
end

if isempty(grfTimeStamps)
    error('The GRF timestamp vector is empty.');
end

if any(~isfinite(grfTimeStamps))
    error('GRF timestamps contain non-finite values.');
end

if any(diff(grfTimeStamps) <= 0)
    error('GRF timestamps are not strictly increasing.');
end

nGRFChannels = size(grfData, 1);
nGRFSamples = size(grfData, 2);

grfTimeSec = ...
    grfTimeStamps - grfTimeStamps(1);

nominalSrate = streamRates(grfIndex);

measuredSrate = ...
    1 / median(diff(grfTimeStamps));

channelLabels = ...
    "GRF_Ch" + compose('%02d', (1:nGRFChannels)');

fprintf('Selected GRF stream: %s\n', ...
    streamNames(grfIndex));

fprintf('GRF channels:        %d\n', ...
    nGRFChannels);

fprintf('GRF samples:         %d\n', ...
    nGRFSamples);

fprintf('Nominal rate:        %.6g Hz\n', ...
    nominalSrate);

fprintf('Measured rate:       %.6g Hz\n', ...
    measuredSrate);

fprintf('Duration:            %.3f s\n\n', ...
    grfTimeSec(end));

if nGRFChannels ~= 8
    warning( ...
        'Expected 8 GRF channels, but found %d.', ...
        nGRFChannels);
end

%% Find GRF_Markers

% Only use a marker stream explicitly associated with GRF.
% Other unrelated marker streams are ignored.
grfMarkerCandidates = find( ...
    contains(upper(streamNames), "GRF_MARKER"));

markerLabels = strings(0, 1);
markerTimeStamps = zeros(0, 1);
markerTimeSec = zeros(0, 1);
markerStreamName = "";

if ~isempty(grfMarkerCandidates)

    markerIndex = grfMarkerCandidates(1);
    markerStream = streams{markerIndex};

    markerStreamName = streamNames(markerIndex);

    markerLabels = marker_to_string( ...
        markerStream.time_series);

    markerTimeStamps = double( ...
        markerStream.time_stamps(:));

    nMarkers = min( ...
        numel(markerLabels), ...
        numel(markerTimeStamps));

    markerLabels = markerLabels(1:nMarkers);
    markerTimeStamps = markerTimeStamps(1:nMarkers);

    inGRFRange = ...
        markerTimeStamps >= grfTimeStamps(1) & ...
        markerTimeStamps <= grfTimeStamps(end);

    markerLabels = markerLabels(inGRFRange);
    markerTimeStamps = markerTimeStamps(inGRFRange);

    markerTimeSec = ...
        markerTimeStamps - grfTimeStamps(1);

    fprintf('GRF marker stream:   %s\n', ...
        markerStreamName);

    fprintf('Markers in range:    %d\n\n', ...
        numel(markerLabels));

    if ~isempty(markerLabels)

        markerDisplayTable = table( ...
            markerTimeSec, ...
            markerTimeStamps, ...
            markerLabels, ...
            'VariableNames', { ...
                'RelativeTimeSec', ...
                'LSLTime', ...
                'Marker'});

        disp(markerDisplayTable);
    end

else
    fprintf([ ...
        'No GRF_Markers stream was found.\n' ...
        'Automatic GRF-activity segmentation will be used.\n\n']);
end

%% Plot GRF

% Do not sum the eight GRF channels. They may represent different
% physical quantities and may also contain different baseline offsets.
%
% Instead:
% 1. Display every channel separately.
% 2. Build a normalized GRF activity trace from the absolute first
%    differences across channels.
% 3. Use only this activity trace for selecting walking intervals.
%
% The activity trace is a visualization aid. It is not a vertical-GRF
% signal and must not be used later for RHS/LHS/RTO/LTO detection.
grfDifference = [ ...
    zeros(nGRFChannels, 1), ...
    diff(grfData, 1, 2)];

differenceScale = median( ...
    abs(grfDifference), ...
    2, ...
    'omitnan');

validDifferenceScale = ...
    isfinite(differenceScale) & ...
    differenceScale > 0;

if any(validDifferenceScale)
    fallbackScale = median( ...
        differenceScale(validDifferenceScale), ...
        'omitnan');
else
    fallbackScale = 1;
end

differenceScale(~validDifferenceScale) = fallbackScale;

normalizedDifference = ...
    abs(grfDifference) ./ differenceScale;

grfActivityTrace = median( ...
    normalizedDifference, ...
    1, ...
    'omitnan');

activitySmoothingSamples = max( ...
    1, ...
    round(0.50 * measuredSrate));

grfActivityTrace = smoothdata( ...
    grfActivityTrace, ...
    'movmedian', ...
    activitySmoothingSamples);

qcFigure = figure( ...
    'Color', 'w', ...
    'Name', ['GRF segmentation: ' xdfBaseName], ...
    'NumberTitle', 'off', ...
    'Visible', figureVisibility, ...
    'Position', [40 40 1550 950]);

plotLayout = tiledlayout( ...
    qcFigure, ...
    5, 2, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

channelAxes = gobjects(nGRFChannels, 1);

for iChannel = 1:nGRFChannels

    channelAxes(iChannel) = nexttile( ...
        plotLayout, ...
        iChannel);

    plot( ...
        channelAxes(iChannel), ...
        grfTimeSec, ...
        grfData(iChannel, :), ...
        'LineWidth', ...
        0.7);

    grid(channelAxes(iChannel), 'on');

    ylabel( ...
        channelAxes(iChannel), ...
        char(channelLabels(iChannel)), ...
        'Interpreter', ...
        'none');

    title( ...
        channelAxes(iChannel), ...
        char(channelLabels(iChannel)), ...
        'Interpreter', ...
        'none');

    xlim( ...
        channelAxes(iChannel), ...
        [grfTimeSec(1), grfTimeSec(end)]);

    if iChannel > max(nGRFChannels - 2, 0)
        xlabel( ...
            channelAxes(iChannel), ...
            'Time from first GRF sample (s)');
    else
        channelAxes(iChannel).XTickLabel = [];
    end
end

totalAxes = nexttile( ...
    plotLayout, ...
    [1 2]);

plot( ...
    totalAxes, ...
    grfTimeSec, ...
    grfActivityTrace, ...
    'Color', ...
    [0.00 0.90 1.00], ...
    'LineWidth', ...
    1.5);

grid(totalAxes, 'on');

xlabel( ...
    totalAxes, ...
    'Time from first GRF sample (s)');

ylabel( ...
    totalAxes, ...
    'Normalized GRF activity');

title( ...
    totalAxes, ...
    ['SELECT WALKING INTERVALS HERE - ' ...
     'normalized activity overview (not Fz)'], ...
    'Interpreter', ...
    'none');

xlim( ...
    totalAxes, ...
    [grfTimeSec(1), grfTimeSec(end)]);

hold(totalAxes, 'on');

% Display recorded GRF markers.
markerColors = lines(max(numel(markerTimeSec), 1));

for iMarker = 1:numel(markerTimeSec)

    xline( ...
        totalAxes, ...
        markerTimeSec(iMarker), ...
        '--', ...
        char(markerLabels(iMarker)), ...
        'Color', markerColors(iMarker, :), ...
        'LabelOrientation', 'horizontal', ...
        'LabelVerticalAlignment', 'middle', ...
        'Interpreter', 'none', ...
        'HandleVisibility', 'off');
end

linkaxes([channelAxes; totalAxes], 'x');

sgtitle( ...
    qcFigure, ...
    ['GRF channel inspection: ' xdfBaseName], ...
    'Interpreter', ...
    'none');

drawnow;

%% Extract metadata from filename

subject = extract_subject(xdfBaseName);

day = extract_token( ...
    xdfBaseName, ...
    '(day[0-9]+)', ...
    "UnknownDay");

session = extract_session(xdfBaseName);

%% Initialize interval variables

intervalStartSec = zeros(0, 1);
intervalEndSec = zeros(0, 1);
conditions = strings(0, 1);

startMarkerLabels = strings(0, 1);
endMarkerLabels = strings(0, 1);

segmentationMethods = strings(0, 1);
activityThreshold = NaN;
useActivitySegmentation = false;
forceManualSegmentation = false;

%% Try GRF marker segmentation

useMarkers = ...
    strcmpi(segmentationMode, "auto") && ...
    ~isempty(markerLabels);

if useMarkers

    [intervalStartSec, ...
     intervalEndSec, ...
     conditions, ...
     startMarkerLabels, ...
     endMarkerLabels] = pair_markers( ...
        markerLabels, ...
        markerTimeSec, ...
        excludedMarkerWords);

    if isempty(intervalStartSec)

        fprintf([ ...
            'GRF markers were present, but no valid ' ...
            'START/END pairs were found.\n' ...
            'Trying automatic GRF-activity segmentation.\n']);

        useMarkers = false;

    else

        segmentationMethods = repmat( ...
            "GRF_Marker", ...
            numel(intervalStartSec), ...
            1);

        draw_intervals( ...
            totalAxes, ...
            intervalStartSec, ...
            intervalEndSec, ...
            conditions, ...
            [0.10 0.60 0.20]);

        drawnow;

        if batchUnattended

            markerAnswer = 'Accept markers';

            fprintf([ ...
                'Unattended mode: accepting valid paired ' ...
                'GRF marker interval(s) automatically.\n']);

        else

            markerAnswer = questdlg( ...
                ['Marker intervals are shown in green. ' ...
                 'Do they correctly define the walking intervals?'], ...
                'Confirm marker intervals', ...
                'Accept markers', ...
                'Use manual clicks', ...
                'Cancel', ...
                'Accept markers');
        end

        if strcmp(markerAnswer, 'Use manual clicks')

            useMarkers = false;
            forceManualSegmentation = true;

            delete(findall( ...
                totalAxes, ...
                'Tag', ...
                'WalkingIntervalOverlay'));

        elseif isempty(markerAnswer) || ...
                strcmp(markerAnswer, 'Cancel')

            error('Segmentation was cancelled.');
        end
    end
end

%% Try automatic GRF-activity segmentation

% If usable GRF markers are unavailable or invalid, automatically
% identify long continuous walking intervals from the normalized GRF
% activity trace. Manual clicking remains available only as a fallback.
if strcmpi(segmentationMode, "auto") && ...
        ~useMarkers && ...
        ~forceManualSegmentation

    [intervalStartSec, ...
     intervalEndSec, ...
     activityThreshold] = hipexo.detect_walking_intervals( ...
        grfActivityTrace, ...
        grfTimeSec, ...
        measuredSrate, ...
        cfg.segmentation);

    if ~isempty(intervalStartSec)

        nAutomaticIntervals = ...
            numel(intervalStartSec);

        conditions = repmat( ...
            session, ...
            nAutomaticIntervals, ...
            1);

        startMarkerLabels = ...
            repmat("", nAutomaticIntervals, 1);

        endMarkerLabels = ...
            repmat("", nAutomaticIntervals, 1);

        segmentationMethods = repmat( ...
            "Automatic_GRF_Activity", ...
            nAutomaticIntervals, ...
            1);

        yline( ...
            totalAxes, ...
            activityThreshold, ...
            ':', ...
            'Automatic activity threshold', ...
            'Color', ...
            [1.00 0.85 0.00], ...
            'LineWidth', ...
            1.4, ...
            'Interpreter', ...
            'none', ...
            'HandleVisibility', ...
            'off', ...
            'Tag', ...
            'WalkingIntervalOverlay');

        draw_intervals( ...
            totalAxes, ...
            intervalStartSec, ...
            intervalEndSec, ...
            conditions, ...
            [0.10 0.55 0.85]);

        title( ...
            totalAxes, ...
            ['Automatically detected walking intervals ' ...
             '(blue)'], ...
            'Interpreter', ...
            'none');

        drawnow;

        fprintf('\nAutomatically detected walking intervals:\n');

        automaticIntervalDisplay = table( ...
            (1:nAutomaticIntervals)', ...
            intervalStartSec, ...
            intervalEndSec, ...
            intervalEndSec - intervalStartSec, ...
            'VariableNames', { ...
                'Interval', ...
                'StartSec', ...
                'EndSec', ...
                'DurationSec'});

        disp(automaticIntervalDisplay);

        if batchUnattended

            automaticAnswer = 'Accept automatic';

            fprintf([ ...
                'Unattended mode: accepting automatically detected ' ...
                'GRF-activity interval(s).\n']);

        else

            automaticAnswer = questdlg( ...
                ['Automatically detected walking intervals are ' ...
                 'shown in blue. Are they correct?'], ...
                'Confirm automatic GRF segmentation', ...
                'Accept automatic', ...
                'Use manual clicks', ...
                'Cancel', ...
                'Accept automatic');
        end

        if strcmp(automaticAnswer, 'Accept automatic')

            useActivitySegmentation = true;

        elseif strcmp(automaticAnswer, 'Use manual clicks')

            delete(findall( ...
                totalAxes, ...
                'Tag', ...
                'WalkingIntervalOverlay'));

        else
            error('Segmentation was cancelled.');
        end

    else

        if batchUnattended
            error([ ...
                'Automatic GRF-activity segmentation did not find ' ...
                'a valid walking interval. No manual interval was ' ...
                'created in unattended mode.']);
        end

        fprintf([ ...
            'Automatic GRF-activity segmentation did not find ' ...
            'a valid walking interval.\n' ...
            'Switching to manual segmentation.\n']);
    end
end

%% Manual segmentation

if ~useMarkers && ...
        ~useActivitySegmentation

    if batchUnattended
        error([ ...
            'A manual GRF interval would be required, but unattended ' ...
            'mode does not permit manual selection. This XDF will be ' ...
            'reported as failed.']);
    end

    intervalStartSec = zeros(0, 1);
    intervalEndSec = zeros(0, 1);
    conditions = strings(0, 1);

    startMarkerLabels = strings(0, 1);
    endMarkerLabels = strings(0, 1);

    intervalAnswer = inputdlg( ...
        {'Number of valid walking intervals in this XDF:'}, ...
        'Manual GRF segmentation', ...
        [1 55], ...
        {'1'});

    if isempty(intervalAnswer)
        error('Manual segmentation was cancelled.');
    end

    nIntervals = str2double(intervalAnswer{1});

    if ~isscalar(nIntervals) || ...
            ~isfinite(nIntervals) || ...
            nIntervals < 1 || ...
            nIntervals ~= round(nIntervals)

        error('Number of intervals must be a positive integer.');
    end

    axes(totalAxes);

    title( ...
        totalAxes, ...
        sprintf([ ...
            'Click START and then END for each interval ' ...
            '(%d clicks required)'], ...
            2 * nIntervals));

    fprintf('\nManual segmentation\n');
    fprintf('Click START and then END for each interval.\n');
    fprintf('Required clicks: %d\n\n', 2 * nIntervals);

    [clickedTimes, ~] = ginput(2 * nIntervals);

    clickedTimes = clickedTimes(:);

    intervalStartSec = clickedTimes(1:2:end);
    intervalEndSec = clickedTimes(2:2:end);

    % Correct reversed click pairs.
    reversedPairs = ...
        intervalStartSec > intervalEndSec;

    temporaryStart = ...
        intervalStartSec(reversedPairs);

    intervalStartSec(reversedPairs) = ...
        intervalEndSec(reversedPairs);

    intervalEndSec(reversedPairs) = ...
        temporaryStart;

    % Sort intervals chronologically.
    [intervalStartSec, sortOrder] = ...
        sort(intervalStartSec);

    intervalEndSec = ...
        intervalEndSec(sortOrder);

    if any(intervalStartSec < grfTimeSec(1)) || ...
            any(intervalEndSec > grfTimeSec(end))

        error('One or more intervals are outside the GRF range.');
    end

    if any(intervalEndSec <= intervalStartSec)
        error('Every interval must have EndTime > StartTime.');
    end

    if numel(intervalStartSec) > 1 && ...
            any(intervalStartSec(2:end) < ...
                intervalEndSec(1:end-1))

        error('Selected walking intervals overlap.');
    end

    conditions = strings(nIntervals, 1);

    for iInterval = 1:nIntervals

        conditionAnswer = inputdlg( ...
            {sprintf( ...
                'Condition label for interval %d:', ...
                iInterval)}, ...
            'Condition label', ...
            [1 65], ...
            {char(session)});

        if isempty(conditionAnswer)
            error('Condition entry was cancelled.');
        end

        conditions(iInterval) = ...
            string(conditionAnswer{1});

        if strlength(strtrim(conditions(iInterval))) == 0
            conditions(iInterval) = session;
        end
    end

    startMarkerLabels = ...
        repmat("", nIntervals, 1);

    endMarkerLabels = ...
        repmat("", nIntervals, 1);

    segmentationMethods = ...
        repmat("Manual_GRF", nIntervals, 1);

    draw_intervals( ...
        totalAxes, ...
        intervalStartSec, ...
        intervalEndSec, ...
        conditions, ...
        [0.85 0.20 0.15]);

    drawnow;

    manualAnswer = questdlg( ...
        'Do the manually selected intervals look correct?', ...
        'Confirm manual intervals', ...
        'Accept', ...
        'Cancel', ...
        'Accept');

    if isempty(manualAnswer) || ...
            strcmp(manualAnswer, 'Cancel')

        error([ ...
            'Intervals were not saved. ' ...
            'Run the script again to repeat the selection.']);
    end
end

%% Snap boundaries to actual GRF samples

nIntervals = numel(intervalStartSec);

startGRFSample = zeros(nIntervals, 1);
endGRFSample = zeros(nIntervals, 1);

startLSLTime = zeros(nIntervals, 1);
endLSLTime = zeros(nIntervals, 1);

for iInterval = 1:nIntervals

    [~, startGRFSample(iInterval)] = min( ...
        abs(grfTimeSec - intervalStartSec(iInterval)));

    [~, endGRFSample(iInterval)] = min( ...
        abs(grfTimeSec - intervalEndSec(iInterval)));

    intervalStartSec(iInterval) = ...
        grfTimeSec(startGRFSample(iInterval));

    intervalEndSec(iInterval) = ...
        grfTimeSec(endGRFSample(iInterval));

    startLSLTime(iInterval) = ...
        grfTimeStamps(startGRFSample(iInterval));

    endLSLTime(iInterval) = ...
        grfTimeStamps(endGRFSample(iInterval));
end

if any(intervalEndSec <= intervalStartSec)
    error('At least one snapped GRF interval has EndTime <= StartTime.');
end

if nIntervals > 1 && ...
        any(intervalStartSec(2:end) < intervalEndSec(1:end-1))
    error('Snapped GRF walking intervals overlap.');
end

durationSec = ...
    intervalEndSec - intervalStartSec;

%% Build output table

reviewedFlags = ...
    repmat(~batchUnattended, nIntervals, 1);

reviewNotes = ...
    repmat("", nIntervals, 1);

if batchUnattended
    reviewNotes(:) = ...
        "Automatically accepted; QC PNG not manually reviewed";
end

intervalTable = table( ...
    repmat(subject, nIntervals, 1), ...
    repmat(day, nIntervals, 1), ...
    repmat(session, nIntervals, 1), ...
    conditions, ...
    (1:nIntervals)', ...
    intervalStartSec, ...
    intervalEndSec, ...
    durationSec, ...
    startLSLTime, ...
    endLSLTime, ...
    startGRFSample, ...
    endGRFSample, ...
    segmentationMethods, ...
    startMarkerLabels, ...
    endMarkerLabels, ...
    repmat(string(xdfFile), nIntervals, 1), ...
    reviewedFlags, ...
    reviewNotes, ...
    'VariableNames', { ...
        'Subject', ...
        'Day', ...
        'Session', ...
        'Condition', ...
        'SegmentIndex', ...
        'StartTimeSec', ...
        'EndTimeSec', ...
        'DurationSec', ...
        'StartLSLTime', ...
        'EndLSLTime', ...
        'StartGRFSample', ...
        'EndGRFSample', ...
        'SegmentationMethod', ...
        'StartMarkerLabel', ...
        'EndMarkerLabel', ...
        'XDFPath', ...
        'Reviewed', ...
        'Notes'});

%% Define output files

matFile = fullfile( ...
    grfOutputFolder, ...
    [safeBaseName '_GRF_stream.mat']);

figureFile = fullfile( ...
    grfOutputFolder, ...
    [safeBaseName '_GRF_segmentation_QC.png']);

%% Save extracted GRF

processingInfo = struct();
processingInfo.version = char(processingVersion);
processingInfo.source_xdf = xdfFile;
processingInfo.source_xdf_signature = char(sourceXDFSignature);
processingInfo.segmentation_mode = char(segmentationMode);
processingInfo.excluded_marker_words = excludedMarkerWords;
processingInfo.created_on = char(datetime( ...
    'now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

save( ...
    matFile, ...
    'grfData', ...
    'grfTimeStamps', ...
    'grfTimeSec', ...
    'grfActivityTrace', ...
    'activitySmoothingSamples', ...
    'activityThreshold', ...
    'channelLabels', ...
    'nominalSrate', ...
    'measuredSrate', ...
    'markerLabels', ...
    'markerTimeStamps', ...
    'markerTimeSec', ...
    'markerStreamName', ...
    'streamSummary', ...
    'intervalTable', ...
    'xdfFile', ...
    'processingInfo', ...
    '-v7.3');

%% Save QC figure

title( ...
    totalAxes, ...
    'Accepted walking intervals', ...
    'Interpreter', ...
    'none');

exportgraphics( ...
    qcFigure, ...
    figureFile, ...
    'Resolution', ...
    200);

fprintf('GRF segmentation completed: %d interval(s).\n', nIntervals);

%% Local functions

function value = get_info_text(stream, fieldName)

value = "";

if ~isfield(stream, 'info') || ...
        ~isfield(stream.info, fieldName)
    return;
end

rawValue = stream.info.(fieldName);

while iscell(rawValue) && ...
        numel(rawValue) == 1

    rawValue = rawValue{1};
end

try
    value = string(rawValue);
    value = value(1);
catch
    value = "";
end
end

function labels = marker_to_string(timeSeries)

if isempty(timeSeries)
    labels = strings(0, 1);
    return;
end

rawValues = timeSeries(:);
labels = strings(numel(rawValues), 1);

for iValue = 1:numel(rawValues)

    if iscell(rawValues)
        currentValue = rawValues{iValue};
    else
        currentValue = rawValues(iValue);
    end

    while iscell(currentValue) && ...
            numel(currentValue) == 1

        currentValue = currentValue{1};
    end

    try
        convertedValue = string(currentValue);
        labels(iValue) = convertedValue(1);
    catch
        labels(iValue) = "";
    end
end

labels = strtrim(labels);
end

function subject = extract_subject(fileName)

match = regexp( ...
    fileName, ...
    'sub-(.+?)_(day[0-9]+)', ...
    'tokens', ...
    'once');

if isempty(match)
    subject = "UnknownSubject";
else
    subject = string(match{1});
end
end

function token = extract_token( ...
        fileName, ...
        expression, ...
        fallback)

match = regexp( ...
    fileName, ...
    expression, ...
    'tokens', ...
    'once');

if isempty(match)
    token = string(fallback);
else
    token = string(match{1});
end
end

function session = extract_session(fileName)

match = regexp( ...
    fileName, ...
    'ses-(.+?)_task-', ...
    'tokens', ...
    'once');

if isempty(match)

    match = regexp( ...
        fileName, ...
        'ses-([^_]+)', ...
        'tokens', ...
        'once');
end

if isempty(match)
    session = "UnknownSession";
else
    session = string(match{1});
end
end

function [startSec, endSec, conditions, ...
    startLabels, endLabels] = pair_markers( ...
        markerLabels, ...
        markerTimeSec, ...
        excludedWords)

markerLabels = string(markerLabels(:));
markerTimeSec = double(markerTimeSec(:));

upperLabels = upper(strtrim(markerLabels));

isStart = ...
    startsWith(upperLabels, "START_") | ...
    strcmp(upperLabels, "START");

isEnd = ...
    startsWith(upperLabels, "END_") | ...
    strcmp(upperLabels, "END");

usedEnd = false(numel(markerLabels), 1);

startSec = zeros(0, 1);
endSec = zeros(0, 1);
conditions = strings(0, 1);

startLabels = strings(0, 1);
endLabels = strings(0, 1);

startIndices = find(isStart);

for iStart = 1:numel(startIndices)

    startIndex = startIndices(iStart);

    condition = regexprep( ...
        markerLabels(startIndex), ...
        '(?i)^START_?', ...
        '');

    condition = strtrim(condition);

    if strlength(condition) == 0
        condition = "Unspecified";
    end

    excludeCondition = false;

    for iWord = 1:numel(excludedWords)

        if contains( ...
                upper(condition), ...
                upper(excludedWords(iWord)))

            excludeCondition = true;
            break;
        end
    end

    if excludeCondition
        continue;
    end

    endConditions = regexprep( ...
        markerLabels, ...
        '(?i)^END_?', ...
        '');

    sameCondition = strcmpi( ...
        strtrim(endConditions), ...
        condition);

    if condition == "Unspecified"
        sameCondition = ...
            strlength(strtrim(endConditions)) == 0;
    end

    matchingEnd = find( ...
        isEnd & ...
        sameCondition & ...
        ~usedEnd & ...
        markerTimeSec > markerTimeSec(startIndex), ...
        1, ...
        'first');

    if isempty(matchingEnd)

        warning( ...
            ['No condition-matched END marker found for %s. ' ...
            'This START marker is not used.'], ...
            markerLabels(startIndex));

        continue;
    end

    usedEnd(matchingEnd) = true;

    startSec(end + 1, 1) = ...
        markerTimeSec(startIndex); %#ok<AGROW>

    endSec(end + 1, 1) = ...
        markerTimeSec(matchingEnd); %#ok<AGROW>

    conditions(end + 1, 1) = ...
        condition; %#ok<AGROW>

    startLabels(end + 1, 1) = ...
        markerLabels(startIndex); %#ok<AGROW>

    endLabels(end + 1, 1) = ...
        markerLabels(matchingEnd); %#ok<AGROW>
end

validIntervals = ...
    isfinite(startSec) & ...
    isfinite(endSec) & ...
    endSec > startSec;

startSec = startSec(validIntervals);
endSec = endSec(validIntervals);

conditions = conditions(validIntervals);
startLabels = startLabels(validIntervals);
endLabels = endLabels(validIntervals);

[startSec, sortOrder] = sort(startSec);

endSec = endSec(sortOrder);
conditions = conditions(sortOrder);
startLabels = startLabels(sortOrder);
endLabels = endLabels(sortOrder);

if numel(startSec) > 1 && ...
        any(startSec(2:end) < endSec(1:end-1))
    error([ ...
        'Condition-matched marker intervals overlap. ' ...
        'Do not accept these marker boundaries automatically.']);
end
end

function draw_intervals( ...
        targetAxes, ...
        startSec, ...
        endSec, ...
        labels, ...
        intervalColor)

targetYLimits = ylim(targetAxes);

for iInterval = 1:numel(startSec)

    patch( ...
        targetAxes, ...
        [startSec(iInterval), ...
         endSec(iInterval), ...
         endSec(iInterval), ...
         startSec(iInterval)], ...
        [targetYLimits(1), ...
         targetYLimits(1), ...
         targetYLimits(2), ...
         targetYLimits(2)], ...
        intervalColor, ...
        'FaceAlpha', 0.12, ...
        'EdgeColor', intervalColor, ...
        'LineWidth', 1.2, ...
        'HandleVisibility', 'off', ...
        'Tag', 'WalkingIntervalOverlay');

    text( ...
        targetAxes, ...
        mean([ ...
            startSec(iInterval), ...
            endSec(iInterval)]), ...
        targetYLimits(2), ...
        char(labels(iInterval)), ...
        'Color', intervalColor, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'Interpreter', 'none', ...
        'FontWeight', 'bold', ...
        'Tag', 'WalkingIntervalOverlay');
end
end

